import { instantiate } from "#workerd-loader";
import wasmModule from "#workerd-wasm";

// workerd supplies a precompiled module; never fetch or compile Wasm bytes here.
export const {
  applyCommandsAndCompileHandle,
  applyCommandsAndConvertToHastHandle,
  applyCommandsAndRenderHandle,
  applyCommandsToHandle,
  applyCommandsToMdastHandle,
  applyMdastCommandsAndConvertAndCompile,
  applyMdastCommandsAndConvertAndRender,
  compileHandle,
  compileMdx,
  convertMdastToHastHandle,
  createHastHandle,
  createHastHandleFromHtml,
  createHastHandleWithFrontmatter,
  createMdastHandle,
  createMdxHastHandle,
  createMdxHastHandleWithFrontmatter,
  createMdxMdastHandle,
  dropHandle,
  getHandleSource,
  getMdastFrontmatter,
  getNodeData,
  markdownToHtmlFast,
  markdownToJsFast,
  mdastTextContentHandle,
  mdxToJsFast,
  parseEsm,
  parseExpression,
  parseToHtml,
  renderHandle,
  renderHastOpstream,
  parseHastWire,
  parseMdastWire,
  serializeHandle,
  setNodeData,
  textContentHandle,
  walkHandle,
  walkMdastHandle,
} = await instantiate(wasmModule);
