packages:
  - packages/*
  - packages/vite-plugin-satteri/example
  - examples
  - website

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  workerd: true

supportedArchitectures:
  cpu:
    - current
    - wasm32
