//! Emitters: turn the [`schema`] table into Rust and TS source.

use std::fmt::Write as _;

use crate::schema::{ArenaStruct, Js, Layout, Node, Wire};

const HEADER_RS: &str =
    "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n";
const HEADER_TS: &str =
    "// @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n";

fn tag_pattern(tags: &[u8]) -> String {
    tags.iter()
        .map(u8::to_string)
        .collect::<Vec<_>>()
        .join(" | ")
}

/// The Rust walk-path serializer: resolve each field from `type_data` onto the
/// inline wire. Returns `false` for tags it does not own, so the caller can fall
/// through to the hand-written arms (list, table, MDX JSX, directives).
pub fn walk_rs(layouts: &[Layout]) -> String {
    let mut out = String::from(HEADER_RS);
    out.push_str(
        "use crate::walk::{write_str16, write_str32};\nuse satteri_arena::{Arena, Mdast};\n\n",
    );
    out.push_str("/// Serialize a node's `type_data` to the walk wire. `true` if handled here.\n");
    out.push_str("#[allow(clippy::manual_range_patterns)]\n");
    out.push_str(
        "pub(crate) fn write_mdast_type_data_inline(\n    arena: &Arena<Mdast>,\n    node_type: u8,\n    type_data: &[u8],\n    out: &mut Vec<u8>,\n) -> bool {\n    match node_type {\n",
    );
    for layout in layouts {
        let _ = writeln!(out, "        {} => {{", tag_pattern(&layout.tags));
        for f in layout.fields {
            // Const fields are stored but never crossed over the wire.
            if matches!(f.js_kind, Js::Const(_)) {
                continue;
            }
            let line = match f.wire {
                Wire::Str16 => format!("write_str16(arena, out, type_data, {});", f.offset),
                Wire::Str32 => format!("write_str32(arena, out, type_data, {});", f.offset),
                Wire::U8 => {
                    let cond = if f.offset == 0 {
                        "!type_data.is_empty()".to_string()
                    } else {
                        format!("type_data.len() > {}", f.offset)
                    };
                    format!(
                        "out.push(if {cond} {{ type_data[{}] }} else {{ {} }});",
                        f.offset, f.u8_default
                    )
                }
            };
            let _ = writeln!(out, "            {line}");
        }
        out.push_str("        }\n");
    }
    out.push_str("        _ => return false,\n    }\n    true\n}\n");
    out
}

/// The node-type discriminant enum plus `from_u8` / `name`, generated from the
/// registry so the tag <-> variant <-> name mapping is declared exactly once.
pub fn node_types_rs(enum_name: &str, nodes: &[Node]) -> String {
    let mut out = String::from(HEADER_RS);
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n#[repr(u8)]\n");
    let _ = writeln!(out, "pub enum {enum_name} {{");
    for node in nodes {
        let _ = writeln!(out, "    {} = {},", node.variant, node.tag);
    }
    out.push_str("}\n\n");
    let _ = writeln!(out, "impl {enum_name} {{");
    out.push_str("    pub fn from_u8(v: u8) -> Option<Self> {\n        match v {\n");
    for node in nodes {
        let _ = writeln!(
            out,
            "            {} => Some({enum_name}::{}),",
            node.tag, node.variant
        );
    }
    out.push_str("            _ => None,\n        }\n    }\n\n");
    out.push_str("    /// The canonical type name, as used in the public AST and diagnostics.\n");
    out.push_str("    pub fn name(self) -> &'static str {\n        match self {\n");
    for node in nodes {
        let _ = writeln!(
            out,
            "            {enum_name}::{} => {:?},",
            node.variant, node.name
        );
    }
    out.push_str("        }\n    }\n\n");
    out.push_str("    /// The node type for an AST name, or `None` if unrecognized.\n");
    out.push_str("    pub fn from_name(name: &str) -> Option<Self> {\n        Some(match name {\n");
    for node in nodes {
        let _ = writeln!(
            out,
            "            {:?} => {enum_name}::{},",
            node.name, node.variant
        );
    }
    out.push_str("            _ => return None,\n        })\n    }\n}\n");
    out
}

/// Total stored `type_data` size for a layout: the max field extent, rounded up
/// to 4 when it holds any `StringRef` (matching the codec structs' alignment).
fn layout_size(layout: &Layout) -> usize {
    let mut max = 0usize;
    let mut has_ref = false;
    for f in layout.fields {
        let size = match f.wire {
            Wire::Str16 | Wire::Str32 => {
                has_ref = true;
                8
            }
            Wire::U8 => 1,
        };
        max = max.max(f.offset + size);
    }
    if has_ref { max.div_ceil(4) * 4 } else { max }
}

/// SCREAMING_SNAKE of a camelCase field name (`referenceType` -> `REFERENCE_TYPE`).
fn screaming(js: &str) -> String {
    let mut out = String::new();
    for ch in js.chars() {
        if ch.is_ascii_uppercase() {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

/// One field's encode statement, or `None` for a `skip` field (left zero).
/// `src` is the value source: `"js"` (a `&JsNode`) or `"ops"` (a `&FieldCollector`).
fn encode_stmt(f: &crate::schema::Field, src: &str) -> Option<String> {
    let str_src = |name: &str| match src {
        "js" => format!("js_node.{}.as_deref()", screaming(name).to_lowercase()),
        _ => format!("c.strs[OF_{} as usize]", screaming(name)),
    };
    let end = f.offset + 8;
    match f.js_kind {
        Js::Str | Js::StrNull => Some(format!(
            "let r = alloc_opt_str(builder, {});\n            buf[{}..{end}].copy_from_slice(&r.as_bytes());",
            str_src(f.js),
            f.offset,
        )),
        Js::Num => {
            let v = match src {
                "js" => format!("js_node.{}.unwrap_or({})", f.js, f.u8_default),
                _ => format!("c.{}.unwrap_or({})", f.js, f.u8_default),
            };
            Some(format!("buf[{}] = {v};", f.offset))
        }
        Js::Enum(_) => Some(format!(
            "buf[{}] = reference_kind({});",
            f.offset,
            str_src("referenceType"),
        )),
        Js::Const(v) => Some(format!("buf[{}] = {v};", f.offset)),
        Js::Skip => None,
    }
}

/// Both arena encoders (`JsNode` -> bytes and op-stream `FieldCollector` -> bytes),
/// generated per type from the registry. Emitted as `plugin-api/src/generated/encode.rs`
/// and imported by `js_commands.rs`; writes bytes directly at the registry offsets.
pub fn encode_rs(layouts: &[Layout]) -> String {
    let mut ofs: Vec<String> = Vec::new();
    for layout in layouts {
        for f in layout.fields {
            let name = match f.js_kind {
                Js::Str | Js::StrNull => screaming(f.js),
                Js::Enum(_) => "REFERENCE_TYPE".to_string(),
                _ => continue,
            };
            let of = format!("OF_{name}");
            if !ofs.contains(&of) {
                ofs.push(of);
            }
        }
    }
    ofs.sort();

    let mut out = String::from(
        "// @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n",
    );
    let _ = writeln!(
        out,
        "use crate::js_commands::{{FieldCollector, alloc_opt_str, reference_kind, {}}};",
        ofs.join(", ")
    );
    out.push_str("use satteri_arena::{ArenaBuilder, Mdast};\n");
    out.push_str("use satteri_ast::commands::JsNode;\n\n");
    for (fn_name, param, src) in [
        ("encode_mdast_type_data", "js_node: &JsNode", "js"),
        (
            "encode_mdast_type_data_from_ops",
            "c: &FieldCollector",
            "ops",
        ),
    ] {
        let _ = writeln!(
            out,
            "/// Encode a node's `type_data` bytes from {}; `None` for types whose\n/// variable-length codec stays hand-written.\n#[allow(clippy::manual_range_patterns)]\npub(crate) fn {fn_name}(\n    {param},\n    node_type: u8,\n    builder: &mut ArenaBuilder<Mdast>,\n) -> Option<Vec<u8>> {{\n    let buf = match node_type {{",
            if src == "js" {
                "a `JsNode`"
            } else {
                "an op-stream collector"
            },
        );
        for layout in layouts {
            let _ = writeln!(out, "        {} => {{", tag_pattern(&layout.tags));
            let _ = writeln!(
                out,
                "            let mut buf = vec![0u8; {}];",
                layout_size(layout)
            );
            for f in layout.fields {
                if let Some(stmt) = encode_stmt(f, src) {
                    let _ = writeln!(out, "            {stmt}");
                }
            }
            out.push_str("            buf\n        }\n");
        }
        out.push_str("        _ => return None,\n    };\n    Some(buf)\n}\n\n");
    }
    out
}

/// Compile-time assertions pinning the codec structs to the offsets the table
/// assumes. If a struct's layout shifts, the build fails until codegen reruns.
pub fn asserts_rs(structs: &[ArenaStruct]) -> String {
    let mut out = String::from(HEADER_RS);
    let names = structs
        .iter()
        .map(|s| s.rust)
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(out, "use crate::mdast::codec::{{{names}}};");
    out.push_str("use satteri_arena::StringRef;\n\n");
    out.push_str("const _: () = {\n");
    out.push_str("    assert!(core::mem::size_of::<StringRef>() == 8);\n");
    for s in structs {
        let _ = writeln!(
            out,
            "    assert!(core::mem::size_of::<{}>() == {});",
            s.rust, s.size
        );
        for (field, offset) in s.offsets {
            let _ = writeln!(
                out,
                "    assert!(core::mem::offset_of!({}, {field}) == {offset});",
                s.rust
            );
        }
    }
    out.push_str("};\n");
    out
}

fn ts_field(f: &crate::schema::Field) -> String {
    let mut parts = vec![format!("js: {:?}", f.js), format!("offset: {}", f.offset)];
    parts.push(format!(
        "kind: {:?}",
        match f.wire {
            Wire::Str16 => "str16",
            Wire::Str32 => "str32",
            Wire::U8 => "u8",
        }
    ));
    match f.js_kind {
        Js::StrNull => parts.push("nullable: true".to_string()),
        Js::Enum(values) => {
            let list = values
                .iter()
                .map(|v| format!("{v:?}"))
                .collect::<Vec<_>>()
                .join(", ");
            parts.push(format!("values: [{list}]"));
        }
        Js::Skip => parts.push("skip: true".to_string()),
        Js::Str | Js::Num | Js::Const(_) => {}
    }
    if f.phantom {
        parts.push("phantom: true".to_string());
    }
    format!("{{ {} }}", parts.join(", "))
}

/// TS name maps generated from the registry: `TYPE_NAMES` (tag -> name),
/// `NAME_TO_TYPE` (name -> tag), and `VISITOR_KEYS` (visitable names, i.e. every
/// node except `root`).
pub fn node_types_ts(nodes: &[Node]) -> String {
    let mut out = String::from(HEADER_TS);
    out.push_str("/** Node-type tag -> canonical AST name. */\n");
    out.push_str("export const TYPE_NAMES: Readonly<Record<number, string>> = {\n");
    for node in nodes {
        let _ = writeln!(out, "  {}: {:?},", node.tag, node.name);
    }
    out.push_str("};\n\n");
    out.push_str("/** Canonical AST name -> node-type tag. */\n");
    out.push_str("export const NAME_TO_TYPE: Readonly<Record<string, number>> = {\n");
    for node in nodes {
        let _ = writeln!(out, "  {:?}: {},", node.name, node.tag);
    }
    out.push_str("};\n\n");
    out.push_str("/** Names a plugin can subscribe to (every node except `root`). */\n");
    out.push_str("export const VISITOR_KEYS: ReadonlySet<string> = new Set([\n");
    for node in nodes.iter().filter(|n| n.name != "root") {
        let _ = writeln!(out, "  {:?},", node.name);
    }
    out.push_str("]);\n");
    out
}

/// The TS walk-path decoder: a descriptor table plus one generic loop that
/// replaces the hand-written per-type `switch` in `readMdastMatchedNode`.
pub fn layout_ts(layouts: &[Layout]) -> String {
    let mut out = String::from(HEADER_TS);
    out.push_str("import { ru16, ru32, rstr } from \"../wire-read.js\";\n");
    out.push_str("import { restorePhantomSpaces } from \"../../phantom.js\";\n");
    out.push_str("import { lazyGroup } from \"../../lazy-props.js\";\n");
    out.push_str("import type { MdastReader } from \"../mdast-reader.js\";\n\n");
    out.push_str("type FieldKind = \"str16\" | \"str32\" | \"u8\";\n\n");
    out.push_str("interface LayoutField {\n");
    out.push_str("  readonly js: string;\n");
    out.push_str("  readonly offset: number;\n");
    out.push_str("  readonly kind: FieldKind;\n");
    out.push_str("  readonly nullable?: boolean;\n");
    out.push_str("  readonly values?: readonly string[];\n");
    out.push_str("  readonly skip?: boolean;\n");
    out.push_str("  readonly phantom?: boolean;\n");
    out.push_str("}\n\n");
    out.push_str(
        "/** Walk-wire fields per node-type tag (see Rust `write_mdast_type_data_inline`). */\n",
    );
    out.push_str("const MDAST_LAYOUTS: Readonly<Record<number, readonly LayoutField[]>> = {\n");
    for layout in layouts {
        let fields = layout
            .fields
            .iter()
            .filter(|f| !matches!(f.js_kind, Js::Const(_)))
            .map(ts_field)
            .collect::<Vec<_>>()
            .join(", ");
        for tag in &layout.tags {
            let _ = writeln!(out, "  {tag}: [{fields}],");
        }
    }
    out.push_str("};\n\n");
    out.push_str(DECODER_TS);
    out.push_str(STORED_DECODER_TS);
    out
}

/// The generic decoder is type-agnostic, so it is emitted verbatim — its only
/// per-type input is `MDAST_LAYOUTS` above.
const DECODER_TS: &str = r#"/**
 * Decode a node's type-specific `type_data` from the walk buffer onto `node`,
 * driven entirely by `MDAST_LAYOUTS`. Returns `false` for tags with no entry, so
 * the caller falls through to the hand-written cases (list, table, directives,
 * MDX JSX).
 */
export function decodeMdastTypeData(
  view: DataView,
  buf: Uint8Array,
  start: number,
  nodeType: number,
  node: Record<string, unknown>,
): boolean {
  const fields = MDAST_LAYOUTS[nodeType];
  if (fields === undefined) return false;
  let pos = start;
  for (const f of fields) {
    if (f.kind === "u8") {
      const b = buf[pos]!;
      pos += 1;
      if (f.skip) continue;
      node[f.js] = f.values ? (f.values[b] ?? f.values[0]) : b;
    } else {
      const len = f.kind === "str32" ? ru32(view, pos) : ru16(view, pos);
      pos += f.kind === "str32" ? 4 : 2;
      const raw = rstr(buf, pos, len);
      pos += len;
      if (f.skip) continue;
      node[f.js] = f.nullable && len === 0 ? null : f.phantom ? restorePhantomSpaces(raw) : raw;
    }
  }
  return true;
}
"#;

/// The arena-snapshot decoder: the same `MDAST_LAYOUTS`, but resolving each
/// `StringRef` from the string pool instead of reading an inline wire. Replaces
/// the per-type getters in `mdast-reader.ts` and their `lazyGroup` wiring.
const STORED_DECODER_TS: &str = r#"
/**
 * Attach a node's fixed `type_data` fields, materialized from the arena
 * snapshot, driven by `MDAST_LAYOUTS`. Returns `false` for tags with no entry,
 * so the materializer falls through to its hand-written cases (list, table,
 * directives, MDX JSX). Fields resolve lazily on first access.
 */
export function materializeMdastFields(
  reader: MdastReader,
  node: object,
  nodeId: number,
  nodeType: number,
): boolean {
  const fields = MDAST_LAYOUTS[nodeType];
  if (fields === undefined) return false;
  const keys = fields.filter((f) => !f.skip).map((f) => f.js);
  lazyGroup(node, keys, () => {
    const data = reader.getTypeData(nodeId);
    const out: Record<string, unknown> = {};
    for (const f of fields) {
      if (f.kind === "u8") {
        const b = data[f.offset] ?? 0;
        if (!f.skip) out[f.js] = f.values ? (f.values[b] ?? f.values[0]) : b;
      } else {
        const ref = reader.readStringRef(data, f.offset);
        if (f.skip) continue;
        const s = f.nullable && ref.len === 0 ? null : reader.getString(ref.offset, ref.len);
        out[f.js] = f.phantom && typeof s === "string" ? restorePhantomSpaces(s) : s;
      }
    }
    return out;
  });
  return true;
}
"#;
