//! Emitter: pack [`property_schema`] into relocation-free lookup tables.
//!
//! A `&'static str` in a `static` table costs a relocation record and a pointer
//! slot, so rows are keyed by `(offset, length)` into one packed blob instead.

use std::fmt::Write as _;

use crate::property_schema::Row;

const HEADER_RS: &str = "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\
     //!\n\
     //! Source of truth: `crates/satteri-layout-codegen/src/property_schema.rs`.\n\n";

/// Lays each distinct name down once, longest first so shorter ones can reuse
/// a span inside one already written.
fn pack(tables: &[&[Row]]) -> (String, Vec<(String, usize)>) {
    let mut distinct: Vec<&str> = tables
        .iter()
        .flat_map(|rows| {
            rows.iter()
                .flat_map(|(name, prop, attr, _)| [*name, *prop, *attr])
        })
        .collect();
    distinct.sort_unstable();
    distinct.dedup();
    distinct.sort_by_key(|s| (std::cmp::Reverse(s.len()), *s));

    let mut blob = String::new();
    let mut offsets: Vec<(String, usize)> = Vec::new();
    for text in distinct {
        let at = blob.find(text).unwrap_or_else(|| {
            blob.push_str(text);
            blob.len() - text.len()
        });
        offsets.push((text.to_string(), at));
    }
    offsets.sort_by(|a, b| a.0.cmp(&b.0));
    (blob, offsets)
}

fn offset_of(offsets: &[(String, usize)], text: &str) -> usize {
    let at = offsets
        .binary_search_by(|probe| probe.0.as_str().cmp(text))
        .unwrap_or_else(|_| panic!("{text} missing from the packed blob"));
    offsets[at].1
}

fn table(out: &mut String, name: &str, rows: &[Row], offsets: &[(String, usize)]) {
    let _ = write!(
        out,
        "\n/// Sorted by name for binary search.\npub(crate) static {name}: &[Row] = &[\n"
    );
    for (key, property, attribute, class) in rows {
        let _ = writeln!(
            out,
            "    ({}, {}, {}, {}, {}, {}, {}), // {key}",
            offset_of(offsets, key),
            key.len(),
            offset_of(offsets, property),
            property.len(),
            offset_of(offsets, attribute),
            attribute.len(),
            class.code(),
        );
    }
    out.push_str("];\n");
}

pub fn property_tables_rs(html: &[Row], svg: &[Row]) -> String {
    let (blob, offsets) = pack(&[html, svg]);
    assert!(blob.len() < u16::MAX as usize, "blob outgrew u16 offsets");
    assert!(
        [html, svg]
            .iter()
            .flat_map(|rows| rows.iter())
            .all(|(k, p, a, _)| k.len() < 256 && p.len() < 256 && a.len() < 256),
        "a name outgrew its u8 length"
    );

    let mut out = String::from(HEADER_RS);
    out.push_str("/// Every distinct name, property, and attribute, overlapped where one is a\n");
    out.push_str("/// substring of another.\npub(crate) static STRINGS: &str = \"");
    for (i, chunk) in blob.as_bytes().chunks(96).enumerate() {
        if i > 0 {
            out.push_str("\\\n    ");
        }
        out.push_str(std::str::from_utf8(chunk).expect("chunk splits a code point"));
    }
    out.push_str("\";\n\n");
    out.push_str(
        "/// `(name, property, attribute)` as `(offset, length)` pairs into [`STRINGS`],\n",
    );
    out.push_str("/// then the coercion class.\n");
    out.push_str("pub(crate) type Row = (u16, u8, u16, u8, u16, u8, u8);\n");

    table(&mut out, "HTML_TABLE", html, &offsets);
    table(&mut out, "SVG_TABLE", svg, &offsets);
    out
}
