//! Emitters: turn the [`schema`] table into Rust and TS source.

use std::fmt::Write as _;

use crate::schema::{
    ArenaStruct, Field, Js, Layout, Node, SetSlot, Slot, Tail, TailJs, TailLayout, Wire, WireTable,
};

const HEADER_RS: &str =
    "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n";
const HEADER_TS: &str =
    "// @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n";

fn tag_pattern(tags: &[u8]) -> String {
    tags.iter()
        .map(u8::to_string)
        .collect::<Vec<_>>()
        .join(" | ")
}

/// One wire-field write statement, or `None` for an encode-only const byte.
/// `off` is an offset expression: a literal for fixed layouts and tail heads,
/// `base`-relative for tail items.
fn wire_stmt(f: &crate::schema::Field, off: &str) -> Option<String> {
    // Const fields are stored but never crossed over the wire.
    if matches!(f.js_kind, Js::Const(_)) {
        return None;
    }
    Some(match f.wire {
        Wire::Str16 => format!("write_str16(arena, out, type_data, {off});"),
        Wire::Str32 => format!("write_str32(arena, out, type_data, {off});"),
        Wire::U8 => {
            let cond = if off == "0" {
                "!type_data.is_empty()".to_string()
            } else {
                format!("type_data.len() > {off}")
            };
            format!(
                "out.push(if {cond} {{ type_data[{off}] }} else {{ {} }});",
                f.u8_default
            )
        }
    })
}

/// The Rust walk-path serializer: resolve each fixed field — and, for tail
/// nodes, the head + clamped count + per-item fields — from `type_data` onto
/// the inline wire. Returns `false` for tags it does not own, so the caller
/// can fall through to the hand-written arms (raw-byte tails, generic blob).
pub fn walk_rs(fn_name: &str, kind: &str, layouts: &[Layout], tails: &[TailLayout]) -> String {
    let mut out = String::from(HEADER_RS);
    let _ = writeln!(
        out,
        "use crate::walk::{{write_str16, write_str32}};\nuse satteri_arena::{{Arena, {kind}}};\n",
    );
    out.push_str("/// Serialize a node's `type_data` to the walk wire. `true` if handled here.\n");
    out.push_str("#[allow(clippy::manual_range_patterns)]\n");
    let _ = writeln!(
        out,
        "pub(crate) fn {fn_name}(\n    arena: &Arena<{kind}>,\n    node_type: u8,\n    type_data: &[u8],\n    out: &mut Vec<u8>,\n) -> bool {{\n    match node_type {{",
    );
    for layout in layouts {
        let _ = writeln!(out, "        {} => {{", tag_pattern(&layout.tags));
        for f in layout.fields {
            if let Some(line) = wire_stmt(f, &f.offset.to_string()) {
                let _ = writeln!(out, "            {line}");
            }
        }
        out.push_str("        }\n");
    }
    for t in tails {
        let tail = &t.tail;
        let _ = writeln!(out, "        {} => {{", tag_pattern(&t.tags));
        for f in tail.head {
            if let Some(line) = wire_stmt(f, &f.offset.to_string()) {
                let _ = writeln!(out, "            {line}");
            }
        }
        let _ = writeln!(
            out,
            "            if type_data.len() >= {} {{",
            tail.items_offset
        );
        let _ = writeln!(
            out,
            "                let stored = u32::from_le_bytes(type_data[{}..{}].try_into().unwrap());",
            tail.count_offset,
            tail.count_offset + 4
        );
        out.push_str(
            "                // Clamp like write_str16: an oversized list truncates visibly\n\
             \x20               // instead of wrapping the u16 count prefix.\n\
             \x20               let count = (stored as usize).min(u16::MAX as usize);\n\
             \x20               out.extend_from_slice(&(count as u16).to_le_bytes());\n\
             \x20               for i in 0..count {\n",
        );
        // Single-byte items (table align) have stride 1; emit `+ i` so clippy
        // doesn't flag the `i * 1` identity op.
        if tail.stride == 1 {
            let _ = writeln!(
                out,
                "                    let base = {} + i;",
                tail.items_offset
            );
        } else {
            let _ = writeln!(
                out,
                "                    let base = {} + i * {};",
                tail.items_offset, tail.stride
            );
        }
        for f in tail.item {
            let off = if f.offset == 0 {
                "base".to_string()
            } else {
                format!("base + {}", f.offset)
            };
            if let Some(line) = wire_stmt(f, &off) {
                let _ = writeln!(out, "                    {line}");
            }
        }
        out.push_str(
            "                }\n\
             \x20           } else {\n\
             \x20               out.extend_from_slice(&0u16.to_le_bytes());\n\
             \x20           }\n",
        );
        out.push_str("        }\n");
    }
    out.push_str("        _ => return false,\n    }\n    true\n}\n");
    out
}

fn remap_arm(out: &mut String, layouts: &[Layout], tails: &[TailLayout]) {
    for layout in layouts {
        let refs: Vec<&Field> = layout
            .fields
            .iter()
            .filter(|f| matches!(f.wire, Wire::Str16 | Wire::Str32))
            .collect();
        if refs.is_empty() {
            continue;
        }
        let _ = writeln!(out, "        {} => {{", tag_pattern(&layout.tags));
        for f in &refs {
            let _ = writeln!(out, "            remap_ref(data, {}, remap);", f.offset);
        }
        out.push_str("        }\n");
    }
    for t in tails {
        let tail = &t.tail;
        let head_refs: Vec<&Field> = tail
            .head
            .iter()
            .filter(|f| matches!(f.wire, Wire::Str16 | Wire::Str32))
            .collect();
        let item_refs: Vec<&Field> = tail
            .item
            .iter()
            .filter(|f| matches!(f.wire, Wire::Str16 | Wire::Str32))
            .collect();
        if head_refs.is_empty() && item_refs.is_empty() {
            continue;
        }
        let _ = writeln!(out, "        {} => {{", tag_pattern(&t.tags));
        for f in &head_refs {
            let _ = writeln!(out, "            remap_ref(data, {}, remap);", f.offset);
        }
        if !item_refs.is_empty() {
            let _ = writeln!(out, "            if data.len() >= {} {{", tail.items_offset);
            let _ = writeln!(
                out,
                "                let stored = u32::from_le_bytes(data[{}..{}].try_into().unwrap()) as usize;",
                tail.count_offset,
                tail.count_offset + 4
            );
            let _ = writeln!(
                out,
                "                let count = stored.min((data.len() - {}) / {});",
                tail.items_offset, tail.stride
            );
            out.push_str("                for i in 0..count {\n");
            let _ = writeln!(
                out,
                "                    let base = {} + i * {};",
                tail.items_offset, tail.stride
            );
            for f in &item_refs {
                if f.offset == 0 {
                    out.push_str("                    remap_ref(data, base, remap);\n");
                } else {
                    let _ = writeln!(
                        out,
                        "                    remap_ref(data, base + {}, remap);",
                        f.offset
                    );
                }
            }
            out.push_str("                }\n            }\n");
        }
        out.push_str("        }\n");
    }
}

/// The serialize-time StringRef byte-to-UTF-16 remap over a wire `type_data` copy.
pub fn remap_refs_rs(
    mdast_layouts: &[Layout],
    mdast_tails: &[TailLayout],
    hast_layouts: &[Layout],
    hast_tails: &[TailLayout],
) -> String {
    let mut out = String::from(HEADER_RS);
    out.push_str(
        "/// Both ends of a ref sit on char boundaries, so the UTF-16 remap is exact; absent optional fields are out of bounds and left untouched.\n\
         fn remap_ref(data: &mut [u8], off: usize, remap: &mut dyn FnMut(u32) -> u32) {\n\
         \x20   let Some(bytes) = data.get_mut(off..off + 8) else {\n\
         \x20       return;\n\
         \x20   };\n\
         \x20   let start = u32::from_le_bytes(bytes[0..4].try_into().unwrap());\n\
         \x20   let len = u32::from_le_bytes(bytes[4..8].try_into().unwrap());\n\
         \x20   let new_start = remap(start);\n\
         \x20   let new_len = remap(start + len) - new_start;\n\
         \x20   bytes[0..4].copy_from_slice(&new_start.to_le_bytes());\n\
         \x20   bytes[4..8].copy_from_slice(&new_len.to_le_bytes());\n\
         }\n\n",
    );
    for (fn_name, layouts, tails) in [
        ("remap_mdast_string_refs", mdast_layouts, mdast_tails),
        ("remap_hast_string_refs", hast_layouts, hast_tails),
    ] {
        let _ = writeln!(
            out,
            "/// Remap every StringRef in one node's wire `type_data` blob.\n\
             #[allow(clippy::manual_range_patterns)]\n\
             pub(crate) fn {fn_name}(node_type: u8, data: &mut [u8], remap: &mut dyn FnMut(u32) -> u32) {{\n\
             \x20   match node_type {{",
        );
        remap_arm(&mut out, layouts, tails);
        out.push_str("        _ => {}\n    }\n}\n\n");
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

/// The node-type discriminant enum plus `from_u8` / `name`, generated from the
/// registry so the tag <-> variant <-> name mapping is declared exactly once.
pub fn node_types_rs(enum_name: &str, nodes: &[Node]) -> String {
    let mut out = String::from(HEADER_RS);
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n#[repr(u8)]\n");
    let _ = writeln!(out, "pub enum {enum_name} {{");
    for node in nodes {
        let _ = writeln!(out, "    {} = {},", node.variant, node.tag);
    }
    out.push_str("}\n\n");
    let _ = writeln!(out, "impl {enum_name} {{");
    out.push_str("    pub fn from_u8(v: u8) -> Option<Self> {\n        match v {\n");
    for node in nodes {
        let _ = writeln!(
            out,
            "            {} => Some({enum_name}::{}),",
            node.tag, node.variant
        );
    }
    out.push_str("            _ => None,\n        }\n    }\n\n");
    out.push_str("    /// The canonical type name, as used in the public AST and diagnostics.\n");
    out.push_str("    pub fn name(self) -> &'static str {\n        match self {\n");
    for node in nodes {
        let _ = writeln!(
            out,
            "            {enum_name}::{} => {:?},",
            node.variant, node.name
        );
    }
    out.push_str("        }\n    }\n\n");
    out.push_str("    /// The node type for an AST name, or `None` if unrecognized.\n");
    out.push_str("    pub fn from_name(name: &str) -> Option<Self> {\n        Some(match name {\n");
    for node in nodes {
        let _ = writeln!(
            out,
            "            {:?} => {enum_name}::{},",
            node.name, node.variant
        );
    }
    out.push_str("            _ => return None,\n        })\n    }\n}\n");
    out
}

/// SCREAMING_SNAKE of a camelCase field name (`referenceType` -> `REFERENCE_TYPE`).
fn screaming(js: &str) -> String {
    let mut out = String::new();
    for ch in js.chars() {
        if ch.is_ascii_uppercase() {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

/// One field's encode statement, or `None` for a `skip` field (left zero).
/// Reads from the op-stream collector `c` (the only structural encoder).
fn encode_stmt(f: &crate::schema::Field) -> Option<String> {
    let str_src = |name: &str| format!("c.strs[OF_{} as usize]", screaming(name));
    let end = f.offset + 8;
    match f.js_kind {
        Js::Str | Js::StrNull => Some(format!(
            "let r = alloc_opt_str(builder, {});\n            buf[{}..{end}].copy_from_slice(&r.as_bytes());",
            str_src(f.js),
            f.offset,
        )),
        Js::Num => {
            let v = format!("c.{}.unwrap_or({})", f.js, f.u8_default);
            Some(format!("buf[{}] = {v};", f.offset))
        }
        Js::Enum(values) => {
            // Byte = index in the declared value list; unknown/missing falls back
            // to 0 (the first entry), matching the TS decoder's `values[0]`.
            let arms = values
                .iter()
                .enumerate()
                .skip(1)
                .map(|(i, v)| format!("Some({v:?}) => {i},\n                "))
                .collect::<String>();
            Some(format!(
                "buf[{}] = match {} {{\n                {arms}_ => 0,\n            }};",
                f.offset,
                str_src(f.js),
            ))
        }
        Js::Const(v) => Some(format!("buf[{}] = {v};", f.offset)),
        Js::Skip => None,
    }
}

/// Emit one tail-encoder function (`FieldCollector`/`HastFieldCollector` ->
/// bytes). `is_hast` selects the head source: mdast reads the head string from
/// `c.strs[OF_*]`, hast from `c.tag`.
fn emit_tail_encoder(
    out: &mut String,
    fn_name: &str,
    collector: &str,
    kind: &str,
    tails: &[&TailLayout],
    is_hast: bool,
) {
    let _ = writeln!(
        out,
        "\n/// Encode a tail node's `type_data` from an op-stream collector, or `None`\n/// for tags with no generated tail (the remaining hand-written arms).\n#[allow(clippy::manual_range_patterns)]\npub(crate) fn {fn_name}(\n    c: &{collector},\n    node_type: u8,\n    builder: &mut ArenaBuilder<{kind}>,\n) -> Option<Vec<u8>> {{\n    match node_type {{",
    );
    for t in tails {
        let mdast_head = || {
            format!(
                "let head = alloc_opt_str(builder, c.strs[OF_{} as usize]);",
                screaming(t.tail.head[0].js)
            )
        };
        match t.tail.js {
            Some(TailJs::Map { codec, .. }) => {
                let _ = writeln!(out, "        {} => {{", tag_pattern(&t.tags));
                let _ = writeln!(out, "            {}", mdast_head());
                out.push_str("            let mut items = Vec::with_capacity(c.props.len());\n");
                out.push_str("            for &(key, _kind, value) in &c.props {\n");
                out.push_str(
                    "                items.push((builder.alloc_string(key), builder.alloc_string(value)));\n",
                );
                out.push_str("            }\n");
                let _ = writeln!(out, "            Some({codec}(head, &items))");
                out.push_str("        }\n");
            }
            Some(TailJs::JsxAttrs { codec, .. }) => {
                out.push_str("        #[cfg(feature = \"mdx\")]\n");
                let _ = writeln!(out, "        {} => {{", tag_pattern(&t.tags));
                if is_hast {
                    out.push_str(
                        "            let head = builder.alloc_string(c.tag.unwrap_or(\"\"));\n",
                    );
                } else {
                    let _ = writeln!(out, "            {}", mdast_head());
                }
                out.push_str("            let attrs = intern_mdx_jsx_attrs(&c.props, builder);\n");
                let _ = writeln!(
                    out,
                    "            Some({codec}(head, &attrs, c.explicit.unwrap_or(false)))"
                );
                out.push_str("        }\n");
            }
            Some(TailJs::ElementProps { codec, .. }) => {
                let _ = writeln!(out, "        {} => {{", tag_pattern(&t.tags));
                out.push_str(
                    "            let tag = builder.alloc_string(c.tag.unwrap_or(\"div\"));\n",
                );
                out.push_str("            let mut props = Vec::with_capacity(c.props.len());\n");
                out.push_str("            for &(name, kind, value) in &c.props {\n");
                out.push_str("                let n = builder.alloc_string(name);\n");
                out.push_str("                let v = if kind == PROP_BOOL_TRUE || kind == PROP_BOOL_FALSE {\n");
                out.push_str("                    StringRef::empty()\n");
                out.push_str("                } else {\n");
                out.push_str("                    builder.alloc_string(value)\n");
                out.push_str("                };\n");
                out.push_str("                props.push((n, kind, v));\n");
                out.push_str("            }\n");
                let _ = writeln!(out, "            Some({codec}(tag, &props))");
                out.push_str("        }\n");
            }
            Some(TailJs::ByteList { codec, .. }) => {
                let _ = writeln!(out, "        {} => {{", tag_pattern(&t.tags));
                out.push_str("            let aligns: Vec<ColumnAlign> = c\n");
                out.push_str("                .align\n");
                out.push_str("                .unwrap_or(&[])\n");
                out.push_str("                .iter()\n");
                out.push_str(
                    "                .map(|&b| ColumnAlign::from_u8(b).unwrap_or(ColumnAlign::None))\n",
                );
                out.push_str("                .collect();\n");
                let _ = writeln!(out, "            Some({codec}(&aligns))");
                out.push_str("        }\n");
            }
            None => {}
        }
    }
    out.push_str("        _ => None,\n    }\n}\n");
}

/// The op-stream arena encoders (collector -> bytes), generated per type from
/// the registry. Emitted as `plugin-api/src/generated/encode.rs` and imported
/// by `js_commands.rs`; writes bytes directly at the registry offsets.
pub fn encode_rs(
    layouts: &[Layout],
    mdast_tails: &[TailLayout],
    hast_tails: &[TailLayout],
) -> String {
    let mut ofs: Vec<String> = Vec::new();
    for layout in layouts {
        for f in layout.fields {
            let name = match f.js_kind {
                Js::Str | Js::StrNull | Js::Enum(_) => screaming(f.js),
                _ => continue,
            };
            let of = format!("OF_{name}");
            if !ofs.contains(&of) {
                ofs.push(of);
            }
        }
    }
    // mdast tail encoders read the head string from `c.strs[OF_*]` (hast reads
    // `c.tag`, so its head needs no OF constant).
    let mdast_js_tails: Vec<&TailLayout> =
        mdast_tails.iter().filter(|t| t.tail.js.is_some()).collect();
    let hast_js_tails: Vec<&TailLayout> =
        hast_tails.iter().filter(|t| t.tail.js.is_some()).collect();
    for t in &mdast_js_tails {
        // `ByteList` (table) is head-less, so it contributes no OF constant.
        if let Some(f) = t.tail.head.first() {
            let of = format!("OF_{}", screaming(f.js));
            if !ofs.contains(&of) {
                ofs.push(of);
            }
        }
    }
    ofs.sort();

    // Codecs split by source module and `mdx` gating: Map / ByteList ->
    // mdast::codec, ElementProps -> hast::codec (all ungated), JsxAttrs ->
    // mdast::codec (`mdx`-gated, with `intern_mdx_jsx_attrs`).
    let mut mdast_codecs: Vec<&str> = Vec::new();
    let mut hast_codecs: Vec<&str> = Vec::new();
    let mut mdx_codecs: Vec<&str> = Vec::new();
    let mut has_element_props = false;
    for t in mdast_js_tails.iter().chain(&hast_js_tails) {
        match t.tail.js {
            Some(TailJs::Map { codec, .. }) => mdast_codecs.push(codec),
            Some(TailJs::JsxAttrs { codec, .. }) => mdx_codecs.push(codec),
            Some(TailJs::ElementProps { codec, .. }) => {
                hast_codecs.push(codec);
                has_element_props = true;
            }
            Some(TailJs::ByteList { codec, .. }) => {
                mdast_codecs.push(codec);
                mdast_codecs.push("ColumnAlign");
            }
            None => {}
        }
    }
    for v in [&mut mdast_codecs, &mut hast_codecs, &mut mdx_codecs] {
        v.sort();
        v.dedup();
    }

    let mut out = String::from(
        "// @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n",
    );
    let _ = writeln!(
        out,
        "use crate::generated::wire_constants::{{{}}};",
        ofs.join(", ")
    );
    if hast_js_tails.is_empty() {
        out.push_str("use crate::js_commands::{FieldCollector, alloc_opt_str};\n");
    } else {
        out.push_str(
            "use crate::js_commands::{FieldCollector, HastFieldCollector, alloc_opt_str};\n",
        );
    }
    let mut arena_items = vec!["ArenaBuilder", "Mdast"];
    if !hast_js_tails.is_empty() {
        arena_items.push("Hast");
    }
    if has_element_props {
        arena_items.push("StringRef");
    }
    arena_items.sort();
    let _ = writeln!(out, "use satteri_arena::{{{}}};", arena_items.join(", "));
    if !mdast_codecs.is_empty() {
        let _ = writeln!(
            out,
            "use satteri_ast::mdast::codec::{{{}}};",
            mdast_codecs.join(", ")
        );
    }
    if !hast_codecs.is_empty() {
        let _ = writeln!(
            out,
            "use satteri_ast::hast::codec::{{{}}};",
            hast_codecs.join(", ")
        );
    }
    if has_element_props {
        out.push_str("use satteri_ast::shared::{PROP_BOOL_FALSE, PROP_BOOL_TRUE};\n");
    }
    if !mdx_codecs.is_empty() {
        let _ = writeln!(
            out,
            "#[cfg(feature = \"mdx\")]\nuse satteri_ast::mdast::codec::{{{}}};",
            mdx_codecs.join(", ")
        );
        out.push_str("#[cfg(feature = \"mdx\")]\nuse crate::js_commands::intern_mdx_jsx_attrs;\n");
    }
    out.push('\n');

    let max_size = layouts
        .iter()
        .map(|l| crate::schema::layout_size(l.fields))
        .max()
        .unwrap_or(0);
    let _ = writeln!(
        out,
        "/// Largest fixed-field `type_data` layout; callers stack-allocate this much.\npub(crate) const MAX_FIXED_TYPE_DATA: usize = {max_size};\n",
    );
    let _ = writeln!(
        out,
        "/// Encode a node's `type_data` from an op-stream collector into the zeroed\n/// stack buffer `buf`, returning the encoded length; `None` for types whose\n/// variable-length codec stays hand-written.\n#[allow(clippy::manual_range_patterns)]\npub(crate) fn encode_mdast_type_data_from_ops(\n    c: &FieldCollector,\n    node_type: u8,\n    builder: &mut ArenaBuilder<Mdast>,\n    buf: &mut [u8; MAX_FIXED_TYPE_DATA],\n) -> Option<usize> {{\n    Some(match node_type {{",
    );
    for layout in layouts {
        let _ = writeln!(out, "        {} => {{", tag_pattern(&layout.tags));
        for f in layout.fields {
            if let Some(stmt) = encode_stmt(f) {
                let _ = writeln!(out, "            {stmt}");
            }
        }
        let _ = writeln!(
            out,
            "            {}\n        }}",
            crate::schema::layout_size(layout.fields)
        );
    }
    out.push_str("        _ => return None,\n    })\n}\n");

    emit_tail_encoder(
        &mut out,
        "encode_mdast_tail_from_ops",
        "FieldCollector",
        "Mdast",
        &mdast_js_tails,
        false,
    );
    if !hast_js_tails.is_empty() {
        emit_tail_encoder(
            &mut out,
            "encode_hast_tail_from_ops",
            "HastFieldCollector",
            "Hast",
            &hast_js_tails,
            true,
        );
    }
    out
}

fn slot_expr(slot: &SetSlot) -> String {
    let variant = match slot.kind {
        Slot::Str => "Str",
        Slot::U8 => "U8",
        Slot::U32 => "U32",
        Slot::Bool => "Bool",
        Slot::CheckedTri => "CheckedTri",
        Slot::Enum8(_) => unreachable!("Enum8 arms are emitted vertically"),
    };
    format!("MdastPropSlot::{variant} {{ offset: {} }}", slot.offset)
}

/// Intern an Enum8 value list as a generated `const`, returning its name.
fn enum_values_const(
    slot: &SetSlot,
    value_consts: &mut Vec<(String, &'static [&'static str])>,
) -> String {
    let Slot::Enum8(values) = slot.kind else {
        unreachable!()
    };
    let name = format!("{}_VALUES", screaming(slot.js));
    match value_consts.iter().find(|(n, _)| *n == name) {
        Some((_, existing)) => {
            assert!(*existing == values, "enum value-list name clash for {name}")
        }
        None => value_consts.push((name.clone(), values)),
    }
    name
}

/// The MDAST set-property dispatch: a flat `(node_type, name)` match compiled
/// from the registry — non-skip/const fixed fields plus the declared
/// `set_slots`. Emitted as `plugin-api/src/generated/prop_slots.rs` and
/// consumed by `apply_mdast_set_property` (js_commands.rs).
pub fn prop_slots_rs(nodes: &[Node]) -> String {
    struct Group {
        tags: Vec<u8>,
        slots: Vec<SetSlot>,
    }
    let mut groups: Vec<Group> = Vec::new();
    for node in nodes {
        let mut slots: Vec<SetSlot> = Vec::new();
        for f in node.fields {
            let kind = match f.js_kind {
                Js::Str | Js::StrNull => Slot::Str,
                Js::Num => Slot::U8,
                Js::Enum(values) => Slot::Enum8(values),
                // Hidden / encode-only bytes are not settable.
                Js::Skip | Js::Const(_) => continue,
            };
            slots.push(SetSlot {
                js: f.js,
                offset: f.offset,
                kind,
            });
        }
        slots.extend_from_slice(node.set_slots);
        if slots.is_empty() {
            continue;
        }
        for (i, s) in slots.iter().enumerate() {
            assert!(
                slots[..i].iter().all(|p| p.js != s.js),
                "{}: duplicate settable slot {:?}",
                node.name,
                s.js
            );
        }
        match groups.iter_mut().find(|g| g.slots == slots) {
            Some(g) => g.tags.push(node.tag),
            None => groups.push(Group {
                tags: vec![node.tag],
                slots,
            }),
        }
    }

    let mut value_consts: Vec<(String, &'static [&'static str])> = Vec::new();
    let mut arms = String::new();
    for g in &groups {
        let tags = tag_pattern(&g.tags);
        for s in &g.slots {
            // Two-field literals exceed rustfmt's struct_lit_width and go
            // vertical; the single-field kinds stay on one line.
            if let Slot::Enum8(_) = s.kind {
                let name = enum_values_const(s, &mut value_consts);
                let _ = writeln!(
                    arms,
                    "        ({tags}, {:?}) => MdastPropSlot::Enum8 {{\n            offset: {},\n            values: {name},\n        }},",
                    s.js, s.offset
                );
            } else {
                let _ = writeln!(arms, "        ({tags}, {:?}) => {},", s.js, slot_expr(s));
            }
        }
    }

    let mut out = String::from(
        "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n//!\n\
         //! MDAST set-property slot dispatch, compiled from the node registry in\n\
         //! `satteri-layout-codegen/src/schema.rs`: maps a settable `(node_type,\n\
         //! property)` to its stored `type_data` slot.\n\n",
    );
    out.push_str("/// A settable MDAST `type_data` slot, resolved by [`mdast_prop_slot`].\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("pub(crate) enum MdastPropSlot {\n");
    out.push_str("    /// 8-byte `StringRef` written in place.\n");
    out.push_str("    Str { offset: usize },\n");
    out.push_str("    /// Single numeric byte.\n");
    out.push_str("    U8 { offset: usize },\n");
    out.push_str("    /// u32 little-endian scalar.\n");
    out.push_str("    U32 { offset: usize },\n");
    out.push_str("    /// bool byte (0/1).\n");
    out.push_str("    Bool { offset: usize },\n");
    out.push_str("    /// Tri-state checked byte: true=1, false=0, null=2.\n");
    out.push_str("    CheckedTri { offset: usize },\n");
    out.push_str("    /// Byte mapped through an enum value list.\n");
    out.push_str(
        "    Enum8 {\n        offset: usize,\n        values: &'static [&'static str],\n    },\n",
    );
    out.push_str("}\n\n");
    for (name, values) in &value_consts {
        let list = values
            .iter()
            .map(|v| format!("{v:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "const {name}: &[&str] = &[{list}];");
    }
    if !value_consts.is_empty() {
        out.push('\n');
    }
    out.push_str("/// Resolve a settable MDAST property to its stored `type_data` slot.\n");
    out.push_str("#[allow(clippy::manual_range_patterns)]\n");
    out.push_str(
        "pub(crate) fn mdast_prop_slot(node_type: u8, name: &str) -> Option<MdastPropSlot> {\n",
    );
    out.push_str("    Some(match (node_type, name) {\n");
    out.push_str(&arms);
    out.push_str("        _ => return None,\n    })\n}\n");
    out
}

/// Compile-time assertions pinning the codec structs to the offsets the table
/// assumes. If a struct's layout shifts, the build fails until codegen reruns.
/// `codec_path` is the module the struct names import from.
pub fn asserts_rs(codec_path: &str, structs: &[ArenaStruct]) -> String {
    let mut out = String::from(HEADER_RS);
    match structs {
        [single] => {
            let _ = writeln!(out, "use {codec_path}::{};", single.rust);
        }
        _ => {
            let names = structs
                .iter()
                .map(|s| s.rust)
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "use {codec_path}::{{{names}}};");
        }
    }
    out.push_str("use satteri_arena::StringRef;\n\n");
    out.push_str("const _: () = {\n");
    out.push_str("    assert!(core::mem::size_of::<StringRef>() == 8);\n");
    for s in structs {
        let _ = writeln!(
            out,
            "    assert!(core::mem::size_of::<{}>() == {});",
            s.rust, s.size
        );
        for (field, offset) in s.offsets {
            let _ = writeln!(
                out,
                "    assert!(core::mem::offset_of!({}, {field}) == {offset});",
                s.rust
            );
        }
    }
    out.push_str("};\n");
    out
}

fn ts_field(f: &crate::schema::Field) -> String {
    let mut parts = vec![format!("js: {:?}", f.js), format!("offset: {}", f.offset)];
    parts.push(format!(
        "kind: {:?}",
        match f.wire {
            Wire::Str16 => "str16",
            Wire::Str32 => "str32",
            Wire::U8 => "u8",
        }
    ));
    if f.u8_default != 0 {
        parts.push(format!("default: {}", f.u8_default));
    }
    match f.js_kind {
        Js::StrNull => parts.push("nullable: true".to_string()),
        Js::Enum(values) => {
            let list = values
                .iter()
                .map(|v| format!("{v:?}"))
                .collect::<Vec<_>>()
                .join(", ");
            parts.push(format!("values: [{list}]"));
        }
        Js::Skip => parts.push("skip: true".to_string()),
        Js::Str | Js::Num | Js::Const(_) => {}
    }
    if f.phantom {
        parts.push("phantom: true".to_string());
    }
    format!("{{ {} }}", parts.join(", "))
}

/// TS name maps generated from the registry: `TYPE_NAMES` (tag -> name),
/// `NAME_TO_TYPE` (name -> tag), `VISITOR_KEYS` (visitable names, i.e. every
/// node except `root`), and the `{prefix}_OPSTREAM_TYPES` replay set. With
/// `variant_maps`, also the PascalCase `NodeType` / `NodeTypeName` maps that
/// `mdast-reader.ts` re-exports.
pub fn node_types_ts(
    nodes: &[Node],
    prefix: &str,
    opstream_excluded: &[&str],
    variant_maps: bool,
) -> String {
    for ex in opstream_excluded {
        assert!(
            nodes.iter().any(|n| n.name == *ex),
            "op-stream exclusion {ex:?} is not a registry node name"
        );
    }
    let mut out = String::from(HEADER_TS);
    out.push_str("/** Node-type tag -> canonical AST name. */\n");
    out.push_str("export const TYPE_NAMES: Readonly<Record<number, string>> = {\n");
    for node in nodes {
        let _ = writeln!(out, "  {}: {:?},", node.tag, node.name);
    }
    out.push_str("};\n\n");
    out.push_str("/** Canonical AST name -> node-type tag. */\n");
    out.push_str("export const NAME_TO_TYPE: Readonly<Record<string, number>> = {\n");
    for node in nodes {
        let _ = writeln!(out, "  {:?}: {},", node.name, node.tag);
    }
    out.push_str("};\n\n");
    if variant_maps {
        out.push_str("/** Node-type tag by Rust enum variant name. */\n");
        out.push_str("export const NodeType = Object.freeze({\n");
        for node in nodes {
            let _ = writeln!(out, "  {}: {},", node.variant, node.tag);
        }
        out.push_str("} as const);\n\n");
        out.push_str("/** Node-type tag -> Rust variant name (`typeName` diagnostics). */\n");
        out.push_str("export const NodeTypeName: Readonly<Record<number, string>> = {\n");
        for node in nodes {
            let _ = writeln!(out, "  {}: {:?},", node.tag, node.variant);
        }
        out.push_str("};\n\n");
    }
    out.push_str("/** Names a plugin can subscribe to (every node except `root`). */\n");
    out.push_str("export const VISITOR_KEYS: ReadonlySet<string> = new Set([\n");
    for node in nodes.iter().filter(|n| n.name != "root") {
        let _ = writeln!(out, "  {:?},", node.name);
    }
    out.push_str("]);\n\n");
    out.push_str("/** Name -> tag for the types the op-stream can encode; one lookup gates AND\n");
    out.push_str(" *  resolves the emit-path tag. Excluded names (see `*_OPSTREAM_EXCLUDED` in\n");
    out.push_str(" *  schema.rs) have no encoding — the visitor throws for them. */\n");
    let _ = writeln!(
        out,
        "export const {prefix}_OPSTREAM_TYPES: Readonly<Record<string, number>> = {{"
    );
    for node in nodes
        .iter()
        .filter(|n| !opstream_excluded.contains(&n.name))
    {
        let _ = writeln!(out, "  {}: {},", node.name, node.tag);
    }
    out.push_str("};\n\n");
    out.push_str(
        "/** Names of the variable-length `custom` node types (hand-written or\n\
         \x20*  `Tail`-generated codec). The op-stream round-trip oracle asserts it covers\n\
         \x20*  every one, so a forgotten or drifted encode/decode arm fails loudly. */\n",
    );
    let _ = writeln!(
        out,
        "export const {prefix}_CUSTOM_TYPES: readonly string[] = ["
    );
    for node in nodes.iter().filter(|n| n.custom) {
        let _ = writeln!(out, "  {:?},", node.name);
    }
    out.push_str("];\n");
    out
}

/// One walk-wire field descriptor for the generic tail decoder.
fn tail_field_ts(f: &crate::schema::Field) -> String {
    let kind = match f.wire {
        Wire::Str16 => "str16",
        Wire::Str32 => "str32",
        Wire::U8 => "u8",
    };
    let phantom = if f.phantom { ", phantom: true" } else { "" };
    format!("{{ js: {:?}, kind: {kind:?}{phantom} }}", f.js)
}

/// The TS walk-path decoder: a descriptor table plus one generic decode loop.
pub fn layout_ts(layouts: &[Layout], tails: &[TailLayout]) -> String {
    let mut out = String::from(HEADER_TS);
    out.push_str("import { ru16, ru32, rstr } from \"../../wire-read.js\";\n");
    out.push_str("import { restorePhantomSpaces } from \"../../phantom.js\";\n");
    out.push_str("import { decodeMdxJsxAttr } from \"../../mdx-attr.js\";\n");
    out.push_str("import { decodeColumnAlign } from \"../column-align.js\";\n");
    out.push_str("import type { MdastReader } from \"../mdast-reader.js\";\n\n");
    out.push_str("type FieldKind = \"str16\" | \"str32\" | \"u8\";\n\n");
    out.push_str("interface LayoutField {\n");
    out.push_str("  readonly js: string;\n");
    out.push_str("  readonly offset: number;\n");
    out.push_str("  readonly kind: FieldKind;\n");
    out.push_str("  readonly default?: number;\n");
    out.push_str("  readonly nullable?: boolean;\n");
    out.push_str("  readonly values?: readonly string[];\n");
    out.push_str("  readonly skip?: boolean;\n");
    out.push_str("  readonly phantom?: boolean;\n");
    out.push_str("}\n\n");
    out.push_str(
        "/** Walk-wire fields per node-type tag (see Rust `write_mdast_type_data_inline`). */\n",
    );
    out.push_str("const MDAST_LAYOUTS: Readonly<Record<number, readonly LayoutField[]>> = {\n");
    for layout in layouts {
        let fields = layout
            .fields
            .iter()
            .filter(|f| !matches!(f.js_kind, Js::Const(_)))
            .map(ts_field)
            .collect::<Vec<_>>()
            .join(", ");
        for tag in &layout.tags {
            let _ = writeln!(out, "  {tag}: [{fields}],");
        }
    }
    out.push_str("};\n\n");
    out.push_str("/** Materialized property names per tag (the non-skip `js` names above),\n");
    out.push_str(" *  exported for the child-stub field tables. */\n");
    out.push_str(
        "export const MDAST_LAYOUT_KEYS: Readonly<Record<number, readonly string[]>> = {\n",
    );
    for layout in layouts {
        let keys = layout
            .fields
            .iter()
            .filter(|f| !matches!(f.js_kind, Js::Skip | Js::Const(_)))
            .map(|f| format!("{:?}", f.js))
            .collect::<Vec<_>>()
            .join(", ");
        for tag in &layout.tags {
            let _ = writeln!(out, "  {tag}: [{keys}],");
        }
    }
    out.push_str("};\n\n");
    out.push_str(
        "/** Walk-wire tail descriptors (a name head, then a counted item list) for\n\
         \x20*  the variable-length attribute types the generic decoder below handles\n\
         \x20*  without a hand-written case: `map` is a string key/value object\n\
         \x20*  (directives), `jsx` a typed MDX-JSX attribute array. */\n",
    );
    out.push_str("const MDAST_TAILS: Readonly<Record<number, TailDescriptor>> = {\n");
    for t in tails {
        let assembly = match t.tail.js {
            Some(TailJs::Map {
                attrs_key,
                key,
                value,
                ..
            }) => format!("map: {{ attrsKey: {attrs_key:?}, key: {key:?}, value: {value:?} }}"),
            Some(TailJs::JsxAttrs { attrs_key, .. }) => {
                format!("jsx: {{ attrsKey: {attrs_key:?} }}")
            }
            Some(TailJs::ByteList { attrs_key, .. }) => {
                format!("bytes: {{ attrsKey: {attrs_key:?} }}")
            }
            // ElementProps is HAST-only; the hast matched-node decode (the lazy
            // `WalkElement`) stays hand-written, so this generic decoder skips it.
            Some(TailJs::ElementProps { .. }) | None => continue,
        };
        let head = t
            .tail
            .head
            .iter()
            .map(tail_field_ts)
            .collect::<Vec<_>>()
            .join(", ");
        let item = t
            .tail
            .item
            .iter()
            .map(tail_field_ts)
            .collect::<Vec<_>>()
            .join(", ");
        for tag in &t.tags {
            let _ = writeln!(
                out,
                "  {tag}: {{ head: [{head}], item: [{item}], {assembly} }},"
            );
        }
    }
    out.push_str("};\n\n");
    out.push_str(DECODER_PRELUDE_TS);
    out.push_str(&walk_plain_string_fast_path_ts(layouts));
    out.push_str(DECODER_BODY_TS);
    out.push_str(&stored_decoder_ts(layouts));
    out
}

/// One wire-decode call per node for the fused tree materializers, emitted so the hand-written files stay at reader level.
pub fn fused_wire_ts(mdast_nodes: &[Node], hast_nodes: &[Node]) -> String {
    use crate::schema::ARENA_NODE_FIELDS;
    let word = |name: &str| -> usize {
        ARENA_NODE_FIELDS
            .iter()
            .find(|(f, _)| *f == name)
            .expect("known ArenaNode field")
            .1
            / 4
    };
    let p = word("start_offset");
    let pos = [
        word("end_offset") - p,
        word("start_line") - p,
        word("start_column") - p,
        word("end_line") - p,
        word("end_column") - p,
    ];

    let mut enums: Vec<&'static [&'static str]> = Vec::new();
    for node in mdast_nodes.iter().chain(hast_nodes) {
        for field in node.fields {
            if let Js::Enum(values) = field.js_kind
                && !enums.contains(&values)
            {
                enums.push(values);
            }
        }
    }

    let mut out = String::from(HEADER_TS);
    out.push_str(
        "import type { Position } from \"unist\";\n\
         import type { ArenaWire } from \"../types.js\";\n\
         import type { HastProperty } from \"../hast/hast-reader.js\";\n\
         import { decodeElementProp } from \"../hast/element-props.js\";\n\
         import { restorePhantomSpaces } from \"../phantom.js\";\n\
         import { W_START_OFFSET, W_DATA_LEN, W_DATA_OFFSET } from \"./arena-layout.js\";\n\n",
    );
    for (i, values) in enums.iter().enumerate() {
        let list = values
            .iter()
            .map(|v| format!("{v:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "const FUSED_ENUM_{i} = [{list}] as const;");
    }
    if !enums.is_empty() {
        out.push('\n');
    }

    for (fn_name, nodes) in [
        ("readMdastWireNode", mdast_nodes),
        ("readHastWireNode", hast_nodes),
    ] {
        out.push_str(&fused_node_fn(fn_name, nodes, &enums, &pos));
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

fn is_plain_fields(fields: &[Field]) -> bool {
    let significant: Vec<&Field> = fields
        .iter()
        .filter(|f| !matches!(f.js_kind, Js::Const(_) | Js::Skip))
        .collect();
    let [field] = significant.as_slice() else {
        return false;
    };
    field.offset == 0 && !field.phantom && matches!(field.js_kind, Js::Str)
}

/// Position install plus a per-tag straight-line field decode; `false` hands the tag
/// to the caller's reader path (the user-defined node, struct scalars, non-element tails).
fn fused_node_fn(
    fn_name: &str,
    nodes: &[Node],
    enums: &[&'static [&'static str]],
    pos: &[usize; 5],
) -> String {
    let mut field_groups: Vec<(Vec<u8>, &'static [Field])> = Vec::new();
    let mut element_tags: Vec<u8> = Vec::new();
    let mut element_tail: Option<Tail> = None;
    let mut bare_tags: Vec<u8> = Vec::new();
    for node in nodes {
        // The user-defined node keeps its reader path: the hand-written
        // decode renames its stored `name` to the open `node.type`.
        if node.name == "custom" {
            continue;
        }
        if let Some(tail) = node.tail {
            if matches!(tail.js, Some(TailJs::ElementProps { .. })) {
                element_tags.push(node.tag);
                element_tail = Some(tail);
            }
            continue;
        }
        let significant = node
            .fields
            .iter()
            .any(|f| !matches!(f.js_kind, Js::Const(_) | Js::Skip));
        if significant {
            match field_groups.iter_mut().find(|(_, f)| *f == node.fields) {
                Some((tags, _)) => tags.push(node.tag),
                None => field_groups.push((vec![node.tag], node.fields)),
            }
        } else if node.set_slots.is_empty() && !node.custom {
            bare_tags.push(node.tag);
        }
    }
    field_groups.sort_by_key(|(_, fields)| !is_plain_fields(fields));

    let [end_off, start_line, start_col, end_line, end_col] = *pos;
    let mut out = format!(
        "/** Install `position` (a zero start line marks a synthesized node) and the tag's fixed\n\
         \x20*  fields straight off the wire; `false` hands the tag to the caller's reader path. */\n\
         export function {fn_name}(\n\
         \x20 wire: ArenaWire,\n\
         \x20 nodeId: number,\n\
         \x20 nodeType: number,\n\
         \x20 node: object,\n\
         ): boolean {{\n\
         \x20 const {{ u8, u32, pool }} = wire;\n\
         \x20 const w = wire.nodesW + nodeId * wire.strideW;\n\
         \x20 const wp = w + W_START_OFFSET;\n\
         \x20 const startLine = u32[wp + {start_line}] ?? 0;\n\
         \x20 if (startLine !== 0) {{\n\
         \x20   (node as {{ position?: Position }}).position = {{\n\
         \x20     start: {{ offset: u32[wp] ?? 0, line: startLine, column: u32[wp + {start_col}] ?? 0 }},\n\
         \x20     end: {{ offset: u32[wp + {end_off}] ?? 0, line: u32[wp + {end_line}] ?? 0, column: u32[wp + {end_col}] ?? 0 }},\n\
         \x20   }};\n\
         \x20 }}\n\
         \x20 const n = node as Record<string, unknown>;\n\
         \x20 switch (nodeType) {{\n"
    );

    for (tags, fields) in &field_groups {
        for tag in tags {
            let _ = writeln!(out, "    case {tag}:");
        }
        out.push_str("    {\n");
        out.push_str("      const dl = u32[w + W_DATA_LEN] ?? 0;\n");
        out.push_str("      const db = (wire.typeDataB + (u32[w + W_DATA_OFFSET] ?? 0)) >> 2;\n");
        for (i, field) in fields
            .iter()
            .filter(|f| !matches!(f.js_kind, Js::Const(_) | Js::Skip))
            .enumerate()
        {
            out.push_str(&fused_field_stmt(field, i, enums));
        }
        out.push_str("      return true;\n    }\n");
    }

    if let Some(tail) = element_tail {
        for tag in &element_tags {
            let _ = writeln!(out, "    case {tag}:");
        }
        out.push_str(&fused_element_arm(&tail));
    }

    if !bare_tags.is_empty() {
        for tag in &bare_tags {
            let _ = writeln!(out, "    case {tag}:");
        }
        out.push_str("      return true;\n");
    }

    out.push_str("    default:\n      return false;\n  }\n}\n\n");
    out
}

fn word_expr(base: &str, w: usize) -> String {
    if w == 0 {
        base.to_string()
    } else {
        format!("{base} + {w}")
    }
}

fn fused_field_stmt(field: &Field, index: usize, enums: &[&'static [&'static str]]) -> String {
    let js = field.js;
    let off = field.offset;
    if matches!(field.wire, Wire::U8) {
        let d = field.u8_default;
        let read = format!("dl > {off} ? (u8[(db << 2) + {off}] ?? {d}) : {d}");
        return match field.js_kind {
            Js::Enum(values) => {
                let slot = enums.iter().position(|e| *e == values).unwrap_or(0);
                format!(
                    "      const b{index} = {read};\n      n.{js} = FUSED_ENUM_{slot}[b{index}] ?? FUSED_ENUM_{slot}[0];\n"
                )
            }
            _ => format!("      n.{js} = {read};\n"),
        };
    }
    let end = off + 8;
    let idx0 = word_expr("db", off / 4);
    let idx1 = word_expr("db", off / 4 + 1);
    let head = format!("      const o{index} = u32[{idx0}] ?? 0;\n");
    let sub = format!("pool.substring(o{index}, o{index} + (u32[{idx1}] ?? 0))");
    let read = format!("dl >= {end} ? {sub} : \"\"");
    let read = if field.phantom {
        format!("restorePhantomSpaces({read})")
    } else {
        read
    };
    match field.js_kind {
        Js::StrNull => format!(
            "{head}      const s{index} = {read};\n      n.{js} = s{index} === \"\" ? null : s{index};\n"
        ),
        _ => format!("{head}      n.{js} = {read};\n"),
    }
}

fn fused_element_arm(tail: &Tail) -> String {
    let tag0 = word_expr("db", tail.head[0].offset / 4);
    let tag1 = word_expr("db", tail.head[0].offset / 4 + 1);
    let count_word = tail.count_offset / 4;
    let items_word = tail.items_offset / 4;
    let stride_words = tail.stride / 4;
    let min_bytes = tail.items_offset;
    let refs: Vec<&Field> = tail
        .item
        .iter()
        .filter(|f| matches!(f.wire, Wire::Str16 | Wire::Str32))
        .collect();
    let name0 = word_expr("base", refs[0].offset / 4);
    let name1 = word_expr("base", refs[0].offset / 4 + 1);
    let value0 = word_expr("base", refs[1].offset / 4);
    let value1 = word_expr("base", refs[1].offset / 4 + 1);
    let kind_byte = tail
        .item
        .iter()
        .find(|f| matches!(f.wire, Wire::U8))
        .expect("element kind byte")
        .offset;
    format!(
        "    {{\n\
         \x20     const dl = u32[w + W_DATA_LEN] ?? 0;\n\
         \x20     const db = (wire.typeDataB + (u32[w + W_DATA_OFFSET] ?? 0)) >> 2;\n\
         \x20     let tagName = \"\";\n\
         \x20     const properties: Record<string, HastProperty[\"value\"]> = {{}};\n\
         \x20     if (dl >= {min_bytes}) {{\n\
         \x20       const toff = u32[{tag0}] ?? 0;\n\
         \x20       tagName = pool.substring(toff, toff + (u32[{tag1}] ?? 0));\n\
         \x20       const count = u32[{count_expr}] ?? 0;\n\
         \x20       for (let i = 0; i < count; i++) {{\n\
         \x20         const base = db + {items_word} + i * {stride_words};\n\
         \x20         const noff = u32[{name0}] ?? 0;\n\
         \x20         const voff = u32[{value0}] ?? 0;\n\
         \x20         properties[pool.substring(noff, noff + (u32[{name1}] ?? 0))] = decodeElementProp(\n\
         \x20           u8[(base << 2) + {kind_byte}] ?? 0,\n\
         \x20           pool.substring(voff, voff + (u32[{value1}] ?? 0)),\n\
         \x20         );\n\
         \x20       }}\n\
         \x20     }}\n\
         \x20     n.tagName = tagName;\n\
         \x20     n.properties = properties;\n\
         \x20     return true;\n\
         \x20   }}\n",
        count_expr = word_expr("db", count_word),
    )
}

/// Single-`str32` layouts dominate walks; one named store skips the descriptor loop the unoptimized tiers pay for.
fn walk_plain_string_fast_path_ts(layouts: &[Layout]) -> String {
    let mut out = String::new();
    for layout in layouts {
        if !is_plain_string_layout(layout) {
            continue;
        }
        let fields: Vec<&Field> = layout
            .fields
            .iter()
            .filter(|f| !matches!(f.js_kind, Js::Const(_) | Js::Skip))
            .collect();
        let [field] = fields.as_slice() else {
            continue;
        };
        if !matches!(field.wire, Wire::Str32) {
            continue;
        }
        let cond = layout
            .tags
            .iter()
            .map(|t| format!("nodeType === {t}"))
            .collect::<Vec<_>>()
            .join(" || ");
        let js = field.js;
        let _ = writeln!(out, "  if ({cond}) {{");
        out.push_str("    const len = ru32(view, start);\n");
        let _ = writeln!(out, "    node.{js} = rstr(buf, start + 4, len);");
        out.push_str("    return true;\n  }\n");
    }
    out
}

const DECODER_PRELUDE_TS: &str = r#"interface TailField {
  readonly js: string;
  readonly kind: FieldKind;
  readonly phantom?: boolean;
}

interface TailDescriptor {
  readonly head: readonly TailField[];
  readonly item: readonly TailField[];
  // Exactly one assembly is present: `map` for a string key/value object,
  // `jsx` for a typed MDX-JSX attribute array (kind-dispatched per item),
  // `bytes` for an enum-byte array (table column alignment).
  readonly map?: { readonly attrsKey: string; readonly key: string; readonly value: string };
  readonly jsx?: { readonly attrsKey: string };
  readonly bytes?: { readonly attrsKey: string };
}

/**
 * Decode a node's type-specific `type_data` from the walk buffer onto `node`,
 * driven by `MDAST_LAYOUTS` (fixed-field types) and `MDAST_TAILS` (counted
 * attribute lists). Returns `false` for tags in neither, so the caller falls
 * through to the remaining hand-written cases (list, listItem).
 */
export function decodeMdastTypeData(
  view: DataView,
  buf: Uint8Array,
  start: number,
  nodeType: number,
  node: Record<string, unknown>,
): boolean {
"#;

const DECODER_BODY_TS: &str = r#"  const fields = MDAST_LAYOUTS[nodeType];
  if (fields !== undefined) {
    let pos = start;
    for (const f of fields) {
      if (f.kind === "u8") {
        const b = buf[pos]!;
        pos += 1;
        if (f.skip) continue;
        node[f.js] = f.values ? (f.values[b] ?? f.values[0]) : b;
      } else {
        const len = f.kind === "str32" ? ru32(view, pos) : ru16(view, pos);
        pos += f.kind === "str32" ? 4 : 2;
        const raw = rstr(buf, pos, len);
        pos += len;
        if (f.skip) continue;
        node[f.js] = f.nullable && len === 0 ? null : f.phantom ? restorePhantomSpaces(raw) : raw;
      }
    }
    return true;
  }

  const tail = MDAST_TAILS[nodeType];
  if (tail !== undefined) {
    let pos = start;
    // Reads are inlined and advance `pos` in place (no per-field tuple): this
    // runs per attribute item in the matched-node decode path, and the
    // unoptimized tiers CodSpeed measures won't elide the allocation.
    for (const f of tail.head) {
      let value: string | number;
      if (f.kind === "u8") {
        value = buf[pos]!;
        pos += 1;
      } else {
        const len = f.kind === "str32" ? ru32(view, pos) : ru16(view, pos);
        pos += f.kind === "str32" ? 4 : 2;
        const raw = rstr(buf, pos, len);
        pos += len;
        value = f.phantom ? restorePhantomSpaces(raw) : raw;
      }
      // MDX JSX elements carry a nullable name (empty → null); map heads keep it.
      node[f.js] = tail.jsx !== undefined && value === "" ? null : value;
    }
    const count = ru16(view, pos);
    pos += 2;
    const readItem = (): Record<string, string | number> => {
      const item: Record<string, string | number> = {};
      for (const f of tail.item) {
        if (f.kind === "u8") {
          item[f.js] = buf[pos]!;
          pos += 1;
        } else {
          const len = f.kind === "str32" ? ru32(view, pos) : ru16(view, pos);
          pos += f.kind === "str32" ? 4 : 2;
          const raw = rstr(buf, pos, len);
          pos += len;
          item[f.js] = f.phantom ? restorePhantomSpaces(raw) : raw;
        }
      }
      return item;
    };
    if (tail.map !== undefined) {
      const attrs: Record<string, string | number> = {};
      for (let i = 0; i < count; i++) {
        const item = readItem();
        attrs[item[tail.map.key] as string] = item[tail.map.value]!;
      }
      node[tail.map.attrsKey] = attrs;
    } else if (tail.jsx !== undefined) {
      const attrs: ReturnType<typeof decodeMdxJsxAttr>[] = [];
      for (let i = 0; i < count; i++) {
        const item = readItem();
        attrs.push(
          decodeMdxJsxAttr(item.kind as number, item.name as string, item.value as string),
        );
      }
      node[tail.jsx.attrsKey] = attrs;
    } else {
      const align: (string | null)[] = [];
      for (let i = 0; i < count; i++) {
        const item = readItem();
        align.push(decodeColumnAlign(item.align as number));
      }
      node[tail.bytes!.attrsKey] = align;
    }
    return true;
  }

  return false;
}
"#;

/// The arena-snapshot decoder: the same `MDAST_LAYOUTS`, but resolving each
/// `StringRef` from the string pool instead of reading an inline wire.
/// The arena-snapshot decoder: straight-line stores per node type, so each
/// field is a monomorphic write instead of a descriptor-driven polymorphic one.
fn stored_decoder_ts(layouts: &[Layout]) -> String {
    let mut out = String::new();
    let mut enums: Vec<&'static [&'static str]> = Vec::new();
    for layout in layouts {
        for field in layout.fields {
            if let Js::Enum(values) = field.js_kind
                && !enums.contains(&values)
            {
                enums.push(values);
            }
        }
    }
    for (i, values) in enums.iter().enumerate() {
        let list = values
            .iter()
            .map(|v| format!("{v:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "const MDAST_ENUM_{i} = [{list}] as const;");
    }
    if !enums.is_empty() {
        out.push('\n');
    }

    out.push_str(
        "/**\n\
         \x20* Attach a node's fixed `type_data` fields, materialized from the arena\n\
         \x20* snapshot. Returns `false` for tags with no fixed layout, so the\n\
         \x20* materializer falls through to its hand-written cases (list, table,\n\
         \x20* directives, MDX JSX). Fields are eager plain stores.\n\
         \x20*/\n",
    );
    out.push_str("export function materializeMdastFields(\n");
    out.push_str("  reader: MdastReader,\n  node: object,\n  nodeId: number,\n");
    out.push_str("  nodeType: number,\n): boolean {\n");
    out.push_str("  const n = node as Record<string, unknown>;\n");
    out.push_str("  switch (nodeType) {\n");

    // Single plain string first: those tags dominate real documents, and a JS
    // switch is a compare chain before it tiers up.
    let mut ordered: Vec<&Layout> = layouts.iter().collect();
    ordered.sort_by_key(|l| !is_plain_string_layout(l));

    for layout in ordered {
        let fields: Vec<&Field> = layout
            .fields
            .iter()
            .filter(|f| !matches!(f.js_kind, Js::Const(_) | Js::Skip))
            .collect();
        if fields.is_empty() {
            continue;
        }
        for tag in &layout.tags {
            let _ = writeln!(out, "    case {tag}:");
        }
        let needs_block = fields.iter().any(|f| matches!(f.js_kind, Js::StrNull));
        if needs_block {
            out.push_str("    {\n");
        }
        for (i, field) in fields.iter().enumerate() {
            out.push_str(&stored_field_stmt(field, i, &enums));
        }
        out.push_str("      return true;\n");
        if needs_block {
            out.push_str("    }\n");
        }
    }

    out.push_str("    default:\n      return false;\n  }\n}\n");
    out
}

fn is_plain_string_layout(layout: &Layout) -> bool {
    let fields: Vec<&Field> = layout
        .fields
        .iter()
        .filter(|f| !matches!(f.js_kind, Js::Const(_) | Js::Skip))
        .collect();
    let [field] = fields.as_slice() else {
        return false;
    };
    field.offset == 0 && !field.phantom && matches!(field.js_kind, Js::Str)
}

fn stored_field_stmt(field: &Field, index: usize, enums: &[&'static [&'static str]]) -> String {
    let js = field.js;
    let offset = field.offset;
    if matches!(field.wire, Wire::U8) {
        let default = field.u8_default;
        let read = format!("reader.fieldU8(nodeId, {offset}, {default})");
        return match field.js_kind {
            Js::Enum(values) => {
                let slot = enums.iter().position(|e| *e == values).unwrap_or(0);
                format!("      n.{js} = MDAST_ENUM_{slot}[{read}] ?? MDAST_ENUM_{slot}[0];\n")
            }
            _ => format!("      n.{js} = {read};\n"),
        };
    }
    let read = format!("reader.fieldString(nodeId, {offset})");
    let read = if field.phantom {
        format!("restorePhantomSpaces({read})")
    } else {
        read
    };
    match field.js_kind {
        Js::StrNull => {
            let tmp = format!("s{index}");
            format!("      const {tmp} = {read};\n      n.{js} = {tmp} === \"\" ? null : {tmp};\n")
        }
        _ => format!("      n.{js} = {read};\n"),
    }
}

fn wire_value(value: u8, hex: bool) -> String {
    if hex {
        format!("0x{value:02x}")
    } else {
        value.to_string()
    }
}

/// One Rust wire-constants module: each table as a comment block plus
/// `pub const NAME: u8 = …;` lines with trailing operand docs.
pub fn wire_constants_rs(tables: &[&WireTable], module_doc: &[&str]) -> String {
    let mut out = String::from(
        "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n//!\n",
    );
    for line in module_doc {
        let _ = writeln!(out, "//! {line}");
    }
    for table in tables {
        out.push('\n');
        for line in table.doc {
            let _ = writeln!(out, "// {line}");
        }
        for c in table.consts {
            if let Some(cfg) = table.cfg {
                let _ = writeln!(out, "#[cfg({cfg})]");
            }
            let val = wire_value(c.value, table.hex);
            if c.doc.is_empty() {
                let _ = writeln!(out, "pub const {}: u8 = {val};", c.name);
            } else {
                let _ = writeln!(out, "pub const {}: u8 = {val}; // {}", c.name, c.doc);
            }
        }
        // One-past-max of the op-field ids: scratch tables indexed by an OF_*
        // (e.g. `FieldCollector.strs`) size with this so a new field id can
        // never out-index them. The tables are `const`s, so identify OP_FIELDS
        // by its id namespace rather than by address.
        let is_op_fields =
            !table.consts.is_empty() && table.consts.iter().all(|c| c.name.starts_with("OF_"));
        if is_op_fields {
            let count = table.consts.iter().map(|c| c.value).max().unwrap_or(0) as usize + 1;
            let _ = writeln!(
                out,
                "// One past the highest op-field id; sizes per-node field scratch tables."
            );
            let _ = writeln!(out, "pub const OF_FIELD_COUNT: usize = {count};");
        }
    }
    out
}

/// The TS wire-constants module (every table; Rust-only `cfg`s are ignored).
pub fn wire_constants_ts(tables: &[&WireTable]) -> String {
    let mut out = String::from(HEADER_TS);
    out.push_str(
        "// JS<->Rust wire-protocol byte values, declared once in\n\
         // `satteri-layout-codegen/src/schema.rs`. Rust twins live in\n\
         // `satteri-plugin-api/src/generated/wire_constants.rs` and\n\
         // `satteri-ast/src/generated/wire_constants.rs`.\n",
    );
    for table in tables {
        out.push('\n');
        for line in table.doc {
            let _ = writeln!(out, "// {line}");
        }
        for c in table.consts {
            let val = wire_value(c.value, table.hex);
            if c.doc.is_empty() {
                let _ = writeln!(out, "export const {} = {val};", c.name);
            } else {
                let _ = writeln!(out, "export const {} = {val}; // {}", c.name, c.doc);
            }
        }
    }
    out
}

/// Raw-buffer layout for satteri-arena: the header offsets `to_raw_buffer`
/// writes at, plus compile-time asserts pinning the schema-declared
/// `ArenaNode` offsets, kind tags, and magic to the real definitions.
pub fn arena_layout_rs() -> String {
    use crate::schema::{
        ARENA_HEADER_FIELDS, ARENA_KINDS, ARENA_MAGIC, ARENA_NODE_FIELDS, ARENA_NODE_SIZE,
    };
    let mut out = String::from(
        "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n//!\n\
         //! Raw-buffer layout: header offsets for `Arena::to_raw_buffer` and asserts\n\
         //! pinning the schema-declared `ArenaNode` offsets (mirrored by the JS readers\n\
         //! via `packages/satteri/src/generated/arena-layout.ts`) to the real structs.\n\n",
    );
    out.push_str("use crate::kind::{ArenaKind, Hast, Mdast};\nuse crate::node::ArenaNode;\n\n");
    out.push_str("/// Raw-buffer header byte offsets (4-byte fields, in write order).\n");
    out.push_str("pub(crate) mod header {\n");
    for (i, name) in ARENA_HEADER_FIELDS.iter().enumerate() {
        let _ = writeln!(
            out,
            "    pub(crate) const {}: usize = {};",
            name.to_uppercase(),
            i * 4
        );
    }
    let _ = writeln!(
        out,
        "    pub(crate) const SIZE: usize = {};",
        ARENA_HEADER_FIELDS.len() * 4
    );
    out.push_str("}\n\n");
    out.push_str("const _: () = {\n");
    let _ = writeln!(
        out,
        "    assert!(core::mem::size_of::<ArenaNode>() == {ARENA_NODE_SIZE});"
    );
    for (field, offset) in ARENA_NODE_FIELDS {
        let _ = writeln!(
            out,
            "    assert!(core::mem::offset_of!(ArenaNode, {field}) == {offset});"
        );
    }
    let _ = writeln!(
        out,
        "    assert!(u32::from_le_bytes(crate::raw_buffer::BUFFER_MAGIC) == 0x{ARENA_MAGIC:08x});"
    );
    for (kind, tag) in ARENA_KINDS {
        let _ = writeln!(
            out,
            "    assert!(<{kind} as ArenaKind>::KIND_TAG == {tag});"
        );
    }
    out.push_str("};\n");
    out
}

/// The TS twin: `FIELD` / `HEADER` offset tables plus the magic and kind tags,
/// imported by `mdast-reader.ts` and `hast-reader.ts`.
pub fn arena_layout_ts() -> String {
    use crate::schema::{ARENA_HEADER_FIELDS, ARENA_KINDS, ARENA_MAGIC, ARENA_NODE_FIELDS};
    let mut out = String::from(HEADER_TS);
    out.push_str(
        "// Arena raw-buffer layout, declared once in `satteri-layout-codegen/src/schema.rs`.\n\
         // The Rust side is pinned to these offsets by the compile-time asserts in\n\
         // `satteri-arena/src/generated/layout.rs`.\n\n",
    );
    let _ = writeln!(
        out,
        "/** `b\"MDAR\"` magic, read as a little-endian u32. */\nexport const ARENA_MAGIC = 0x{ARENA_MAGIC:08x};\n"
    );
    out.push_str("/** `Arena<K>` kind tags carried in the header's `kind` field. */\n");
    for (kind, tag) in ARENA_KINDS {
        let _ = writeln!(out, "export const KIND_{} = {tag};", kind.to_uppercase());
    }
    out.push('\n');
    out.push_str(
        "/** `ArenaNode` `#[repr(C)]` field byte offsets (u32 fields; `node_type` is a u8). */\n",
    );
    out.push_str("export const FIELD = {\n");
    for (field, offset) in ARENA_NODE_FIELDS {
        let _ = writeln!(out, "  {field}: {offset},");
    }
    out.push_str("} as const;\n\n");
    out.push_str(
        "/** Word (u32) indices of the `FIELD` byte offsets, for readers indexing a `Uint32Array` view of the wire. */\n",
    );
    for (field, offset) in ARENA_NODE_FIELDS {
        if matches!(
            *field,
            "parent"
                | "start_offset"
                | "children_start"
                | "children_count"
                | "data_offset"
                | "data_len"
        ) {
            let _ = writeln!(
                out,
                "export const W_{} = {};",
                field.to_uppercase(),
                offset / 4
            );
        }
    }
    out.push('\n');
    out.push_str("/** Raw-buffer header byte offsets (4-byte fields, u32 LE). */\n");
    out.push_str("export const HEADER = {\n");
    for (i, name) in ARENA_HEADER_FIELDS.iter().enumerate() {
        let _ = writeln!(out, "  {name}: {},", i * 4);
    }
    out.push_str("} as const;\n");
    out
}

/// Compile-time pins tying the schema's parse-option bits to the real
/// `satteri_pulldown_cmark::Options` flags, so the TS twin can never drift.
pub fn parse_options_rs() -> String {
    use crate::schema::PARSE_OPTION_BITS;
    let mut out = String::from(
        "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n//!\n\
         //! Pins the parse-option bits JS packs into `parseOptions` (see\n\
         //! `packages/satteri/src/generated/parse-options.ts`) to the real\n\
         //! `satteri_pulldown_cmark::Options` flags.\n\n",
    );
    out.push_str("use satteri_pulldown_cmark::Options;\n\nconst _: () = {\n");
    for (flag, bit) in PARSE_OPTION_BITS {
        let _ = writeln!(out, "    assert!(Options::{flag}.bits() == 1 << {bit});");
    }
    out.push_str("};\n");
    out
}

/// The TS twin: the parse-option bits `featuresToNative` packs into the single
/// integer the NAPI compile entry points take.
pub fn parse_options_ts() -> String {
    use crate::schema::PARSE_OPTION_BITS;
    let mut out = String::from(HEADER_TS);
    out.push_str(
        "// Parser option bits, declared once in `satteri-layout-codegen/src/schema.rs`.\n\
         // `featuresToNative` packs them into the `parseOptions` integer the NAPI entry\n\
         // points take; the compile-time asserts in\n\
         // `satteri-napi-binding/src/generated/parse_options.rs` pin them to the real\n\
         // `satteri_pulldown_cmark::Options` flags.\n\n",
    );
    for (flag, bit) in PARSE_OPTION_BITS {
        let _ = writeln!(out, "export const {flag} = 1 << {bit};");
    }
    out
}
