//! Emitters: turn the [`schema`] table into Rust and TS source.

use std::fmt::Write as _;

use crate::schema::{ArenaStruct, Js, Layout, Node, Wire, WireTable};

const HEADER_RS: &str =
    "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n";
const HEADER_TS: &str =
    "// @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n";

fn tag_pattern(tags: &[u8]) -> String {
    tags.iter()
        .map(u8::to_string)
        .collect::<Vec<_>>()
        .join(" | ")
}

/// The Rust walk-path serializer: resolve each field from `type_data` onto the
/// inline wire. Returns `false` for tags it does not own, so the caller can fall
/// through to the hand-written arms (list, table, MDX JSX, directives).
pub fn walk_rs(layouts: &[Layout]) -> String {
    let mut out = String::from(HEADER_RS);
    out.push_str(
        "use crate::walk::{write_str16, write_str32};\nuse satteri_arena::{Arena, Mdast};\n\n",
    );
    out.push_str("/// Serialize a node's `type_data` to the walk wire. `true` if handled here.\n");
    out.push_str("#[allow(clippy::manual_range_patterns)]\n");
    out.push_str(
        "pub(crate) fn write_mdast_type_data_inline(\n    arena: &Arena<Mdast>,\n    node_type: u8,\n    type_data: &[u8],\n    out: &mut Vec<u8>,\n) -> bool {\n    match node_type {\n",
    );
    for layout in layouts {
        let _ = writeln!(out, "        {} => {{", tag_pattern(&layout.tags));
        for f in layout.fields {
            // Const fields are stored but never crossed over the wire.
            if matches!(f.js_kind, Js::Const(_)) {
                continue;
            }
            let line = match f.wire {
                Wire::Str16 => format!("write_str16(arena, out, type_data, {});", f.offset),
                Wire::Str32 => format!("write_str32(arena, out, type_data, {});", f.offset),
                Wire::U8 => {
                    let cond = if f.offset == 0 {
                        "!type_data.is_empty()".to_string()
                    } else {
                        format!("type_data.len() > {}", f.offset)
                    };
                    format!(
                        "out.push(if {cond} {{ type_data[{}] }} else {{ {} }});",
                        f.offset, f.u8_default
                    )
                }
            };
            let _ = writeln!(out, "            {line}");
        }
        out.push_str("        }\n");
    }
    out.push_str("        _ => return false,\n    }\n    true\n}\n");
    out
}

/// The node-type discriminant enum plus `from_u8` / `name`, generated from the
/// registry so the tag <-> variant <-> name mapping is declared exactly once.
pub fn node_types_rs(enum_name: &str, nodes: &[Node]) -> String {
    let mut out = String::from(HEADER_RS);
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n#[repr(u8)]\n");
    let _ = writeln!(out, "pub enum {enum_name} {{");
    for node in nodes {
        let _ = writeln!(out, "    {} = {},", node.variant, node.tag);
    }
    out.push_str("}\n\n");
    let _ = writeln!(out, "impl {enum_name} {{");
    out.push_str("    pub fn from_u8(v: u8) -> Option<Self> {\n        match v {\n");
    for node in nodes {
        let _ = writeln!(
            out,
            "            {} => Some({enum_name}::{}),",
            node.tag, node.variant
        );
    }
    out.push_str("            _ => None,\n        }\n    }\n\n");
    out.push_str("    /// The canonical type name, as used in the public AST and diagnostics.\n");
    out.push_str("    pub fn name(self) -> &'static str {\n        match self {\n");
    for node in nodes {
        let _ = writeln!(
            out,
            "            {enum_name}::{} => {:?},",
            node.variant, node.name
        );
    }
    out.push_str("        }\n    }\n\n");
    out.push_str("    /// The node type for an AST name, or `None` if unrecognized.\n");
    out.push_str("    pub fn from_name(name: &str) -> Option<Self> {\n        Some(match name {\n");
    for node in nodes {
        let _ = writeln!(
            out,
            "            {:?} => {enum_name}::{},",
            node.name, node.variant
        );
    }
    out.push_str("            _ => return None,\n        })\n    }\n}\n");
    out
}

/// SCREAMING_SNAKE of a camelCase field name (`referenceType` -> `REFERENCE_TYPE`).
fn screaming(js: &str) -> String {
    let mut out = String::new();
    for ch in js.chars() {
        if ch.is_ascii_uppercase() {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

/// One field's encode statement, or `None` for a `skip` field (left zero).
/// `src` is the value source: `"js"` (a `&JsNode`) or `"ops"` (a `&FieldCollector`).
fn encode_stmt(f: &crate::schema::Field, src: &str) -> Option<String> {
    let str_src = |name: &str| match src {
        "js" => format!("js_node.{}.as_deref()", screaming(name).to_lowercase()),
        _ => format!("c.strs[OF_{} as usize]", screaming(name)),
    };
    let end = f.offset + 8;
    match f.js_kind {
        Js::Str | Js::StrNull => Some(format!(
            "let r = alloc_opt_str(builder, {});\n            buf[{}..{end}].copy_from_slice(&r.as_bytes());",
            str_src(f.js),
            f.offset,
        )),
        Js::Num => {
            let v = match src {
                "js" => format!("js_node.{}.unwrap_or({})", f.js, f.u8_default),
                _ => format!("c.{}.unwrap_or({})", f.js, f.u8_default),
            };
            Some(format!("buf[{}] = {v};", f.offset))
        }
        Js::Enum(values) => {
            // Byte = index in the declared value list; unknown/missing falls back
            // to 0 (the first entry), matching the TS decoder's `values[0]`.
            let arms = values
                .iter()
                .enumerate()
                .skip(1)
                .map(|(i, v)| format!("Some({v:?}) => {i},\n                "))
                .collect::<String>();
            Some(format!(
                "buf[{}] = match {} {{\n                {arms}_ => 0,\n            }};",
                f.offset,
                str_src(f.js),
            ))
        }
        Js::Const(v) => Some(format!("buf[{}] = {v};", f.offset)),
        Js::Skip => None,
    }
}

/// Both arena encoders (`JsNode` -> bytes and op-stream `FieldCollector` -> bytes),
/// generated per type from the registry. Emitted as `plugin-api/src/generated/encode.rs`
/// and imported by `js_commands.rs`; writes bytes directly at the registry offsets.
pub fn encode_rs(layouts: &[Layout]) -> String {
    let mut ofs: Vec<String> = Vec::new();
    for layout in layouts {
        for f in layout.fields {
            let name = match f.js_kind {
                Js::Str | Js::StrNull | Js::Enum(_) => screaming(f.js),
                _ => continue,
            };
            let of = format!("OF_{name}");
            if !ofs.contains(&of) {
                ofs.push(of);
            }
        }
    }
    ofs.sort();

    let mut out = String::from(
        "// @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n",
    );
    let _ = writeln!(
        out,
        "use crate::generated::wire_constants::{{{}}};",
        ofs.join(", ")
    );
    out.push_str("use crate::js_commands::{FieldCollector, alloc_opt_str};\n");
    out.push_str("use satteri_arena::{ArenaBuilder, Mdast};\n");
    out.push_str("use satteri_ast::commands::JsNode;\n\n");
    let max_size = layouts
        .iter()
        .map(|l| crate::schema::layout_size(l.fields))
        .max()
        .unwrap_or(0);
    let _ = writeln!(
        out,
        "/// Largest fixed-field `type_data` layout; callers stack-allocate this much.\npub(crate) const MAX_FIXED_TYPE_DATA: usize = {max_size};\n",
    );
    for (fn_name, param, src) in [
        ("encode_mdast_type_data", "js_node: &JsNode", "js"),
        (
            "encode_mdast_type_data_from_ops",
            "c: &FieldCollector",
            "ops",
        ),
    ] {
        let _ = writeln!(
            out,
            "/// Encode a node's `type_data` from {} into the zeroed stack buffer\n/// `buf`, returning the encoded length; `None` for types whose variable-length\n/// codec stays hand-written.\n#[allow(clippy::manual_range_patterns)]\npub(crate) fn {fn_name}(\n    {param},\n    node_type: u8,\n    builder: &mut ArenaBuilder<Mdast>,\n    buf: &mut [u8; MAX_FIXED_TYPE_DATA],\n) -> Option<usize> {{\n    Some(match node_type {{",
            if src == "js" {
                "a `JsNode`"
            } else {
                "an op-stream collector"
            },
        );
        for layout in layouts {
            let _ = writeln!(out, "        {} => {{", tag_pattern(&layout.tags));
            for f in layout.fields {
                if let Some(stmt) = encode_stmt(f, src) {
                    let _ = writeln!(out, "            {stmt}");
                }
            }
            let _ = writeln!(
                out,
                "            {}\n        }}",
                crate::schema::layout_size(layout.fields)
            );
        }
        out.push_str("        _ => return None,\n    })\n}\n\n");
    }
    out
}

/// Compile-time assertions pinning the codec structs to the offsets the table
/// assumes. If a struct's layout shifts, the build fails until codegen reruns.
pub fn asserts_rs(structs: &[ArenaStruct]) -> String {
    let mut out = String::from(HEADER_RS);
    let names = structs
        .iter()
        .map(|s| s.rust)
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(out, "use crate::mdast::codec::{{{names}}};");
    out.push_str("use satteri_arena::StringRef;\n\n");
    out.push_str("const _: () = {\n");
    out.push_str("    assert!(core::mem::size_of::<StringRef>() == 8);\n");
    for s in structs {
        let _ = writeln!(
            out,
            "    assert!(core::mem::size_of::<{}>() == {});",
            s.rust, s.size
        );
        for (field, offset) in s.offsets {
            let _ = writeln!(
                out,
                "    assert!(core::mem::offset_of!({}, {field}) == {offset});",
                s.rust
            );
        }
    }
    out.push_str("};\n");
    out
}

fn ts_field(f: &crate::schema::Field) -> String {
    let mut parts = vec![format!("js: {:?}", f.js), format!("offset: {}", f.offset)];
    parts.push(format!(
        "kind: {:?}",
        match f.wire {
            Wire::Str16 => "str16",
            Wire::Str32 => "str32",
            Wire::U8 => "u8",
        }
    ));
    match f.js_kind {
        Js::StrNull => parts.push("nullable: true".to_string()),
        Js::Enum(values) => {
            let list = values
                .iter()
                .map(|v| format!("{v:?}"))
                .collect::<Vec<_>>()
                .join(", ");
            parts.push(format!("values: [{list}]"));
        }
        Js::Skip => parts.push("skip: true".to_string()),
        Js::Str | Js::Num | Js::Const(_) => {}
    }
    if f.phantom {
        parts.push("phantom: true".to_string());
    }
    format!("{{ {} }}", parts.join(", "))
}

/// TS name maps generated from the registry: `TYPE_NAMES` (tag -> name),
/// `NAME_TO_TYPE` (name -> tag), `VISITOR_KEYS` (visitable names, i.e. every
/// node except `root`), and the `{prefix}_OPSTREAM_TYPES` replay set. With
/// `variant_maps`, also the PascalCase `NodeType` / `NodeTypeName` maps that
/// `mdast-reader.ts` re-exports.
pub fn node_types_ts(
    nodes: &[Node],
    prefix: &str,
    opstream_excluded: &[&str],
    variant_maps: bool,
) -> String {
    for ex in opstream_excluded {
        assert!(
            nodes.iter().any(|n| n.name == *ex),
            "op-stream exclusion {ex:?} is not a registry node name"
        );
    }
    let mut out = String::from(HEADER_TS);
    out.push_str("/** Node-type tag -> canonical AST name. */\n");
    out.push_str("export const TYPE_NAMES: Readonly<Record<number, string>> = {\n");
    for node in nodes {
        let _ = writeln!(out, "  {}: {:?},", node.tag, node.name);
    }
    out.push_str("};\n\n");
    out.push_str("/** Canonical AST name -> node-type tag. */\n");
    out.push_str("export const NAME_TO_TYPE: Readonly<Record<string, number>> = {\n");
    for node in nodes {
        let _ = writeln!(out, "  {:?}: {},", node.name, node.tag);
    }
    out.push_str("};\n\n");
    if variant_maps {
        out.push_str("/** Node-type tag by Rust enum variant name. */\n");
        out.push_str("export const NodeType = Object.freeze({\n");
        for node in nodes {
            let _ = writeln!(out, "  {}: {},", node.variant, node.tag);
        }
        out.push_str("} as const);\n\n");
        out.push_str("/** Node-type tag -> Rust variant name (`typeName` diagnostics). */\n");
        out.push_str("export const NodeTypeName: Readonly<Record<number, string>> = {\n");
        for node in nodes {
            let _ = writeln!(out, "  {}: {:?},", node.tag, node.variant);
        }
        out.push_str("};\n\n");
    }
    out.push_str("/** Names a plugin can subscribe to (every node except `root`). */\n");
    out.push_str("export const VISITOR_KEYS: ReadonlySet<string> = new Set([\n");
    for node in nodes.iter().filter(|n| n.name != "root") {
        let _ = writeln!(out, "  {:?},", node.name);
    }
    out.push_str("]);\n\n");
    out.push_str("/** Name -> tag for the types the op-stream replay rebuilds byte-identically\n");
    out.push_str(
        " *  to the JSON path; one lookup gates AND resolves the emit-path tag. Excluded\n",
    );
    out.push_str(" *  names fall back to JSON (see `*_OPSTREAM_EXCLUDED` in schema.rs). */\n");
    let _ = writeln!(
        out,
        "export const {prefix}_OPSTREAM_TYPES: Readonly<Record<string, number>> = {{"
    );
    for node in nodes
        .iter()
        .filter(|n| !opstream_excluded.contains(&n.name))
    {
        let _ = writeln!(out, "  {}: {},", node.name, node.tag);
    }
    out.push_str("};\n");
    out
}

/// The TS walk-path decoder: a descriptor table plus one generic loop that
/// replaces the hand-written per-type `switch` in `readMdastMatchedNode`.
pub fn layout_ts(layouts: &[Layout]) -> String {
    let mut out = String::from(HEADER_TS);
    out.push_str("import { ru16, ru32, rstr } from \"../wire-read.js\";\n");
    out.push_str("import { restorePhantomSpaces } from \"../../phantom.js\";\n");
    out.push_str("import { lazyGroup } from \"../../lazy-props.js\";\n");
    out.push_str("import type { MdastReader } from \"../mdast-reader.js\";\n\n");
    out.push_str("type FieldKind = \"str16\" | \"str32\" | \"u8\";\n\n");
    out.push_str("interface LayoutField {\n");
    out.push_str("  readonly js: string;\n");
    out.push_str("  readonly offset: number;\n");
    out.push_str("  readonly kind: FieldKind;\n");
    out.push_str("  readonly nullable?: boolean;\n");
    out.push_str("  readonly values?: readonly string[];\n");
    out.push_str("  readonly skip?: boolean;\n");
    out.push_str("  readonly phantom?: boolean;\n");
    out.push_str("}\n\n");
    out.push_str(
        "/** Walk-wire fields per node-type tag (see Rust `write_mdast_type_data_inline`). */\n",
    );
    out.push_str("const MDAST_LAYOUTS: Readonly<Record<number, readonly LayoutField[]>> = {\n");
    for layout in layouts {
        let fields = layout
            .fields
            .iter()
            .filter(|f| !matches!(f.js_kind, Js::Const(_)))
            .map(ts_field)
            .collect::<Vec<_>>()
            .join(", ");
        for tag in &layout.tags {
            let _ = writeln!(out, "  {tag}: [{fields}],");
        }
    }
    out.push_str("};\n\n");
    out.push_str("/** Materialized property names per tag (the non-skip `js` names above),\n");
    out.push_str(" *  precomputed so `materializeMdastFields` doesn't rebuild them per node. */\n");
    out.push_str("const MDAST_LAYOUT_KEYS: Readonly<Record<number, readonly string[]>> = {\n");
    for layout in layouts {
        let keys = layout
            .fields
            .iter()
            .filter(|f| !matches!(f.js_kind, Js::Skip | Js::Const(_)))
            .map(|f| format!("{:?}", f.js))
            .collect::<Vec<_>>()
            .join(", ");
        for tag in &layout.tags {
            let _ = writeln!(out, "  {tag}: [{keys}],");
        }
    }
    out.push_str("};\n\n");
    out.push_str(DECODER_TS);
    out.push_str(STORED_DECODER_TS);
    out
}

/// The generic decoder is type-agnostic, so it is emitted verbatim — its only
/// per-type input is `MDAST_LAYOUTS` above.
const DECODER_TS: &str = r#"/**
 * Decode a node's type-specific `type_data` from the walk buffer onto `node`,
 * driven entirely by `MDAST_LAYOUTS`. Returns `false` for tags with no entry, so
 * the caller falls through to the hand-written cases (list, table, directives,
 * MDX JSX).
 */
export function decodeMdastTypeData(
  view: DataView,
  buf: Uint8Array,
  start: number,
  nodeType: number,
  node: Record<string, unknown>,
): boolean {
  const fields = MDAST_LAYOUTS[nodeType];
  if (fields === undefined) return false;
  let pos = start;
  for (const f of fields) {
    if (f.kind === "u8") {
      const b = buf[pos]!;
      pos += 1;
      if (f.skip) continue;
      node[f.js] = f.values ? (f.values[b] ?? f.values[0]) : b;
    } else {
      const len = f.kind === "str32" ? ru32(view, pos) : ru16(view, pos);
      pos += f.kind === "str32" ? 4 : 2;
      const raw = rstr(buf, pos, len);
      pos += len;
      if (f.skip) continue;
      node[f.js] = f.nullable && len === 0 ? null : f.phantom ? restorePhantomSpaces(raw) : raw;
    }
  }
  return true;
}
"#;

/// The arena-snapshot decoder: the same `MDAST_LAYOUTS`, but resolving each
/// `StringRef` from the string pool instead of reading an inline wire. Replaces
/// the per-type getters in `mdast-reader.ts` and their `lazyGroup` wiring.
const STORED_DECODER_TS: &str = r#"
/**
 * Attach a node's fixed `type_data` fields, materialized from the arena
 * snapshot, driven by `MDAST_LAYOUTS`. Returns `false` for tags with no entry,
 * so the materializer falls through to its hand-written cases (list, table,
 * directives, MDX JSX). Fields resolve lazily on first access.
 */
export function materializeMdastFields(
  reader: MdastReader,
  node: object,
  nodeId: number,
  nodeType: number,
): boolean {
  const fields = MDAST_LAYOUTS[nodeType];
  if (fields === undefined) return false;
  lazyGroup(node, MDAST_LAYOUT_KEYS[nodeType]!, () => {
    const data = reader.getTypeData(nodeId);
    const out: Record<string, unknown> = {};
    for (const f of fields) {
      if (f.kind === "u8") {
        const b = data[f.offset] ?? 0;
        if (!f.skip) out[f.js] = f.values ? (f.values[b] ?? f.values[0]) : b;
      } else {
        // Short type_data (e.g. a 20-byte ReferenceData-only imageReference)
        // yields an empty ref, mirroring the Rust decoders' bounds checks.
        const ref =
          f.offset + 8 <= data.length ? reader.readStringRef(data, f.offset) : { offset: 0, len: 0 };
        if (f.skip) continue;
        const s = f.nullable && ref.len === 0 ? null : reader.getString(ref.offset, ref.len);
        out[f.js] = f.phantom && typeof s === "string" ? restorePhantomSpaces(s) : s;
      }
    }
    return out;
  });
  return true;
}
"#;

fn wire_value(value: u8, hex: bool) -> String {
    if hex {
        format!("0x{value:02x}")
    } else {
        value.to_string()
    }
}

/// One Rust wire-constants module: each table as a comment block plus
/// `pub const NAME: u8 = …;` lines with trailing operand docs.
pub fn wire_constants_rs(tables: &[&WireTable], module_doc: &[&str]) -> String {
    let mut out = String::from(
        "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n//!\n",
    );
    for line in module_doc {
        let _ = writeln!(out, "//! {line}");
    }
    for table in tables {
        out.push('\n');
        for line in table.doc {
            let _ = writeln!(out, "// {line}");
        }
        for c in table.consts {
            if let Some(cfg) = table.cfg {
                let _ = writeln!(out, "#[cfg({cfg})]");
            }
            let val = wire_value(c.value, table.hex);
            if c.doc.is_empty() {
                let _ = writeln!(out, "pub const {}: u8 = {val};", c.name);
            } else {
                let _ = writeln!(out, "pub const {}: u8 = {val}; // {}", c.name, c.doc);
            }
        }
    }
    out
}

/// The TS wire-constants module (every table; Rust-only `cfg`s are ignored).
pub fn wire_constants_ts(tables: &[&WireTable]) -> String {
    let mut out = String::from(HEADER_TS);
    out.push_str(
        "// JS<->Rust wire-protocol byte values, declared once in\n\
         // `satteri-layout-codegen/src/schema.rs`. Rust twins live in\n\
         // `satteri-plugin-api/src/generated/wire_constants.rs` and\n\
         // `satteri-ast/src/generated/wire_constants.rs`.\n",
    );
    for table in tables {
        out.push('\n');
        for line in table.doc {
            let _ = writeln!(out, "// {line}");
        }
        for c in table.consts {
            let val = wire_value(c.value, table.hex);
            if c.doc.is_empty() {
                let _ = writeln!(out, "export const {} = {val};", c.name);
            } else {
                let _ = writeln!(out, "export const {} = {val}; // {}", c.name, c.doc);
            }
        }
    }
    out
}

/// Raw-buffer layout for satteri-arena: the header offsets `to_raw_buffer`
/// writes at, plus compile-time asserts pinning the schema-declared
/// `ArenaNode` offsets, kind tags, and magic to the real definitions.
pub fn arena_layout_rs() -> String {
    use crate::schema::{
        ARENA_HEADER_FIELDS, ARENA_KINDS, ARENA_MAGIC, ARENA_NODE_FIELDS, ARENA_NODE_SIZE,
    };
    let mut out = String::from(
        "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n//!\n\
         //! Raw-buffer layout: header offsets for `Arena::to_raw_buffer` and asserts\n\
         //! pinning the schema-declared `ArenaNode` offsets (mirrored by the JS readers\n\
         //! via `packages/satteri/src/generated/arena-layout.ts`) to the real structs.\n\n",
    );
    out.push_str("use crate::kind::{ArenaKind, Hast, Mdast};\nuse crate::node::ArenaNode;\n\n");
    out.push_str("/// Raw-buffer header byte offsets (4-byte fields, in write order).\n");
    out.push_str("pub(crate) mod header {\n");
    for (i, name) in ARENA_HEADER_FIELDS.iter().enumerate() {
        let _ = writeln!(
            out,
            "    pub(crate) const {}: usize = {};",
            name.to_uppercase(),
            i * 4
        );
    }
    let _ = writeln!(
        out,
        "    pub(crate) const SIZE: usize = {};",
        ARENA_HEADER_FIELDS.len() * 4
    );
    out.push_str("}\n\n");
    out.push_str("const _: () = {\n");
    let _ = writeln!(
        out,
        "    assert!(core::mem::size_of::<ArenaNode>() == {ARENA_NODE_SIZE});"
    );
    for (field, offset) in ARENA_NODE_FIELDS {
        let _ = writeln!(
            out,
            "    assert!(core::mem::offset_of!(ArenaNode, {field}) == {offset});"
        );
    }
    let _ = writeln!(
        out,
        "    assert!(u32::from_le_bytes(crate::raw_buffer::BUFFER_MAGIC) == 0x{ARENA_MAGIC:08x});"
    );
    for (kind, tag) in ARENA_KINDS {
        let _ = writeln!(
            out,
            "    assert!(<{kind} as ArenaKind>::KIND_TAG == {tag});"
        );
    }
    out.push_str("};\n");
    out
}

/// The TS twin: `FIELD` / `HEADER` offset tables plus the magic and kind tags,
/// imported by `mdast-reader.ts` and `hast-reader.ts`.
pub fn arena_layout_ts() -> String {
    use crate::schema::{ARENA_HEADER_FIELDS, ARENA_KINDS, ARENA_MAGIC, ARENA_NODE_FIELDS};
    let mut out = String::from(HEADER_TS);
    out.push_str(
        "// Arena raw-buffer layout, declared once in `satteri-layout-codegen/src/schema.rs`.\n\
         // The Rust side is pinned to these offsets by the compile-time asserts in\n\
         // `satteri-arena/src/generated/layout.rs`.\n\n",
    );
    let _ = writeln!(
        out,
        "/** `b\"MDAR\"` magic, read as a little-endian u32. */\nexport const ARENA_MAGIC = 0x{ARENA_MAGIC:08x};\n"
    );
    out.push_str("/** `Arena<K>` kind tags carried in the header's `kind` field. */\n");
    for (kind, tag) in ARENA_KINDS {
        let _ = writeln!(out, "export const KIND_{} = {tag};", kind.to_uppercase());
    }
    out.push('\n');
    out.push_str(
        "/** `ArenaNode` `#[repr(C)]` field byte offsets (u32 fields; `node_type` is a u8). */\n",
    );
    out.push_str("export const FIELD = {\n");
    for (field, offset) in ARENA_NODE_FIELDS {
        let _ = writeln!(out, "  {field}: {offset},");
    }
    out.push_str("} as const;\n\n");
    out.push_str("/** Raw-buffer header byte offsets (4-byte fields, u32 LE). */\n");
    out.push_str("export const HEADER = {\n");
    for (i, name) in ARENA_HEADER_FIELDS.iter().enumerate() {
        let _ = writeln!(out, "  {name}: {},", i * 4);
    }
    out.push_str("} as const;\n");
    out
}
