//! Standalone layout/node-type code generator.
//!
//! Reads the node registry in [`schema`] and writes the generated Rust and TS
//! into the `generated/` folders. Run via `pnpm codegen` (or directly with
//! `cargo run -p satteri-layout-codegen`); the output is committed to git and a
//! CI check reruns this and fails on any diff.

mod emit;
mod schema;

use std::fs;
use std::path::{Path, PathBuf};

use schema::{HAST_NODES, MDAST_NODES, MDAST_STRUCTS};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("resolve workspace root");

    let mdast_rs = root.join("crates/satteri-ast/src/mdast/generated");
    let hast_rs = root.join("crates/satteri-ast/src/hast/generated");
    let plugin_rs = root.join("crates/satteri-plugin-api/src/generated");
    let mdast_ts = root.join("packages/satteri/src/mdast/generated");
    for dir in [&mdast_rs, &hast_rs, &plugin_rs, &mdast_ts] {
        fs::create_dir_all(dir).unwrap_or_else(|e| panic!("create {}: {e}", dir.display()));
    }

    let mdast_layouts = schema::layouts(MDAST_NODES);

    // MDAST (Rust)
    write(&mdast_rs.join("mod.rs"), MDAST_MOD_RS);
    write(
        &mdast_rs.join("node_types.rs"),
        &emit::node_types_rs("MdastNodeType", MDAST_NODES),
    );
    write(
        &mdast_rs.join("walk_type_data.rs"),
        &emit::walk_rs(&mdast_layouts),
    );
    write(
        &mdast_rs.join("assert_layouts.rs"),
        &emit::asserts_rs(MDAST_STRUCTS),
    );

    // HAST (Rust)
    write(&hast_rs.join("mod.rs"), HAST_MOD_RS);
    write(
        &hast_rs.join("node_types.rs"),
        &emit::node_types_rs("HastNodeType", HAST_NODES),
    );

    // Plugin-api encoders
    write(&plugin_rs.join("mod.rs"), PLUGIN_MOD_RS);
    write(
        &plugin_rs.join("encode.rs"),
        &emit::encode_rs(&mdast_layouts),
    );

    // MDAST (TS)
    write(
        &mdast_ts.join("node-types.ts"),
        &emit::node_types_ts(MDAST_NODES),
    );
    write(
        &mdast_ts.join("layout.ts"),
        &emit::layout_ts(&mdast_layouts),
    );
}

const MDAST_MOD_RS: &str = "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n\
    pub mod node_types;\npub(crate) mod walk_type_data;\nmod assert_layouts;\n";

const HAST_MOD_RS: &str = "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n\
    pub mod node_types;\n";

const PLUGIN_MOD_RS: &str = "//! @generated by `cargo run -p satteri-layout-codegen`. Do not edit by hand.\n\n\
    pub(crate) mod encode;\n";

/// Write only when the content changed, so an unchanged rerun touches nothing
/// (and reports cleanly in the CI diff check).
fn write(path: &Path, contents: &str) {
    let changed = fs::read_to_string(path)
        .map(|old| old != contents)
        .unwrap_or(true);
    if changed {
        fs::write(path, contents).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
        eprintln!("wrote {}", path.display());
    } else {
        eprintln!("unchanged {}", path.display());
    }
}
