//! The HTML and SVG property tables, in readable form.
//!
//! Ported from [`property-information`]. Edit these tables, then run
//! `pnpm codegen`, which packs them into
//! `crates/satteri-property-info/src/generated/tables.rs`.
//!
//! [`property-information`]: https://github.com/wooorm/property-information

use Class::*;

/// `(normalized name, hast property, HTML/SVG attribute, value coercion)`.
pub type Row = (&'static str, &'static str, &'static str, Class);

/// How an attribute's string value is coerced, mirroring
/// `satteri_property_info::PropKind`.
#[derive(Clone, Copy)]
pub enum Class {
    Text,
    Boolean,
    OverloadedBoolean,
    Number,
    SpaceSeparated,
    CommaSeparated,
    CommaOrSpaceSeparated,
    NumberCommaSeparated,
}

impl Class {
    /// The discriminant `PropKind::from_class` reads back.
    pub fn code(self) -> u8 {
        match self {
            Class::Text => 0,
            Class::Boolean => 1,
            Class::OverloadedBoolean => 2,
            Class::Number => 3,
            Class::SpaceSeparated => 4,
            Class::CommaSeparated => 5,
            Class::CommaOrSpaceSeparated => 6,
            Class::NumberCommaSeparated => 7,
        }
    }
}

/// Sorted by name for binary search.
pub const HTML: &[Row] = &[
    ("abbr", "abbr", "abbr", Text),
    ("accept", "accept", "accept", CommaSeparated),
    (
        "accept-charset",
        "acceptCharset",
        "accept-charset",
        SpaceSeparated,
    ),
    (
        "acceptcharset",
        "acceptCharset",
        "accept-charset",
        SpaceSeparated,
    ),
    ("accesskey", "accessKey", "accesskey", SpaceSeparated),
    ("action", "action", "action", Text),
    ("align", "align", "align", Text),
    ("alink", "aLink", "alink", Text),
    ("allow", "allow", "allow", Text),
    (
        "allowfullscreen",
        "allowFullScreen",
        "allowfullscreen",
        Boolean,
    ),
    (
        "allowpaymentrequest",
        "allowPaymentRequest",
        "allowpaymentrequest",
        Boolean,
    ),
    (
        "allowtransparency",
        "allowTransparency",
        "allowtransparency",
        Text,
    ),
    (
        "allowusermedia",
        "allowUserMedia",
        "allowusermedia",
        Boolean,
    ),
    ("alpha", "alpha", "alpha", Boolean),
    ("alt", "alt", "alt", Text),
    ("archive", "archive", "archive", SpaceSeparated),
    (
        "aria-activedescendant",
        "ariaActiveDescendant",
        "aria-activedescendant",
        Text,
    ),
    ("aria-atomic", "ariaAtomic", "aria-atomic", Text),
    (
        "aria-autocomplete",
        "ariaAutoComplete",
        "aria-autocomplete",
        Text,
    ),
    ("aria-busy", "ariaBusy", "aria-busy", Text),
    ("aria-checked", "ariaChecked", "aria-checked", Text),
    ("aria-colcount", "ariaColCount", "aria-colcount", Number),
    ("aria-colindex", "ariaColIndex", "aria-colindex", Number),
    ("aria-colspan", "ariaColSpan", "aria-colspan", Number),
    (
        "aria-controls",
        "ariaControls",
        "aria-controls",
        SpaceSeparated,
    ),
    ("aria-current", "ariaCurrent", "aria-current", Text),
    (
        "aria-describedby",
        "ariaDescribedBy",
        "aria-describedby",
        SpaceSeparated,
    ),
    ("aria-details", "ariaDetails", "aria-details", Text),
    ("aria-disabled", "ariaDisabled", "aria-disabled", Text),
    (
        "aria-dropeffect",
        "ariaDropEffect",
        "aria-dropeffect",
        SpaceSeparated,
    ),
    (
        "aria-errormessage",
        "ariaErrorMessage",
        "aria-errormessage",
        Text,
    ),
    ("aria-expanded", "ariaExpanded", "aria-expanded", Text),
    ("aria-flowto", "ariaFlowTo", "aria-flowto", SpaceSeparated),
    ("aria-grabbed", "ariaGrabbed", "aria-grabbed", Text),
    ("aria-haspopup", "ariaHasPopup", "aria-haspopup", Text),
    ("aria-hidden", "ariaHidden", "aria-hidden", Text),
    ("aria-invalid", "ariaInvalid", "aria-invalid", Text),
    (
        "aria-keyshortcuts",
        "ariaKeyShortcuts",
        "aria-keyshortcuts",
        Text,
    ),
    ("aria-label", "ariaLabel", "aria-label", Text),
    (
        "aria-labelledby",
        "ariaLabelledBy",
        "aria-labelledby",
        SpaceSeparated,
    ),
    ("aria-level", "ariaLevel", "aria-level", Number),
    ("aria-live", "ariaLive", "aria-live", Text),
    ("aria-modal", "ariaModal", "aria-modal", Text),
    ("aria-multiline", "ariaMultiLine", "aria-multiline", Text),
    (
        "aria-multiselectable",
        "ariaMultiSelectable",
        "aria-multiselectable",
        Text,
    ),
    (
        "aria-orientation",
        "ariaOrientation",
        "aria-orientation",
        Text,
    ),
    ("aria-owns", "ariaOwns", "aria-owns", SpaceSeparated),
    (
        "aria-placeholder",
        "ariaPlaceholder",
        "aria-placeholder",
        Text,
    ),
    ("aria-posinset", "ariaPosInSet", "aria-posinset", Number),
    ("aria-pressed", "ariaPressed", "aria-pressed", Text),
    ("aria-readonly", "ariaReadOnly", "aria-readonly", Text),
    ("aria-relevant", "ariaRelevant", "aria-relevant", Text),
    ("aria-required", "ariaRequired", "aria-required", Text),
    (
        "aria-roledescription",
        "ariaRoleDescription",
        "aria-roledescription",
        SpaceSeparated,
    ),
    ("aria-rowcount", "ariaRowCount", "aria-rowcount", Number),
    ("aria-rowindex", "ariaRowIndex", "aria-rowindex", Number),
    ("aria-rowspan", "ariaRowSpan", "aria-rowspan", Number),
    ("aria-selected", "ariaSelected", "aria-selected", Text),
    ("aria-setsize", "ariaSetSize", "aria-setsize", Number),
    ("aria-sort", "ariaSort", "aria-sort", Text),
    ("aria-valuemax", "ariaValueMax", "aria-valuemax", Number),
    ("aria-valuemin", "ariaValueMin", "aria-valuemin", Number),
    ("aria-valuenow", "ariaValueNow", "aria-valuenow", Number),
    ("aria-valuetext", "ariaValueText", "aria-valuetext", Text),
    (
        "ariaactivedescendant",
        "ariaActiveDescendant",
        "aria-activedescendant",
        Text,
    ),
    ("ariaatomic", "ariaAtomic", "aria-atomic", Text),
    (
        "ariaautocomplete",
        "ariaAutoComplete",
        "aria-autocomplete",
        Text,
    ),
    ("ariabusy", "ariaBusy", "aria-busy", Text),
    ("ariachecked", "ariaChecked", "aria-checked", Text),
    ("ariacolcount", "ariaColCount", "aria-colcount", Number),
    ("ariacolindex", "ariaColIndex", "aria-colindex", Number),
    ("ariacolspan", "ariaColSpan", "aria-colspan", Number),
    (
        "ariacontrols",
        "ariaControls",
        "aria-controls",
        SpaceSeparated,
    ),
    ("ariacurrent", "ariaCurrent", "aria-current", Text),
    (
        "ariadescribedby",
        "ariaDescribedBy",
        "aria-describedby",
        SpaceSeparated,
    ),
    ("ariadetails", "ariaDetails", "aria-details", Text),
    ("ariadisabled", "ariaDisabled", "aria-disabled", Text),
    (
        "ariadropeffect",
        "ariaDropEffect",
        "aria-dropeffect",
        SpaceSeparated,
    ),
    (
        "ariaerrormessage",
        "ariaErrorMessage",
        "aria-errormessage",
        Text,
    ),
    ("ariaexpanded", "ariaExpanded", "aria-expanded", Text),
    ("ariaflowto", "ariaFlowTo", "aria-flowto", SpaceSeparated),
    ("ariagrabbed", "ariaGrabbed", "aria-grabbed", Text),
    ("ariahaspopup", "ariaHasPopup", "aria-haspopup", Text),
    ("ariahidden", "ariaHidden", "aria-hidden", Text),
    ("ariainvalid", "ariaInvalid", "aria-invalid", Text),
    (
        "ariakeyshortcuts",
        "ariaKeyShortcuts",
        "aria-keyshortcuts",
        Text,
    ),
    ("arialabel", "ariaLabel", "aria-label", Text),
    (
        "arialabelledby",
        "ariaLabelledBy",
        "aria-labelledby",
        SpaceSeparated,
    ),
    ("arialevel", "ariaLevel", "aria-level", Number),
    ("arialive", "ariaLive", "aria-live", Text),
    ("ariamodal", "ariaModal", "aria-modal", Text),
    ("ariamultiline", "ariaMultiLine", "aria-multiline", Text),
    (
        "ariamultiselectable",
        "ariaMultiSelectable",
        "aria-multiselectable",
        Text,
    ),
    (
        "ariaorientation",
        "ariaOrientation",
        "aria-orientation",
        Text,
    ),
    ("ariaowns", "ariaOwns", "aria-owns", SpaceSeparated),
    (
        "ariaplaceholder",
        "ariaPlaceholder",
        "aria-placeholder",
        Text,
    ),
    ("ariaposinset", "ariaPosInSet", "aria-posinset", Number),
    ("ariapressed", "ariaPressed", "aria-pressed", Text),
    ("ariareadonly", "ariaReadOnly", "aria-readonly", Text),
    ("ariarelevant", "ariaRelevant", "aria-relevant", Text),
    ("ariarequired", "ariaRequired", "aria-required", Text),
    (
        "ariaroledescription",
        "ariaRoleDescription",
        "aria-roledescription",
        SpaceSeparated,
    ),
    ("ariarowcount", "ariaRowCount", "aria-rowcount", Number),
    ("ariarowindex", "ariaRowIndex", "aria-rowindex", Number),
    ("ariarowspan", "ariaRowSpan", "aria-rowspan", Number),
    ("ariaselected", "ariaSelected", "aria-selected", Text),
    ("ariasetsize", "ariaSetSize", "aria-setsize", Number),
    ("ariasort", "ariaSort", "aria-sort", Text),
    ("ariavaluemax", "ariaValueMax", "aria-valuemax", Number),
    ("ariavaluemin", "ariaValueMin", "aria-valuemin", Number),
    ("ariavaluenow", "ariaValueNow", "aria-valuenow", Number),
    ("ariavaluetext", "ariaValueText", "aria-valuetext", Text),
    ("as", "as", "as", Text),
    ("async", "async", "async", Boolean),
    ("autocapitalize", "autoCapitalize", "autocapitalize", Text),
    (
        "autocomplete",
        "autoComplete",
        "autocomplete",
        SpaceSeparated,
    ),
    ("autocorrect", "autoCorrect", "autocorrect", Text),
    ("autofocus", "autoFocus", "autofocus", Boolean),
    ("autoplay", "autoPlay", "autoplay", Boolean),
    ("autosave", "autoSave", "autosave", Text),
    ("axis", "axis", "axis", Text),
    ("background", "background", "background", Text),
    ("bgcolor", "bgColor", "bgcolor", Text),
    ("blocking", "blocking", "blocking", SpaceSeparated),
    ("border", "border", "border", Number),
    ("bordercolor", "borderColor", "bordercolor", Text),
    ("bottommargin", "bottomMargin", "bottommargin", Number),
    ("capture", "capture", "capture", Text),
    ("cellpadding", "cellPadding", "cellpadding", Text),
    ("cellspacing", "cellSpacing", "cellspacing", Text),
    ("char", "char", "char", Text),
    ("charoff", "charOff", "charoff", Text),
    ("charset", "charSet", "charset", Text),
    ("checked", "checked", "checked", Boolean),
    ("cite", "cite", "cite", Text),
    ("class", "className", "class", SpaceSeparated),
    ("classid", "classId", "classid", Text),
    ("classname", "className", "class", SpaceSeparated),
    ("clear", "clear", "clear", Text),
    ("closedby", "closedBy", "closedby", Text),
    ("code", "code", "code", Text),
    ("codebase", "codeBase", "codebase", Text),
    ("codetype", "codeType", "codetype", Text),
    ("color", "color", "color", Text),
    ("colorspace", "colorSpace", "colorspace", Text),
    ("cols", "cols", "cols", Number),
    ("colspan", "colSpan", "colspan", Number),
    ("command", "command", "command", Text),
    ("commandfor", "commandFor", "commandfor", Text),
    ("compact", "compact", "compact", Boolean),
    ("content", "content", "content", Text),
    (
        "contenteditable",
        "contentEditable",
        "contenteditable",
        Text,
    ),
    ("controls", "controls", "controls", Boolean),
    (
        "controlslist",
        "controlsList",
        "controlslist",
        SpaceSeparated,
    ),
    ("coords", "coords", "coords", NumberCommaSeparated),
    (
        "credentialless",
        "credentialless",
        "credentialless",
        Boolean,
    ),
    ("crossorigin", "crossOrigin", "crossorigin", Text),
    ("data", "data", "data", Text),
    ("datetime", "dateTime", "datetime", Text),
    ("declare", "declare", "declare", Boolean),
    ("decoding", "decoding", "decoding", Text),
    ("default", "default", "default", Boolean),
    ("defer", "defer", "defer", Boolean),
    ("dir", "dir", "dir", Text),
    ("dirname", "dirName", "dirname", Text),
    ("disabled", "disabled", "disabled", Boolean),
    (
        "disablepictureinpicture",
        "disablePictureInPicture",
        "disablepictureinpicture",
        Boolean,
    ),
    (
        "disableremoteplayback",
        "disableRemotePlayback",
        "disableremoteplayback",
        Boolean,
    ),
    ("download", "download", "download", OverloadedBoolean),
    ("draggable", "draggable", "draggable", Text),
    ("enctype", "encType", "enctype", Text),
    ("enterkeyhint", "enterKeyHint", "enterkeyhint", Text),
    ("event", "event", "event", Text),
    ("exportparts", "exportParts", "exportparts", CommaSeparated),
    ("face", "face", "face", Text),
    ("fetchpriority", "fetchPriority", "fetchpriority", Text),
    ("for", "htmlFor", "for", SpaceSeparated),
    ("form", "form", "form", Text),
    ("formaction", "formAction", "formaction", Text),
    ("formenctype", "formEncType", "formenctype", Text),
    ("formmethod", "formMethod", "formmethod", Text),
    (
        "formnovalidate",
        "formNoValidate",
        "formnovalidate",
        Boolean,
    ),
    ("formtarget", "formTarget", "formtarget", Text),
    ("frame", "frame", "frame", Text),
    ("frameborder", "frameBorder", "frameborder", Text),
    ("headers", "headers", "headers", SpaceSeparated),
    ("height", "height", "height", Number),
    ("hidden", "hidden", "hidden", OverloadedBoolean),
    ("high", "high", "high", Number),
    ("href", "href", "href", Text),
    ("hreflang", "hrefLang", "hreflang", Text),
    ("hspace", "hSpace", "hspace", Number),
    ("htmlfor", "htmlFor", "for", SpaceSeparated),
    ("http-equiv", "httpEquiv", "http-equiv", SpaceSeparated),
    ("httpequiv", "httpEquiv", "http-equiv", SpaceSeparated),
    ("id", "id", "id", Text),
    ("imagesizes", "imageSizes", "imagesizes", Text),
    ("imagesrcset", "imageSrcSet", "imagesrcset", Text),
    ("inert", "inert", "inert", Boolean),
    ("inputmode", "inputMode", "inputmode", Text),
    ("integrity", "integrity", "integrity", Text),
    ("is", "is", "is", Text),
    ("ismap", "isMap", "ismap", Boolean),
    ("itemid", "itemId", "itemid", Text),
    ("itemprop", "itemProp", "itemprop", SpaceSeparated),
    ("itemref", "itemRef", "itemref", SpaceSeparated),
    ("itemscope", "itemScope", "itemscope", Boolean),
    ("itemtype", "itemType", "itemtype", SpaceSeparated),
    ("kind", "kind", "kind", Text),
    ("label", "label", "label", Text),
    ("lang", "lang", "lang", Text),
    ("language", "language", "language", Text),
    ("leftmargin", "leftMargin", "leftmargin", Number),
    ("link", "link", "link", Text),
    ("list", "list", "list", Text),
    ("loading", "loading", "loading", Text),
    ("longdesc", "longDesc", "longdesc", Text),
    ("loop", "loop", "loop", Boolean),
    ("low", "low", "low", Number),
    ("lowsrc", "lowSrc", "lowsrc", Text),
    ("manifest", "manifest", "manifest", Text),
    ("marginheight", "marginHeight", "marginheight", Number),
    ("marginwidth", "marginWidth", "marginwidth", Number),
    ("max", "max", "max", Text),
    ("maxlength", "maxLength", "maxlength", Number),
    ("media", "media", "media", Text),
    ("method", "method", "method", Text),
    ("min", "min", "min", Text),
    ("minlength", "minLength", "minlength", Number),
    ("multiple", "multiple", "multiple", Boolean),
    ("muted", "muted", "muted", Boolean),
    ("name", "name", "name", Text),
    ("nohref", "noHref", "nohref", Boolean),
    ("nomodule", "noModule", "nomodule", Boolean),
    ("nonce", "nonce", "nonce", Text),
    ("noresize", "noResize", "noresize", Boolean),
    ("noshade", "noShade", "noshade", Boolean),
    ("novalidate", "noValidate", "novalidate", Boolean),
    ("nowrap", "noWrap", "nowrap", Boolean),
    ("object", "object", "object", Text),
    ("onabort", "onAbort", "onabort", Text),
    ("onafterprint", "onAfterPrint", "onafterprint", Text),
    ("onauxclick", "onAuxClick", "onauxclick", Text),
    ("onbeforematch", "onBeforeMatch", "onbeforematch", Text),
    ("onbeforeprint", "onBeforePrint", "onbeforeprint", Text),
    ("onbeforetoggle", "onBeforeToggle", "onbeforetoggle", Text),
    ("onbeforeunload", "onBeforeUnload", "onbeforeunload", Text),
    ("onblur", "onBlur", "onblur", Text),
    ("oncancel", "onCancel", "oncancel", Text),
    ("oncanplay", "onCanPlay", "oncanplay", Text),
    (
        "oncanplaythrough",
        "onCanPlayThrough",
        "oncanplaythrough",
        Text,
    ),
    ("onchange", "onChange", "onchange", Text),
    ("onclick", "onClick", "onclick", Text),
    ("onclose", "onClose", "onclose", Text),
    ("oncontextlost", "onContextLost", "oncontextlost", Text),
    ("oncontextmenu", "onContextMenu", "oncontextmenu", Text),
    (
        "oncontextrestored",
        "onContextRestored",
        "oncontextrestored",
        Text,
    ),
    ("oncopy", "onCopy", "oncopy", Text),
    ("oncuechange", "onCueChange", "oncuechange", Text),
    ("oncut", "onCut", "oncut", Text),
    ("ondblclick", "onDblClick", "ondblclick", Text),
    ("ondrag", "onDrag", "ondrag", Text),
    ("ondragend", "onDragEnd", "ondragend", Text),
    ("ondragenter", "onDragEnter", "ondragenter", Text),
    ("ondragexit", "onDragExit", "ondragexit", Text),
    ("ondragleave", "onDragLeave", "ondragleave", Text),
    ("ondragover", "onDragOver", "ondragover", Text),
    ("ondragstart", "onDragStart", "ondragstart", Text),
    ("ondrop", "onDrop", "ondrop", Text),
    (
        "ondurationchange",
        "onDurationChange",
        "ondurationchange",
        Text,
    ),
    ("onemptied", "onEmptied", "onemptied", Text),
    ("onended", "onEnded", "onended", Text),
    ("onerror", "onError", "onerror", Text),
    ("onfocus", "onFocus", "onfocus", Text),
    ("onformdata", "onFormData", "onformdata", Text),
    ("onhashchange", "onHashChange", "onhashchange", Text),
    ("oninput", "onInput", "oninput", Text),
    ("oninvalid", "onInvalid", "oninvalid", Text),
    ("onkeydown", "onKeyDown", "onkeydown", Text),
    ("onkeypress", "onKeyPress", "onkeypress", Text),
    ("onkeyup", "onKeyUp", "onkeyup", Text),
    (
        "onlanguagechange",
        "onLanguageChange",
        "onlanguagechange",
        Text,
    ),
    ("onload", "onLoad", "onload", Text),
    ("onloadeddata", "onLoadedData", "onloadeddata", Text),
    (
        "onloadedmetadata",
        "onLoadedMetadata",
        "onloadedmetadata",
        Text,
    ),
    ("onloadend", "onLoadEnd", "onloadend", Text),
    ("onloadstart", "onLoadStart", "onloadstart", Text),
    ("onmessage", "onMessage", "onmessage", Text),
    ("onmessageerror", "onMessageError", "onmessageerror", Text),
    ("onmousedown", "onMouseDown", "onmousedown", Text),
    ("onmouseenter", "onMouseEnter", "onmouseenter", Text),
    ("onmouseleave", "onMouseLeave", "onmouseleave", Text),
    ("onmousemove", "onMouseMove", "onmousemove", Text),
    ("onmouseout", "onMouseOut", "onmouseout", Text),
    ("onmouseover", "onMouseOver", "onmouseover", Text),
    ("onmouseup", "onMouseUp", "onmouseup", Text),
    ("onoffline", "onOffline", "onoffline", Text),
    ("ononline", "onOnline", "ononline", Text),
    ("onpagehide", "onPageHide", "onpagehide", Text),
    ("onpageshow", "onPageShow", "onpageshow", Text),
    ("onpaste", "onPaste", "onpaste", Text),
    ("onpause", "onPause", "onpause", Text),
    ("onplay", "onPlay", "onplay", Text),
    ("onplaying", "onPlaying", "onplaying", Text),
    ("onpopstate", "onPopState", "onpopstate", Text),
    ("onprogress", "onProgress", "onprogress", Text),
    ("onratechange", "onRateChange", "onratechange", Text),
    (
        "onrejectionhandled",
        "onRejectionHandled",
        "onrejectionhandled",
        Text,
    ),
    ("onreset", "onReset", "onreset", Text),
    ("onresize", "onResize", "onresize", Text),
    ("onscroll", "onScroll", "onscroll", Text),
    ("onscrollend", "onScrollEnd", "onscrollend", Text),
    (
        "onsecuritypolicyviolation",
        "onSecurityPolicyViolation",
        "onsecuritypolicyviolation",
        Text,
    ),
    ("onseeked", "onSeeked", "onseeked", Text),
    ("onseeking", "onSeeking", "onseeking", Text),
    ("onselect", "onSelect", "onselect", Text),
    ("onslotchange", "onSlotChange", "onslotchange", Text),
    ("onstalled", "onStalled", "onstalled", Text),
    ("onstorage", "onStorage", "onstorage", Text),
    ("onsubmit", "onSubmit", "onsubmit", Text),
    ("onsuspend", "onSuspend", "onsuspend", Text),
    ("ontimeupdate", "onTimeUpdate", "ontimeupdate", Text),
    ("ontoggle", "onToggle", "ontoggle", Text),
    (
        "onunhandledrejection",
        "onUnhandledRejection",
        "onunhandledrejection",
        Text,
    ),
    ("onunload", "onUnload", "onunload", Text),
    ("onvolumechange", "onVolumeChange", "onvolumechange", Text),
    ("onwaiting", "onWaiting", "onwaiting", Text),
    ("onwheel", "onWheel", "onwheel", Text),
    ("open", "open", "open", Boolean),
    ("optimum", "optimum", "optimum", Number),
    ("part", "part", "part", SpaceSeparated),
    ("pattern", "pattern", "pattern", Text),
    ("ping", "ping", "ping", SpaceSeparated),
    ("placeholder", "placeholder", "placeholder", Text),
    ("playsinline", "playsInline", "playsinline", Boolean),
    ("popover", "popover", "popover", Text),
    ("popovertarget", "popoverTarget", "popovertarget", Text),
    (
        "popovertargetaction",
        "popoverTargetAction",
        "popovertargetaction",
        Text,
    ),
    ("poster", "poster", "poster", Text),
    ("prefix", "prefix", "prefix", Text),
    ("preload", "preload", "preload", Text),
    ("profile", "profile", "profile", Text),
    ("prompt", "prompt", "prompt", Text),
    ("property", "property", "property", Text),
    ("readonly", "readOnly", "readonly", Boolean),
    ("referrerpolicy", "referrerPolicy", "referrerpolicy", Text),
    ("rel", "rel", "rel", SpaceSeparated),
    ("required", "required", "required", Boolean),
    ("results", "results", "results", Number),
    ("rev", "rev", "rev", Text),
    ("reversed", "reversed", "reversed", Boolean),
    ("rightmargin", "rightMargin", "rightmargin", Number),
    ("role", "role", "role", Text),
    ("rows", "rows", "rows", Number),
    ("rowspan", "rowSpan", "rowspan", Number),
    ("rules", "rules", "rules", Text),
    ("sandbox", "sandbox", "sandbox", SpaceSeparated),
    ("scheme", "scheme", "scheme", Text),
    ("scope", "scope", "scope", Text),
    ("scoped", "scoped", "scoped", Boolean),
    ("scrolling", "scrolling", "scrolling", Text),
    ("seamless", "seamless", "seamless", Boolean),
    ("security", "security", "security", Text),
    ("selected", "selected", "selected", Boolean),
    (
        "shadowrootclonable",
        "shadowRootClonable",
        "shadowrootclonable",
        Boolean,
    ),
    (
        "shadowrootcustomelementregistry",
        "shadowRootCustomElementRegistry",
        "shadowrootcustomelementregistry",
        Boolean,
    ),
    (
        "shadowrootdelegatesfocus",
        "shadowRootDelegatesFocus",
        "shadowrootdelegatesfocus",
        Boolean,
    ),
    ("shadowrootmode", "shadowRootMode", "shadowrootmode", Text),
    (
        "shadowrootserializable",
        "shadowRootSerializable",
        "shadowrootserializable",
        Boolean,
    ),
    ("shape", "shape", "shape", Text),
    ("size", "size", "size", Number),
    ("sizes", "sizes", "sizes", Text),
    ("slot", "slot", "slot", Text),
    ("span", "span", "span", Number),
    ("spellcheck", "spellCheck", "spellcheck", Text),
    ("src", "src", "src", Text),
    ("srcdoc", "srcDoc", "srcdoc", Text),
    ("srclang", "srcLang", "srclang", Text),
    ("srcset", "srcSet", "srcset", Text),
    ("standby", "standby", "standby", Text),
    ("start", "start", "start", Number),
    ("step", "step", "step", Text),
    ("style", "style", "style", Text),
    ("summary", "summary", "summary", Text),
    ("tabindex", "tabIndex", "tabindex", Number),
    ("target", "target", "target", Text),
    ("text", "text", "text", Text),
    ("title", "title", "title", Text),
    ("topmargin", "topMargin", "topmargin", Number),
    ("translate", "translate", "translate", Text),
    ("type", "type", "type", Text),
    ("typemustmatch", "typeMustMatch", "typemustmatch", Boolean),
    ("unselectable", "unselectable", "unselectable", Text),
    ("usemap", "useMap", "usemap", Text),
    ("valign", "vAlign", "valign", Text),
    ("value", "value", "value", Text),
    ("valuetype", "valueType", "valuetype", Text),
    ("version", "version", "version", Text),
    ("vlink", "vLink", "vlink", Text),
    ("vspace", "vSpace", "vspace", Number),
    ("width", "width", "width", Number),
    ("wrap", "wrap", "wrap", Text),
    (
        "writingsuggestions",
        "writingSuggestions",
        "writingsuggestions",
        Text,
    ),
    ("xlink:actuate", "xLinkActuate", "xlink:actuate", Text),
    ("xlink:arcrole", "xLinkArcRole", "xlink:arcrole", Text),
    ("xlink:href", "xLinkHref", "xlink:href", Text),
    ("xlink:role", "xLinkRole", "xlink:role", Text),
    ("xlink:show", "xLinkShow", "xlink:show", Text),
    ("xlink:title", "xLinkTitle", "xlink:title", Text),
    ("xlink:type", "xLinkType", "xlink:type", Text),
    ("xlinkactuate", "xLinkActuate", "xlink:actuate", Text),
    ("xlinkarcrole", "xLinkArcRole", "xlink:arcrole", Text),
    ("xlinkhref", "xLinkHref", "xlink:href", Text),
    ("xlinkrole", "xLinkRole", "xlink:role", Text),
    ("xlinkshow", "xLinkShow", "xlink:show", Text),
    ("xlinktitle", "xLinkTitle", "xlink:title", Text),
    ("xlinktype", "xLinkType", "xlink:type", Text),
    ("xml:base", "xmlBase", "xml:base", Text),
    ("xml:lang", "xmlLang", "xml:lang", Text),
    ("xml:space", "xmlSpace", "xml:space", Text),
    ("xmlbase", "xmlBase", "xml:base", Text),
    ("xmllang", "xmlLang", "xml:lang", Text),
    ("xmlns", "xmlns", "xmlns", Text),
    ("xmlns:xlink", "xmlnsXLink", "xmlns:xlink", Text),
    ("xmlnsxlink", "xmlnsXLink", "xmlns:xlink", Text),
    ("xmlspace", "xmlSpace", "xml:space", Text),
];

/// Sorted by name for binary search.
pub const SVG: &[Row] = &[
    ("about", "about", "about", CommaOrSpaceSeparated),
    ("accent-height", "accentHeight", "accent-height", Number),
    ("accentheight", "accentHeight", "accent-height", Number),
    ("accumulate", "accumulate", "accumulate", Text),
    ("additive", "additive", "additive", Text),
    (
        "alignment-baseline",
        "alignmentBaseline",
        "alignment-baseline",
        Text,
    ),
    (
        "alignmentbaseline",
        "alignmentBaseline",
        "alignment-baseline",
        Text,
    ),
    ("alphabetic", "alphabetic", "alphabetic", Number),
    ("amplitude", "amplitude", "amplitude", Number),
    ("arabic-form", "arabicForm", "arabic-form", Text),
    ("arabicform", "arabicForm", "arabic-form", Text),
    (
        "aria-activedescendant",
        "ariaActiveDescendant",
        "aria-activedescendant",
        Text,
    ),
    ("aria-atomic", "ariaAtomic", "aria-atomic", Text),
    (
        "aria-autocomplete",
        "ariaAutoComplete",
        "aria-autocomplete",
        Text,
    ),
    ("aria-busy", "ariaBusy", "aria-busy", Text),
    ("aria-checked", "ariaChecked", "aria-checked", Text),
    ("aria-colcount", "ariaColCount", "aria-colcount", Number),
    ("aria-colindex", "ariaColIndex", "aria-colindex", Number),
    ("aria-colspan", "ariaColSpan", "aria-colspan", Number),
    (
        "aria-controls",
        "ariaControls",
        "aria-controls",
        SpaceSeparated,
    ),
    ("aria-current", "ariaCurrent", "aria-current", Text),
    (
        "aria-describedby",
        "ariaDescribedBy",
        "aria-describedby",
        SpaceSeparated,
    ),
    ("aria-details", "ariaDetails", "aria-details", Text),
    ("aria-disabled", "ariaDisabled", "aria-disabled", Text),
    (
        "aria-dropeffect",
        "ariaDropEffect",
        "aria-dropeffect",
        SpaceSeparated,
    ),
    (
        "aria-errormessage",
        "ariaErrorMessage",
        "aria-errormessage",
        Text,
    ),
    ("aria-expanded", "ariaExpanded", "aria-expanded", Text),
    ("aria-flowto", "ariaFlowTo", "aria-flowto", SpaceSeparated),
    ("aria-grabbed", "ariaGrabbed", "aria-grabbed", Text),
    ("aria-haspopup", "ariaHasPopup", "aria-haspopup", Text),
    ("aria-hidden", "ariaHidden", "aria-hidden", Text),
    ("aria-invalid", "ariaInvalid", "aria-invalid", Text),
    (
        "aria-keyshortcuts",
        "ariaKeyShortcuts",
        "aria-keyshortcuts",
        Text,
    ),
    ("aria-label", "ariaLabel", "aria-label", Text),
    (
        "aria-labelledby",
        "ariaLabelledBy",
        "aria-labelledby",
        SpaceSeparated,
    ),
    ("aria-level", "ariaLevel", "aria-level", Number),
    ("aria-live", "ariaLive", "aria-live", Text),
    ("aria-modal", "ariaModal", "aria-modal", Text),
    ("aria-multiline", "ariaMultiLine", "aria-multiline", Text),
    (
        "aria-multiselectable",
        "ariaMultiSelectable",
        "aria-multiselectable",
        Text,
    ),
    (
        "aria-orientation",
        "ariaOrientation",
        "aria-orientation",
        Text,
    ),
    ("aria-owns", "ariaOwns", "aria-owns", SpaceSeparated),
    (
        "aria-placeholder",
        "ariaPlaceholder",
        "aria-placeholder",
        Text,
    ),
    ("aria-posinset", "ariaPosInSet", "aria-posinset", Number),
    ("aria-pressed", "ariaPressed", "aria-pressed", Text),
    ("aria-readonly", "ariaReadOnly", "aria-readonly", Text),
    ("aria-relevant", "ariaRelevant", "aria-relevant", Text),
    ("aria-required", "ariaRequired", "aria-required", Text),
    (
        "aria-roledescription",
        "ariaRoleDescription",
        "aria-roledescription",
        SpaceSeparated,
    ),
    ("aria-rowcount", "ariaRowCount", "aria-rowcount", Number),
    ("aria-rowindex", "ariaRowIndex", "aria-rowindex", Number),
    ("aria-rowspan", "ariaRowSpan", "aria-rowspan", Number),
    ("aria-selected", "ariaSelected", "aria-selected", Text),
    ("aria-setsize", "ariaSetSize", "aria-setsize", Number),
    ("aria-sort", "ariaSort", "aria-sort", Text),
    ("aria-valuemax", "ariaValueMax", "aria-valuemax", Number),
    ("aria-valuemin", "ariaValueMin", "aria-valuemin", Number),
    ("aria-valuenow", "ariaValueNow", "aria-valuenow", Number),
    ("aria-valuetext", "ariaValueText", "aria-valuetext", Text),
    (
        "ariaactivedescendant",
        "ariaActiveDescendant",
        "aria-activedescendant",
        Text,
    ),
    ("ariaatomic", "ariaAtomic", "aria-atomic", Text),
    (
        "ariaautocomplete",
        "ariaAutoComplete",
        "aria-autocomplete",
        Text,
    ),
    ("ariabusy", "ariaBusy", "aria-busy", Text),
    ("ariachecked", "ariaChecked", "aria-checked", Text),
    ("ariacolcount", "ariaColCount", "aria-colcount", Number),
    ("ariacolindex", "ariaColIndex", "aria-colindex", Number),
    ("ariacolspan", "ariaColSpan", "aria-colspan", Number),
    (
        "ariacontrols",
        "ariaControls",
        "aria-controls",
        SpaceSeparated,
    ),
    ("ariacurrent", "ariaCurrent", "aria-current", Text),
    (
        "ariadescribedby",
        "ariaDescribedBy",
        "aria-describedby",
        SpaceSeparated,
    ),
    ("ariadetails", "ariaDetails", "aria-details", Text),
    ("ariadisabled", "ariaDisabled", "aria-disabled", Text),
    (
        "ariadropeffect",
        "ariaDropEffect",
        "aria-dropeffect",
        SpaceSeparated,
    ),
    (
        "ariaerrormessage",
        "ariaErrorMessage",
        "aria-errormessage",
        Text,
    ),
    ("ariaexpanded", "ariaExpanded", "aria-expanded", Text),
    ("ariaflowto", "ariaFlowTo", "aria-flowto", SpaceSeparated),
    ("ariagrabbed", "ariaGrabbed", "aria-grabbed", Text),
    ("ariahaspopup", "ariaHasPopup", "aria-haspopup", Text),
    ("ariahidden", "ariaHidden", "aria-hidden", Text),
    ("ariainvalid", "ariaInvalid", "aria-invalid", Text),
    (
        "ariakeyshortcuts",
        "ariaKeyShortcuts",
        "aria-keyshortcuts",
        Text,
    ),
    ("arialabel", "ariaLabel", "aria-label", Text),
    (
        "arialabelledby",
        "ariaLabelledBy",
        "aria-labelledby",
        SpaceSeparated,
    ),
    ("arialevel", "ariaLevel", "aria-level", Number),
    ("arialive", "ariaLive", "aria-live", Text),
    ("ariamodal", "ariaModal", "aria-modal", Text),
    ("ariamultiline", "ariaMultiLine", "aria-multiline", Text),
    (
        "ariamultiselectable",
        "ariaMultiSelectable",
        "aria-multiselectable",
        Text,
    ),
    (
        "ariaorientation",
        "ariaOrientation",
        "aria-orientation",
        Text,
    ),
    ("ariaowns", "ariaOwns", "aria-owns", SpaceSeparated),
    (
        "ariaplaceholder",
        "ariaPlaceholder",
        "aria-placeholder",
        Text,
    ),
    ("ariaposinset", "ariaPosInSet", "aria-posinset", Number),
    ("ariapressed", "ariaPressed", "aria-pressed", Text),
    ("ariareadonly", "ariaReadOnly", "aria-readonly", Text),
    ("ariarelevant", "ariaRelevant", "aria-relevant", Text),
    ("ariarequired", "ariaRequired", "aria-required", Text),
    (
        "ariaroledescription",
        "ariaRoleDescription",
        "aria-roledescription",
        SpaceSeparated,
    ),
    ("ariarowcount", "ariaRowCount", "aria-rowcount", Number),
    ("ariarowindex", "ariaRowIndex", "aria-rowindex", Number),
    ("ariarowspan", "ariaRowSpan", "aria-rowspan", Number),
    ("ariaselected", "ariaSelected", "aria-selected", Text),
    ("ariasetsize", "ariaSetSize", "aria-setsize", Number),
    ("ariasort", "ariaSort", "aria-sort", Text),
    ("ariavaluemax", "ariaValueMax", "aria-valuemax", Number),
    ("ariavaluemin", "ariaValueMin", "aria-valuemin", Number),
    ("ariavaluenow", "ariaValueNow", "aria-valuenow", Number),
    ("ariavaluetext", "ariaValueText", "aria-valuetext", Text),
    ("ascent", "ascent", "ascent", Number),
    ("attributename", "attributeName", "attributeName", Text),
    ("attributetype", "attributeType", "attributeType", Text),
    ("azimuth", "azimuth", "azimuth", Number),
    ("bandwidth", "bandwidth", "bandwidth", Text),
    ("basefrequency", "baseFrequency", "baseFrequency", Text),
    ("baseline-shift", "baselineShift", "baseline-shift", Text),
    ("baselineshift", "baselineShift", "baseline-shift", Text),
    ("baseprofile", "baseProfile", "baseProfile", Text),
    ("bbox", "bbox", "bbox", Text),
    ("begin", "begin", "begin", Text),
    ("bias", "bias", "bias", Number),
    ("by", "by", "by", Text),
    ("calcmode", "calcMode", "calcMode", Text),
    ("cap-height", "capHeight", "cap-height", Number),
    ("capheight", "capHeight", "cap-height", Number),
    ("class", "className", "class", SpaceSeparated),
    ("classname", "className", "class", SpaceSeparated),
    ("clip", "clip", "clip", Text),
    ("clip-path", "clipPath", "clip-path", Text),
    ("clip-rule", "clipRule", "clip-rule", Text),
    ("clippath", "clipPath", "clip-path", Text),
    ("clippathunits", "clipPathUnits", "clipPathUnits", Text),
    ("cliprule", "clipRule", "clip-rule", Text),
    ("color", "color", "color", Text),
    (
        "color-interpolation",
        "colorInterpolation",
        "color-interpolation",
        Text,
    ),
    (
        "color-interpolation-filters",
        "colorInterpolationFilters",
        "color-interpolation-filters",
        Text,
    ),
    ("color-profile", "colorProfile", "color-profile", Text),
    ("color-rendering", "colorRendering", "color-rendering", Text),
    (
        "colorinterpolation",
        "colorInterpolation",
        "color-interpolation",
        Text,
    ),
    (
        "colorinterpolationfilters",
        "colorInterpolationFilters",
        "color-interpolation-filters",
        Text,
    ),
    ("colorprofile", "colorProfile", "color-profile", Text),
    ("colorrendering", "colorRendering", "color-rendering", Text),
    ("content", "content", "content", Text),
    (
        "contentscripttype",
        "contentScriptType",
        "contentScriptType",
        Text,
    ),
    (
        "contentstyletype",
        "contentStyleType",
        "contentStyleType",
        Text,
    ),
    ("crossorigin", "crossOrigin", "crossorigin", Text),
    ("cursor", "cursor", "cursor", Text),
    ("cx", "cx", "cx", Text),
    ("cy", "cy", "cy", Text),
    ("d", "d", "d", Text),
    ("datatype", "dataType", "datatype", Text),
    ("defaultaction", "defaultAction", "defaultAction", Text),
    ("descent", "descent", "descent", Number),
    (
        "diffuseconstant",
        "diffuseConstant",
        "diffuseConstant",
        Number,
    ),
    ("direction", "direction", "direction", Text),
    ("display", "display", "display", Text),
    ("divisor", "divisor", "divisor", Number),
    (
        "dominant-baseline",
        "dominantBaseline",
        "dominant-baseline",
        Text,
    ),
    (
        "dominantbaseline",
        "dominantBaseline",
        "dominant-baseline",
        Text,
    ),
    ("download", "download", "download", Boolean),
    ("dur", "dur", "dur", Text),
    ("dx", "dx", "dx", Text),
    ("dy", "dy", "dy", Text),
    ("edgemode", "edgeMode", "edgeMode", Text),
    ("editable", "editable", "editable", Text),
    ("elevation", "elevation", "elevation", Number),
    (
        "enable-background",
        "enableBackground",
        "enable-background",
        Text,
    ),
    (
        "enablebackground",
        "enableBackground",
        "enable-background",
        Text,
    ),
    ("end", "end", "end", Text),
    ("event", "event", "event", Text),
    ("exponent", "exponent", "exponent", Number),
    (
        "externalresourcesrequired",
        "externalResourcesRequired",
        "externalResourcesRequired",
        Text,
    ),
    ("fill", "fill", "fill", Text),
    ("fill-opacity", "fillOpacity", "fill-opacity", Number),
    ("fill-rule", "fillRule", "fill-rule", Text),
    ("fillopacity", "fillOpacity", "fill-opacity", Number),
    ("fillrule", "fillRule", "fill-rule", Text),
    ("filter", "filter", "filter", Text),
    ("filterres", "filterRes", "filterRes", Text),
    ("filterunits", "filterUnits", "filterUnits", Text),
    ("flood-color", "floodColor", "flood-color", Text),
    ("flood-opacity", "floodOpacity", "flood-opacity", Text),
    ("floodcolor", "floodColor", "flood-color", Text),
    ("floodopacity", "floodOpacity", "flood-opacity", Text),
    ("focusable", "focusable", "focusable", Text),
    ("focushighlight", "focusHighlight", "focusHighlight", Text),
    ("font-family", "fontFamily", "font-family", Text),
    ("font-size", "fontSize", "font-size", Text),
    (
        "font-size-adjust",
        "fontSizeAdjust",
        "font-size-adjust",
        Text,
    ),
    ("font-stretch", "fontStretch", "font-stretch", Text),
    ("font-style", "fontStyle", "font-style", Text),
    ("font-variant", "fontVariant", "font-variant", Text),
    ("font-weight", "fontWeight", "font-weight", Text),
    ("fontfamily", "fontFamily", "font-family", Text),
    ("fontsize", "fontSize", "font-size", Text),
    ("fontsizeadjust", "fontSizeAdjust", "font-size-adjust", Text),
    ("fontstretch", "fontStretch", "font-stretch", Text),
    ("fontstyle", "fontStyle", "font-style", Text),
    ("fontvariant", "fontVariant", "font-variant", Text),
    ("fontweight", "fontWeight", "font-weight", Text),
    ("format", "format", "format", Text),
    ("fr", "fr", "fr", Text),
    ("from", "from", "from", Text),
    ("fx", "fx", "fx", Text),
    ("fy", "fy", "fy", Text),
    ("g1", "g1", "g1", CommaSeparated),
    ("g2", "g2", "g2", CommaSeparated),
    ("glyph-name", "glyphName", "glyph-name", CommaSeparated),
    (
        "glyph-orientation-horizontal",
        "glyphOrientationHorizontal",
        "glyph-orientation-horizontal",
        Text,
    ),
    (
        "glyph-orientation-vertical",
        "glyphOrientationVertical",
        "glyph-orientation-vertical",
        Text,
    ),
    ("glyphname", "glyphName", "glyph-name", CommaSeparated),
    (
        "glyphorientationhorizontal",
        "glyphOrientationHorizontal",
        "glyph-orientation-horizontal",
        Text,
    ),
    (
        "glyphorientationvertical",
        "glyphOrientationVertical",
        "glyph-orientation-vertical",
        Text,
    ),
    ("glyphref", "glyphRef", "glyphRef", Text),
    (
        "gradienttransform",
        "gradientTransform",
        "gradientTransform",
        Text,
    ),
    ("gradientunits", "gradientUnits", "gradientUnits", Text),
    ("handler", "handler", "handler", Text),
    ("hanging", "hanging", "hanging", Number),
    (
        "hatchcontentunits",
        "hatchContentUnits",
        "hatchContentUnits",
        Text,
    ),
    ("hatchunits", "hatchUnits", "hatchUnits", Text),
    ("height", "height", "height", Text),
    ("horiz-adv-x", "horizAdvX", "horiz-adv-x", Number),
    ("horiz-origin-x", "horizOriginX", "horiz-origin-x", Number),
    ("horiz-origin-y", "horizOriginY", "horiz-origin-y", Number),
    ("horizadvx", "horizAdvX", "horiz-adv-x", Number),
    ("horizoriginx", "horizOriginX", "horiz-origin-x", Number),
    ("horizoriginy", "horizOriginY", "horiz-origin-y", Number),
    ("href", "href", "href", Text),
    ("hreflang", "hrefLang", "hreflang", Text),
    ("id", "id", "id", Text),
    ("ideographic", "ideographic", "ideographic", Number),
    ("image-rendering", "imageRendering", "image-rendering", Text),
    ("imagerendering", "imageRendering", "image-rendering", Text),
    ("in", "in", "in", Text),
    ("in2", "in2", "in2", Text),
    (
        "initialvisibility",
        "initialVisibility",
        "initialVisibility",
        Text,
    ),
    ("intercept", "intercept", "intercept", Number),
    ("k", "k", "k", Number),
    ("k1", "k1", "k1", Number),
    ("k2", "k2", "k2", Number),
    ("k3", "k3", "k3", Number),
    ("k4", "k4", "k4", Number),
    (
        "kernelmatrix",
        "kernelMatrix",
        "kernelMatrix",
        CommaOrSpaceSeparated,
    ),
    (
        "kernelunitlength",
        "kernelUnitLength",
        "kernelUnitLength",
        Text,
    ),
    ("kerning", "kerning", "kerning", Text),
    ("keypoints", "keyPoints", "keyPoints", Text),
    ("keysplines", "keySplines", "keySplines", Text),
    ("keytimes", "keyTimes", "keyTimes", Text),
    ("lang", "lang", "lang", Text),
    ("lengthadjust", "lengthAdjust", "lengthAdjust", Text),
    ("letter-spacing", "letterSpacing", "letter-spacing", Text),
    ("letterspacing", "letterSpacing", "letter-spacing", Text),
    ("lighting-color", "lightingColor", "lighting-color", Text),
    ("lightingcolor", "lightingColor", "lighting-color", Text),
    (
        "limitingconeangle",
        "limitingConeAngle",
        "limitingConeAngle",
        Number,
    ),
    ("local", "local", "local", Text),
    ("marker-end", "markerEnd", "marker-end", Text),
    ("marker-mid", "markerMid", "marker-mid", Text),
    ("marker-start", "markerStart", "marker-start", Text),
    ("markerend", "markerEnd", "marker-end", Text),
    ("markerheight", "markerHeight", "markerHeight", Text),
    ("markermid", "markerMid", "marker-mid", Text),
    ("markerstart", "markerStart", "marker-start", Text),
    ("markerunits", "markerUnits", "markerUnits", Text),
    ("markerwidth", "markerWidth", "markerWidth", Text),
    ("mask", "mask", "mask", Text),
    ("mask-type", "maskType", "mask-type", Text),
    (
        "maskcontentunits",
        "maskContentUnits",
        "maskContentUnits",
        Text,
    ),
    ("masktype", "maskType", "mask-type", Text),
    ("maskunits", "maskUnits", "maskUnits", Text),
    ("mathematical", "mathematical", "mathematical", Text),
    ("max", "max", "max", Text),
    ("media", "media", "media", Text),
    (
        "mediacharacterencoding",
        "mediaCharacterEncoding",
        "mediaCharacterEncoding",
        Text,
    ),
    (
        "mediacontentencodings",
        "mediaContentEncodings",
        "mediaContentEncodings",
        Text,
    ),
    ("mediasize", "mediaSize", "mediaSize", Number),
    ("mediatime", "mediaTime", "mediaTime", Text),
    ("method", "method", "method", Text),
    ("min", "min", "min", Text),
    ("mode", "mode", "mode", Text),
    ("name", "name", "name", Text),
    ("nav-down", "navDown", "nav-down", Text),
    ("nav-down-left", "navDownLeft", "nav-down-left", Text),
    ("nav-down-right", "navDownRight", "nav-down-right", Text),
    ("nav-left", "navLeft", "nav-left", Text),
    ("nav-next", "navNext", "nav-next", Text),
    ("nav-prev", "navPrev", "nav-prev", Text),
    ("nav-right", "navRight", "nav-right", Text),
    ("nav-up", "navUp", "nav-up", Text),
    ("nav-up-left", "navUpLeft", "nav-up-left", Text),
    ("nav-up-right", "navUpRight", "nav-up-right", Text),
    ("navdown", "navDown", "nav-down", Text),
    ("navdownleft", "navDownLeft", "nav-down-left", Text),
    ("navdownright", "navDownRight", "nav-down-right", Text),
    ("navleft", "navLeft", "nav-left", Text),
    ("navnext", "navNext", "nav-next", Text),
    ("navprev", "navPrev", "nav-prev", Text),
    ("navright", "navRight", "nav-right", Text),
    ("navup", "navUp", "nav-up", Text),
    ("navupleft", "navUpLeft", "nav-up-left", Text),
    ("navupright", "navUpRight", "nav-up-right", Text),
    ("numoctaves", "numOctaves", "numOctaves", Text),
    ("observer", "observer", "observer", Text),
    ("offset", "offset", "offset", Text),
    ("onabort", "onAbort", "onabort", Text),
    ("onactivate", "onActivate", "onactivate", Text),
    ("onafterprint", "onAfterPrint", "onafterprint", Text),
    ("onbeforeprint", "onBeforePrint", "onbeforeprint", Text),
    ("onbegin", "onBegin", "onbegin", Text),
    ("oncancel", "onCancel", "oncancel", Text),
    ("oncanplay", "onCanPlay", "oncanplay", Text),
    (
        "oncanplaythrough",
        "onCanPlayThrough",
        "oncanplaythrough",
        Text,
    ),
    ("onchange", "onChange", "onchange", Text),
    ("onclick", "onClick", "onclick", Text),
    ("onclose", "onClose", "onclose", Text),
    ("oncopy", "onCopy", "oncopy", Text),
    ("oncuechange", "onCueChange", "oncuechange", Text),
    ("oncut", "onCut", "oncut", Text),
    ("ondblclick", "onDblClick", "ondblclick", Text),
    ("ondrag", "onDrag", "ondrag", Text),
    ("ondragend", "onDragEnd", "ondragend", Text),
    ("ondragenter", "onDragEnter", "ondragenter", Text),
    ("ondragexit", "onDragExit", "ondragexit", Text),
    ("ondragleave", "onDragLeave", "ondragleave", Text),
    ("ondragover", "onDragOver", "ondragover", Text),
    ("ondragstart", "onDragStart", "ondragstart", Text),
    ("ondrop", "onDrop", "ondrop", Text),
    (
        "ondurationchange",
        "onDurationChange",
        "ondurationchange",
        Text,
    ),
    ("onemptied", "onEmptied", "onemptied", Text),
    ("onend", "onEnd", "onend", Text),
    ("onended", "onEnded", "onended", Text),
    ("onerror", "onError", "onerror", Text),
    ("onfocus", "onFocus", "onfocus", Text),
    ("onfocusin", "onFocusIn", "onfocusin", Text),
    ("onfocusout", "onFocusOut", "onfocusout", Text),
    ("onhashchange", "onHashChange", "onhashchange", Text),
    ("oninput", "onInput", "oninput", Text),
    ("oninvalid", "onInvalid", "oninvalid", Text),
    ("onkeydown", "onKeyDown", "onkeydown", Text),
    ("onkeypress", "onKeyPress", "onkeypress", Text),
    ("onkeyup", "onKeyUp", "onkeyup", Text),
    ("onload", "onLoad", "onload", Text),
    ("onloadeddata", "onLoadedData", "onloadeddata", Text),
    (
        "onloadedmetadata",
        "onLoadedMetadata",
        "onloadedmetadata",
        Text,
    ),
    ("onloadstart", "onLoadStart", "onloadstart", Text),
    ("onmessage", "onMessage", "onmessage", Text),
    ("onmousedown", "onMouseDown", "onmousedown", Text),
    ("onmouseenter", "onMouseEnter", "onmouseenter", Text),
    ("onmouseleave", "onMouseLeave", "onmouseleave", Text),
    ("onmousemove", "onMouseMove", "onmousemove", Text),
    ("onmouseout", "onMouseOut", "onmouseout", Text),
    ("onmouseover", "onMouseOver", "onmouseover", Text),
    ("onmouseup", "onMouseUp", "onmouseup", Text),
    ("onmousewheel", "onMouseWheel", "onmousewheel", Text),
    ("onoffline", "onOffline", "onoffline", Text),
    ("ononline", "onOnline", "ononline", Text),
    ("onpagehide", "onPageHide", "onpagehide", Text),
    ("onpageshow", "onPageShow", "onpageshow", Text),
    ("onpaste", "onPaste", "onpaste", Text),
    ("onpause", "onPause", "onpause", Text),
    ("onplay", "onPlay", "onplay", Text),
    ("onplaying", "onPlaying", "onplaying", Text),
    ("onpopstate", "onPopState", "onpopstate", Text),
    ("onprogress", "onProgress", "onprogress", Text),
    ("onratechange", "onRateChange", "onratechange", Text),
    ("onrepeat", "onRepeat", "onrepeat", Text),
    ("onreset", "onReset", "onreset", Text),
    ("onresize", "onResize", "onresize", Text),
    ("onscroll", "onScroll", "onscroll", Text),
    ("onseeked", "onSeeked", "onseeked", Text),
    ("onseeking", "onSeeking", "onseeking", Text),
    ("onselect", "onSelect", "onselect", Text),
    ("onshow", "onShow", "onshow", Text),
    ("onstalled", "onStalled", "onstalled", Text),
    ("onstorage", "onStorage", "onstorage", Text),
    ("onsubmit", "onSubmit", "onsubmit", Text),
    ("onsuspend", "onSuspend", "onsuspend", Text),
    ("ontimeupdate", "onTimeUpdate", "ontimeupdate", Text),
    ("ontoggle", "onToggle", "ontoggle", Text),
    ("onunload", "onUnload", "onunload", Text),
    ("onvolumechange", "onVolumeChange", "onvolumechange", Text),
    ("onwaiting", "onWaiting", "onwaiting", Text),
    ("onzoom", "onZoom", "onzoom", Text),
    ("opacity", "opacity", "opacity", Text),
    ("operator", "operator", "operator", Text),
    ("order", "order", "order", Text),
    ("orient", "orient", "orient", Text),
    ("orientation", "orientation", "orientation", Text),
    ("origin", "origin", "origin", Text),
    ("overflow", "overflow", "overflow", Text),
    ("overlay", "overlay", "overlay", Text),
    (
        "overline-position",
        "overlinePosition",
        "overline-position",
        Number,
    ),
    (
        "overline-thickness",
        "overlineThickness",
        "overline-thickness",
        Number,
    ),
    (
        "overlineposition",
        "overlinePosition",
        "overline-position",
        Number,
    ),
    (
        "overlinethickness",
        "overlineThickness",
        "overline-thickness",
        Number,
    ),
    ("paint-order", "paintOrder", "paint-order", Text),
    ("paintorder", "paintOrder", "paint-order", Text),
    ("panose-1", "panose1", "panose-1", Text),
    ("panose1", "panose1", "panose-1", Text),
    ("path", "path", "path", Text),
    ("pathlength", "pathLength", "pathLength", Number),
    (
        "patterncontentunits",
        "patternContentUnits",
        "patternContentUnits",
        Text,
    ),
    (
        "patterntransform",
        "patternTransform",
        "patternTransform",
        Text,
    ),
    ("patternunits", "patternUnits", "patternUnits", Text),
    ("phase", "phase", "phase", Text),
    ("ping", "ping", "ping", SpaceSeparated),
    ("pitch", "pitch", "pitch", Text),
    ("playbackorder", "playbackOrder", "playbackorder", Text),
    ("pointer-events", "pointerEvents", "pointer-events", Text),
    ("pointerevents", "pointerEvents", "pointer-events", Text),
    ("points", "points", "points", Text),
    ("pointsatx", "pointsAtX", "pointsAtX", Number),
    ("pointsaty", "pointsAtY", "pointsAtY", Number),
    ("pointsatz", "pointsAtZ", "pointsAtZ", Number),
    ("preservealpha", "preserveAlpha", "preserveAlpha", Text),
    (
        "preserveaspectratio",
        "preserveAspectRatio",
        "preserveAspectRatio",
        Text,
    ),
    ("primitiveunits", "primitiveUnits", "primitiveUnits", Text),
    ("propagate", "propagate", "propagate", Text),
    ("property", "property", "property", CommaOrSpaceSeparated),
    ("r", "r", "r", Text),
    ("radius", "radius", "radius", Text),
    ("referrerpolicy", "referrerPolicy", "referrerpolicy", Text),
    ("refx", "refX", "refX", Text),
    ("refy", "refY", "refY", Text),
    ("rel", "rel", "rel", CommaOrSpaceSeparated),
    (
        "rendering-intent",
        "renderingIntent",
        "rendering-intent",
        Text,
    ),
    (
        "renderingintent",
        "renderingIntent",
        "rendering-intent",
        Text,
    ),
    ("repeatcount", "repeatCount", "repeatCount", Text),
    ("repeatdur", "repeatDur", "repeatDur", Text),
    (
        "requiredextensions",
        "requiredExtensions",
        "requiredExtensions",
        CommaOrSpaceSeparated,
    ),
    (
        "requiredfeatures",
        "requiredFeatures",
        "requiredFeatures",
        CommaOrSpaceSeparated,
    ),
    (
        "requiredfonts",
        "requiredFonts",
        "requiredFonts",
        CommaOrSpaceSeparated,
    ),
    (
        "requiredformats",
        "requiredFormats",
        "requiredFormats",
        CommaOrSpaceSeparated,
    ),
    ("resource", "resource", "resource", Text),
    ("restart", "restart", "restart", Text),
    ("result", "result", "result", Text),
    ("rev", "rev", "rev", CommaOrSpaceSeparated),
    ("role", "role", "role", Text),
    ("rotate", "rotate", "rotate", Text),
    ("rx", "rx", "rx", Text),
    ("ry", "ry", "ry", Text),
    ("scale", "scale", "scale", Text),
    ("seed", "seed", "seed", Text),
    ("shape-rendering", "shapeRendering", "shape-rendering", Text),
    ("shaperendering", "shapeRendering", "shape-rendering", Text),
    ("side", "side", "side", Text),
    ("slope", "slope", "slope", Text),
    ("snapshottime", "snapshotTime", "snapshotTime", Text),
    ("spacing", "spacing", "spacing", Text),
    (
        "specularconstant",
        "specularConstant",
        "specularConstant",
        Number,
    ),
    (
        "specularexponent",
        "specularExponent",
        "specularExponent",
        Number,
    ),
    ("spreadmethod", "spreadMethod", "spreadMethod", Text),
    ("startoffset", "startOffset", "startOffset", Text),
    ("stddeviation", "stdDeviation", "stdDeviation", Text),
    ("stemh", "stemh", "stemh", Text),
    ("stemv", "stemv", "stemv", Text),
    ("stitchtiles", "stitchTiles", "stitchTiles", Text),
    ("stop-color", "stopColor", "stop-color", Text),
    ("stop-opacity", "stopOpacity", "stop-opacity", Text),
    ("stopcolor", "stopColor", "stop-color", Text),
    ("stopopacity", "stopOpacity", "stop-opacity", Text),
    (
        "strikethrough-position",
        "strikethroughPosition",
        "strikethrough-position",
        Number,
    ),
    (
        "strikethrough-thickness",
        "strikethroughThickness",
        "strikethrough-thickness",
        Number,
    ),
    (
        "strikethroughposition",
        "strikethroughPosition",
        "strikethrough-position",
        Number,
    ),
    (
        "strikethroughthickness",
        "strikethroughThickness",
        "strikethrough-thickness",
        Number,
    ),
    ("string", "string", "string", Text),
    ("stroke", "stroke", "stroke", Text),
    (
        "stroke-dasharray",
        "strokeDashArray",
        "stroke-dasharray",
        CommaOrSpaceSeparated,
    ),
    (
        "stroke-dashoffset",
        "strokeDashOffset",
        "stroke-dashoffset",
        Text,
    ),
    ("stroke-linecap", "strokeLineCap", "stroke-linecap", Text),
    ("stroke-linejoin", "strokeLineJoin", "stroke-linejoin", Text),
    (
        "stroke-miterlimit",
        "strokeMiterLimit",
        "stroke-miterlimit",
        Number,
    ),
    ("stroke-opacity", "strokeOpacity", "stroke-opacity", Number),
    ("stroke-width", "strokeWidth", "stroke-width", Text),
    (
        "strokedasharray",
        "strokeDashArray",
        "stroke-dasharray",
        CommaOrSpaceSeparated,
    ),
    (
        "strokedashoffset",
        "strokeDashOffset",
        "stroke-dashoffset",
        Text,
    ),
    ("strokelinecap", "strokeLineCap", "stroke-linecap", Text),
    ("strokelinejoin", "strokeLineJoin", "stroke-linejoin", Text),
    (
        "strokemiterlimit",
        "strokeMiterLimit",
        "stroke-miterlimit",
        Number,
    ),
    ("strokeopacity", "strokeOpacity", "stroke-opacity", Number),
    ("strokewidth", "strokeWidth", "stroke-width", Text),
    ("style", "style", "style", Text),
    ("surfacescale", "surfaceScale", "surfaceScale", Number),
    ("syncbehavior", "syncBehavior", "syncBehavior", Text),
    (
        "syncbehaviordefault",
        "syncBehaviorDefault",
        "syncBehaviorDefault",
        Text,
    ),
    ("syncmaster", "syncMaster", "syncMaster", Text),
    ("synctolerance", "syncTolerance", "syncTolerance", Text),
    (
        "synctolerancedefault",
        "syncToleranceDefault",
        "syncToleranceDefault",
        Text,
    ),
    (
        "systemlanguage",
        "systemLanguage",
        "systemLanguage",
        CommaOrSpaceSeparated,
    ),
    ("tabindex", "tabIndex", "tabindex", Number),
    ("tablevalues", "tableValues", "tableValues", Text),
    ("target", "target", "target", Text),
    ("targetx", "targetX", "targetX", Number),
    ("targety", "targetY", "targetY", Number),
    ("text-anchor", "textAnchor", "text-anchor", Text),
    ("text-decoration", "textDecoration", "text-decoration", Text),
    ("text-rendering", "textRendering", "text-rendering", Text),
    ("textanchor", "textAnchor", "text-anchor", Text),
    ("textdecoration", "textDecoration", "text-decoration", Text),
    ("textlength", "textLength", "textLength", Text),
    ("textrendering", "textRendering", "text-rendering", Text),
    ("timelinebegin", "timelineBegin", "timelinebegin", Text),
    ("title", "title", "title", Text),
    ("to", "to", "to", Text),
    ("transform", "transform", "transform", Text),
    (
        "transform-origin",
        "transformOrigin",
        "transform-origin",
        Text,
    ),
    (
        "transformbehavior",
        "transformBehavior",
        "transformBehavior",
        Text,
    ),
    (
        "transformorigin",
        "transformOrigin",
        "transform-origin",
        Text,
    ),
    ("type", "type", "type", Text),
    ("typeof", "typeOf", "typeof", CommaOrSpaceSeparated),
    ("u1", "u1", "u1", Text),
    ("u2", "u2", "u2", Text),
    (
        "underline-position",
        "underlinePosition",
        "underline-position",
        Number,
    ),
    (
        "underline-thickness",
        "underlineThickness",
        "underline-thickness",
        Number,
    ),
    (
        "underlineposition",
        "underlinePosition",
        "underline-position",
        Number,
    ),
    (
        "underlinethickness",
        "underlineThickness",
        "underline-thickness",
        Number,
    ),
    ("unicode", "unicode", "unicode", Text),
    ("unicode-bidi", "unicodeBidi", "unicode-bidi", Text),
    ("unicode-range", "unicodeRange", "unicode-range", Text),
    ("unicodebidi", "unicodeBidi", "unicode-bidi", Text),
    ("unicoderange", "unicodeRange", "unicode-range", Text),
    ("units-per-em", "unitsPerEm", "units-per-em", Number),
    ("unitsperem", "unitsPerEm", "units-per-em", Number),
    ("v-alphabetic", "vAlphabetic", "v-alphabetic", Number),
    ("v-hanging", "vHanging", "v-hanging", Number),
    ("v-ideographic", "vIdeographic", "v-ideographic", Number),
    ("v-mathematical", "vMathematical", "v-mathematical", Number),
    ("valphabetic", "vAlphabetic", "v-alphabetic", Number),
    ("values", "values", "values", Text),
    ("vector-effect", "vectorEffect", "vector-effect", Text),
    ("vectoreffect", "vectorEffect", "vector-effect", Text),
    ("version", "version", "version", Text),
    ("vert-adv-y", "vertAdvY", "vert-adv-y", Number),
    ("vert-origin-x", "vertOriginX", "vert-origin-x", Number),
    ("vert-origin-y", "vertOriginY", "vert-origin-y", Number),
    ("vertadvy", "vertAdvY", "vert-adv-y", Number),
    ("vertoriginx", "vertOriginX", "vert-origin-x", Number),
    ("vertoriginy", "vertOriginY", "vert-origin-y", Number),
    ("vhanging", "vHanging", "v-hanging", Number),
    ("videographic", "vIdeographic", "v-ideographic", Number),
    ("viewbox", "viewBox", "viewBox", Text),
    ("viewtarget", "viewTarget", "viewTarget", Text),
    ("visibility", "visibility", "visibility", Text),
    ("vmathematical", "vMathematical", "v-mathematical", Number),
    ("width", "width", "width", Text),
    ("widths", "widths", "widths", Text),
    ("word-spacing", "wordSpacing", "word-spacing", Text),
    ("wordspacing", "wordSpacing", "word-spacing", Text),
    ("writing-mode", "writingMode", "writing-mode", Text),
    ("writingmode", "writingMode", "writing-mode", Text),
    ("x", "x", "x", Text),
    ("x-height", "xHeight", "x-height", Number),
    ("x1", "x1", "x1", Text),
    ("x2", "x2", "x2", Text),
    (
        "xchannelselector",
        "xChannelSelector",
        "xChannelSelector",
        Text,
    ),
    ("xheight", "xHeight", "x-height", Number),
    ("xlink:actuate", "xLinkActuate", "xlink:actuate", Text),
    ("xlink:arcrole", "xLinkArcRole", "xlink:arcrole", Text),
    ("xlink:href", "xLinkHref", "xlink:href", Text),
    ("xlink:role", "xLinkRole", "xlink:role", Text),
    ("xlink:show", "xLinkShow", "xlink:show", Text),
    ("xlink:title", "xLinkTitle", "xlink:title", Text),
    ("xlink:type", "xLinkType", "xlink:type", Text),
    ("xlinkactuate", "xLinkActuate", "xlink:actuate", Text),
    ("xlinkarcrole", "xLinkArcRole", "xlink:arcrole", Text),
    ("xlinkhref", "xLinkHref", "xlink:href", Text),
    ("xlinkrole", "xLinkRole", "xlink:role", Text),
    ("xlinkshow", "xLinkShow", "xlink:show", Text),
    ("xlinktitle", "xLinkTitle", "xlink:title", Text),
    ("xlinktype", "xLinkType", "xlink:type", Text),
    ("xml:base", "xmlBase", "xml:base", Text),
    ("xml:lang", "xmlLang", "xml:lang", Text),
    ("xml:space", "xmlSpace", "xml:space", Text),
    ("xmlbase", "xmlBase", "xml:base", Text),
    ("xmllang", "xmlLang", "xml:lang", Text),
    ("xmlns", "xmlns", "xmlns", Text),
    ("xmlns:xlink", "xmlnsXLink", "xmlns:xlink", Text),
    ("xmlnsxlink", "xmlnsXLink", "xmlns:xlink", Text),
    ("xmlspace", "xmlSpace", "xml:space", Text),
    ("y", "y", "y", Text),
    ("y1", "y1", "y1", Text),
    ("y2", "y2", "y2", Text),
    (
        "ychannelselector",
        "yChannelSelector",
        "yChannelSelector",
        Text,
    ),
    ("z", "z", "z", Text),
    ("zoomandpan", "zoomAndPan", "zoomAndPan", Text),
];
