// Copyright 2015 Google Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

//! Expansions of HTML5 entities

// Autogenerated by mk_entities.py

/// Entity names, concatenated in sorted order.
static ENTITY_KEYS: &[u8] = b"AEligAMPAacuteAbreveAcircAcyAfrAgraveAlphaAmacrAndAogon\
    AopfApplyFunctionAringAscrAssignAtildeAumlBackslashBarvBarwedBcyBecause\
    BernoullisBetaBfrBopfBreveBscrBumpeqCHcyCOPYCacuteCapCapitalDifferentialD\
    CayleysCcaronCcedilCcircCconintCdotCedillaCenterDotCfrChiCircleDotCircleMinus\
    CirclePlusCircleTimesClockwiseContourIntegralCloseCurlyDoubleQuoteCloseCurlyQuoteColonColoneCongruentConintContourIntegralCopfCoproduct\
    CounterClockwiseContourIntegralCrossCscrCupCupCapDDDDotrahdDJcyDScyDZcyDaggerDarr\
    DashvDcaronDcyDelDeltaDfrDiacriticalAcuteDiacriticalDotDiacriticalDoubleAcuteDiacriticalGraveDiacriticalTildeDiamond\
    DifferentialDDopfDotDotDotDotEqualDoubleContourIntegralDoubleDotDoubleDownArrowDoubleLeftArrowDoubleLeftRightArrowDoubleLeftTeeDoubleLongLeftArrow\
    DoubleLongLeftRightArrowDoubleLongRightArrowDoubleRightArrowDoubleRightTeeDoubleUpArrowDoubleUpDownArrowDoubleVerticalBarDownArrowDownArrowBarDownArrowUpArrowDownBreveDownLeftRightVector\
    DownLeftTeeVectorDownLeftVectorDownLeftVectorBarDownRightTeeVectorDownRightVectorDownRightVectorBarDownTeeDownTeeArrowDownarrowDscrDstrokENG\
    ETHEacuteEcaronEcircEcyEdotEfrEgraveElementEmacrEmptySmallSquareEmptyVerySmallSquare\
    EogonEopfEpsilonEqualEqualTildeEquilibriumEscrEsimEtaEumlExistsExponentialE\
    FcyFfrFilledSmallSquareFilledVerySmallSquareFopfForAllFouriertrfFscrGJcyGTGammaGammad\
    GbreveGcedilGcircGcyGdotGfrGgGopfGreaterEqualGreaterEqualLessGreaterFullEqualGreaterGreater\
    GreaterLessGreaterSlantEqualGreaterTildeGscrGtHARDcyHacekHatHcircHfrHilbertSpaceHopf\
    HorizontalLineHscrHstrokHumpDownHumpHumpEqualIEcyIJligIOcyIacuteIcircIcyIdot\
    IfrIgraveImImacrImaginaryIImpliesIntIntegralIntersectionInvisibleCommaInvisibleTimesIogon\
    IopfIotaIscrItildeIukcyIumlJcircJcyJfrJopfJscrJsercy\
    JukcyKHcyKJcyKappaKcedilKcyKfrKopfKscrLJcyLTLacute\
    LambdaLangLaplacetrfLarrLcaronLcedilLcyLeftAngleBracketLeftArrowLeftArrowBarLeftArrowRightArrowLeftCeiling\
    LeftDoubleBracketLeftDownTeeVectorLeftDownVectorLeftDownVectorBarLeftFloorLeftRightArrowLeftRightVectorLeftTeeLeftTeeArrowLeftTeeVectorLeftTriangleLeftTriangleBar\
    LeftTriangleEqualLeftUpDownVectorLeftUpTeeVectorLeftUpVectorLeftUpVectorBarLeftVectorLeftVectorBarLeftarrowLeftrightarrowLessEqualGreaterLessFullEqualLessGreater\
    LessLessLessSlantEqualLessTildeLfrLlLleftarrowLmidotLongLeftArrowLongLeftRightArrowLongRightArrowLongleftarrowLongleftrightarrow\
    LongrightarrowLopfLowerLeftArrowLowerRightArrowLscrLshLstrokLtMapMcyMediumSpaceMellintrf\
    MfrMinusPlusMopfMscrMuNJcyNacuteNcaronNcedilNcyNegativeMediumSpaceNegativeThickSpace\
    NegativeThinSpaceNegativeVeryThinSpaceNestedGreaterGreaterNestedLessLessNewLineNfrNoBreakNonBreakingSpaceNopfNotNotCongruentNotCupCap\
    NotDoubleVerticalBarNotElementNotEqualNotEqualTildeNotExistsNotGreaterNotGreaterEqualNotGreaterFullEqualNotGreaterGreaterNotGreaterLessNotGreaterSlantEqualNotGreaterTilde\
    NotHumpDownHumpNotHumpEqualNotLeftTriangleNotLeftTriangleBarNotLeftTriangleEqualNotLessNotLessEqualNotLessGreaterNotLessLessNotLessSlantEqualNotLessTildeNotNestedGreaterGreater\
    NotNestedLessLessNotPrecedesNotPrecedesEqualNotPrecedesSlantEqualNotReverseElementNotRightTriangleNotRightTriangleBarNotRightTriangleEqualNotSquareSubsetNotSquareSubsetEqualNotSquareSupersetNotSquareSupersetEqual\
    NotSubsetNotSubsetEqualNotSucceedsNotSucceedsEqualNotSucceedsSlantEqualNotSucceedsTildeNotSupersetNotSupersetEqualNotTildeNotTildeEqualNotTildeFullEqualNotTildeTilde\
    NotVerticalBarNscrNtildeNuOEligOacuteOcircOcyOdblacOfrOgraveOmacr\
    OmegaOmicronOopfOpenCurlyDoubleQuoteOpenCurlyQuoteOrOscrOslashOtildeOtimesOumlOverBar\
    OverBraceOverBracketOverParenthesisPartialDPcyPfrPhiPiPlusMinusPoincareplanePopfPr\
    PrecedesPrecedesEqualPrecedesSlantEqualPrecedesTildePrimeProductProportionProportionalPscrPsiQUOTQfr\
    QopfQscrRBarrREGRacuteRangRarrRarrtlRcaronRcedilRcyRe\
    ReverseElementReverseEquilibriumReverseUpEquilibriumRfrRhoRightAngleBracketRightArrowRightArrowBarRightArrowLeftArrowRightCeilingRightDoubleBracketRightDownTeeVector\
    RightDownVectorRightDownVectorBarRightFloorRightTeeRightTeeArrowRightTeeVectorRightTriangleRightTriangleBarRightTriangleEqualRightUpDownVectorRightUpTeeVectorRightUpVector\
    RightUpVectorBarRightVectorRightVectorBarRightarrowRopfRoundImpliesRrightarrowRscrRshRuleDelayedSHCHcySHcy\
    SOFTcySacuteScScaronScedilScircScySfrShortDownArrowShortLeftArrowShortRightArrowShortUpArrow\
    SigmaSmallCircleSopfSqrtSquareSquareIntersectionSquareSubsetSquareSubsetEqualSquareSupersetSquareSupersetEqualSquareUnionSscr\
    StarSubSubsetSubsetEqualSucceedsSucceedsEqualSucceedsSlantEqualSucceedsTildeSuchThatSumSupSuperset\
    SupersetEqualSupsetTHORNTRADETSHcyTScyTabTauTcaronTcedilTcyTfr\
    ThereforeThetaThickSpaceThinSpaceTildeTildeEqualTildeFullEqualTildeTildeTopfTripleDotTscrTstrok\
    UacuteUarrUarrocirUbrcyUbreveUcircUcyUdblacUfrUgraveUmacrUnderBar\
    UnderBraceUnderBracketUnderParenthesisUnionUnionPlusUogonUopfUpArrowUpArrowBarUpArrowDownArrowUpDownArrowUpEquilibrium\
    UpTeeUpTeeArrowUparrowUpdownarrowUpperLeftArrowUpperRightArrowUpsiUpsilonUringUscrUtildeUuml\
    VDashVbarVcyVdashVdashlVeeVerbarVertVerticalBarVerticalLineVerticalSeparatorVerticalTilde\
    VeryThinSpaceVfrVopfVscrVvdashWcircWedgeWfrWopfWscrXfrXi\
    XopfXscrYAcyYIcyYUcyYacuteYcircYcyYfrYopfYscrYuml\
    ZHcyZacuteZcaronZcyZdotZeroWidthSpaceZetaZfrZopfZscraacuteabreve\
    acacEacdacircacuteacyaeligafafragravealefsymaleph\
    alphaamacramalgampandandandanddandslopeandvangangeangle\
    angmsdangmsdaaangmsdabangmsdacangmsdadangmsdaeangmsdafangmsdagangmsdahangrtangrtvbangrtvbd\
    angsphangstangzarraogonaopfapapEapacirapeapidaposapprox\
    approxeqaringascrastasympasympeqatildeaumlawconintawintbNotbackcong\
    backepsilonbackprimebacksimbacksimeqbarveebarwedbarwedgebbrkbbrktbrkbcongbcybdquo\
    becausbecausebemptyvbepsibernoubetabethbetweenbfrbigcapbigcircbigcup\
    bigodotbigoplusbigotimesbigsqcupbigstarbigtriangledownbigtriangleupbiguplusbigveebigwedgebkarowblacklozenge\
    blacksquareblacktriangleblacktriangledownblacktriangleleftblacktrianglerightblankblk12blk14blk34blockbnebnequiv\
    bnotbopfbotbottombowtieboxDLboxDRboxDlboxDrboxHboxHDboxHU\
    boxHdboxHuboxULboxURboxUlboxUrboxVboxVHboxVLboxVRboxVhboxVl\
    boxVrboxboxboxdLboxdRboxdlboxdrboxhboxhDboxhUboxhdboxhuboxminus\
    boxplusboxtimesboxuLboxuRboxulboxurboxvboxvHboxvLboxvRboxvhboxvl\
    boxvrbprimebrevebrvbarbscrbsemibsimbsimebsolbsolbbsolhsubbull\
    bulletbumpbumpEbumpebumpeqcacutecapcapandcapbrcupcapcapcapcupcapdot\
    capscaretcaronccapsccaronccedilccircccupsccupssmcdotcedilcemptyv\
    centcenterdotcfrchcycheckcheckmarkchicircirEcirccirceqcirclearrowleft\
    circlearrowrightcircledRcircledScircledastcircledcirccircleddashcirecirfnintcirmidcirscirclubsclubsuit\
    coloncolonecoloneqcommacommatcompcompfncomplementcomplexescongcongdotconint\
    copfcoprodcopycopysrcrarrcrosscscrcsubcsubecsupcsupectdot\
    cudarrlcudarrrcueprcuesccularrcularrpcupcupbrcapcupcapcupcupcupdotcupor\
    cupscurarrcurarrmcurlyeqpreccurlyeqsucccurlyveecurlywedgecurrencurvearrowleftcurvearrowrightcuveecuwed\
    cwconintcwintcylctydArrdHardaggerdalethdarrdashdashvdbkarowdblac\
    dcarondcyddddaggerddarrddotseqdegdeltademptyvdfishtdfrdharl\
    dharrdiamdiamonddiamondsuitdiamsdiedigammadisindivdividedivideontimesdivonx\
    djcydlcorndlcropdollardopfdotdoteqdoteqdotdotminusdotplusdotsquaredoublebarwedge\
    downarrowdowndownarrowsdownharpoonleftdownharpoonrightdrbkarowdrcorndrcropdscrdscydsoldstrokdtdot\
    dtridtrifduarrduhardwangledzcydzigrarreDDoteDoteacuteeasterecaron\
    ecirecircecolonecyedoteeefDotefregegraveegsegsdot\
    elelintersellelselsdotemacremptyemptysetemptyvemspemsp13emsp14\
    engenspeogoneopfepareparsleplusepsiepsilonepsiveqcirceqcolon\
    eqsimeqslantgtreqslantlessequalsequestequivequivDDeqvparslerDoterarrescresdot\
    esimetaetheumleuroexclexistexpectationexponentialefallingdotseqfcyfemale\
    ffiligffligfflligffrfiligfjligflatflligfltnsfnoffopfforall\
    forkforkvfpartintfrac12frac13frac14frac15frac16frac18frac23frac25frac34\
    frac35frac38frac45frac56frac58frac78fraslfrownfscrgEgElgacute\
    gammagammadgapgbrevegcircgcygdotgegelgeqgeqqgeqslant\
    gesgesccgesdotgesdotogesdotolgeslgeslesgfrggggggimelgjcy\
    glglEglagljgnEgnapgnapproxgnegneqgneqqgnsimgopf\
    gravegscrgsimgsimegsimlgtgtccgtcirgtdotgtlPargtquestgtrapprox\
    gtrarrgtrdotgtreqlessgtreqqlessgtrlessgtrsimgvertneqqgvnEhArrhairsphalfhamilt\
    hardcyharrharrcirharrwhbarhcircheartsheartsuithellipherconhfrhksearow\
    hkswarowhoarrhomththookleftarrowhookrightarrowhopfhorbarhscrhslashhstrokhybullhyphen\
    iacuteicicircicyiecyiexcliffifrigraveiiiiiintiiint\
    iinfiniiotaijligimacrimageimaglineimagpartimathimofimpedinincare\
    infininfintieinodotintintcalintegersintercalintlarhkintprodiocyiogoniopf\
    iotaiprodiquestiscrisinisinEisindotisinsisinsvisinvititilde\
    iukcyiumljcircjcyjfrjmathjopfjscrjsercyjukcykappakappav\
    kcedilkcykfrkgreenkhcykjcykopfkscrlAarrlArrlAtaillBarr\
    lElEglHarlacutelaemptyvlagranlambdalanglangdlanglelaplaquo\
    larrlarrblarrbfslarrfslarrhklarrlplarrpllarrsimlarrtllatlataillate\
    lateslbarrlbbrklbracelbracklbrkelbrksldlbrkslulcaronlcedillceillcub\
    lcyldcaldquoldquorldrdharldrusharldshleleftarrowleftarrowtailleftharpoondownleftharpoonup\
    leftleftarrowsleftrightarrowleftrightarrowsleftrightharpoonsleftrightsquigarrowleftthreetimeslegleqleqqleqslantleslescc\
    lesdotlesdotolesdotorlesglesgeslessapproxlessdotlesseqgtrlesseqqgtrlessgtrlesssimlfisht\
    lfloorlfrlglgElhardlharulharullhblkljcyllllarrllcorner\
    llhardlltrilmidotlmoustlmoustachelnElnaplnapproxlnelneqlneqqlnsim\
    loangloarrlobrklongleftarrowlongleftrightarrowlongmapstolongrightarrowlooparrowleftlooparrowrightloparlopfloplus\
    lotimeslowastlowbarlozlozengelozflparlparltlrarrlrcornerlrharlrhard\
    lrmlrtrilsaquolscrlshlsimlsimelsimglsqblsquolsquorlstrok\
    ltltccltcirltdotlthreeltimesltlarrltquestltrParltriltrieltrif\
    lurdsharluruharlvertneqqlvnEmDDotmacrmalemaltmaltesemapmapstomapstodown\
    mapstoleftmapstoupmarkermcommamcymdashmeasuredanglemfrmhomicromidmidast\
    midcirmiddotminusminusbminusdminusdumlcpmldrmnplusmodelsmopfmp\
    mscrmstposmumultimapmumapnGgnGtnGtvnLeftarrownLeftrightarrownLlnLt\
    nLtvnRightarrownVDashnVdashnablanacutenangnapnapEnapidnaposnapprox\
    naturnaturalnaturalsnbspnbumpnbumpencapncaronncedilncongncongdotncup\
    ncyndashneneArrnearhknearrnearrownedotnequivnesearnesimnexist\
    nexistsnfrngEngengeqngeqqngeqslantngesngsimngtngtrnhArr\
    nharrnhparninisnisdnivnjcynlArrnlEnlarrnldrnle\
    nleftarrownleftrightarrownleqnleqqnleqslantnlesnlessnlsimnltnltrinltrienmid\
    nopfnotnotinnotinEnotindotnotinvanotinvbnotinvcnotninotnivanotnivbnotnivc\
    nparnparallelnparslnpartnpolintnprnprcuenprenprecnpreceqnrArrnrarr\
    nrarrcnrarrwnrightarrownrtrinrtrienscnsccuenscenscrnshortmidnshortparallelnsim\
    nsimensimeqnsmidnsparnsqsubensqsupensubnsubEnsubensubsetnsubseteqnsubseteqq\
    nsuccnsucceqnsupnsupEnsupensupsetnsupseteqnsupseteqqntglntildentlgntriangleleft\
    ntrianglelefteqntrianglerightntrianglerighteqnunumnumeronumspnvDashnvHarrnvapnvdashnvge\
    nvgtnvinfinnvlArrnvlenvltnvltrienvrArrnvrtrienvsimnwArrnwarhknwarr\
    nwarrownwnearoSoacuteoastocirocircocyodashodblacodivodot\
    odsoldoeligofcirofrogonograveogtohbarohmointolarrolcir\
    olcrossolineoltomacromegaomicronomidominusoopfoparoperpoplus\
    ororarrordorderorderofordfordmorigoforororslopeorvoscr\
    oslashosolotildeotimesotimesasoumlovbarparparaparallelparsimparsl\
    partpcypercntperiodpermilperppertenkpfrphiphivphmmatphone\
    pipitchforkpivplanckplanckhplankvplusplusacirplusbpluscirplusdoplusdu\
    pluseplusmnplussimplustwopmpointintpopfpoundprprEprapprcue\
    preprecprecapproxpreccurlyeqpreceqprecnapproxprecneqqprecnsimprecsimprimeprimesprnE\
    prnapprnsimprodprofalarproflineprofsurfpropproptoprsimprurelpscrpsi\
    puncspqfrqintqopfqprimeqscrquaternionsquatintquestquesteqquotrAarr\
    rArrrAtailrBarrrHarraceracuteradicraemptyvrangrangdrangerangle\
    raquorarrrarraprarrbrarrbfsrarrcrarrfsrarrhkrarrlprarrplrarrsimrarrtl\
    rarrwratailratiorationalsrbarrrbbrkrbracerbrackrbrkerbrksldrbrkslurcaron\
    rcedilrceilrcubrcyrdcardldharrdquordquorrdshrealrealinerealpart\
    realsrectregrfishtrfloorrfrrhardrharurharulrhorhovrightarrow\
    rightarrowtailrightharpoondownrightharpoonuprightleftarrowsrightleftharpoonsrightrightarrowsrightsquigarrowrightthreetimesringrisingdotseqrlarrrlhar\
    rlmrmoustrmoustachernmidroangroarrrobrkroparropfroplusrotimesrpar\
    rpargtrppolintrrarrrsaquorscrrshrsqbrsquorsquorrthreertimesrtri\
    rtriertrifrtriltriruluharrxsacutesbquoscscEscapscaronsccue\
    scescedilscircscnEscnapscnsimscpolintscsimscysdotsdotbsdote\
    seArrsearhksearrsearrowsectsemiseswarsetminussetmnsextsfrsfrown\
    sharpshchcyshcyshortmidshortparallelshysigmasigmafsigmavsimsimdotsime\
    simeqsimgsimgEsimlsimlEsimnesimplussimrarrslarrsmallsetminussmashpsmeparsl\
    smidsmilesmtsmtesmtessoftcysolsolbsolbarsopfspadesspadesuit\
    sparsqcapsqcapssqcupsqcupssqsubsqsubesqsubsetsqsubseteqsqsupsqsupesqsupset\
    sqsupseteqsqusquaresquarfsqufsrarrsscrssetmnssmilesstarfstarstarf\
    straightepsilonstraightphistrnssubsubEsubdotsubesubedotsubmultsubnEsubnesubplus\
    subrarrsubsetsubseteqsubseteqqsubsetneqsubsetneqqsubsimsubsubsubsupsuccsuccapproxsucccurlyeq\
    succeqsuccnapproxsuccneqqsuccnsimsuccsimsumsungsupsup1sup2sup3supE\
    supdotsupdsubsupesupedotsuphsolsuphsubsuplarrsupmultsupnEsupnesupplussupset\
    supseteqsupseteqqsupsetneqsupsetneqqsupsimsupsubsupsupswArrswarhkswarrswarrowswnwar\
    szligtargettautbrktcarontcediltcytdottelrectfrthere4therefore\
    thetathetasymthetavthickapproxthicksimthinspthkapthksimthorntildetimestimesb\
    timesbartimesdtinttoeatoptopbottopcirtopftopforktosatprimetrade\
    triangletriangledowntrianglelefttrianglelefteqtriangleqtrianglerighttrianglerighteqtridottrietriminustriplustrisb\
    tritimetrpeziumtscrtscytshcytstroktwixttwoheadleftarrowtwoheadrightarrowuArruHaruacute\
    uarrubrcyubreveucircucyudarrudblacudharufishtufrugraveuharl\
    uharruhblkulcornulcornerulcropultriumacrumluogonuopfuparrowupdownarrow\
    upharpoonleftupharpoonrightuplusupsiupsihupsilonupuparrowsurcornurcornerurcropuringurtri\
    uscrutdotutildeutriutrifuuarruumluwanglevArrvBarvBarvvDash\
    vangrtvarepsilonvarkappavarnothingvarphivarpivarproptovarrvarrhovarsigmavarsubsetneqvarsubsetneqq\
    varsupsetneqvarsupsetneqqvarthetavartriangleleftvartrianglerightvcyvdashveeveebarveeeqvellipverbar\
    vertvfrvltrivnsubvnsupvopfvpropvrtrivscrvsubnEvsubnevsupnE\
    vsupnevzigzagwcircwedbarwedgewedgeqweierpwfrwopfwpwrwreath\
    wscrxcapxcircxcupxdtrixfrxhArrxharrxixlArrxlarrxmap\
    xnisxodotxopfxoplusxotimexrArrxrarrxscrxsqcupxuplusxutrixvee\
    xwedgeyacuteyacyycircycyyenyfryicyyopfyscryucyyuml\
    zacutezcaronzcyzdotzeetrfzetazfrzhcyzigrarrzopfzscrzwj\
    zwnj";

/// Entity expansions, in the same order as [`ENTITY_KEYS`].
static ENTITY_VALUES: &str = "\u{00C6}\u{0026}\u{00C1}\u{0102}\u{00C2}\u{0410}\
    \u{1D504}\u{00C0}\u{0391}\u{0100}\u{2A53}\u{0104}\
    \u{1D538}\u{2061}\u{00C5}\u{1D49C}\u{2254}\u{00C3}\
    \u{00C4}\u{2216}\u{2AE7}\u{2306}\u{0411}\u{2235}\
    \u{212C}\u{0392}\u{1D505}\u{1D539}\u{02D8}\u{212C}\
    \u{224E}\u{0427}\u{00A9}\u{0106}\u{22D2}\u{2145}\
    \u{212D}\u{010C}\u{00C7}\u{0108}\u{2230}\u{010A}\
    \u{00B8}\u{00B7}\u{212D}\u{03A7}\u{2299}\u{2296}\
    \u{2295}\u{2297}\u{2232}\u{201D}\u{2019}\u{2237}\
    \u{2A74}\u{2261}\u{222F}\u{222E}\u{2102}\u{2210}\
    \u{2233}\u{2A2F}\u{1D49E}\u{22D3}\u{224D}\u{2145}\
    \u{2911}\u{0402}\u{0405}\u{040F}\u{2021}\u{21A1}\
    \u{2AE4}\u{010E}\u{0414}\u{2207}\u{0394}\u{1D507}\
    \u{00B4}\u{02D9}\u{02DD}\u{0060}\u{02DC}\u{22C4}\
    \u{2146}\u{1D53B}\u{00A8}\u{20DC}\u{2250}\u{222F}\
    \u{00A8}\u{21D3}\u{21D0}\u{21D4}\u{2AE4}\u{27F8}\
    \u{27FA}\u{27F9}\u{21D2}\u{22A8}\u{21D1}\u{21D5}\
    \u{2225}\u{2193}\u{2913}\u{21F5}\u{0311}\u{2950}\
    \u{295E}\u{21BD}\u{2956}\u{295F}\u{21C1}\u{2957}\
    \u{22A4}\u{21A7}\u{21D3}\u{1D49F}\u{0110}\u{014A}\
    \u{00D0}\u{00C9}\u{011A}\u{00CA}\u{042D}\u{0116}\
    \u{1D508}\u{00C8}\u{2208}\u{0112}\u{25FB}\u{25AB}\
    \u{0118}\u{1D53C}\u{0395}\u{2A75}\u{2242}\u{21CC}\
    \u{2130}\u{2A73}\u{0397}\u{00CB}\u{2203}\u{2147}\
    \u{0424}\u{1D509}\u{25FC}\u{25AA}\u{1D53D}\u{2200}\
    \u{2131}\u{2131}\u{0403}\u{003E}\u{0393}\u{03DC}\
    \u{011E}\u{0122}\u{011C}\u{0413}\u{0120}\u{1D50A}\
    \u{22D9}\u{1D53E}\u{2265}\u{22DB}\u{2267}\u{2AA2}\
    \u{2277}\u{2A7E}\u{2273}\u{1D4A2}\u{226B}\u{042A}\
    \u{02C7}\u{005E}\u{0124}\u{210C}\u{210B}\u{210D}\
    \u{2500}\u{210B}\u{0126}\u{224E}\u{224F}\u{0415}\
    \u{0132}\u{0401}\u{00CD}\u{00CE}\u{0418}\u{0130}\
    \u{2111}\u{00CC}\u{2111}\u{012A}\u{2148}\u{21D2}\
    \u{222C}\u{222B}\u{22C2}\u{2063}\u{2062}\u{012E}\
    \u{1D540}\u{0399}\u{2110}\u{0128}\u{0406}\u{00CF}\
    \u{0134}\u{0419}\u{1D50D}\u{1D541}\u{1D4A5}\u{0408}\
    \u{0404}\u{0425}\u{040C}\u{039A}\u{0136}\u{041A}\
    \u{1D50E}\u{1D542}\u{1D4A6}\u{0409}\u{003C}\u{0139}\
    \u{039B}\u{27EA}\u{2112}\u{219E}\u{013D}\u{013B}\
    \u{041B}\u{27E8}\u{2190}\u{21E4}\u{21C6}\u{2308}\
    \u{27E6}\u{2961}\u{21C3}\u{2959}\u{230A}\u{2194}\
    \u{294E}\u{22A3}\u{21A4}\u{295A}\u{22B2}\u{29CF}\
    \u{22B4}\u{2951}\u{2960}\u{21BF}\u{2958}\u{21BC}\
    \u{2952}\u{21D0}\u{21D4}\u{22DA}\u{2266}\u{2276}\
    \u{2AA1}\u{2A7D}\u{2272}\u{1D50F}\u{22D8}\u{21DA}\
    \u{013F}\u{27F5}\u{27F7}\u{27F6}\u{27F8}\u{27FA}\
    \u{27F9}\u{1D543}\u{2199}\u{2198}\u{2112}\u{21B0}\
    \u{0141}\u{226A}\u{2905}\u{041C}\u{205F}\u{2133}\
    \u{1D510}\u{2213}\u{1D544}\u{2133}\u{039C}\u{040A}\
    \u{0143}\u{0147}\u{0145}\u{041D}\u{200B}\u{200B}\
    \u{200B}\u{200B}\u{226B}\u{226A}\u{000A}\u{1D511}\
    \u{2060}\u{00A0}\u{2115}\u{2AEC}\u{2262}\u{226D}\
    \u{2226}\u{2209}\u{2260}\u{2242}\u{0338}\u{2204}\u{226F}\
    \u{2271}\u{2267}\u{0338}\u{226B}\u{0338}\u{2279}\u{2A7E}\u{0338}\u{2275}\
    \u{224E}\u{0338}\u{224F}\u{0338}\u{22EA}\u{29CF}\u{0338}\u{22EC}\u{226E}\
    \u{2270}\u{2278}\u{226A}\u{0338}\u{2A7D}\u{0338}\u{2274}\u{2AA2}\u{0338}\
    \u{2AA1}\u{0338}\u{2280}\u{2AAF}\u{0338}\u{22E0}\u{220C}\u{22EB}\
    \u{29D0}\u{0338}\u{22ED}\u{228F}\u{0338}\u{22E2}\u{2290}\u{0338}\u{22E3}\
    \u{2282}\u{20D2}\u{2288}\u{2281}\u{2AB0}\u{0338}\u{22E1}\u{227F}\u{0338}\
    \u{2283}\u{20D2}\u{2289}\u{2241}\u{2244}\u{2247}\u{2249}\
    \u{2224}\u{1D4A9}\u{00D1}\u{039D}\u{0152}\u{00D3}\
    \u{00D4}\u{041E}\u{0150}\u{1D512}\u{00D2}\u{014C}\
    \u{03A9}\u{039F}\u{1D546}\u{201C}\u{2018}\u{2A54}\
    \u{1D4AA}\u{00D8}\u{00D5}\u{2A37}\u{00D6}\u{203E}\
    \u{23DE}\u{23B4}\u{23DC}\u{2202}\u{041F}\u{1D513}\
    \u{03A6}\u{03A0}\u{00B1}\u{210C}\u{2119}\u{2ABB}\
    \u{227A}\u{2AAF}\u{227C}\u{227E}\u{2033}\u{220F}\
    \u{2237}\u{221D}\u{1D4AB}\u{03A8}\u{0022}\u{1D514}\
    \u{211A}\u{1D4AC}\u{2910}\u{00AE}\u{0154}\u{27EB}\
    \u{21A0}\u{2916}\u{0158}\u{0156}\u{0420}\u{211C}\
    \u{220B}\u{21CB}\u{296F}\u{211C}\u{03A1}\u{27E9}\
    \u{2192}\u{21E5}\u{21C4}\u{2309}\u{27E7}\u{295D}\
    \u{21C2}\u{2955}\u{230B}\u{22A2}\u{21A6}\u{295B}\
    \u{22B3}\u{29D0}\u{22B5}\u{294F}\u{295C}\u{21BE}\
    \u{2954}\u{21C0}\u{2953}\u{21D2}\u{211D}\u{2970}\
    \u{21DB}\u{211B}\u{21B1}\u{29F4}\u{0429}\u{0428}\
    \u{042C}\u{015A}\u{2ABC}\u{0160}\u{015E}\u{015C}\
    \u{0421}\u{1D516}\u{2193}\u{2190}\u{2192}\u{2191}\
    \u{03A3}\u{2218}\u{1D54A}\u{221A}\u{25A1}\u{2293}\
    \u{228F}\u{2291}\u{2290}\u{2292}\u{2294}\u{1D4AE}\
    \u{22C6}\u{22D0}\u{22D0}\u{2286}\u{227B}\u{2AB0}\
    \u{227D}\u{227F}\u{220B}\u{2211}\u{22D1}\u{2283}\
    \u{2287}\u{22D1}\u{00DE}\u{2122}\u{040B}\u{0426}\
    \u{0009}\u{03A4}\u{0164}\u{0162}\u{0422}\u{1D517}\
    \u{2234}\u{0398}\u{205F}\u{200A}\u{2009}\u{223C}\u{2243}\
    \u{2245}\u{2248}\u{1D54B}\u{20DB}\u{1D4AF}\u{0166}\
    \u{00DA}\u{219F}\u{2949}\u{040E}\u{016C}\u{00DB}\
    \u{0423}\u{0170}\u{1D518}\u{00D9}\u{016A}\u{005F}\
    \u{23DF}\u{23B5}\u{23DD}\u{22C3}\u{228E}\u{0172}\
    \u{1D54C}\u{2191}\u{2912}\u{21C5}\u{2195}\u{296E}\
    \u{22A5}\u{21A5}\u{21D1}\u{21D5}\u{2196}\u{2197}\
    \u{03D2}\u{03A5}\u{016E}\u{1D4B0}\u{0168}\u{00DC}\
    \u{22AB}\u{2AEB}\u{0412}\u{22A9}\u{2AE6}\u{22C1}\
    \u{2016}\u{2016}\u{2223}\u{007C}\u{2758}\u{2240}\
    \u{200A}\u{1D519}\u{1D54D}\u{1D4B1}\u{22AA}\u{0174}\
    \u{22C0}\u{1D51A}\u{1D54E}\u{1D4B2}\u{1D51B}\u{039E}\
    \u{1D54F}\u{1D4B3}\u{042F}\u{0407}\u{042E}\u{00DD}\
    \u{0176}\u{042B}\u{1D51C}\u{1D550}\u{1D4B4}\u{0178}\
    \u{0416}\u{0179}\u{017D}\u{0417}\u{017B}\u{200B}\
    \u{0396}\u{2128}\u{2124}\u{1D4B5}\u{00E1}\u{0103}\
    \u{223E}\u{223E}\u{0333}\u{223F}\u{00E2}\u{00B4}\u{0430}\
    \u{00E6}\u{2061}\u{1D51E}\u{00E0}\u{2135}\u{2135}\
    \u{03B1}\u{0101}\u{2A3F}\u{0026}\u{2227}\u{2A55}\
    \u{2A5C}\u{2A58}\u{2A5A}\u{2220}\u{29A4}\u{2220}\
    \u{2221}\u{29A8}\u{29A9}\u{29AA}\u{29AB}\u{29AC}\
    \u{29AD}\u{29AE}\u{29AF}\u{221F}\u{22BE}\u{299D}\
    \u{2222}\u{00C5}\u{237C}\u{0105}\u{1D552}\u{2248}\
    \u{2A70}\u{2A6F}\u{224A}\u{224B}\u{0027}\u{2248}\
    \u{224A}\u{00E5}\u{1D4B6}\u{002A}\u{2248}\u{224D}\
    \u{00E3}\u{00E4}\u{2233}\u{2A11}\u{2AED}\u{224C}\
    \u{03F6}\u{2035}\u{223D}\u{22CD}\u{22BD}\u{2305}\
    \u{2305}\u{23B5}\u{23B6}\u{224C}\u{0431}\u{201E}\
    \u{2235}\u{2235}\u{29B0}\u{03F6}\u{212C}\u{03B2}\
    \u{2136}\u{226C}\u{1D51F}\u{22C2}\u{25EF}\u{22C3}\
    \u{2A00}\u{2A01}\u{2A02}\u{2A06}\u{2605}\u{25BD}\
    \u{25B3}\u{2A04}\u{22C1}\u{22C0}\u{290D}\u{29EB}\
    \u{25AA}\u{25B4}\u{25BE}\u{25C2}\u{25B8}\u{2423}\
    \u{2592}\u{2591}\u{2593}\u{2588}\u{003D}\u{20E5}\u{2261}\u{20E5}\
    \u{2310}\u{1D553}\u{22A5}\u{22A5}\u{22C8}\u{2557}\
    \u{2554}\u{2556}\u{2553}\u{2550}\u{2566}\u{2569}\
    \u{2564}\u{2567}\u{255D}\u{255A}\u{255C}\u{2559}\
    \u{2551}\u{256C}\u{2563}\u{2560}\u{256B}\u{2562}\
    \u{255F}\u{29C9}\u{2555}\u{2552}\u{2510}\u{250C}\
    \u{2500}\u{2565}\u{2568}\u{252C}\u{2534}\u{229F}\
    \u{229E}\u{22A0}\u{255B}\u{2558}\u{2518}\u{2514}\
    \u{2502}\u{256A}\u{2561}\u{255E}\u{253C}\u{2524}\
    \u{251C}\u{2035}\u{02D8}\u{00A6}\u{1D4B7}\u{204F}\
    \u{223D}\u{22CD}\u{005C}\u{29C5}\u{27C8}\u{2022}\
    \u{2022}\u{224E}\u{2AAE}\u{224F}\u{224F}\u{0107}\
    \u{2229}\u{2A44}\u{2A49}\u{2A4B}\u{2A47}\u{2A40}\
    \u{2229}\u{FE00}\u{2041}\u{02C7}\u{2A4D}\u{010D}\u{00E7}\
    \u{0109}\u{2A4C}\u{2A50}\u{010B}\u{00B8}\u{29B2}\
    \u{00A2}\u{00B7}\u{1D520}\u{0447}\u{2713}\u{2713}\
    \u{03C7}\u{25CB}\u{29C3}\u{02C6}\u{2257}\u{21BA}\
    \u{21BB}\u{00AE}\u{24C8}\u{229B}\u{229A}\u{229D}\
    \u{2257}\u{2A10}\u{2AEF}\u{29C2}\u{2663}\u{2663}\
    \u{003A}\u{2254}\u{2254}\u{002C}\u{0040}\u{2201}\
    \u{2218}\u{2201}\u{2102}\u{2245}\u{2A6D}\u{222E}\
    \u{1D554}\u{2210}\u{00A9}\u{2117}\u{21B5}\u{2717}\
    \u{1D4B8}\u{2ACF}\u{2AD1}\u{2AD0}\u{2AD2}\u{22EF}\
    \u{2938}\u{2935}\u{22DE}\u{22DF}\u{21B6}\u{293D}\
    \u{222A}\u{2A48}\u{2A46}\u{2A4A}\u{228D}\u{2A45}\
    \u{222A}\u{FE00}\u{21B7}\u{293C}\u{22DE}\u{22DF}\u{22CE}\
    \u{22CF}\u{00A4}\u{21B6}\u{21B7}\u{22CE}\u{22CF}\
    \u{2232}\u{2231}\u{232D}\u{21D3}\u{2965}\u{2020}\
    \u{2138}\u{2193}\u{2010}\u{22A3}\u{290F}\u{02DD}\
    \u{010F}\u{0434}\u{2146}\u{2021}\u{21CA}\u{2A77}\
    \u{00B0}\u{03B4}\u{29B1}\u{297F}\u{1D521}\u{21C3}\
    \u{21C2}\u{22C4}\u{22C4}\u{2666}\u{2666}\u{00A8}\
    \u{03DD}\u{22F2}\u{00F7}\u{00F7}\u{22C7}\u{22C7}\
    \u{0452}\u{231E}\u{230D}\u{0024}\u{1D555}\u{02D9}\
    \u{2250}\u{2251}\u{2238}\u{2214}\u{22A1}\u{2306}\
    \u{2193}\u{21CA}\u{21C3}\u{21C2}\u{2910}\u{231F}\
    \u{230C}\u{1D4B9}\u{0455}\u{29F6}\u{0111}\u{22F1}\
    \u{25BF}\u{25BE}\u{21F5}\u{296F}\u{29A6}\u{045F}\
    \u{27FF}\u{2A77}\u{2251}\u{00E9}\u{2A6E}\u{011B}\
    \u{2256}\u{00EA}\u{2255}\u{044D}\u{0117}\u{2147}\
    \u{2252}\u{1D522}\u{2A9A}\u{00E8}\u{2A96}\u{2A98}\
    \u{2A99}\u{23E7}\u{2113}\u{2A95}\u{2A97}\u{0113}\
    \u{2205}\u{2205}\u{2205}\u{2003}\u{2004}\u{2005}\
    \u{014B}\u{2002}\u{0119}\u{1D556}\u{22D5}\u{29E3}\
    \u{2A71}\u{03B5}\u{03B5}\u{03F5}\u{2256}\u{2255}\
    \u{2242}\u{2A96}\u{2A95}\u{003D}\u{225F}\u{2261}\
    \u{2A78}\u{29E5}\u{2253}\u{2971}\u{212F}\u{2250}\
    \u{2242}\u{03B7}\u{00F0}\u{00EB}\u{20AC}\u{0021}\
    \u{2203}\u{2130}\u{2147}\u{2252}\u{0444}\u{2640}\
    \u{FB03}\u{FB00}\u{FB04}\u{1D523}\u{FB01}\u{0066}\u{006A}\
    \u{266D}\u{FB02}\u{25B1}\u{0192}\u{1D557}\u{2200}\
    \u{22D4}\u{2AD9}\u{2A0D}\u{00BD}\u{2153}\u{00BC}\
    \u{2155}\u{2159}\u{215B}\u{2154}\u{2156}\u{00BE}\
    \u{2157}\u{215C}\u{2158}\u{215A}\u{215D}\u{215E}\
    \u{2044}\u{2322}\u{1D4BB}\u{2267}\u{2A8C}\u{01F5}\
    \u{03B3}\u{03DD}\u{2A86}\u{011F}\u{011D}\u{0433}\
    \u{0121}\u{2265}\u{22DB}\u{2265}\u{2267}\u{2A7E}\
    \u{2A7E}\u{2AA9}\u{2A80}\u{2A82}\u{2A84}\u{22DB}\u{FE00}\
    \u{2A94}\u{1D524}\u{226B}\u{22D9}\u{2137}\u{0453}\
    \u{2277}\u{2A92}\u{2AA5}\u{2AA4}\u{2269}\u{2A8A}\
    \u{2A8A}\u{2A88}\u{2A88}\u{2269}\u{22E7}\u{1D558}\
    \u{0060}\u{210A}\u{2273}\u{2A8E}\u{2A90}\u{003E}\
    \u{2AA7}\u{2A7A}\u{22D7}\u{2995}\u{2A7C}\u{2A86}\
    \u{2978}\u{22D7}\u{22DB}\u{2A8C}\u{2277}\u{2273}\
    \u{2269}\u{FE00}\u{2269}\u{FE00}\u{21D4}\u{200A}\u{00BD}\u{210B}\
    \u{044A}\u{2194}\u{2948}\u{21AD}\u{210F}\u{0125}\
    \u{2665}\u{2665}\u{2026}\u{22B9}\u{1D525}\u{2925}\
    \u{2926}\u{21FF}\u{223B}\u{21A9}\u{21AA}\u{1D559}\
    \u{2015}\u{1D4BD}\u{210F}\u{0127}\u{2043}\u{2010}\
    \u{00ED}\u{2063}\u{00EE}\u{0438}\u{0435}\u{00A1}\
    \u{21D4}\u{1D526}\u{00EC}\u{2148}\u{2A0C}\u{222D}\
    \u{29DC}\u{2129}\u{0133}\u{012B}\u{2111}\u{2110}\
    \u{2111}\u{0131}\u{22B7}\u{01B5}\u{2208}\u{2105}\
    \u{221E}\u{29DD}\u{0131}\u{222B}\u{22BA}\u{2124}\
    \u{22BA}\u{2A17}\u{2A3C}\u{0451}\u{012F}\u{1D55A}\
    \u{03B9}\u{2A3C}\u{00BF}\u{1D4BE}\u{2208}\u{22F9}\
    \u{22F5}\u{22F4}\u{22F3}\u{2208}\u{2062}\u{0129}\
    \u{0456}\u{00EF}\u{0135}\u{0439}\u{1D527}\u{0237}\
    \u{1D55B}\u{1D4BF}\u{0458}\u{0454}\u{03BA}\u{03F0}\
    \u{0137}\u{043A}\u{1D528}\u{0138}\u{0445}\u{045C}\
    \u{1D55C}\u{1D4C0}\u{21DA}\u{21D0}\u{291B}\u{290E}\
    \u{2266}\u{2A8B}\u{2962}\u{013A}\u{29B4}\u{2112}\
    \u{03BB}\u{27E8}\u{2991}\u{27E8}\u{2A85}\u{00AB}\
    \u{2190}\u{21E4}\u{291F}\u{291D}\u{21A9}\u{21AB}\
    \u{2939}\u{2973}\u{21A2}\u{2AAB}\u{2919}\u{2AAD}\
    \u{2AAD}\u{FE00}\u{290C}\u{2772}\u{007B}\u{005B}\u{298B}\
    \u{298F}\u{298D}\u{013E}\u{013C}\u{2308}\u{007B}\
    \u{043B}\u{2936}\u{201C}\u{201E}\u{2967}\u{294B}\
    \u{21B2}\u{2264}\u{2190}\u{21A2}\u{21BD}\u{21BC}\
    \u{21C7}\u{2194}\u{21C6}\u{21CB}\u{21AD}\u{22CB}\
    \u{22DA}\u{2264}\u{2266}\u{2A7D}\u{2A7D}\u{2AA8}\
    \u{2A7F}\u{2A81}\u{2A83}\u{22DA}\u{FE00}\u{2A93}\u{2A85}\
    \u{22D6}\u{22DA}\u{2A8B}\u{2276}\u{2272}\u{297C}\
    \u{230A}\u{1D529}\u{2276}\u{2A91}\u{21BD}\u{21BC}\
    \u{296A}\u{2584}\u{0459}\u{226A}\u{21C7}\u{231E}\
    \u{296B}\u{25FA}\u{0140}\u{23B0}\u{23B0}\u{2268}\
    \u{2A89}\u{2A89}\u{2A87}\u{2A87}\u{2268}\u{22E6}\
    \u{27EC}\u{21FD}\u{27E6}\u{27F5}\u{27F7}\u{27FC}\
    \u{27F6}\u{21AB}\u{21AC}\u{2985}\u{1D55D}\u{2A2D}\
    \u{2A34}\u{2217}\u{005F}\u{25CA}\u{25CA}\u{29EB}\
    \u{0028}\u{2993}\u{21C6}\u{231F}\u{21CB}\u{296D}\
    \u{200E}\u{22BF}\u{2039}\u{1D4C1}\u{21B0}\u{2272}\
    \u{2A8D}\u{2A8F}\u{005B}\u{2018}\u{201A}\u{0142}\
    \u{003C}\u{2AA6}\u{2A79}\u{22D6}\u{22CB}\u{22C9}\
    \u{2976}\u{2A7B}\u{2996}\u{25C3}\u{22B4}\u{25C2}\
    \u{294A}\u{2966}\u{2268}\u{FE00}\u{2268}\u{FE00}\u{223A}\u{00AF}\
    \u{2642}\u{2720}\u{2720}\u{21A6}\u{21A6}\u{21A7}\
    \u{21A4}\u{21A5}\u{25AE}\u{2A29}\u{043C}\u{2014}\
    \u{2221}\u{1D52A}\u{2127}\u{00B5}\u{2223}\u{002A}\
    \u{2AF0}\u{00B7}\u{2212}\u{229F}\u{2238}\u{2A2A}\
    \u{2ADB}\u{2026}\u{2213}\u{22A7}\u{1D55E}\u{2213}\
    \u{1D4C2}\u{223E}\u{03BC}\u{22B8}\u{22B8}\u{22D9}\u{0338}\
    \u{226B}\u{20D2}\u{226B}\u{0338}\u{21CD}\u{21CE}\u{22D8}\u{0338}\u{226A}\u{20D2}\
    \u{226A}\u{0338}\u{21CF}\u{22AF}\u{22AE}\u{2207}\u{0144}\
    \u{2220}\u{20D2}\u{2249}\u{2A70}\u{0338}\u{224B}\u{0338}\u{0149}\u{2249}\
    \u{266E}\u{266E}\u{2115}\u{00A0}\u{224E}\u{0338}\u{224F}\u{0338}\
    \u{2A43}\u{0148}\u{0146}\u{2247}\u{2A6D}\u{0338}\u{2A42}\
    \u{043D}\u{2013}\u{2260}\u{21D7}\u{2924}\u{2197}\
    \u{2197}\u{2250}\u{0338}\u{2262}\u{2928}\u{2242}\u{0338}\u{2204}\
    \u{2204}\u{1D52B}\u{2267}\u{0338}\u{2271}\u{2271}\u{2267}\u{0338}\
    \u{2A7E}\u{0338}\u{2A7E}\u{0338}\u{2275}\u{226F}\u{226F}\u{21CE}\
    \u{21AE}\u{2AF2}\u{220B}\u{22FC}\u{22FA}\u{220B}\
    \u{045A}\u{21CD}\u{2266}\u{0338}\u{219A}\u{2025}\u{2270}\
    \u{219A}\u{21AE}\u{2270}\u{2266}\u{0338}\u{2A7D}\u{0338}\u{2A7D}\u{0338}\
    \u{226E}\u{2274}\u{226E}\u{22EA}\u{22EC}\u{2224}\
    \u{1D55F}\u{00AC}\u{2209}\u{22F9}\u{0338}\u{22F5}\u{0338}\u{2209}\
    \u{22F7}\u{22F6}\u{220C}\u{220C}\u{22FE}\u{22FD}\
    \u{2226}\u{2226}\u{2AFD}\u{20E5}\u{2202}\u{0338}\u{2A14}\u{2280}\
    \u{22E0}\u{2AAF}\u{0338}\u{2280}\u{2AAF}\u{0338}\u{21CF}\u{219B}\
    \u{2933}\u{0338}\u{219D}\u{0338}\u{219B}\u{22EB}\u{22ED}\u{2281}\
    \u{22E1}\u{2AB0}\u{0338}\u{1D4C3}\u{2224}\u{2226}\u{2241}\
    \u{2244}\u{2244}\u{2224}\u{2226}\u{22E2}\u{22E3}\
    \u{2284}\u{2AC5}\u{0338}\u{2288}\u{2282}\u{20D2}\u{2288}\u{2AC5}\u{0338}\
    \u{2281}\u{2AB0}\u{0338}\u{2285}\u{2AC6}\u{0338}\u{2289}\u{2283}\u{20D2}\
    \u{2289}\u{2AC6}\u{0338}\u{2279}\u{00F1}\u{2278}\u{22EA}\
    \u{22EC}\u{22EB}\u{22ED}\u{03BD}\u{0023}\u{2116}\
    \u{2007}\u{22AD}\u{2904}\u{224D}\u{20D2}\u{22AC}\u{2265}\u{20D2}\
    \u{003E}\u{20D2}\u{29DE}\u{2902}\u{2264}\u{20D2}\u{003C}\u{20D2}\u{22B4}\u{20D2}\
    \u{2903}\u{22B5}\u{20D2}\u{223C}\u{20D2}\u{21D6}\u{2923}\u{2196}\
    \u{2196}\u{2927}\u{24C8}\u{00F3}\u{229B}\u{229A}\
    \u{00F4}\u{043E}\u{229D}\u{0151}\u{2A38}\u{2299}\
    \u{29BC}\u{0153}\u{29BF}\u{1D52C}\u{02DB}\u{00F2}\
    \u{29C1}\u{29B5}\u{03A9}\u{222E}\u{21BA}\u{29BE}\
    \u{29BB}\u{203E}\u{29C0}\u{014D}\u{03C9}\u{03BF}\
    \u{29B6}\u{2296}\u{1D560}\u{29B7}\u{29B9}\u{2295}\
    \u{2228}\u{21BB}\u{2A5D}\u{2134}\u{2134}\u{00AA}\
    \u{00BA}\u{22B6}\u{2A56}\u{2A57}\u{2A5B}\u{2134}\
    \u{00F8}\u{2298}\u{00F5}\u{2297}\u{2A36}\u{00F6}\
    \u{233D}\u{2225}\u{00B6}\u{2225}\u{2AF3}\u{2AFD}\
    \u{2202}\u{043F}\u{0025}\u{002E}\u{2030}\u{22A5}\
    \u{2031}\u{1D52D}\u{03C6}\u{03D5}\u{2133}\u{260E}\
    \u{03C0}\u{22D4}\u{03D6}\u{210F}\u{210E}\u{210F}\
    \u{002B}\u{2A23}\u{229E}\u{2A22}\u{2214}\u{2A25}\
    \u{2A72}\u{00B1}\u{2A26}\u{2A27}\u{00B1}\u{2A15}\
    \u{1D561}\u{00A3}\u{227A}\u{2AB3}\u{2AB7}\u{227C}\
    \u{2AAF}\u{227A}\u{2AB7}\u{227C}\u{2AAF}\u{2AB9}\
    \u{2AB5}\u{22E8}\u{227E}\u{2032}\u{2119}\u{2AB5}\
    \u{2AB9}\u{22E8}\u{220F}\u{232E}\u{2312}\u{2313}\
    \u{221D}\u{221D}\u{227E}\u{22B0}\u{1D4C5}\u{03C8}\
    \u{2008}\u{1D52E}\u{2A0C}\u{1D562}\u{2057}\u{1D4C6}\
    \u{210D}\u{2A16}\u{003F}\u{225F}\u{0022}\u{21DB}\
    \u{21D2}\u{291C}\u{290F}\u{2964}\u{223D}\u{0331}\u{0155}\
    \u{221A}\u{29B3}\u{27E9}\u{2992}\u{29A5}\u{27E9}\
    \u{00BB}\u{2192}\u{2975}\u{21E5}\u{2920}\u{2933}\
    \u{291E}\u{21AA}\u{21AC}\u{2945}\u{2974}\u{21A3}\
    \u{219D}\u{291A}\u{2236}\u{211A}\u{290D}\u{2773}\
    \u{007D}\u{005D}\u{298C}\u{298E}\u{2990}\u{0159}\
    \u{0157}\u{2309}\u{007D}\u{0440}\u{2937}\u{2969}\
    \u{201D}\u{201D}\u{21B3}\u{211C}\u{211B}\u{211C}\
    \u{211D}\u{25AD}\u{00AE}\u{297D}\u{230B}\u{1D52F}\
    \u{21C1}\u{21C0}\u{296C}\u{03C1}\u{03F1}\u{2192}\
    \u{21A3}\u{21C1}\u{21C0}\u{21C4}\u{21CC}\u{21C9}\
    \u{219D}\u{22CC}\u{02DA}\u{2253}\u{21C4}\u{21CC}\
    \u{200F}\u{23B1}\u{23B1}\u{2AEE}\u{27ED}\u{21FE}\
    \u{27E7}\u{2986}\u{1D563}\u{2A2E}\u{2A35}\u{0029}\
    \u{2994}\u{2A12}\u{21C9}\u{203A}\u{1D4C7}\u{21B1}\
    \u{005D}\u{2019}\u{2019}\u{22CC}\u{22CA}\u{25B9}\
    \u{22B5}\u{25B8}\u{29CE}\u{2968}\u{211E}\u{015B}\
    \u{201A}\u{227B}\u{2AB4}\u{2AB8}\u{0161}\u{227D}\
    \u{2AB0}\u{015F}\u{015D}\u{2AB6}\u{2ABA}\u{22E9}\
    \u{2A13}\u{227F}\u{0441}\u{22C5}\u{22A1}\u{2A66}\
    \u{21D8}\u{2925}\u{2198}\u{2198}\u{00A7}\u{003B}\
    \u{2929}\u{2216}\u{2216}\u{2736}\u{1D530}\u{2322}\
    \u{266F}\u{0449}\u{0448}\u{2223}\u{2225}\u{00AD}\
    \u{03C3}\u{03C2}\u{03C2}\u{223C}\u{2A6A}\u{2243}\
    \u{2243}\u{2A9E}\u{2AA0}\u{2A9D}\u{2A9F}\u{2246}\
    \u{2A24}\u{2972}\u{2190}\u{2216}\u{2A33}\u{29E4}\
    \u{2223}\u{2323}\u{2AAA}\u{2AAC}\u{2AAC}\u{FE00}\u{044C}\
    \u{002F}\u{29C4}\u{233F}\u{1D564}\u{2660}\u{2660}\
    \u{2225}\u{2293}\u{2293}\u{FE00}\u{2294}\u{2294}\u{FE00}\u{228F}\
    \u{2291}\u{228F}\u{2291}\u{2290}\u{2292}\u{2290}\
    \u{2292}\u{25A1}\u{25A1}\u{25AA}\u{25AA}\u{2192}\
    \u{1D4C8}\u{2216}\u{2323}\u{22C6}\u{2606}\u{2605}\
    \u{03F5}\u{03D5}\u{00AF}\u{2282}\u{2AC5}\u{2ABD}\
    \u{2286}\u{2AC3}\u{2AC1}\u{2ACB}\u{228A}\u{2ABF}\
    \u{2979}\u{2282}\u{2286}\u{2AC5}\u{228A}\u{2ACB}\
    \u{2AC7}\u{2AD5}\u{2AD3}\u{227B}\u{2AB8}\u{227D}\
    \u{2AB0}\u{2ABA}\u{2AB6}\u{22E9}\u{227F}\u{2211}\
    \u{266A}\u{2283}\u{00B9}\u{00B2}\u{00B3}\u{2AC6}\
    \u{2ABE}\u{2AD8}\u{2287}\u{2AC4}\u{27C9}\u{2AD7}\
    \u{297B}\u{2AC2}\u{2ACC}\u{228B}\u{2AC0}\u{2283}\
    \u{2287}\u{2AC6}\u{228B}\u{2ACC}\u{2AC8}\u{2AD4}\
    \u{2AD6}\u{21D9}\u{2926}\u{2199}\u{2199}\u{292A}\
    \u{00DF}\u{2316}\u{03C4}\u{23B4}\u{0165}\u{0163}\
    \u{0442}\u{20DB}\u{2315}\u{1D531}\u{2234}\u{2234}\
    \u{03B8}\u{03D1}\u{03D1}\u{2248}\u{223C}\u{2009}\
    \u{2248}\u{223C}\u{00FE}\u{02DC}\u{00D7}\u{22A0}\
    \u{2A31}\u{2A30}\u{222D}\u{2928}\u{22A4}\u{2336}\
    \u{2AF1}\u{1D565}\u{2ADA}\u{2929}\u{2034}\u{2122}\
    \u{25B5}\u{25BF}\u{25C3}\u{22B4}\u{225C}\u{25B9}\
    \u{22B5}\u{25EC}\u{225C}\u{2A3A}\u{2A39}\u{29CD}\
    \u{2A3B}\u{23E2}\u{1D4C9}\u{0446}\u{045B}\u{0167}\
    \u{226C}\u{219E}\u{21A0}\u{21D1}\u{2963}\u{00FA}\
    \u{2191}\u{045E}\u{016D}\u{00FB}\u{0443}\u{21C5}\
    \u{0171}\u{296E}\u{297E}\u{1D532}\u{00F9}\u{21BF}\
    \u{21BE}\u{2580}\u{231C}\u{231C}\u{230F}\u{25F8}\
    \u{016B}\u{00A8}\u{0173}\u{1D566}\u{2191}\u{2195}\
    \u{21BF}\u{21BE}\u{228E}\u{03C5}\u{03D2}\u{03C5}\
    \u{21C8}\u{231D}\u{231D}\u{230E}\u{016F}\u{25F9}\
    \u{1D4CA}\u{22F0}\u{0169}\u{25B5}\u{25B4}\u{21C8}\
    \u{00FC}\u{29A7}\u{21D5}\u{2AE8}\u{2AE9}\u{22A8}\
    \u{299C}\u{03F5}\u{03F0}\u{2205}\u{03D5}\u{03D6}\
    \u{221D}\u{2195}\u{03F1}\u{03C2}\u{228A}\u{FE00}\u{2ACB}\u{FE00}\
    \u{228B}\u{FE00}\u{2ACC}\u{FE00}\u{03D1}\u{22B2}\u{22B3}\u{0432}\
    \u{22A2}\u{2228}\u{22BB}\u{225A}\u{22EE}\u{007C}\
    \u{007C}\u{1D533}\u{22B2}\u{2282}\u{20D2}\u{2283}\u{20D2}\u{1D567}\
    \u{221D}\u{22B3}\u{1D4CB}\u{2ACB}\u{FE00}\u{228A}\u{FE00}\u{2ACC}\u{FE00}\
    \u{228B}\u{FE00}\u{299A}\u{0175}\u{2A5F}\u{2227}\u{2259}\
    \u{2118}\u{1D534}\u{1D568}\u{2118}\u{2240}\u{2240}\
    \u{1D4CC}\u{22C2}\u{25EF}\u{22C3}\u{25BD}\u{1D535}\
    \u{27FA}\u{27F7}\u{03BE}\u{27F8}\u{27F5}\u{27FC}\
    \u{22FB}\u{2A00}\u{1D569}\u{2A01}\u{2A02}\u{27F9}\
    \u{27F6}\u{1D4CD}\u{2A06}\u{2A04}\u{25B3}\u{22C1}\
    \u{22C0}\u{00FD}\u{044F}\u{0177}\u{044B}\u{00A5}\
    \u{1D536}\u{0457}\u{1D56A}\u{1D4CE}\u{044E}\u{00FF}\
    \u{017A}\u{017E}\u{0437}\u{017C}\u{2128}\u{03B6}\
    \u{1D537}\u{0436}\u{21DD}\u{1D56B}\u{1D4CF}\u{200D}\
    \u{200C}";

/// `(name offset, name length, expansion offset, expansion length)` per entity,
/// sorted by name for binary search. Offsets, not `&str`, to avoid relocations.
static ENTITY_INDEX: [(u16, u8, u16, u8); 2125] = [
    (0, 5, 0, 2),
    (5, 3, 2, 1),
    (8, 6, 3, 2),
    (14, 6, 5, 2),
    (20, 5, 7, 2),
    (25, 3, 9, 2),
    (28, 3, 11, 4),
    (31, 6, 15, 2),
    (37, 5, 17, 2),
    (42, 5, 19, 2),
    (47, 3, 21, 3),
    (50, 5, 24, 2),
    (55, 4, 26, 4),
    (59, 13, 30, 3),
    (72, 5, 33, 2),
    (77, 4, 35, 4),
    (81, 6, 39, 3),
    (87, 6, 42, 2),
    (93, 4, 44, 2),
    (97, 9, 46, 3),
    (106, 4, 49, 3),
    (110, 6, 52, 3),
    (116, 3, 55, 2),
    (119, 7, 57, 3),
    (126, 10, 60, 3),
    (136, 4, 63, 2),
    (140, 3, 65, 4),
    (143, 4, 69, 4),
    (147, 5, 73, 2),
    (152, 4, 75, 3),
    (156, 6, 78, 3),
    (162, 4, 81, 2),
    (166, 4, 83, 2),
    (170, 6, 85, 2),
    (176, 3, 87, 3),
    (179, 20, 90, 3),
    (199, 7, 93, 3),
    (206, 6, 96, 2),
    (212, 6, 98, 2),
    (218, 5, 100, 2),
    (223, 7, 102, 3),
    (230, 4, 105, 2),
    (234, 7, 107, 2),
    (241, 9, 109, 2),
    (250, 3, 111, 3),
    (253, 3, 114, 2),
    (256, 9, 116, 3),
    (265, 11, 119, 3),
    (276, 10, 122, 3),
    (286, 11, 125, 3),
    (297, 24, 128, 3),
    (321, 21, 131, 3),
    (342, 15, 134, 3),
    (357, 5, 137, 3),
    (362, 6, 140, 3),
    (368, 9, 143, 3),
    (377, 6, 146, 3),
    (383, 15, 149, 3),
    (398, 4, 152, 3),
    (402, 9, 155, 3),
    (411, 31, 158, 3),
    (442, 5, 161, 3),
    (447, 4, 164, 4),
    (451, 3, 168, 3),
    (454, 6, 171, 3),
    (460, 2, 174, 3),
    (462, 8, 177, 3),
    (470, 4, 180, 2),
    (474, 4, 182, 2),
    (478, 4, 184, 2),
    (482, 6, 186, 3),
    (488, 4, 189, 3),
    (492, 5, 192, 3),
    (497, 6, 195, 2),
    (503, 3, 197, 2),
    (506, 3, 199, 3),
    (509, 5, 202, 2),
    (514, 3, 204, 4),
    (517, 16, 208, 2),
    (533, 14, 210, 2),
    (547, 22, 212, 2),
    (569, 16, 214, 1),
    (585, 16, 215, 2),
    (601, 7, 217, 3),
    (608, 13, 220, 3),
    (621, 4, 223, 4),
    (625, 3, 227, 2),
    (628, 6, 229, 3),
    (634, 8, 232, 3),
    (642, 21, 235, 3),
    (663, 9, 238, 2),
    (672, 15, 240, 3),
    (687, 15, 243, 3),
    (702, 20, 246, 3),
    (722, 13, 249, 3),
    (735, 19, 252, 3),
    (754, 24, 255, 3),
    (778, 20, 258, 3),
    (798, 16, 261, 3),
    (814, 14, 264, 3),
    (828, 13, 267, 3),
    (841, 17, 270, 3),
    (858, 17, 273, 3),
    (875, 9, 276, 3),
    (884, 12, 279, 3),
    (896, 16, 282, 3),
    (912, 9, 285, 2),
    (921, 19, 287, 3),
    (940, 17, 290, 3),
    (957, 14, 293, 3),
    (971, 17, 296, 3),
    (988, 18, 299, 3),
    (1006, 15, 302, 3),
    (1021, 18, 305, 3),
    (1039, 7, 308, 3),
    (1046, 12, 311, 3),
    (1058, 9, 314, 3),
    (1067, 4, 317, 4),
    (1071, 6, 321, 2),
    (1077, 3, 323, 2),
    (1080, 3, 325, 2),
    (1083, 6, 327, 2),
    (1089, 6, 329, 2),
    (1095, 5, 331, 2),
    (1100, 3, 333, 2),
    (1103, 4, 335, 2),
    (1107, 3, 337, 4),
    (1110, 6, 341, 2),
    (1116, 7, 343, 3),
    (1123, 5, 346, 2),
    (1128, 16, 348, 3),
    (1144, 20, 351, 3),
    (1164, 5, 354, 2),
    (1169, 4, 356, 4),
    (1173, 7, 360, 2),
    (1180, 5, 362, 3),
    (1185, 10, 365, 3),
    (1195, 11, 368, 3),
    (1206, 4, 371, 3),
    (1210, 4, 374, 3),
    (1214, 3, 377, 2),
    (1217, 4, 379, 2),
    (1221, 6, 381, 3),
    (1227, 12, 384, 3),
    (1239, 3, 387, 2),
    (1242, 3, 389, 4),
    (1245, 17, 393, 3),
    (1262, 21, 396, 3),
    (1283, 4, 399, 4),
    (1287, 6, 403, 3),
    (1293, 10, 406, 3),
    (1303, 4, 409, 3),
    (1307, 4, 412, 2),
    (1311, 2, 414, 1),
    (1313, 5, 415, 2),
    (1318, 6, 417, 2),
    (1324, 6, 419, 2),
    (1330, 6, 421, 2),
    (1336, 5, 423, 2),
    (1341, 3, 425, 2),
    (1344, 4, 427, 2),
    (1348, 3, 429, 4),
    (1351, 2, 433, 3),
    (1353, 4, 436, 4),
    (1357, 12, 440, 3),
    (1369, 16, 443, 3),
    (1385, 16, 446, 3),
    (1401, 14, 449, 3),
    (1415, 11, 452, 3),
    (1426, 17, 455, 3),
    (1443, 12, 458, 3),
    (1455, 4, 461, 4),
    (1459, 2, 465, 3),
    (1461, 6, 468, 2),
    (1467, 5, 470, 2),
    (1472, 3, 472, 1),
    (1475, 5, 473, 2),
    (1480, 3, 475, 3),
    (1483, 12, 478, 3),
    (1495, 4, 481, 3),
    (1499, 14, 484, 3),
    (1513, 4, 487, 3),
    (1517, 6, 490, 2),
    (1523, 12, 492, 3),
    (1535, 9, 495, 3),
    (1544, 4, 498, 2),
    (1548, 5, 500, 2),
    (1553, 4, 502, 2),
    (1557, 6, 504, 2),
    (1563, 5, 506, 2),
    (1568, 3, 508, 2),
    (1571, 4, 510, 2),
    (1575, 3, 512, 3),
    (1578, 6, 515, 2),
    (1584, 2, 517, 3),
    (1586, 5, 520, 2),
    (1591, 10, 522, 3),
    (1601, 7, 525, 3),
    (1608, 3, 528, 3),
    (1611, 8, 531, 3),
    (1619, 12, 534, 3),
    (1631, 14, 537, 3),
    (1645, 14, 540, 3),
    (1659, 5, 543, 2),
    (1664, 4, 545, 4),
    (1668, 4, 549, 2),
    (1672, 4, 551, 3),
    (1676, 6, 554, 2),
    (1682, 5, 556, 2),
    (1687, 4, 558, 2),
    (1691, 5, 560, 2),
    (1696, 3, 562, 2),
    (1699, 3, 564, 4),
    (1702, 4, 568, 4),
    (1706, 4, 572, 4),
    (1710, 6, 576, 2),
    (1716, 5, 578, 2),
    (1721, 4, 580, 2),
    (1725, 4, 582, 2),
    (1729, 5, 584, 2),
    (1734, 6, 586, 2),
    (1740, 3, 588, 2),
    (1743, 3, 590, 4),
    (1746, 4, 594, 4),
    (1750, 4, 598, 4),
    (1754, 4, 602, 2),
    (1758, 2, 604, 1),
    (1760, 6, 605, 2),
    (1766, 6, 607, 2),
    (1772, 4, 609, 3),
    (1776, 10, 612, 3),
    (1786, 4, 615, 3),
    (1790, 6, 618, 2),
    (1796, 6, 620, 2),
    (1802, 3, 622, 2),
    (1805, 16, 624, 3),
    (1821, 9, 627, 3),
    (1830, 12, 630, 3),
    (1842, 19, 633, 3),
    (1861, 11, 636, 3),
    (1872, 17, 639, 3),
    (1889, 17, 642, 3),
    (1906, 14, 645, 3),
    (1920, 17, 648, 3),
    (1937, 9, 651, 3),
    (1946, 14, 654, 3),
    (1960, 15, 657, 3),
    (1975, 7, 660, 3),
    (1982, 12, 663, 3),
    (1994, 13, 666, 3),
    (2007, 12, 669, 3),
    (2019, 15, 672, 3),
    (2034, 17, 675, 3),
    (2051, 16, 678, 3),
    (2067, 15, 681, 3),
    (2082, 12, 684, 3),
    (2094, 15, 687, 3),
    (2109, 10, 690, 3),
    (2119, 13, 693, 3),
    (2132, 9, 696, 3),
    (2141, 14, 699, 3),
    (2155, 16, 702, 3),
    (2171, 13, 705, 3),
    (2184, 11, 708, 3),
    (2195, 8, 711, 3),
    (2203, 14, 714, 3),
    (2217, 9, 717, 3),
    (2226, 3, 720, 4),
    (2229, 2, 724, 3),
    (2231, 10, 727, 3),
    (2241, 6, 730, 2),
    (2247, 13, 732, 3),
    (2260, 18, 735, 3),
    (2278, 14, 738, 3),
    (2292, 13, 741, 3),
    (2305, 18, 744, 3),
    (2323, 14, 747, 3),
    (2337, 4, 750, 4),
    (2341, 14, 754, 3),
    (2355, 15, 757, 3),
    (2370, 4, 760, 3),
    (2374, 3, 763, 3),
    (2377, 6, 766, 2),
    (2383, 2, 768, 3),
    (2385, 3, 771, 3),
    (2388, 3, 774, 2),
    (2391, 11, 776, 3),
    (2402, 9, 779, 3),
    (2411, 3, 782, 4),
    (2414, 9, 786, 3),
    (2423, 4, 789, 4),
    (2427, 4, 793, 3),
    (2431, 2, 796, 2),
    (2433, 4, 798, 2),
    (2437, 6, 800, 2),
    (2443, 6, 802, 2),
    (2449, 6, 804, 2),
    (2455, 3, 806, 2),
    (2458, 19, 808, 3),
    (2477, 18, 811, 3),
    (2495, 17, 814, 3),
    (2512, 21, 817, 3),
    (2533, 20, 820, 3),
    (2553, 14, 823, 3),
    (2567, 7, 826, 1),
    (2574, 3, 827, 4),
    (2577, 7, 831, 3),
    (2584, 16, 834, 2),
    (2600, 4, 836, 3),
    (2604, 3, 839, 3),
    (2607, 12, 842, 3),
    (2619, 9, 845, 3),
    (2628, 20, 848, 3),
    (2648, 10, 851, 3),
    (2658, 8, 854, 3),
    (2666, 13, 857, 5),
    (2679, 9, 862, 3),
    (2688, 10, 865, 3),
    (2698, 15, 868, 3),
    (2713, 19, 871, 5),
    (2732, 17, 876, 5),
    (2749, 14, 881, 3),
    (2763, 20, 884, 5),
    (2783, 15, 889, 3),
    (2798, 15, 892, 5),
    (2813, 12, 897, 5),
    (2825, 15, 902, 3),
    (2840, 18, 905, 5),
    (2858, 20, 910, 3),
    (2878, 7, 913, 3),
    (2885, 12, 916, 3),
    (2897, 14, 919, 3),
    (2911, 11, 922, 5),
    (2922, 17, 927, 5),
    (2939, 12, 932, 3),
    (2951, 23, 935, 5),
    (2974, 17, 940, 5),
    (2991, 11, 945, 3),
    (3002, 16, 948, 5),
    (3018, 21, 953, 3),
    (3039, 17, 956, 3),
    (3056, 16, 959, 3),
    (3072, 19, 962, 5),
    (3091, 21, 967, 3),
    (3112, 15, 970, 5),
    (3127, 20, 975, 3),
    (3147, 17, 978, 5),
    (3164, 22, 983, 3),
    (3186, 9, 986, 6),
    (3195, 14, 992, 3),
    (3209, 11, 995, 3),
    (3220, 16, 998, 5),
    (3236, 21, 1003, 3),
    (3257, 16, 1006, 5),
    (3273, 11, 1011, 6),
    (3284, 16, 1017, 3),
    (3300, 8, 1020, 3),
    (3308, 13, 1023, 3),
    (3321, 17, 1026, 3),
    (3338, 13, 1029, 3),
    (3351, 14, 1032, 3),
    (3365, 4, 1035, 4),
    (3369, 6, 1039, 2),
    (3375, 2, 1041, 2),
    (3377, 5, 1043, 2),
    (3382, 6, 1045, 2),
    (3388, 5, 1047, 2),
    (3393, 3, 1049, 2),
    (3396, 6, 1051, 2),
    (3402, 3, 1053, 4),
    (3405, 6, 1057, 2),
    (3411, 5, 1059, 2),
    (3416, 5, 1061, 2),
    (3421, 7, 1063, 2),
    (3428, 4, 1065, 4),
    (3432, 20, 1069, 3),
    (3452, 14, 1072, 3),
    (3466, 2, 1075, 3),
    (3468, 4, 1078, 4),
    (3472, 6, 1082, 2),
    (3478, 6, 1084, 2),
    (3484, 6, 1086, 3),
    (3490, 4, 1089, 2),
    (3494, 7, 1091, 3),
    (3501, 9, 1094, 3),
    (3510, 11, 1097, 3),
    (3521, 15, 1100, 3),
    (3536, 8, 1103, 3),
    (3544, 3, 1106, 2),
    (3547, 3, 1108, 4),
    (3550, 3, 1112, 2),
    (3553, 2, 1114, 2),
    (3555, 9, 1116, 2),
    (3564, 13, 1118, 3),
    (3577, 4, 1121, 3),
    (3581, 2, 1124, 3),
    (3583, 8, 1127, 3),
    (3591, 13, 1130, 3),
    (3604, 18, 1133, 3),
    (3622, 13, 1136, 3),
    (3635, 5, 1139, 3),
    (3640, 7, 1142, 3),
    (3647, 10, 1145, 3),
    (3657, 12, 1148, 3),
    (3669, 4, 1151, 4),
    (3673, 3, 1155, 2),
    (3676, 4, 1157, 1),
    (3680, 3, 1158, 4),
    (3683, 4, 1162, 3),
    (3687, 4, 1165, 4),
    (3691, 5, 1169, 3),
    (3696, 3, 1172, 2),
    (3699, 6, 1174, 2),
    (3705, 4, 1176, 3),
    (3709, 4, 1179, 3),
    (3713, 6, 1182, 3),
    (3719, 6, 1185, 2),
    (3725, 6, 1187, 2),
    (3731, 3, 1189, 2),
    (3734, 2, 1191, 3),
    (3736, 14, 1194, 3),
    (3750, 18, 1197, 3),
    (3768, 20, 1200, 3),
    (3788, 3, 1203, 3),
    (3791, 3, 1206, 2),
    (3794, 17, 1208, 3),
    (3811, 10, 1211, 3),
    (3821, 13, 1214, 3),
    (3834, 19, 1217, 3),
    (3853, 12, 1220, 3),
    (3865, 18, 1223, 3),
    (3883, 18, 1226, 3),
    (3901, 15, 1229, 3),
    (3916, 18, 1232, 3),
    (3934, 10, 1235, 3),
    (3944, 8, 1238, 3),
    (3952, 13, 1241, 3),
    (3965, 14, 1244, 3),
    (3979, 13, 1247, 3),
    (3992, 16, 1250, 3),
    (4008, 18, 1253, 3),
    (4026, 17, 1256, 3),
    (4043, 16, 1259, 3),
    (4059, 13, 1262, 3),
    (4072, 16, 1265, 3),
    (4088, 11, 1268, 3),
    (4099, 14, 1271, 3),
    (4113, 10, 1274, 3),
    (4123, 4, 1277, 3),
    (4127, 12, 1280, 3),
    (4139, 11, 1283, 3),
    (4150, 4, 1286, 3),
    (4154, 3, 1289, 3),
    (4157, 11, 1292, 3),
    (4168, 6, 1295, 2),
    (4174, 4, 1297, 2),
    (4178, 6, 1299, 2),
    (4184, 6, 1301, 2),
    (4190, 2, 1303, 3),
    (4192, 6, 1306, 2),
    (4198, 6, 1308, 2),
    (4204, 5, 1310, 2),
    (4209, 3, 1312, 2),
    (4212, 3, 1314, 4),
    (4215, 14, 1318, 3),
    (4229, 14, 1321, 3),
    (4243, 15, 1324, 3),
    (4258, 12, 1327, 3),
    (4270, 5, 1330, 2),
    (4275, 11, 1332, 3),
    (4286, 4, 1335, 4),
    (4290, 4, 1339, 3),
    (4294, 6, 1342, 3),
    (4300, 18, 1345, 3),
    (4318, 12, 1348, 3),
    (4330, 17, 1351, 3),
    (4347, 14, 1354, 3),
    (4361, 19, 1357, 3),
    (4380, 11, 1360, 3),
    (4391, 4, 1363, 4),
    (4395, 4, 1367, 3),
    (4399, 3, 1370, 3),
    (4402, 6, 1373, 3),
    (4408, 11, 1376, 3),
    (4419, 8, 1379, 3),
    (4427, 13, 1382, 3),
    (4440, 18, 1385, 3),
    (4458, 13, 1388, 3),
    (4471, 8, 1391, 3),
    (4479, 3, 1394, 3),
    (4482, 3, 1397, 3),
    (4485, 8, 1400, 3),
    (4493, 13, 1403, 3),
    (4506, 6, 1406, 3),
    (4512, 5, 1409, 2),
    (4517, 5, 1411, 3),
    (4522, 5, 1414, 2),
    (4527, 4, 1416, 2),
    (4531, 3, 1418, 1),
    (4534, 3, 1419, 2),
    (4537, 6, 1421, 2),
    (4543, 6, 1423, 2),
    (4549, 3, 1425, 2),
    (4552, 3, 1427, 4),
    (4555, 9, 1431, 3),
    (4564, 5, 1434, 2),
    (4569, 10, 1436, 6),
    (4579, 9, 1442, 3),
    (4588, 5, 1445, 3),
    (4593, 10, 1448, 3),
    (4603, 14, 1451, 3),
    (4617, 10, 1454, 3),
    (4627, 4, 1457, 4),
    (4631, 9, 1461, 3),
    (4640, 4, 1464, 4),
    (4644, 6, 1468, 2),
    (4650, 6, 1470, 2),
    (4656, 4, 1472, 3),
    (4660, 8, 1475, 3),
    (4668, 5, 1478, 2),
    (4673, 6, 1480, 2),
    (4679, 5, 1482, 2),
    (4684, 3, 1484, 2),
    (4687, 6, 1486, 2),
    (4693, 3, 1488, 4),
    (4696, 6, 1492, 2),
    (4702, 5, 1494, 2),
    (4707, 8, 1496, 1),
    (4715, 10, 1497, 3),
    (4725, 12, 1500, 3),
    (4737, 16, 1503, 3),
    (4753, 5, 1506, 3),
    (4758, 9, 1509, 3),
    (4767, 5, 1512, 2),
    (4772, 4, 1514, 4),
    (4776, 7, 1518, 3),
    (4783, 10, 1521, 3),
    (4793, 16, 1524, 3),
    (4809, 11, 1527, 3),
    (4820, 13, 1530, 3),
    (4833, 5, 1533, 3),
    (4838, 10, 1536, 3),
    (4848, 7, 1539, 3),
    (4855, 11, 1542, 3),
    (4866, 14, 1545, 3),
    (4880, 15, 1548, 3),
    (4895, 4, 1551, 2),
    (4899, 7, 1553, 2),
    (4906, 5, 1555, 2),
    (4911, 4, 1557, 4),
    (4915, 6, 1561, 2),
    (4921, 4, 1563, 2),
    (4925, 5, 1565, 3),
    (4930, 4, 1568, 3),
    (4934, 3, 1571, 2),
    (4937, 5, 1573, 3),
    (4942, 6, 1576, 3),
    (4948, 3, 1579, 3),
    (4951, 6, 1582, 3),
    (4957, 4, 1585, 3),
    (4961, 11, 1588, 3),
    (4972, 12, 1591, 1),
    (4984, 17, 1592, 3),
    (5001, 13, 1595, 3),
    (5014, 13, 1598, 3),
    (5027, 3, 1601, 4),
    (5030, 4, 1605, 4),
    (5034, 4, 1609, 4),
    (5038, 6, 1613, 3),
    (5044, 5, 1616, 2),
    (5049, 5, 1618, 3),
    (5054, 3, 1621, 4),
    (5057, 4, 1625, 4),
    (5061, 4, 1629, 4),
    (5065, 3, 1633, 4),
    (5068, 2, 1637, 2),
    (5070, 4, 1639, 4),
    (5074, 4, 1643, 4),
    (5078, 4, 1647, 2),
    (5082, 4, 1649, 2),
    (5086, 4, 1651, 2),
    (5090, 6, 1653, 2),
    (5096, 5, 1655, 2),
    (5101, 3, 1657, 2),
    (5104, 3, 1659, 4),
    (5107, 4, 1663, 4),
    (5111, 4, 1667, 4),
    (5115, 4, 1671, 2),
    (5119, 4, 1673, 2),
    (5123, 6, 1675, 2),
    (5129, 6, 1677, 2),
    (5135, 3, 1679, 2),
    (5138, 4, 1681, 2),
    (5142, 14, 1683, 3),
    (5156, 4, 1686, 2),
    (5160, 3, 1688, 3),
    (5163, 4, 1691, 3),
    (5167, 4, 1694, 4),
    (5171, 6, 1698, 2),
    (5177, 6, 1700, 2),
    (5183, 2, 1702, 3),
    (5185, 3, 1705, 5),
    (5188, 3, 1710, 3),
    (5191, 5, 1713, 2),
    (5196, 5, 1715, 2),
    (5201, 3, 1717, 2),
    (5204, 5, 1719, 2),
    (5209, 2, 1721, 3),
    (5211, 3, 1724, 4),
    (5214, 6, 1728, 2),
    (5220, 7, 1730, 3),
    (5227, 5, 1733, 3),
    (5232, 5, 1736, 2),
    (5237, 5, 1738, 2),
    (5242, 5, 1740, 3),
    (5247, 3, 1743, 1),
    (5250, 3, 1744, 3),
    (5253, 6, 1747, 3),
    (5259, 4, 1750, 3),
    (5263, 8, 1753, 3),
    (5271, 4, 1756, 3),
    (5275, 3, 1759, 3),
    (5278, 4, 1762, 3),
    (5282, 5, 1765, 3),
    (5287, 6, 1768, 3),
    (5293, 8, 1771, 3),
    (5301, 8, 1774, 3),
    (5309, 8, 1777, 3),
    (5317, 8, 1780, 3),
    (5325, 8, 1783, 3),
    (5333, 8, 1786, 3),
    (5341, 8, 1789, 3),
    (5349, 8, 1792, 3),
    (5357, 5, 1795, 3),
    (5362, 7, 1798, 3),
    (5369, 8, 1801, 3),
    (5377, 6, 1804, 3),
    (5383, 5, 1807, 2),
    (5388, 7, 1809, 3),
    (5395, 5, 1812, 2),
    (5400, 4, 1814, 4),
    (5404, 2, 1818, 3),
    (5406, 3, 1821, 3),
    (5409, 6, 1824, 3),
    (5415, 3, 1827, 3),
    (5418, 4, 1830, 3),
    (5422, 4, 1833, 1),
    (5426, 6, 1834, 3),
    (5432, 8, 1837, 3),
    (5440, 5, 1840, 2),
    (5445, 4, 1842, 4),
    (5449, 3, 1846, 1),
    (5452, 5, 1847, 3),
    (5457, 7, 1850, 3),
    (5464, 6, 1853, 2),
    (5470, 4, 1855, 2),
    (5474, 8, 1857, 3),
    (5482, 5, 1860, 3),
    (5487, 4, 1863, 3),
    (5491, 8, 1866, 3),
    (5499, 11, 1869, 2),
    (5510, 9, 1871, 3),
    (5519, 7, 1874, 3),
    (5526, 9, 1877, 3),
    (5535, 6, 1880, 3),
    (5541, 6, 1883, 3),
    (5547, 8, 1886, 3),
    (5555, 4, 1889, 3),
    (5559, 8, 1892, 3),
    (5567, 5, 1895, 3),
    (5572, 3, 1898, 2),
    (5575, 5, 1900, 3),
    (5580, 6, 1903, 3),
    (5586, 7, 1906, 3),
    (5593, 7, 1909, 3),
    (5600, 5, 1912, 2),
    (5605, 6, 1914, 3),
    (5611, 4, 1917, 2),
    (5615, 4, 1919, 3),
    (5619, 7, 1922, 3),
    (5626, 3, 1925, 4),
    (5629, 6, 1929, 3),
    (5635, 7, 1932, 3),
    (5642, 6, 1935, 3),
    (5648, 7, 1938, 3),
    (5655, 8, 1941, 3),
    (5663, 9, 1944, 3),
    (5672, 8, 1947, 3),
    (5680, 7, 1950, 3),
    (5687, 15, 1953, 3),
    (5702, 13, 1956, 3),
    (5715, 8, 1959, 3),
    (5723, 6, 1962, 3),
    (5729, 8, 1965, 3),
    (5737, 6, 1968, 3),
    (5743, 12, 1971, 3),
    (5755, 11, 1974, 3),
    (5766, 13, 1977, 3),
    (5779, 17, 1980, 3),
    (5796, 17, 1983, 3),
    (5813, 18, 1986, 3),
    (5831, 5, 1989, 3),
    (5836, 5, 1992, 3),
    (5841, 5, 1995, 3),
    (5846, 5, 1998, 3),
    (5851, 5, 2001, 3),
    (5856, 3, 2004, 4),
    (5859, 7, 2008, 6),
    (5866, 4, 2014, 3),
    (5870, 4, 2017, 4),
    (5874, 3, 2021, 3),
    (5877, 6, 2024, 3),
    (5883, 6, 2027, 3),
    (5889, 5, 2030, 3),
    (5894, 5, 2033, 3),
    (5899, 5, 2036, 3),
    (5904, 5, 2039, 3),
    (5909, 4, 2042, 3),
    (5913, 5, 2045, 3),
    (5918, 5, 2048, 3),
    (5923, 5, 2051, 3),
    (5928, 5, 2054, 3),
    (5933, 5, 2057, 3),
    (5938, 5, 2060, 3),
    (5943, 5, 2063, 3),
    (5948, 5, 2066, 3),
    (5953, 4, 2069, 3),
    (5957, 5, 2072, 3),
    (5962, 5, 2075, 3),
    (5967, 5, 2078, 3),
    (5972, 5, 2081, 3),
    (5977, 5, 2084, 3),
    (5982, 5, 2087, 3),
    (5987, 6, 2090, 3),
    (5993, 5, 2093, 3),
    (5998, 5, 2096, 3),
    (6003, 5, 2099, 3),
    (6008, 5, 2102, 3),
    (6013, 4, 2105, 3),
    (6017, 5, 2108, 3),
    (6022, 5, 2111, 3),
    (6027, 5, 2114, 3),
    (6032, 5, 2117, 3),
    (6037, 8, 2120, 3),
    (6045, 7, 2123, 3),
    (6052, 8, 2126, 3),
    (6060, 5, 2129, 3),
    (6065, 5, 2132, 3),
    (6070, 5, 2135, 3),
    (6075, 5, 2138, 3),
    (6080, 4, 2141, 3),
    (6084, 5, 2144, 3),
    (6089, 5, 2147, 3),
    (6094, 5, 2150, 3),
    (6099, 5, 2153, 3),
    (6104, 5, 2156, 3),
    (6109, 5, 2159, 3),
    (6114, 6, 2162, 3),
    (6120, 5, 2165, 2),
    (6125, 6, 2167, 2),
    (6131, 4, 2169, 4),
    (6135, 5, 2173, 3),
    (6140, 4, 2176, 3),
    (6144, 5, 2179, 3),
    (6149, 4, 2182, 1),
    (6153, 5, 2183, 3),
    (6158, 8, 2186, 3),
    (6166, 4, 2189, 3),
    (6170, 6, 2192, 3),
    (6176, 4, 2195, 3),
    (6180, 5, 2198, 3),
    (6185, 5, 2201, 3),
    (6190, 6, 2204, 3),
    (6196, 6, 2207, 2),
    (6202, 3, 2209, 3),
    (6205, 6, 2212, 3),
    (6211, 8, 2215, 3),
    (6219, 6, 2218, 3),
    (6225, 6, 2221, 3),
    (6231, 6, 2224, 3),
    (6237, 4, 2227, 6),
    (6241, 5, 2233, 3),
    (6246, 5, 2236, 2),
    (6251, 5, 2238, 3),
    (6256, 6, 2241, 2),
    (6262, 6, 2243, 2),
    (6268, 5, 2245, 2),
    (6273, 5, 2247, 3),
    (6278, 7, 2250, 3),
    (6285, 4, 2253, 2),
    (6289, 5, 2255, 2),
    (6294, 7, 2257, 3),
    (6301, 4, 2260, 2),
    (6305, 9, 2262, 2),
    (6314, 3, 2264, 4),
    (6317, 4, 2268, 2),
    (6321, 5, 2270, 3),
    (6326, 9, 2273, 3),
    (6335, 3, 2276, 2),
    (6338, 3, 2278, 3),
    (6341, 4, 2281, 3),
    (6345, 4, 2284, 2),
    (6349, 6, 2286, 3),
    (6355, 15, 2289, 3),
    (6370, 16, 2292, 3),
    (6386, 8, 2295, 2),
    (6394, 8, 2297, 3),
    (6402, 10, 2300, 3),
    (6412, 11, 2303, 3),
    (6423, 11, 2306, 3),
    (6434, 4, 2309, 3),
    (6438, 8, 2312, 3),
    (6446, 6, 2315, 3),
    (6452, 7, 2318, 3),
    (6459, 5, 2321, 3),
    (6464, 8, 2324, 3),
    (6472, 5, 2327, 1),
    (6477, 6, 2328, 3),
    (6483, 7, 2331, 3),
    (6490, 5, 2334, 1),
    (6495, 6, 2335, 1),
    (6501, 4, 2336, 3),
    (6505, 6, 2339, 3),
    (6511, 10, 2342, 3),
    (6521, 9, 2345, 3),
    (6530, 4, 2348, 3),
    (6534, 7, 2351, 3),
    (6541, 6, 2354, 3),
    (6547, 4, 2357, 4),
    (6551, 6, 2361, 3),
    (6557, 4, 2364, 2),
    (6561, 6, 2366, 3),
    (6567, 5, 2369, 3),
    (6572, 5, 2372, 3),
    (6577, 4, 2375, 4),
    (6581, 4, 2379, 3),
    (6585, 5, 2382, 3),
    (6590, 4, 2385, 3),
    (6594, 5, 2388, 3),
    (6599, 5, 2391, 3),
    (6604, 7, 2394, 3),
    (6611, 7, 2397, 3),
    (6618, 5, 2400, 3),
    (6623, 5, 2403, 3),
    (6628, 6, 2406, 3),
    (6634, 7, 2409, 3),
    (6641, 3, 2412, 3),
    (6644, 8, 2415, 3),
    (6652, 6, 2418, 3),
    (6658, 6, 2421, 3),
    (6664, 6, 2424, 3),
    (6670, 5, 2427, 3),
    (6675, 4, 2430, 6),
    (6679, 6, 2436, 3),
    (6685, 7, 2439, 3),
    (6692, 11, 2442, 3),
    (6703, 11, 2445, 3),
    (6714, 8, 2448, 3),
    (6722, 10, 2451, 3),
    (6732, 6, 2454, 2),
    (6738, 14, 2456, 3),
    (6752, 15, 2459, 3),
    (6767, 5, 2462, 3),
    (6772, 5, 2465, 3),
    (6777, 8, 2468, 3),
    (6785, 5, 2471, 3),
    (6790, 6, 2474, 3),
    (6796, 4, 2477, 3),
    (6800, 4, 2480, 3),
    (6804, 6, 2483, 3),
    (6810, 6, 2486, 3),
    (6816, 4, 2489, 3),
    (6820, 4, 2492, 3),
    (6824, 5, 2495, 3),
    (6829, 7, 2498, 3),
    (6836, 5, 2501, 2),
    (6841, 6, 2503, 2),
    (6847, 3, 2505, 2),
    (6850, 2, 2507, 3),
    (6852, 7, 2510, 3),
    (6859, 5, 2513, 3),
    (6864, 7, 2516, 3),
    (6871, 3, 2519, 2),
    (6874, 5, 2521, 2),
    (6879, 7, 2523, 3),
    (6886, 6, 2526, 3),
    (6892, 3, 2529, 4),
    (6895, 5, 2533, 3),
    (6900, 5, 2536, 3),
    (6905, 4, 2539, 3),
    (6909, 7, 2542, 3),
    (6916, 11, 2545, 3),
    (6927, 5, 2548, 3),
    (6932, 3, 2551, 2),
    (6935, 7, 2553, 2),
    (6942, 5, 2555, 3),
    (6947, 3, 2558, 2),
    (6950, 6, 2560, 2),
    (6956, 13, 2562, 3),
    (6969, 6, 2565, 3),
    (6975, 4, 2568, 2),
    (6979, 6, 2570, 3),
    (6985, 6, 2573, 3),
    (6991, 6, 2576, 1),
    (6997, 4, 2577, 4),
    (7001, 3, 2581, 2),
    (7004, 5, 2583, 3),
    (7009, 8, 2586, 3),
    (7017, 8, 2589, 3),
    (7025, 7, 2592, 3),
    (7032, 9, 2595, 3),
    (7041, 14, 2598, 3),
    (7055, 9, 2601, 3),
    (7064, 14, 2604, 3),
    (7078, 15, 2607, 3),
    (7093, 16, 2610, 3),
    (7109, 8, 2613, 3),
    (7117, 6, 2616, 3),
    (7123, 6, 2619, 3),
    (7129, 4, 2622, 4),
    (7133, 4, 2626, 2),
    (7137, 4, 2628, 3),
    (7141, 6, 2631, 2),
    (7147, 5, 2633, 3),
    (7152, 4, 2636, 3),
    (7156, 5, 2639, 3),
    (7161, 5, 2642, 3),
    (7166, 5, 2645, 3),
    (7171, 7, 2648, 3),
    (7178, 4, 2651, 2),
    (7182, 8, 2653, 3),
    (7190, 5, 2656, 3),
    (7195, 4, 2659, 3),
    (7199, 6, 2662, 2),
    (7205, 6, 2664, 3),
    (7211, 6, 2667, 2),
    (7217, 4, 2669, 3),
    (7221, 5, 2672, 2),
    (7226, 6, 2674, 3),
    (7232, 3, 2677, 2),
    (7235, 4, 2679, 2),
    (7239, 2, 2681, 3),
    (7241, 5, 2684, 3),
    (7246, 3, 2687, 4),
    (7249, 2, 2691, 3),
    (7251, 6, 2694, 2),
    (7257, 3, 2696, 3),
    (7260, 6, 2699, 3),
    (7266, 2, 2702, 3),
    (7268, 8, 2705, 3),
    (7276, 3, 2708, 3),
    (7279, 3, 2711, 3),
    (7282, 6, 2714, 3),
    (7288, 5, 2717, 2),
    (7293, 5, 2719, 3),
    (7298, 8, 2722, 3),
    (7306, 6, 2725, 3),
    (7312, 4, 2728, 3),
    (7316, 6, 2731, 3),
    (7322, 6, 2734, 3),
    (7328, 3, 2737, 2),
    (7331, 4, 2739, 3),
    (7335, 5, 2742, 2),
    (7340, 4, 2744, 4),
    (7344, 4, 2748, 3),
    (7348, 6, 2751, 3),
    (7354, 5, 2754, 3),
    (7359, 4, 2757, 2),
    (7363, 7, 2759, 2),
    (7370, 5, 2761, 2),
    (7375, 6, 2763, 3),
    (7381, 7, 2766, 3),
    (7388, 5, 2769, 3),
    (7393, 10, 2772, 3),
    (7403, 11, 2775, 3),
    (7414, 6, 2778, 1),
    (7420, 6, 2779, 3),
    (7426, 5, 2782, 3),
    (7431, 7, 2785, 3),
    (7438, 8, 2788, 3),
    (7446, 5, 2791, 3),
    (7451, 5, 2794, 3),
    (7456, 4, 2797, 3),
    (7460, 5, 2800, 3),
    (7465, 4, 2803, 3),
    (7469, 3, 2806, 2),
    (7472, 3, 2808, 2),
    (7475, 4, 2810, 2),
    (7479, 4, 2812, 3),
    (7483, 4, 2815, 1),
    (7487, 5, 2816, 3),
    (7492, 11, 2819, 3),
    (7503, 12, 2822, 3),
    (7515, 13, 2825, 3),
    (7528, 3, 2828, 2),
    (7531, 6, 2830, 3),
    (7537, 6, 2833, 3),
    (7543, 5, 2836, 3),
    (7548, 6, 2839, 3),
    (7554, 3, 2842, 4),
    (7557, 5, 2846, 3),
    (7562, 5, 2849, 2),
    (7567, 4, 2851, 3),
    (7571, 5, 2854, 3),
    (7576, 5, 2857, 3),
    (7581, 4, 2860, 2),
    (7585, 4, 2862, 4),
    (7589, 6, 2866, 3),
    (7595, 4, 2869, 3),
    (7599, 5, 2872, 3),
    (7604, 8, 2875, 3),
    (7612, 6, 2878, 2),
    (7618, 6, 2880, 3),
    (7624, 6, 2883, 2),
    (7630, 6, 2885, 3),
    (7636, 6, 2888, 3),
    (7642, 6, 2891, 3),
    (7648, 6, 2894, 3),
    (7654, 6, 2897, 3),
    (7660, 6, 2900, 2),
    (7666, 6, 2902, 3),
    (7672, 6, 2905, 3),
    (7678, 6, 2908, 3),
    (7684, 6, 2911, 3),
    (7690, 6, 2914, 3),
    (7696, 6, 2917, 3),
    (7702, 5, 2920, 3),
    (7707, 5, 2923, 3),
    (7712, 4, 2926, 4),
    (7716, 2, 2930, 3),
    (7718, 3, 2933, 3),
    (7721, 6, 2936, 2),
    (7727, 5, 2938, 2),
    (7732, 6, 2940, 2),
    (7738, 3, 2942, 3),
    (7741, 6, 2945, 2),
    (7747, 5, 2947, 2),
    (7752, 3, 2949, 2),
    (7755, 4, 2951, 2),
    (7759, 2, 2953, 3),
    (7761, 3, 2956, 3),
    (7764, 3, 2959, 3),
    (7767, 4, 2962, 3),
    (7771, 8, 2965, 3),
    (7779, 3, 2968, 3),
    (7782, 5, 2971, 3),
    (7787, 6, 2974, 3),
    (7793, 7, 2977, 3),
    (7800, 8, 2980, 3),
    (7808, 4, 2983, 6),
    (7812, 6, 2989, 3),
    (7818, 3, 2992, 4),
    (7821, 2, 2996, 3),
    (7823, 3, 2999, 3),
    (7826, 5, 3002, 3),
    (7831, 4, 3005, 2),
    (7835, 2, 3007, 3),
    (7837, 3, 3010, 3),
    (7840, 3, 3013, 3),
    (7843, 3, 3016, 3),
    (7846, 3, 3019, 3),
    (7849, 4, 3022, 3),
    (7853, 8, 3025, 3),
    (7861, 3, 3028, 3),
    (7864, 4, 3031, 3),
    (7868, 5, 3034, 3),
    (7873, 5, 3037, 3),
    (7878, 4, 3040, 4),
    (7882, 5, 3044, 1),
    (7887, 4, 3045, 3),
    (7891, 4, 3048, 3),
    (7895, 5, 3051, 3),
    (7900, 5, 3054, 3),
    (7905, 2, 3057, 1),
    (7907, 4, 3058, 3),
    (7911, 5, 3061, 3),
    (7916, 5, 3064, 3),
    (7921, 6, 3067, 3),
    (7927, 7, 3070, 3),
    (7934, 9, 3073, 3),
    (7943, 6, 3076, 3),
    (7949, 6, 3079, 3),
    (7955, 9, 3082, 3),
    (7964, 10, 3085, 3),
    (7974, 7, 3088, 3),
    (7981, 6, 3091, 3),
    (7987, 9, 3094, 6),
    (7996, 4, 3100, 6),
    (8000, 4, 3106, 3),
    (8004, 6, 3109, 3),
    (8010, 4, 3112, 2),
    (8014, 6, 3114, 3),
    (8020, 6, 3117, 2),
    (8026, 4, 3119, 3),
    (8030, 7, 3122, 3),
    (8037, 5, 3125, 3),
    (8042, 4, 3128, 3),
    (8046, 5, 3131, 2),
    (8051, 6, 3133, 3),
    (8057, 9, 3136, 3),
    (8066, 6, 3139, 3),
    (8072, 6, 3142, 3),
    (8078, 3, 3145, 4),
    (8081, 8, 3149, 3),
    (8089, 8, 3152, 3),
    (8097, 5, 3155, 3),
    (8102, 6, 3158, 3),
    (8108, 13, 3161, 3),
    (8121, 14, 3164, 3),
    (8135, 4, 3167, 4),
    (8139, 6, 3171, 3),
    (8145, 4, 3174, 4),
    (8149, 6, 3178, 3),
    (8155, 6, 3181, 2),
    (8161, 6, 3183, 3),
    (8167, 6, 3186, 3),
    (8173, 6, 3189, 2),
    (8179, 2, 3191, 3),
    (8181, 5, 3194, 2),
    (8186, 3, 3196, 2),
    (8189, 4, 3198, 2),
    (8193, 5, 3200, 2),
    (8198, 3, 3202, 3),
    (8201, 3, 3205, 4),
    (8204, 6, 3209, 2),
    (8210, 2, 3211, 3),
    (8212, 6, 3214, 3),
    (8218, 5, 3217, 3),
    (8223, 6, 3220, 3),
    (8229, 5, 3223, 3),
    (8234, 5, 3226, 2),
    (8239, 5, 3228, 2),
    (8244, 5, 3230, 3),
    (8249, 8, 3233, 3),
    (8257, 8, 3236, 3),
    (8265, 5, 3239, 2),
    (8270, 4, 3241, 3),
    (8274, 5, 3244, 2),
    (8279, 2, 3246, 3),
    (8281, 6, 3249, 3),
    (8287, 5, 3252, 3),
    (8292, 8, 3255, 3),
    (8300, 6, 3258, 2),
    (8306, 3, 3260, 3),
    (8309, 6, 3263, 3),
    (8315, 8, 3266, 3),
    (8323, 8, 3269, 3),
    (8331, 8, 3272, 3),
    (8339, 7, 3275, 3),
    (8346, 4, 3278, 2),
    (8350, 5, 3280, 2),
    (8355, 4, 3282, 4),
    (8359, 4, 3286, 2),
    (8363, 5, 3288, 3),
    (8368, 6, 3291, 2),
    (8374, 4, 3293, 4),
    (8378, 4, 3297, 3),
    (8382, 5, 3300, 3),
    (8387, 7, 3303, 3),
    (8394, 5, 3306, 3),
    (8399, 6, 3309, 3),
    (8405, 5, 3312, 3),
    (8410, 2, 3315, 3),
    (8412, 6, 3318, 2),
    (8418, 5, 3320, 2),
    (8423, 4, 3322, 2),
    (8427, 5, 3324, 2),
    (8432, 3, 3326, 2),
    (8435, 3, 3328, 4),
    (8438, 5, 3332, 2),
    (8443, 4, 3334, 4),
    (8447, 4, 3338, 4),
    (8451, 6, 3342, 2),
    (8457, 5, 3344, 2),
    (8462, 5, 3346, 2),
    (8467, 6, 3348, 2),
    (8473, 6, 3350, 2),
    (8479, 3, 3352, 2),
    (8482, 3, 3354, 4),
    (8485, 6, 3358, 2),
    (8491, 4, 3360, 2),
    (8495, 4, 3362, 2),
    (8499, 4, 3364, 4),
    (8503, 4, 3368, 4),
    (8507, 5, 3372, 3),
    (8512, 4, 3375, 3),
    (8516, 6, 3378, 3),
    (8522, 5, 3381, 3),
    (8527, 2, 3384, 3),
    (8529, 3, 3387, 3),
    (8532, 4, 3390, 3),
    (8536, 6, 3393, 2),
    (8542, 8, 3395, 3),
    (8550, 6, 3398, 3),
    (8556, 6, 3401, 2),
    (8562, 4, 3403, 3),
    (8566, 5, 3406, 3),
    (8571, 6, 3409, 3),
    (8577, 3, 3412, 3),
    (8580, 5, 3415, 2),
    (8585, 4, 3417, 3),
    (8589, 5, 3420, 3),
    (8594, 7, 3423, 3),
    (8601, 6, 3426, 3),
    (8607, 6, 3429, 3),
    (8613, 6, 3432, 3),
    (8619, 6, 3435, 3),
    (8625, 7, 3438, 3),
    (8632, 6, 3441, 3),
    (8638, 3, 3444, 3),
    (8641, 6, 3447, 3),
    (8647, 4, 3450, 3),
    (8651, 5, 3453, 6),
    (8656, 5, 3459, 3),
    (8661, 5, 3462, 3),
    (8666, 6, 3465, 1),
    (8672, 6, 3466, 1),
    (8678, 5, 3467, 3),
    (8683, 7, 3470, 3),
    (8690, 7, 3473, 3),
    (8697, 6, 3476, 2),
    (8703, 6, 3478, 2),
    (8709, 5, 3480, 3),
    (8714, 4, 3483, 1),
    (8718, 3, 3484, 2),
    (8721, 4, 3486, 3),
    (8725, 5, 3489, 3),
    (8730, 6, 3492, 3),
    (8736, 7, 3495, 3),
    (8743, 8, 3498, 3),
    (8751, 4, 3501, 3),
    (8755, 2, 3504, 3),
    (8757, 9, 3507, 3),
    (8766, 13, 3510, 3),
    (8779, 15, 3513, 3),
    (8794, 13, 3516, 3),
    (8807, 14, 3519, 3),
    (8821, 14, 3522, 3),
    (8835, 15, 3525, 3),
    (8850, 17, 3528, 3),
    (8867, 19, 3531, 3),
    (8886, 14, 3534, 3),
    (8900, 3, 3537, 3),
    (8903, 3, 3540, 3),
    (8906, 4, 3543, 3),
    (8910, 8, 3546, 3),
    (8918, 3, 3549, 3),
    (8921, 5, 3552, 3),
    (8926, 6, 3555, 3),
    (8932, 7, 3558, 3),
    (8939, 8, 3561, 3),
    (8947, 4, 3564, 6),
    (8951, 6, 3570, 3),
    (8957, 10, 3573, 3),
    (8967, 7, 3576, 3),
    (8974, 9, 3579, 3),
    (8983, 10, 3582, 3),
    (8993, 7, 3585, 3),
    (9000, 7, 3588, 3),
    (9007, 6, 3591, 3),
    (9013, 6, 3594, 3),
    (9019, 3, 3597, 4),
    (9022, 2, 3601, 3),
    (9024, 3, 3604, 3),
    (9027, 5, 3607, 3),
    (9032, 5, 3610, 3),
    (9037, 6, 3613, 3),
    (9043, 5, 3616, 3),
    (9048, 4, 3619, 2),
    (9052, 2, 3621, 3),
    (9054, 5, 3624, 3),
    (9059, 8, 3627, 3),
    (9067, 6, 3630, 3),
    (9073, 5, 3633, 3),
    (9078, 6, 3636, 2),
    (9084, 6, 3638, 3),
    (9090, 10, 3641, 3),
    (9100, 3, 3644, 3),
    (9103, 4, 3647, 3),
    (9107, 8, 3650, 3),
    (9115, 3, 3653, 3),
    (9118, 4, 3656, 3),
    (9122, 5, 3659, 3),
    (9127, 5, 3662, 3),
    (9132, 5, 3665, 3),
    (9137, 5, 3668, 3),
    (9142, 5, 3671, 3),
    (9147, 13, 3674, 3),
    (9160, 18, 3677, 3),
    (9178, 10, 3680, 3),
    (9188, 14, 3683, 3),
    (9202, 13, 3686, 3),
    (9215, 14, 3689, 3),
    (9229, 5, 3692, 3),
    (9234, 4, 3695, 4),
    (9238, 6, 3699, 3),
    (9244, 7, 3702, 3),
    (9251, 6, 3705, 3),
    (9257, 6, 3708, 1),
    (9263, 3, 3709, 3),
    (9266, 7, 3712, 3),
    (9273, 4, 3715, 3),
    (9277, 4, 3718, 1),
    (9281, 6, 3719, 3),
    (9287, 5, 3722, 3),
    (9292, 8, 3725, 3),
    (9300, 5, 3728, 3),
    (9305, 6, 3731, 3),
    (9311, 3, 3734, 3),
    (9314, 5, 3737, 3),
    (9319, 6, 3740, 3),
    (9325, 4, 3743, 4),
    (9329, 3, 3747, 3),
    (9332, 4, 3750, 3),
    (9336, 5, 3753, 3),
    (9341, 5, 3756, 3),
    (9346, 4, 3759, 1),
    (9350, 5, 3760, 3),
    (9355, 6, 3763, 3),
    (9361, 6, 3766, 2),
    (9367, 2, 3768, 1),
    (9369, 4, 3769, 3),
    (9373, 5, 3772, 3),
    (9378, 5, 3775, 3),
    (9383, 6, 3778, 3),
    (9389, 6, 3781, 3),
    (9395, 6, 3784, 3),
    (9401, 7, 3787, 3),
    (9408, 6, 3790, 3),
    (9414, 4, 3793, 3),
    (9418, 5, 3796, 3),
    (9423, 5, 3799, 3),
    (9428, 8, 3802, 3),
    (9436, 7, 3805, 3),
    (9443, 9, 3808, 6),
    (9452, 4, 3814, 6),
    (9456, 5, 3820, 3),
    (9461, 4, 3823, 2),
    (9465, 4, 3825, 3),
    (9469, 4, 3828, 3),
    (9473, 7, 3831, 3),
    (9480, 3, 3834, 3),
    (9483, 6, 3837, 3),
    (9489, 10, 3840, 3),
    (9499, 10, 3843, 3),
    (9509, 8, 3846, 3),
    (9517, 6, 3849, 3),
    (9523, 6, 3852, 3),
    (9529, 3, 3855, 2),
    (9532, 5, 3857, 3),
    (9537, 13, 3860, 3),
    (9550, 3, 3863, 4),
    (9553, 3, 3867, 3),
    (9556, 5, 3870, 2),
    (9561, 3, 3872, 3),
    (9564, 6, 3875, 1),
    (9570, 6, 3876, 3),
    (9576, 6, 3879, 2),
    (9582, 5, 3881, 3),
    (9587, 6, 3884, 3),
    (9593, 6, 3887, 3),
    (9599, 7, 3890, 3),
    (9606, 4, 3893, 3),
    (9610, 4, 3896, 3),
    (9614, 6, 3899, 3),
    (9620, 6, 3902, 3),
    (9626, 4, 3905, 4),
    (9630, 2, 3909, 3),
    (9632, 4, 3912, 4),
    (9636, 6, 3916, 3),
    (9642, 2, 3919, 2),
    (9644, 8, 3921, 3),
    (9652, 5, 3924, 3),
    (9657, 3, 3927, 5),
    (9660, 3, 3932, 6),
    (9663, 4, 3938, 5),
    (9667, 10, 3943, 3),
    (9677, 15, 3946, 3),
    (9692, 3, 3949, 5),
    (9695, 3, 3954, 6),
    (9698, 4, 3960, 5),
    (9702, 11, 3965, 3),
    (9713, 6, 3968, 3),
    (9719, 6, 3971, 3),
    (9725, 5, 3974, 3),
    (9730, 6, 3977, 2),
    (9736, 4, 3979, 6),
    (9740, 3, 3985, 3),
    (9743, 4, 3988, 5),
    (9747, 5, 3993, 5),
    (9752, 5, 3998, 2),
    (9757, 7, 4000, 3),
    (9764, 5, 4003, 3),
    (9769, 7, 4006, 3),
    (9776, 8, 4009, 3),
    (9784, 4, 4012, 2),
    (9788, 5, 4014, 5),
    (9793, 6, 4019, 5),
    (9799, 4, 4024, 3),
    (9803, 6, 4027, 2),
    (9809, 6, 4029, 2),
    (9815, 5, 4031, 3),
    (9820, 8, 4034, 5),
    (9828, 4, 4039, 3),
    (9832, 3, 4042, 2),
    (9835, 5, 4044, 3),
    (9840, 2, 4047, 3),
    (9842, 5, 4050, 3),
    (9847, 6, 4053, 3),
    (9853, 5, 4056, 3),
    (9858, 7, 4059, 3),
    (9865, 5, 4062, 5),
    (9870, 6, 4067, 3),
    (9876, 6, 4070, 3),
    (9882, 5, 4073, 5),
    (9887, 6, 4078, 3),
    (9893, 7, 4081, 3),
    (9900, 3, 4084, 4),
    (9903, 3, 4088, 5),
    (9906, 3, 4093, 3),
    (9909, 4, 4096, 3),
    (9913, 5, 4099, 5),
    (9918, 9, 4104, 5),
    (9927, 4, 4109, 5),
    (9931, 5, 4114, 3),
    (9936, 3, 4117, 3),
    (9939, 4, 4120, 3),
    (9943, 5, 4123, 3),
    (9948, 5, 4126, 3),
    (9953, 5, 4129, 3),
    (9958, 2, 4132, 3),
    (9960, 3, 4135, 3),
    (9963, 4, 4138, 3),
    (9967, 3, 4141, 3),
    (9970, 4, 4144, 2),
    (9974, 5, 4146, 3),
    (9979, 3, 4149, 5),
    (9982, 5, 4154, 3),
    (9987, 4, 4157, 3),
    (9991, 3, 4160, 3),
    (9994, 10, 4163, 3),
    (10004, 15, 4166, 3),
    (10019, 4, 4169, 3),
    (10023, 5, 4172, 5),
    (10028, 9, 4177, 5),
    (10037, 4, 4182, 5),
    (10041, 5, 4187, 3),
    (10046, 5, 4190, 3),
    (10051, 3, 4193, 3),
    (10054, 5, 4196, 3),
    (10059, 6, 4199, 3),
    (10065, 4, 4202, 3),
    (10069, 4, 4205, 4),
    (10073, 3, 4209, 2),
    (10076, 5, 4211, 3),
    (10081, 6, 4214, 5),
    (10087, 8, 4219, 5),
    (10095, 7, 4224, 3),
    (10102, 7, 4227, 3),
    (10109, 7, 4230, 3),
    (10116, 5, 4233, 3),
    (10121, 7, 4236, 3),
    (10128, 7, 4239, 3),
    (10135, 7, 4242, 3),
    (10142, 4, 4245, 3),
    (10146, 9, 4248, 3),
    (10155, 6, 4251, 6),
    (10161, 5, 4257, 5),
    (10166, 7, 4262, 3),
    (10173, 3, 4265, 3),
    (10176, 6, 4268, 3),
    (10182, 4, 4271, 5),
    (10186, 5, 4276, 3),
    (10191, 7, 4279, 5),
    (10198, 5, 4284, 3),
    (10203, 5, 4287, 3),
    (10208, 6, 4290, 5),
    (10214, 6, 4295, 5),
    (10220, 11, 4300, 3),
    (10231, 5, 4303, 3),
    (10236, 6, 4306, 3),
    (10242, 3, 4309, 3),
    (10245, 6, 4312, 3),
    (10251, 4, 4315, 5),
    (10255, 4, 4320, 4),
    (10259, 9, 4324, 3),
    (10268, 14, 4327, 3),
    (10282, 4, 4330, 3),
    (10286, 5, 4333, 3),
    (10291, 6, 4336, 3),
    (10297, 5, 4339, 3),
    (10302, 5, 4342, 3),
    (10307, 7, 4345, 3),
    (10314, 7, 4348, 3),
    (10321, 4, 4351, 3),
    (10325, 5, 4354, 5),
    (10330, 5, 4359, 3),
    (10335, 7, 4362, 6),
    (10342, 9, 4368, 3),
    (10351, 10, 4371, 5),
    (10361, 5, 4376, 3),
    (10366, 7, 4379, 5),
    (10373, 4, 4384, 3),
    (10377, 5, 4387, 5),
    (10382, 5, 4392, 3),
    (10387, 7, 4395, 6),
    (10394, 9, 4401, 3),
    (10403, 10, 4404, 5),
    (10413, 4, 4409, 3),
    (10417, 6, 4412, 2),
    (10423, 4, 4414, 3),
    (10427, 13, 4417, 3),
    (10440, 15, 4420, 3),
    (10455, 14, 4423, 3),
    (10469, 16, 4426, 3),
    (10485, 2, 4429, 2),
    (10487, 3, 4431, 1),
    (10490, 6, 4432, 3),
    (10496, 5, 4435, 3),
    (10501, 6, 4438, 3),
    (10507, 6, 4441, 3),
    (10513, 4, 4444, 6),
    (10517, 6, 4450, 3),
    (10523, 4, 4453, 6),
    (10527, 4, 4459, 4),
    (10531, 7, 4463, 3),
    (10538, 6, 4466, 3),
    (10544, 4, 4469, 6),
    (10548, 4, 4475, 4),
    (10552, 7, 4479, 6),
    (10559, 6, 4485, 3),
    (10565, 7, 4488, 6),
    (10572, 5, 4494, 6),
    (10577, 5, 4500, 3),
    (10582, 6, 4503, 3),
    (10588, 5, 4506, 3),
    (10593, 7, 4509, 3),
    (10600, 6, 4512, 3),
    (10606, 2, 4515, 3),
    (10608, 6, 4518, 2),
    (10614, 4, 4520, 3),
    (10618, 4, 4523, 3),
    (10622, 5, 4526, 2),
    (10627, 3, 4528, 2),
    (10630, 5, 4530, 3),
    (10635, 6, 4533, 2),
    (10641, 4, 4535, 3),
    (10645, 4, 4538, 3),
    (10649, 6, 4541, 3),
    (10655, 5, 4544, 2),
    (10660, 5, 4546, 3),
    (10665, 3, 4549, 4),
    (10668, 4, 4553, 2),
    (10672, 6, 4555, 2),
    (10678, 3, 4557, 3),
    (10681, 5, 4560, 3),
    (10686, 3, 4563, 2),
    (10689, 4, 4565, 3),
    (10693, 5, 4568, 3),
    (10698, 5, 4571, 3),
    (10703, 7, 4574, 3),
    (10710, 5, 4577, 3),
    (10715, 3, 4580, 3),
    (10718, 5, 4583, 2),
    (10723, 5, 4585, 2),
    (10728, 7, 4587, 2),
    (10735, 4, 4589, 3),
    (10739, 6, 4592, 3),
    (10745, 4, 4595, 4),
    (10749, 4, 4599, 3),
    (10753, 5, 4602, 3),
    (10758, 5, 4605, 3),
    (10763, 2, 4608, 3),
    (10765, 5, 4611, 3),
    (10770, 3, 4614, 3),
    (10773, 5, 4617, 3),
    (10778, 7, 4620, 3),
    (10785, 4, 4623, 2),
    (10789, 4, 4625, 2),
    (10793, 6, 4627, 3),
    (10799, 4, 4630, 3),
    (10803, 7, 4633, 3),
    (10810, 3, 4636, 3),
    (10813, 4, 4639, 3),
    (10817, 6, 4642, 2),
    (10823, 4, 4644, 3),
    (10827, 6, 4647, 2),
    (10833, 6, 4649, 3),
    (10839, 8, 4652, 3),
    (10847, 4, 4655, 2),
    (10851, 5, 4657, 3),
    (10856, 3, 4660, 3),
    (10859, 4, 4663, 2),
    (10863, 8, 4665, 3),
    (10871, 6, 4668, 3),
    (10877, 5, 4671, 3),
    (10882, 4, 4674, 3),
    (10886, 3, 4677, 2),
    (10889, 6, 4679, 1),
    (10895, 6, 4680, 1),
    (10901, 6, 4681, 3),
    (10907, 4, 4684, 3),
    (10911, 7, 4687, 3),
    (10918, 3, 4690, 4),
    (10921, 3, 4694, 2),
    (10924, 4, 4696, 2),
    (10928, 6, 4698, 3),
    (10934, 5, 4701, 3),
    (10939, 2, 4704, 2),
    (10941, 9, 4706, 3),
    (10950, 3, 4709, 2),
    (10953, 6, 4711, 3),
    (10959, 7, 4714, 3),
    (10966, 6, 4717, 3),
    (10972, 4, 4720, 1),
    (10976, 8, 4721, 3),
    (10984, 5, 4724, 3),
    (10989, 7, 4727, 3),
    (10996, 6, 4730, 3),
    (11002, 6, 4733, 3),
    (11008, 5, 4736, 3),
    (11013, 6, 4739, 2),
    (11019, 7, 4741, 3),
    (11026, 7, 4744, 3),
    (11033, 2, 4747, 2),
    (11035, 8, 4749, 3),
    (11043, 4, 4752, 4),
    (11047, 5, 4756, 2),
    (11052, 2, 4758, 3),
    (11054, 3, 4761, 3),
    (11057, 4, 4764, 3),
    (11061, 5, 4767, 3),
    (11066, 3, 4770, 3),
    (11069, 4, 4773, 3),
    (11073, 10, 4776, 3),
    (11083, 11, 4779, 3),
    (11094, 6, 4782, 3),
    (11100, 11, 4785, 3),
    (11111, 8, 4788, 3),
    (11119, 8, 4791, 3),
    (11127, 7, 4794, 3),
    (11134, 5, 4797, 3),
    (11139, 6, 4800, 3),
    (11145, 4, 4803, 3),
    (11149, 5, 4806, 3),
    (11154, 6, 4809, 3),
    (11160, 4, 4812, 3),
    (11164, 8, 4815, 3),
    (11172, 8, 4818, 3),
    (11180, 8, 4821, 3),
    (11188, 4, 4824, 3),
    (11192, 6, 4827, 3),
    (11198, 5, 4830, 3),
    (11203, 6, 4833, 3),
    (11209, 4, 4836, 4),
    (11213, 3, 4840, 2),
    (11216, 6, 4842, 3),
    (11222, 3, 4845, 4),
    (11225, 4, 4849, 3),
    (11229, 4, 4852, 4),
    (11233, 6, 4856, 3),
    (11239, 4, 4859, 4),
    (11243, 11, 4863, 3),
    (11254, 7, 4866, 3),
    (11261, 5, 4869, 1),
    (11266, 7, 4870, 3),
    (11273, 4, 4873, 1),
    (11277, 5, 4874, 3),
    (11282, 4, 4877, 3),
    (11286, 6, 4880, 3),
    (11292, 5, 4883, 3),
    (11297, 4, 4886, 3),
    (11301, 4, 4889, 5),
    (11305, 6, 4894, 2),
    (11311, 5, 4896, 3),
    (11316, 8, 4899, 3),
    (11324, 4, 4902, 3),
    (11328, 5, 4905, 3),
    (11333, 5, 4908, 3),
    (11338, 6, 4911, 3),
    (11344, 5, 4914, 2),
    (11349, 4, 4916, 3),
    (11353, 6, 4919, 3),
    (11359, 5, 4922, 3),
    (11364, 7, 4925, 3),
    (11371, 5, 4928, 3),
    (11376, 6, 4931, 3),
    (11382, 6, 4934, 3),
    (11388, 6, 4937, 3),
    (11394, 6, 4940, 3),
    (11400, 7, 4943, 3),
    (11407, 6, 4946, 3),
    (11413, 5, 4949, 3),
    (11418, 6, 4952, 3),
    (11424, 5, 4955, 3),
    (11429, 9, 4958, 3),
    (11438, 5, 4961, 3),
    (11443, 5, 4964, 3),
    (11448, 6, 4967, 1),
    (11454, 6, 4968, 1),
    (11460, 5, 4969, 3),
    (11465, 7, 4972, 3),
    (11472, 7, 4975, 3),
    (11479, 6, 4978, 2),
    (11485, 6, 4980, 2),
    (11491, 5, 4982, 3),
    (11496, 4, 4985, 1),
    (11500, 3, 4986, 2),
    (11503, 4, 4988, 3),
    (11507, 7, 4991, 3),
    (11514, 5, 4994, 3),
    (11519, 6, 4997, 3),
    (11525, 4, 5000, 3),
    (11529, 4, 5003, 3),
    (11533, 7, 5006, 3),
    (11540, 8, 5009, 3),
    (11548, 5, 5012, 3),
    (11553, 4, 5015, 3),
    (11557, 3, 5018, 2),
    (11560, 6, 5020, 3),
    (11566, 6, 5023, 3),
    (11572, 3, 5026, 4),
    (11575, 5, 5030, 3),
    (11580, 5, 5033, 3),
    (11585, 6, 5036, 3),
    (11591, 3, 5039, 2),
    (11594, 4, 5041, 2),
    (11598, 10, 5043, 3),
    (11608, 14, 5046, 3),
    (11622, 16, 5049, 3),
    (11638, 14, 5052, 3),
    (11652, 15, 5055, 3),
    (11667, 17, 5058, 3),
    (11684, 16, 5061, 3),
    (11700, 15, 5064, 3),
    (11715, 15, 5067, 3),
    (11730, 4, 5070, 2),
    (11734, 12, 5072, 3),
    (11746, 5, 5075, 3),
    (11751, 5, 5078, 3),
    (11756, 3, 5081, 3),
    (11759, 6, 5084, 3),
    (11765, 10, 5087, 3),
    (11775, 5, 5090, 3),
    (11780, 5, 5093, 3),
    (11785, 5, 5096, 3),
    (11790, 5, 5099, 3),
    (11795, 5, 5102, 3),
    (11800, 4, 5105, 4),
    (11804, 6, 5109, 3),
    (11810, 7, 5112, 3),
    (11817, 4, 5115, 1),
    (11821, 6, 5116, 3),
    (11827, 8, 5119, 3),
    (11835, 5, 5122, 3),
    (11840, 6, 5125, 3),
    (11846, 4, 5128, 4),
    (11850, 3, 5132, 3),
    (11853, 4, 5135, 1),
    (11857, 5, 5136, 3),
    (11862, 6, 5139, 3),
    (11868, 6, 5142, 3),
    (11874, 6, 5145, 3),
    (11880, 4, 5148, 3),
    (11884, 5, 5151, 3),
    (11889, 5, 5154, 3),
    (11894, 8, 5157, 3),
    (11902, 7, 5160, 3),
    (11909, 2, 5163, 3),
    (11911, 6, 5166, 2),
    (11917, 5, 5168, 3),
    (11922, 2, 5171, 3),
    (11924, 3, 5174, 3),
    (11927, 4, 5177, 3),
    (11931, 6, 5180, 2),
    (11937, 5, 5182, 3),
    (11942, 3, 5185, 3),
    (11945, 6, 5188, 2),
    (11951, 5, 5190, 2),
    (11956, 4, 5192, 3),
    (11960, 5, 5195, 3),
    (11965, 6, 5198, 3),
    (11971, 8, 5201, 3),
    (11979, 5, 5204, 3),
    (11984, 3, 5207, 2),
    (11987, 4, 5209, 3),
    (11991, 5, 5212, 3),
    (11996, 5, 5215, 3),
    (12001, 5, 5218, 3),
    (12006, 6, 5221, 3),
    (12012, 5, 5224, 3),
    (12017, 7, 5227, 3),
    (12024, 4, 5230, 2),
    (12028, 4, 5232, 1),
    (12032, 6, 5233, 3),
    (12038, 8, 5236, 3),
    (12046, 5, 5239, 3),
    (12051, 4, 5242, 3),
    (12055, 3, 5245, 4),
    (12058, 6, 5249, 3),
    (12064, 5, 5252, 3),
    (12069, 6, 5255, 2),
    (12075, 4, 5257, 2),
    (12079, 8, 5259, 3),
    (12087, 13, 5262, 3),
    (12100, 3, 5265, 2),
    (12103, 5, 5267, 2),
    (12108, 6, 5269, 2),
    (12114, 6, 5271, 2),
    (12120, 3, 5273, 3),
    (12123, 6, 5276, 3),
    (12129, 4, 5279, 3),
    (12133, 5, 5282, 3),
    (12138, 4, 5285, 3),
    (12142, 5, 5288, 3),
    (12147, 4, 5291, 3),
    (12151, 5, 5294, 3),
    (12156, 5, 5297, 3),
    (12161, 7, 5300, 3),
    (12168, 7, 5303, 3),
    (12175, 5, 5306, 3),
    (12180, 13, 5309, 3),
    (12193, 6, 5312, 3),
    (12199, 8, 5315, 3),
    (12207, 4, 5318, 3),
    (12211, 5, 5321, 3),
    (12216, 3, 5324, 3),
    (12219, 4, 5327, 3),
    (12223, 5, 5330, 6),
    (12228, 6, 5336, 2),
    (12234, 3, 5338, 1),
    (12237, 4, 5339, 3),
    (12241, 6, 5342, 3),
    (12247, 4, 5345, 4),
    (12251, 6, 5349, 3),
    (12257, 9, 5352, 3),
    (12266, 4, 5355, 3),
    (12270, 5, 5358, 3),
    (12275, 6, 5361, 6),
    (12281, 5, 5367, 3),
    (12286, 6, 5370, 6),
    (12292, 5, 5376, 3),
    (12297, 6, 5379, 3),
    (12303, 8, 5382, 3),
    (12311, 10, 5385, 3),
    (12321, 5, 5388, 3),
    (12326, 6, 5391, 3),
    (12332, 8, 5394, 3),
    (12340, 10, 5397, 3),
    (12350, 3, 5400, 3),
    (12353, 6, 5403, 3),
    (12359, 6, 5406, 3),
    (12365, 4, 5409, 3),
    (12369, 5, 5412, 3),
    (12374, 4, 5415, 4),
    (12378, 6, 5419, 3),
    (12384, 6, 5422, 3),
    (12390, 6, 5425, 3),
    (12396, 4, 5428, 3),
    (12400, 5, 5431, 3),
    (12405, 15, 5434, 2),
    (12420, 11, 5436, 2),
    (12431, 5, 5438, 2),
    (12436, 3, 5440, 3),
    (12439, 4, 5443, 3),
    (12443, 6, 5446, 3),
    (12449, 4, 5449, 3),
    (12453, 7, 5452, 3),
    (12460, 7, 5455, 3),
    (12467, 5, 5458, 3),
    (12472, 5, 5461, 3),
    (12477, 7, 5464, 3),
    (12484, 7, 5467, 3),
    (12491, 6, 5470, 3),
    (12497, 8, 5473, 3),
    (12505, 9, 5476, 3),
    (12514, 9, 5479, 3),
    (12523, 10, 5482, 3),
    (12533, 6, 5485, 3),
    (12539, 6, 5488, 3),
    (12545, 6, 5491, 3),
    (12551, 4, 5494, 3),
    (12555, 10, 5497, 3),
    (12565, 11, 5500, 3),
    (12576, 6, 5503, 3),
    (12582, 11, 5506, 3),
    (12593, 8, 5509, 3),
    (12601, 8, 5512, 3),
    (12609, 7, 5515, 3),
    (12616, 3, 5518, 3),
    (12619, 4, 5521, 3),
    (12623, 3, 5524, 3),
    (12626, 4, 5527, 2),
    (12630, 4, 5529, 2),
    (12634, 4, 5531, 2),
    (12638, 4, 5533, 3),
    (12642, 6, 5536, 3),
    (12648, 7, 5539, 3),
    (12655, 4, 5542, 3),
    (12659, 7, 5545, 3),
    (12666, 7, 5548, 3),
    (12673, 7, 5551, 3),
    (12680, 7, 5554, 3),
    (12687, 7, 5557, 3),
    (12694, 5, 5560, 3),
    (12699, 5, 5563, 3),
    (12704, 7, 5566, 3),
    (12711, 6, 5569, 3),
    (12717, 8, 5572, 3),
    (12725, 9, 5575, 3),
    (12734, 9, 5578, 3),
    (12743, 10, 5581, 3),
    (12753, 6, 5584, 3),
    (12759, 6, 5587, 3),
    (12765, 6, 5590, 3),
    (12771, 5, 5593, 3),
    (12776, 6, 5596, 3),
    (12782, 5, 5599, 3),
    (12787, 7, 5602, 3),
    (12794, 6, 5605, 3),
    (12800, 5, 5608, 2),
    (12805, 6, 5610, 3),
    (12811, 3, 5613, 2),
    (12814, 4, 5615, 3),
    (12818, 6, 5618, 2),
    (12824, 6, 5620, 2),
    (12830, 3, 5622, 2),
    (12833, 4, 5624, 3),
    (12837, 6, 5627, 3),
    (12843, 3, 5630, 4),
    (12846, 6, 5634, 3),
    (12852, 9, 5637, 3),
    (12861, 5, 5640, 2),
    (12866, 8, 5642, 2),
    (12874, 6, 5644, 2),
    (12880, 11, 5646, 3),
    (12891, 8, 5649, 3),
    (12899, 6, 5652, 3),
    (12905, 5, 5655, 3),
    (12910, 6, 5658, 3),
    (12916, 5, 5661, 2),
    (12921, 5, 5663, 2),
    (12926, 5, 5665, 2),
    (12931, 6, 5667, 3),
    (12937, 8, 5670, 3),
    (12945, 6, 5673, 3),
    (12951, 4, 5676, 3),
    (12955, 4, 5679, 3),
    (12959, 3, 5682, 3),
    (12962, 6, 5685, 3),
    (12968, 6, 5688, 3),
    (12974, 4, 5691, 4),
    (12978, 7, 5695, 3),
    (12985, 4, 5698, 3),
    (12989, 6, 5701, 3),
    (12995, 5, 5704, 3),
    (13000, 8, 5707, 3),
    (13008, 12, 5710, 3),
    (13020, 12, 5713, 3),
    (13032, 14, 5716, 3),
    (13046, 9, 5719, 3),
    (13055, 13, 5722, 3),
    (13068, 15, 5725, 3),
    (13083, 6, 5728, 3),
    (13089, 4, 5731, 3),
    (13093, 8, 5734, 3),
    (13101, 7, 5737, 3),
    (13108, 5, 5740, 3),
    (13113, 7, 5743, 3),
    (13120, 8, 5746, 3),
    (13128, 4, 5749, 4),
    (13132, 4, 5753, 2),
    (13136, 5, 5755, 2),
    (13141, 6, 5757, 2),
    (13147, 5, 5759, 3),
    (13152, 16, 5762, 3),
    (13168, 17, 5765, 3),
    (13185, 4, 5768, 3),
    (13189, 4, 5771, 3),
    (13193, 6, 5774, 2),
    (13199, 4, 5776, 3),
    (13203, 5, 5779, 2),
    (13208, 6, 5781, 2),
    (13214, 5, 5783, 2),
    (13219, 3, 5785, 2),
    (13222, 5, 5787, 3),
    (13227, 6, 5790, 2),
    (13233, 5, 5792, 3),
    (13238, 6, 5795, 3),
    (13244, 3, 5798, 4),
    (13247, 6, 5802, 2),
    (13253, 5, 5804, 3),
    (13258, 5, 5807, 3),
    (13263, 5, 5810, 3),
    (13268, 6, 5813, 3),
    (13274, 8, 5816, 3),
    (13282, 6, 5819, 3),
    (13288, 5, 5822, 3),
    (13293, 5, 5825, 2),
    (13298, 3, 5827, 2),
    (13301, 5, 5829, 2),
    (13306, 4, 5831, 4),
    (13310, 7, 5835, 3),
    (13317, 11, 5838, 3),
    (13328, 13, 5841, 3),
    (13341, 14, 5844, 3),
    (13355, 5, 5847, 3),
    (13360, 4, 5850, 2),
    (13364, 5, 5852, 2),
    (13369, 7, 5854, 2),
    (13376, 10, 5856, 3),
    (13386, 6, 5859, 3),
    (13392, 8, 5862, 3),
    (13400, 6, 5865, 3),
    (13406, 5, 5868, 2),
    (13411, 5, 5870, 3),
    (13416, 4, 5873, 4),
    (13420, 5, 5877, 3),
    (13425, 6, 5880, 2),
    (13431, 4, 5882, 3),
    (13435, 5, 5885, 3),
    (13440, 5, 5888, 3),
    (13445, 4, 5891, 2),
    (13449, 7, 5893, 3),
    (13456, 4, 5896, 3),
    (13460, 4, 5899, 3),
    (13464, 5, 5902, 3),
    (13469, 5, 5905, 3),
    (13474, 6, 5908, 3),
    (13480, 10, 5911, 2),
    (13490, 8, 5913, 2),
    (13498, 10, 5915, 3),
    (13508, 6, 5918, 2),
    (13514, 5, 5920, 2),
    (13519, 9, 5922, 3),
    (13528, 4, 5925, 3),
    (13532, 6, 5928, 2),
    (13538, 8, 5930, 2),
    (13546, 12, 5932, 6),
    (13558, 13, 5938, 6),
    (13571, 12, 5944, 6),
    (13583, 13, 5950, 6),
    (13596, 8, 5956, 2),
    (13604, 15, 5958, 3),
    (13619, 16, 5961, 3),
    (13635, 3, 5964, 2),
    (13638, 5, 5966, 3),
    (13643, 3, 5969, 3),
    (13646, 6, 5972, 3),
    (13652, 5, 5975, 3),
    (13657, 6, 5978, 3),
    (13663, 6, 5981, 1),
    (13669, 4, 5982, 1),
    (13673, 3, 5983, 4),
    (13676, 5, 5987, 3),
    (13681, 5, 5990, 6),
    (13686, 5, 5996, 6),
    (13691, 4, 6002, 4),
    (13695, 5, 6006, 3),
    (13700, 5, 6009, 3),
    (13705, 4, 6012, 4),
    (13709, 6, 6016, 6),
    (13715, 6, 6022, 6),
    (13721, 6, 6028, 6),
    (13727, 6, 6034, 6),
    (13733, 7, 6040, 3),
    (13740, 5, 6043, 2),
    (13745, 6, 6045, 3),
    (13751, 5, 6048, 3),
    (13756, 6, 6051, 3),
    (13762, 6, 6054, 3),
    (13768, 3, 6057, 4),
    (13771, 4, 6061, 4),
    (13775, 2, 6065, 3),
    (13777, 2, 6068, 3),
    (13779, 6, 6071, 3),
    (13785, 4, 6074, 4),
    (13789, 4, 6078, 3),
    (13793, 5, 6081, 3),
    (13798, 4, 6084, 3),
    (13802, 5, 6087, 3),
    (13807, 3, 6090, 4),
    (13810, 5, 6094, 3),
    (13815, 5, 6097, 3),
    (13820, 2, 6100, 2),
    (13822, 5, 6102, 3),
    (13827, 5, 6105, 3),
    (13832, 4, 6108, 3),
    (13836, 4, 6111, 3),
    (13840, 5, 6114, 3),
    (13845, 4, 6117, 4),
    (13849, 6, 6121, 3),
    (13855, 6, 6124, 3),
    (13861, 5, 6127, 3),
    (13866, 5, 6130, 3),
    (13871, 4, 6133, 4),
    (13875, 6, 6137, 3),
    (13881, 6, 6140, 3),
    (13887, 5, 6143, 3),
    (13892, 4, 6146, 3),
    (13896, 6, 6149, 3),
    (13902, 6, 6152, 2),
    (13908, 4, 6154, 2),
    (13912, 5, 6156, 2),
    (13917, 3, 6158, 2),
    (13920, 3, 6160, 2),
    (13923, 3, 6162, 4),
    (13926, 4, 6166, 2),
    (13930, 4, 6168, 4),
    (13934, 4, 6172, 4),
    (13938, 4, 6176, 2),
    (13942, 4, 6178, 2),
    (13946, 6, 6180, 2),
    (13952, 6, 6182, 2),
    (13958, 3, 6184, 2),
    (13961, 4, 6186, 2),
    (13965, 6, 6188, 3),
    (13971, 4, 6191, 2),
    (13975, 3, 6193, 4),
    (13978, 4, 6197, 2),
    (13982, 7, 6199, 3),
    (13989, 4, 6202, 4),
    (13993, 4, 6206, 4),
    (13997, 3, 6210, 3),
    (14000, 4, 6213, 3),
];

pub(crate) fn get_entity(bytes: &[u8]) -> Option<&'static str> {
    let found = ENTITY_INDEX
        .binary_search_by(|&(start, len, _, _)| {
            let start = start as usize;
            ENTITY_KEYS[start..start + len as usize].cmp(bytes)
        })
        .ok()?;
    let (_, _, start, len) = ENTITY_INDEX[found];
    let start = start as usize;
    Some(&ENTITY_VALUES[start..start + len as usize])
}
