# Copyright 2015 Google Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Note: this script no longer works on python 2!

# get https://html.spec.whatwg.org/multipage/entities.json
# Usage: python tools/mk_entities.py entities.json > src/entities.rs

import json
import sys

def chunks(items, per_line):
    joined = [''.join(items[i:i + per_line]) for i in range(0, len(items), per_line)]
    return '\\\n    '.join(joined)


def main(args):
    with open(args[1]) as json_file:
        jsondata = json.load(json_file)
    entities = [entity[1:-1] for entity in jsondata.keys() if entity.endswith(';')]
    entities.sort()

    keys, values, index = [], [], []
    key_at, value_at = 0, 0
    for e in entities:
        codepoints = jsondata['&' + e + ';']["codepoints"]
        escaped = ''.join([r'\u{%04X}' % cp for cp in codepoints])
        value_len = len(''.join(chr(cp) for cp in codepoints).encode('utf-8'))
        index.append((key_at, len(e), value_at, value_len))
        keys.append(e)
        values.append(escaped)
        key_at += len(e)
        value_at += value_len

    print(f"""// Copyright 2015 Google Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

//! Expansions of HTML5 entities

// Autogenerated by mk_entities.py

/// Entity names, concatenated in sorted order.
static ENTITY_KEYS: &[u8] = b"{chunks(keys, 12)}";

/// Entity expansions, in the same order as [`ENTITY_KEYS`].
static ENTITY_VALUES: &str = "{chunks(values, 6)}";

/// `(name offset, name length, expansion offset, expansion length)` per entity,
/// sorted by name for binary search. Offsets, not `&str`, to avoid relocations.
static ENTITY_INDEX: [(u16, u8, u16, u8); {len(index)}] = [""")

    for (a, b, c, d) in index:
        print(f"    ({a}, {b}, {c}, {d}),")
    print("""];

pub(crate) fn get_entity(bytes: &[u8]) -> Option<&'static str> {
    let found = ENTITY_INDEX
        .binary_search_by(|&(start, len, _, _)| {
            let start = start as usize;
            ENTITY_KEYS[start..start + len as usize].cmp(bytes)
        })
        .ok()?;
    let (_, _, start, len) = ENTITY_INDEX[found];
    let start = start as usize;
    Some(&ENTITY_VALUES[start..start + len as usize])
}""")

main(sys.argv)