//! HTML/SVG attribute ↔ hast-property tables.
//!
//! Each row is `(normalized name, hast property, attribute, coercion class)`,
//! sorted by name for binary search. A single table per schema serves both
//! directions: the name is keyed in both its attribute and property forms, so
//! attribute→property lookups read the property column and property→attribute
//! lookups read the attribute column.

/// (normalized name, hast property, HTML/SVG attribute, coercion class),
/// sorted by name for binary search.
pub(crate) static HTML_TABLE: &[(&str, &str, &str, u8)] = &[
    ("abbr", "abbr", "abbr", 0),
    ("accept", "accept", "accept", 5),
    ("accept-charset", "acceptCharset", "accept-charset", 4),
    ("acceptcharset", "acceptCharset", "accept-charset", 4),
    ("accesskey", "accessKey", "accesskey", 4),
    ("action", "action", "action", 0),
    ("align", "align", "align", 0),
    ("alink", "aLink", "alink", 0),
    ("allow", "allow", "allow", 0),
    ("allowfullscreen", "allowFullScreen", "allowfullscreen", 1),
    (
        "allowpaymentrequest",
        "allowPaymentRequest",
        "allowpaymentrequest",
        1,
    ),
    (
        "allowtransparency",
        "allowTransparency",
        "allowtransparency",
        0,
    ),
    ("allowusermedia", "allowUserMedia", "allowusermedia", 1),
    ("alpha", "alpha", "alpha", 1),
    ("alt", "alt", "alt", 0),
    ("archive", "archive", "archive", 4),
    (
        "aria-activedescendant",
        "ariaActiveDescendant",
        "aria-activedescendant",
        0,
    ),
    ("aria-atomic", "ariaAtomic", "aria-atomic", 0),
    (
        "aria-autocomplete",
        "ariaAutoComplete",
        "aria-autocomplete",
        0,
    ),
    ("aria-busy", "ariaBusy", "aria-busy", 0),
    ("aria-checked", "ariaChecked", "aria-checked", 0),
    ("aria-colcount", "ariaColCount", "aria-colcount", 3),
    ("aria-colindex", "ariaColIndex", "aria-colindex", 3),
    ("aria-colspan", "ariaColSpan", "aria-colspan", 3),
    ("aria-controls", "ariaControls", "aria-controls", 4),
    ("aria-current", "ariaCurrent", "aria-current", 0),
    ("aria-describedby", "ariaDescribedBy", "aria-describedby", 4),
    ("aria-details", "ariaDetails", "aria-details", 0),
    ("aria-disabled", "ariaDisabled", "aria-disabled", 0),
    ("aria-dropeffect", "ariaDropEffect", "aria-dropeffect", 4),
    (
        "aria-errormessage",
        "ariaErrorMessage",
        "aria-errormessage",
        0,
    ),
    ("aria-expanded", "ariaExpanded", "aria-expanded", 0),
    ("aria-flowto", "ariaFlowTo", "aria-flowto", 4),
    ("aria-grabbed", "ariaGrabbed", "aria-grabbed", 0),
    ("aria-haspopup", "ariaHasPopup", "aria-haspopup", 0),
    ("aria-hidden", "ariaHidden", "aria-hidden", 0),
    ("aria-invalid", "ariaInvalid", "aria-invalid", 0),
    (
        "aria-keyshortcuts",
        "ariaKeyShortcuts",
        "aria-keyshortcuts",
        0,
    ),
    ("aria-label", "ariaLabel", "aria-label", 0),
    ("aria-labelledby", "ariaLabelledBy", "aria-labelledby", 4),
    ("aria-level", "ariaLevel", "aria-level", 3),
    ("aria-live", "ariaLive", "aria-live", 0),
    ("aria-modal", "ariaModal", "aria-modal", 0),
    ("aria-multiline", "ariaMultiLine", "aria-multiline", 0),
    (
        "aria-multiselectable",
        "ariaMultiSelectable",
        "aria-multiselectable",
        0,
    ),
    ("aria-orientation", "ariaOrientation", "aria-orientation", 0),
    ("aria-owns", "ariaOwns", "aria-owns", 4),
    ("aria-placeholder", "ariaPlaceholder", "aria-placeholder", 0),
    ("aria-posinset", "ariaPosInSet", "aria-posinset", 3),
    ("aria-pressed", "ariaPressed", "aria-pressed", 0),
    ("aria-readonly", "ariaReadOnly", "aria-readonly", 0),
    ("aria-relevant", "ariaRelevant", "aria-relevant", 0),
    ("aria-required", "ariaRequired", "aria-required", 0),
    (
        "aria-roledescription",
        "ariaRoleDescription",
        "aria-roledescription",
        4,
    ),
    ("aria-rowcount", "ariaRowCount", "aria-rowcount", 3),
    ("aria-rowindex", "ariaRowIndex", "aria-rowindex", 3),
    ("aria-rowspan", "ariaRowSpan", "aria-rowspan", 3),
    ("aria-selected", "ariaSelected", "aria-selected", 0),
    ("aria-setsize", "ariaSetSize", "aria-setsize", 3),
    ("aria-sort", "ariaSort", "aria-sort", 0),
    ("aria-valuemax", "ariaValueMax", "aria-valuemax", 3),
    ("aria-valuemin", "ariaValueMin", "aria-valuemin", 3),
    ("aria-valuenow", "ariaValueNow", "aria-valuenow", 3),
    ("aria-valuetext", "ariaValueText", "aria-valuetext", 0),
    (
        "ariaactivedescendant",
        "ariaActiveDescendant",
        "aria-activedescendant",
        0,
    ),
    ("ariaatomic", "ariaAtomic", "aria-atomic", 0),
    (
        "ariaautocomplete",
        "ariaAutoComplete",
        "aria-autocomplete",
        0,
    ),
    ("ariabusy", "ariaBusy", "aria-busy", 0),
    ("ariachecked", "ariaChecked", "aria-checked", 0),
    ("ariacolcount", "ariaColCount", "aria-colcount", 3),
    ("ariacolindex", "ariaColIndex", "aria-colindex", 3),
    ("ariacolspan", "ariaColSpan", "aria-colspan", 3),
    ("ariacontrols", "ariaControls", "aria-controls", 4),
    ("ariacurrent", "ariaCurrent", "aria-current", 0),
    ("ariadescribedby", "ariaDescribedBy", "aria-describedby", 4),
    ("ariadetails", "ariaDetails", "aria-details", 0),
    ("ariadisabled", "ariaDisabled", "aria-disabled", 0),
    ("ariadropeffect", "ariaDropEffect", "aria-dropeffect", 4),
    (
        "ariaerrormessage",
        "ariaErrorMessage",
        "aria-errormessage",
        0,
    ),
    ("ariaexpanded", "ariaExpanded", "aria-expanded", 0),
    ("ariaflowto", "ariaFlowTo", "aria-flowto", 4),
    ("ariagrabbed", "ariaGrabbed", "aria-grabbed", 0),
    ("ariahaspopup", "ariaHasPopup", "aria-haspopup", 0),
    ("ariahidden", "ariaHidden", "aria-hidden", 0),
    ("ariainvalid", "ariaInvalid", "aria-invalid", 0),
    (
        "ariakeyshortcuts",
        "ariaKeyShortcuts",
        "aria-keyshortcuts",
        0,
    ),
    ("arialabel", "ariaLabel", "aria-label", 0),
    ("arialabelledby", "ariaLabelledBy", "aria-labelledby", 4),
    ("arialevel", "ariaLevel", "aria-level", 3),
    ("arialive", "ariaLive", "aria-live", 0),
    ("ariamodal", "ariaModal", "aria-modal", 0),
    ("ariamultiline", "ariaMultiLine", "aria-multiline", 0),
    (
        "ariamultiselectable",
        "ariaMultiSelectable",
        "aria-multiselectable",
        0,
    ),
    ("ariaorientation", "ariaOrientation", "aria-orientation", 0),
    ("ariaowns", "ariaOwns", "aria-owns", 4),
    ("ariaplaceholder", "ariaPlaceholder", "aria-placeholder", 0),
    ("ariaposinset", "ariaPosInSet", "aria-posinset", 3),
    ("ariapressed", "ariaPressed", "aria-pressed", 0),
    ("ariareadonly", "ariaReadOnly", "aria-readonly", 0),
    ("ariarelevant", "ariaRelevant", "aria-relevant", 0),
    ("ariarequired", "ariaRequired", "aria-required", 0),
    (
        "ariaroledescription",
        "ariaRoleDescription",
        "aria-roledescription",
        4,
    ),
    ("ariarowcount", "ariaRowCount", "aria-rowcount", 3),
    ("ariarowindex", "ariaRowIndex", "aria-rowindex", 3),
    ("ariarowspan", "ariaRowSpan", "aria-rowspan", 3),
    ("ariaselected", "ariaSelected", "aria-selected", 0),
    ("ariasetsize", "ariaSetSize", "aria-setsize", 3),
    ("ariasort", "ariaSort", "aria-sort", 0),
    ("ariavaluemax", "ariaValueMax", "aria-valuemax", 3),
    ("ariavaluemin", "ariaValueMin", "aria-valuemin", 3),
    ("ariavaluenow", "ariaValueNow", "aria-valuenow", 3),
    ("ariavaluetext", "ariaValueText", "aria-valuetext", 0),
    ("as", "as", "as", 0),
    ("async", "async", "async", 1),
    ("autocapitalize", "autoCapitalize", "autocapitalize", 0),
    ("autocomplete", "autoComplete", "autocomplete", 4),
    ("autocorrect", "autoCorrect", "autocorrect", 0),
    ("autofocus", "autoFocus", "autofocus", 1),
    ("autoplay", "autoPlay", "autoplay", 1),
    ("autosave", "autoSave", "autosave", 0),
    ("axis", "axis", "axis", 0),
    ("background", "background", "background", 0),
    ("bgcolor", "bgColor", "bgcolor", 0),
    ("blocking", "blocking", "blocking", 4),
    ("border", "border", "border", 3),
    ("bordercolor", "borderColor", "bordercolor", 0),
    ("bottommargin", "bottomMargin", "bottommargin", 3),
    ("capture", "capture", "capture", 0),
    ("cellpadding", "cellPadding", "cellpadding", 0),
    ("cellspacing", "cellSpacing", "cellspacing", 0),
    ("char", "char", "char", 0),
    ("charoff", "charOff", "charoff", 0),
    ("charset", "charSet", "charset", 0),
    ("checked", "checked", "checked", 1),
    ("cite", "cite", "cite", 0),
    ("class", "className", "class", 4),
    ("classid", "classId", "classid", 0),
    ("classname", "className", "class", 4),
    ("clear", "clear", "clear", 0),
    ("closedby", "closedBy", "closedby", 0),
    ("code", "code", "code", 0),
    ("codebase", "codeBase", "codebase", 0),
    ("codetype", "codeType", "codetype", 0),
    ("color", "color", "color", 0),
    ("colorspace", "colorSpace", "colorspace", 0),
    ("cols", "cols", "cols", 3),
    ("colspan", "colSpan", "colspan", 3),
    ("command", "command", "command", 0),
    ("commandfor", "commandFor", "commandfor", 0),
    ("compact", "compact", "compact", 1),
    ("content", "content", "content", 0),
    ("contenteditable", "contentEditable", "contenteditable", 0),
    ("controls", "controls", "controls", 1),
    ("controlslist", "controlsList", "controlslist", 4),
    ("coords", "coords", "coords", 3),
    ("credentialless", "credentialless", "credentialless", 1),
    ("crossorigin", "crossOrigin", "crossorigin", 0),
    ("data", "data", "data", 0),
    ("datetime", "dateTime", "datetime", 0),
    ("declare", "declare", "declare", 1),
    ("decoding", "decoding", "decoding", 0),
    ("default", "default", "default", 1),
    ("defer", "defer", "defer", 1),
    ("dir", "dir", "dir", 0),
    ("dirname", "dirName", "dirname", 0),
    ("disabled", "disabled", "disabled", 1),
    (
        "disablepictureinpicture",
        "disablePictureInPicture",
        "disablepictureinpicture",
        1,
    ),
    (
        "disableremoteplayback",
        "disableRemotePlayback",
        "disableremoteplayback",
        1,
    ),
    ("download", "download", "download", 2),
    ("draggable", "draggable", "draggable", 0),
    ("enctype", "encType", "enctype", 0),
    ("enterkeyhint", "enterKeyHint", "enterkeyhint", 0),
    ("event", "event", "event", 0),
    ("exportparts", "exportParts", "exportparts", 5),
    ("face", "face", "face", 0),
    ("fetchpriority", "fetchPriority", "fetchpriority", 0),
    ("for", "htmlFor", "for", 4),
    ("form", "form", "form", 0),
    ("formaction", "formAction", "formaction", 0),
    ("formenctype", "formEncType", "formenctype", 0),
    ("formmethod", "formMethod", "formmethod", 0),
    ("formnovalidate", "formNoValidate", "formnovalidate", 1),
    ("formtarget", "formTarget", "formtarget", 0),
    ("frame", "frame", "frame", 0),
    ("frameborder", "frameBorder", "frameborder", 0),
    ("headers", "headers", "headers", 4),
    ("height", "height", "height", 3),
    ("hidden", "hidden", "hidden", 2),
    ("high", "high", "high", 3),
    ("href", "href", "href", 0),
    ("hreflang", "hrefLang", "hreflang", 0),
    ("hspace", "hSpace", "hspace", 3),
    ("htmlfor", "htmlFor", "for", 4),
    ("http-equiv", "httpEquiv", "http-equiv", 4),
    ("httpequiv", "httpEquiv", "http-equiv", 4),
    ("id", "id", "id", 0),
    ("imagesizes", "imageSizes", "imagesizes", 0),
    ("imagesrcset", "imageSrcSet", "imagesrcset", 0),
    ("inert", "inert", "inert", 1),
    ("inputmode", "inputMode", "inputmode", 0),
    ("integrity", "integrity", "integrity", 0),
    ("is", "is", "is", 0),
    ("ismap", "isMap", "ismap", 1),
    ("itemid", "itemId", "itemid", 0),
    ("itemprop", "itemProp", "itemprop", 4),
    ("itemref", "itemRef", "itemref", 4),
    ("itemscope", "itemScope", "itemscope", 1),
    ("itemtype", "itemType", "itemtype", 4),
    ("kind", "kind", "kind", 0),
    ("label", "label", "label", 0),
    ("lang", "lang", "lang", 0),
    ("language", "language", "language", 0),
    ("leftmargin", "leftMargin", "leftmargin", 3),
    ("link", "link", "link", 0),
    ("list", "list", "list", 0),
    ("loading", "loading", "loading", 0),
    ("longdesc", "longDesc", "longdesc", 0),
    ("loop", "loop", "loop", 1),
    ("low", "low", "low", 3),
    ("lowsrc", "lowSrc", "lowsrc", 0),
    ("manifest", "manifest", "manifest", 0),
    ("marginheight", "marginHeight", "marginheight", 3),
    ("marginwidth", "marginWidth", "marginwidth", 3),
    ("max", "max", "max", 0),
    ("maxlength", "maxLength", "maxlength", 3),
    ("media", "media", "media", 0),
    ("method", "method", "method", 0),
    ("min", "min", "min", 0),
    ("minlength", "minLength", "minlength", 3),
    ("multiple", "multiple", "multiple", 1),
    ("muted", "muted", "muted", 1),
    ("name", "name", "name", 0),
    ("nohref", "noHref", "nohref", 1),
    ("nomodule", "noModule", "nomodule", 1),
    ("nonce", "nonce", "nonce", 0),
    ("noresize", "noResize", "noresize", 1),
    ("noshade", "noShade", "noshade", 1),
    ("novalidate", "noValidate", "novalidate", 1),
    ("nowrap", "noWrap", "nowrap", 1),
    ("object", "object", "object", 0),
    ("onabort", "onAbort", "onabort", 0),
    ("onafterprint", "onAfterPrint", "onafterprint", 0),
    ("onauxclick", "onAuxClick", "onauxclick", 0),
    ("onbeforematch", "onBeforeMatch", "onbeforematch", 0),
    ("onbeforeprint", "onBeforePrint", "onbeforeprint", 0),
    ("onbeforetoggle", "onBeforeToggle", "onbeforetoggle", 0),
    ("onbeforeunload", "onBeforeUnload", "onbeforeunload", 0),
    ("onblur", "onBlur", "onblur", 0),
    ("oncancel", "onCancel", "oncancel", 0),
    ("oncanplay", "onCanPlay", "oncanplay", 0),
    (
        "oncanplaythrough",
        "onCanPlayThrough",
        "oncanplaythrough",
        0,
    ),
    ("onchange", "onChange", "onchange", 0),
    ("onclick", "onClick", "onclick", 0),
    ("onclose", "onClose", "onclose", 0),
    ("oncontextlost", "onContextLost", "oncontextlost", 0),
    ("oncontextmenu", "onContextMenu", "oncontextmenu", 0),
    (
        "oncontextrestored",
        "onContextRestored",
        "oncontextrestored",
        0,
    ),
    ("oncopy", "onCopy", "oncopy", 0),
    ("oncuechange", "onCueChange", "oncuechange", 0),
    ("oncut", "onCut", "oncut", 0),
    ("ondblclick", "onDblClick", "ondblclick", 0),
    ("ondrag", "onDrag", "ondrag", 0),
    ("ondragend", "onDragEnd", "ondragend", 0),
    ("ondragenter", "onDragEnter", "ondragenter", 0),
    ("ondragexit", "onDragExit", "ondragexit", 0),
    ("ondragleave", "onDragLeave", "ondragleave", 0),
    ("ondragover", "onDragOver", "ondragover", 0),
    ("ondragstart", "onDragStart", "ondragstart", 0),
    ("ondrop", "onDrop", "ondrop", 0),
    (
        "ondurationchange",
        "onDurationChange",
        "ondurationchange",
        0,
    ),
    ("onemptied", "onEmptied", "onemptied", 0),
    ("onended", "onEnded", "onended", 0),
    ("onerror", "onError", "onerror", 0),
    ("onfocus", "onFocus", "onfocus", 0),
    ("onformdata", "onFormData", "onformdata", 0),
    ("onhashchange", "onHashChange", "onhashchange", 0),
    ("oninput", "onInput", "oninput", 0),
    ("oninvalid", "onInvalid", "oninvalid", 0),
    ("onkeydown", "onKeyDown", "onkeydown", 0),
    ("onkeypress", "onKeyPress", "onkeypress", 0),
    ("onkeyup", "onKeyUp", "onkeyup", 0),
    (
        "onlanguagechange",
        "onLanguageChange",
        "onlanguagechange",
        0,
    ),
    ("onload", "onLoad", "onload", 0),
    ("onloadeddata", "onLoadedData", "onloadeddata", 0),
    (
        "onloadedmetadata",
        "onLoadedMetadata",
        "onloadedmetadata",
        0,
    ),
    ("onloadend", "onLoadEnd", "onloadend", 0),
    ("onloadstart", "onLoadStart", "onloadstart", 0),
    ("onmessage", "onMessage", "onmessage", 0),
    ("onmessageerror", "onMessageError", "onmessageerror", 0),
    ("onmousedown", "onMouseDown", "onmousedown", 0),
    ("onmouseenter", "onMouseEnter", "onmouseenter", 0),
    ("onmouseleave", "onMouseLeave", "onmouseleave", 0),
    ("onmousemove", "onMouseMove", "onmousemove", 0),
    ("onmouseout", "onMouseOut", "onmouseout", 0),
    ("onmouseover", "onMouseOver", "onmouseover", 0),
    ("onmouseup", "onMouseUp", "onmouseup", 0),
    ("onoffline", "onOffline", "onoffline", 0),
    ("ononline", "onOnline", "ononline", 0),
    ("onpagehide", "onPageHide", "onpagehide", 0),
    ("onpageshow", "onPageShow", "onpageshow", 0),
    ("onpaste", "onPaste", "onpaste", 0),
    ("onpause", "onPause", "onpause", 0),
    ("onplay", "onPlay", "onplay", 0),
    ("onplaying", "onPlaying", "onplaying", 0),
    ("onpopstate", "onPopState", "onpopstate", 0),
    ("onprogress", "onProgress", "onprogress", 0),
    ("onratechange", "onRateChange", "onratechange", 0),
    (
        "onrejectionhandled",
        "onRejectionHandled",
        "onrejectionhandled",
        0,
    ),
    ("onreset", "onReset", "onreset", 0),
    ("onresize", "onResize", "onresize", 0),
    ("onscroll", "onScroll", "onscroll", 0),
    ("onscrollend", "onScrollEnd", "onscrollend", 0),
    (
        "onsecuritypolicyviolation",
        "onSecurityPolicyViolation",
        "onsecuritypolicyviolation",
        0,
    ),
    ("onseeked", "onSeeked", "onseeked", 0),
    ("onseeking", "onSeeking", "onseeking", 0),
    ("onselect", "onSelect", "onselect", 0),
    ("onslotchange", "onSlotChange", "onslotchange", 0),
    ("onstalled", "onStalled", "onstalled", 0),
    ("onstorage", "onStorage", "onstorage", 0),
    ("onsubmit", "onSubmit", "onsubmit", 0),
    ("onsuspend", "onSuspend", "onsuspend", 0),
    ("ontimeupdate", "onTimeUpdate", "ontimeupdate", 0),
    ("ontoggle", "onToggle", "ontoggle", 0),
    (
        "onunhandledrejection",
        "onUnhandledRejection",
        "onunhandledrejection",
        0,
    ),
    ("onunload", "onUnload", "onunload", 0),
    ("onvolumechange", "onVolumeChange", "onvolumechange", 0),
    ("onwaiting", "onWaiting", "onwaiting", 0),
    ("onwheel", "onWheel", "onwheel", 0),
    ("open", "open", "open", 1),
    ("optimum", "optimum", "optimum", 3),
    ("part", "part", "part", 4),
    ("pattern", "pattern", "pattern", 0),
    ("ping", "ping", "ping", 4),
    ("placeholder", "placeholder", "placeholder", 0),
    ("playsinline", "playsInline", "playsinline", 1),
    ("popover", "popover", "popover", 0),
    ("popovertarget", "popoverTarget", "popovertarget", 0),
    (
        "popovertargetaction",
        "popoverTargetAction",
        "popovertargetaction",
        0,
    ),
    ("poster", "poster", "poster", 0),
    ("prefix", "prefix", "prefix", 0),
    ("preload", "preload", "preload", 0),
    ("profile", "profile", "profile", 0),
    ("prompt", "prompt", "prompt", 0),
    ("property", "property", "property", 0),
    ("readonly", "readOnly", "readonly", 1),
    ("referrerpolicy", "referrerPolicy", "referrerpolicy", 0),
    ("rel", "rel", "rel", 4),
    ("required", "required", "required", 1),
    ("results", "results", "results", 3),
    ("rev", "rev", "rev", 0),
    ("reversed", "reversed", "reversed", 1),
    ("rightmargin", "rightMargin", "rightmargin", 3),
    ("role", "role", "role", 0),
    ("rows", "rows", "rows", 3),
    ("rowspan", "rowSpan", "rowspan", 3),
    ("rules", "rules", "rules", 0),
    ("sandbox", "sandbox", "sandbox", 4),
    ("scheme", "scheme", "scheme", 0),
    ("scope", "scope", "scope", 0),
    ("scoped", "scoped", "scoped", 1),
    ("scrolling", "scrolling", "scrolling", 0),
    ("seamless", "seamless", "seamless", 1),
    ("security", "security", "security", 0),
    ("selected", "selected", "selected", 1),
    (
        "shadowrootclonable",
        "shadowRootClonable",
        "shadowrootclonable",
        1,
    ),
    (
        "shadowrootcustomelementregistry",
        "shadowRootCustomElementRegistry",
        "shadowrootcustomelementregistry",
        1,
    ),
    (
        "shadowrootdelegatesfocus",
        "shadowRootDelegatesFocus",
        "shadowrootdelegatesfocus",
        1,
    ),
    ("shadowrootmode", "shadowRootMode", "shadowrootmode", 0),
    (
        "shadowrootserializable",
        "shadowRootSerializable",
        "shadowrootserializable",
        1,
    ),
    ("shape", "shape", "shape", 0),
    ("size", "size", "size", 3),
    ("sizes", "sizes", "sizes", 0),
    ("slot", "slot", "slot", 0),
    ("span", "span", "span", 3),
    ("spellcheck", "spellCheck", "spellcheck", 0),
    ("src", "src", "src", 0),
    ("srcdoc", "srcDoc", "srcdoc", 0),
    ("srclang", "srcLang", "srclang", 0),
    ("srcset", "srcSet", "srcset", 0),
    ("standby", "standby", "standby", 0),
    ("start", "start", "start", 3),
    ("step", "step", "step", 0),
    ("style", "style", "style", 0),
    ("summary", "summary", "summary", 0),
    ("tabindex", "tabIndex", "tabindex", 3),
    ("target", "target", "target", 0),
    ("text", "text", "text", 0),
    ("title", "title", "title", 0),
    ("topmargin", "topMargin", "topmargin", 3),
    ("translate", "translate", "translate", 0),
    ("type", "type", "type", 0),
    ("typemustmatch", "typeMustMatch", "typemustmatch", 1),
    ("unselectable", "unselectable", "unselectable", 0),
    ("usemap", "useMap", "usemap", 0),
    ("valign", "vAlign", "valign", 0),
    ("value", "value", "value", 0),
    ("valuetype", "valueType", "valuetype", 0),
    ("version", "version", "version", 0),
    ("vlink", "vLink", "vlink", 0),
    ("vspace", "vSpace", "vspace", 3),
    ("width", "width", "width", 3),
    ("wrap", "wrap", "wrap", 0),
    (
        "writingsuggestions",
        "writingSuggestions",
        "writingsuggestions",
        0,
    ),
    ("xlink:actuate", "xLinkActuate", "xlink:actuate", 0),
    ("xlink:arcrole", "xLinkArcRole", "xlink:arcrole", 0),
    ("xlink:href", "xLinkHref", "xlink:href", 0),
    ("xlink:role", "xLinkRole", "xlink:role", 0),
    ("xlink:show", "xLinkShow", "xlink:show", 0),
    ("xlink:title", "xLinkTitle", "xlink:title", 0),
    ("xlink:type", "xLinkType", "xlink:type", 0),
    ("xlinkactuate", "xLinkActuate", "xlink:actuate", 0),
    ("xlinkarcrole", "xLinkArcRole", "xlink:arcrole", 0),
    ("xlinkhref", "xLinkHref", "xlink:href", 0),
    ("xlinkrole", "xLinkRole", "xlink:role", 0),
    ("xlinkshow", "xLinkShow", "xlink:show", 0),
    ("xlinktitle", "xLinkTitle", "xlink:title", 0),
    ("xlinktype", "xLinkType", "xlink:type", 0),
    ("xml:base", "xmlBase", "xml:base", 0),
    ("xml:lang", "xmlLang", "xml:lang", 0),
    ("xml:space", "xmlSpace", "xml:space", 0),
    ("xmlbase", "xmlBase", "xml:base", 0),
    ("xmllang", "xmlLang", "xml:lang", 0),
    ("xmlns", "xmlns", "xmlns", 0),
    ("xmlns:xlink", "xmlnsXLink", "xmlns:xlink", 0),
    ("xmlnsxlink", "xmlnsXLink", "xmlns:xlink", 0),
    ("xmlspace", "xmlSpace", "xml:space", 0),
];

/// (normalized name, hast property, HTML/SVG attribute, coercion class),
/// sorted by name for binary search.
pub(crate) static SVG_TABLE: &[(&str, &str, &str, u8)] = &[
    ("about", "about", "about", 6),
    ("accent-height", "accentHeight", "accent-height", 3),
    ("accentheight", "accentHeight", "accent-height", 3),
    ("accumulate", "accumulate", "accumulate", 0),
    ("additive", "additive", "additive", 0),
    (
        "alignment-baseline",
        "alignmentBaseline",
        "alignment-baseline",
        0,
    ),
    (
        "alignmentbaseline",
        "alignmentBaseline",
        "alignment-baseline",
        0,
    ),
    ("alphabetic", "alphabetic", "alphabetic", 3),
    ("amplitude", "amplitude", "amplitude", 3),
    ("arabic-form", "arabicForm", "arabic-form", 0),
    ("arabicform", "arabicForm", "arabic-form", 0),
    (
        "aria-activedescendant",
        "ariaActiveDescendant",
        "aria-activedescendant",
        0,
    ),
    ("aria-atomic", "ariaAtomic", "aria-atomic", 0),
    (
        "aria-autocomplete",
        "ariaAutoComplete",
        "aria-autocomplete",
        0,
    ),
    ("aria-busy", "ariaBusy", "aria-busy", 0),
    ("aria-checked", "ariaChecked", "aria-checked", 0),
    ("aria-colcount", "ariaColCount", "aria-colcount", 3),
    ("aria-colindex", "ariaColIndex", "aria-colindex", 3),
    ("aria-colspan", "ariaColSpan", "aria-colspan", 3),
    ("aria-controls", "ariaControls", "aria-controls", 4),
    ("aria-current", "ariaCurrent", "aria-current", 0),
    ("aria-describedby", "ariaDescribedBy", "aria-describedby", 4),
    ("aria-details", "ariaDetails", "aria-details", 0),
    ("aria-disabled", "ariaDisabled", "aria-disabled", 0),
    ("aria-dropeffect", "ariaDropEffect", "aria-dropeffect", 4),
    (
        "aria-errormessage",
        "ariaErrorMessage",
        "aria-errormessage",
        0,
    ),
    ("aria-expanded", "ariaExpanded", "aria-expanded", 0),
    ("aria-flowto", "ariaFlowTo", "aria-flowto", 4),
    ("aria-grabbed", "ariaGrabbed", "aria-grabbed", 0),
    ("aria-haspopup", "ariaHasPopup", "aria-haspopup", 0),
    ("aria-hidden", "ariaHidden", "aria-hidden", 0),
    ("aria-invalid", "ariaInvalid", "aria-invalid", 0),
    (
        "aria-keyshortcuts",
        "ariaKeyShortcuts",
        "aria-keyshortcuts",
        0,
    ),
    ("aria-label", "ariaLabel", "aria-label", 0),
    ("aria-labelledby", "ariaLabelledBy", "aria-labelledby", 4),
    ("aria-level", "ariaLevel", "aria-level", 3),
    ("aria-live", "ariaLive", "aria-live", 0),
    ("aria-modal", "ariaModal", "aria-modal", 0),
    ("aria-multiline", "ariaMultiLine", "aria-multiline", 0),
    (
        "aria-multiselectable",
        "ariaMultiSelectable",
        "aria-multiselectable",
        0,
    ),
    ("aria-orientation", "ariaOrientation", "aria-orientation", 0),
    ("aria-owns", "ariaOwns", "aria-owns", 4),
    ("aria-placeholder", "ariaPlaceholder", "aria-placeholder", 0),
    ("aria-posinset", "ariaPosInSet", "aria-posinset", 3),
    ("aria-pressed", "ariaPressed", "aria-pressed", 0),
    ("aria-readonly", "ariaReadOnly", "aria-readonly", 0),
    ("aria-relevant", "ariaRelevant", "aria-relevant", 0),
    ("aria-required", "ariaRequired", "aria-required", 0),
    (
        "aria-roledescription",
        "ariaRoleDescription",
        "aria-roledescription",
        4,
    ),
    ("aria-rowcount", "ariaRowCount", "aria-rowcount", 3),
    ("aria-rowindex", "ariaRowIndex", "aria-rowindex", 3),
    ("aria-rowspan", "ariaRowSpan", "aria-rowspan", 3),
    ("aria-selected", "ariaSelected", "aria-selected", 0),
    ("aria-setsize", "ariaSetSize", "aria-setsize", 3),
    ("aria-sort", "ariaSort", "aria-sort", 0),
    ("aria-valuemax", "ariaValueMax", "aria-valuemax", 3),
    ("aria-valuemin", "ariaValueMin", "aria-valuemin", 3),
    ("aria-valuenow", "ariaValueNow", "aria-valuenow", 3),
    ("aria-valuetext", "ariaValueText", "aria-valuetext", 0),
    (
        "ariaactivedescendant",
        "ariaActiveDescendant",
        "aria-activedescendant",
        0,
    ),
    ("ariaatomic", "ariaAtomic", "aria-atomic", 0),
    (
        "ariaautocomplete",
        "ariaAutoComplete",
        "aria-autocomplete",
        0,
    ),
    ("ariabusy", "ariaBusy", "aria-busy", 0),
    ("ariachecked", "ariaChecked", "aria-checked", 0),
    ("ariacolcount", "ariaColCount", "aria-colcount", 3),
    ("ariacolindex", "ariaColIndex", "aria-colindex", 3),
    ("ariacolspan", "ariaColSpan", "aria-colspan", 3),
    ("ariacontrols", "ariaControls", "aria-controls", 4),
    ("ariacurrent", "ariaCurrent", "aria-current", 0),
    ("ariadescribedby", "ariaDescribedBy", "aria-describedby", 4),
    ("ariadetails", "ariaDetails", "aria-details", 0),
    ("ariadisabled", "ariaDisabled", "aria-disabled", 0),
    ("ariadropeffect", "ariaDropEffect", "aria-dropeffect", 4),
    (
        "ariaerrormessage",
        "ariaErrorMessage",
        "aria-errormessage",
        0,
    ),
    ("ariaexpanded", "ariaExpanded", "aria-expanded", 0),
    ("ariaflowto", "ariaFlowTo", "aria-flowto", 4),
    ("ariagrabbed", "ariaGrabbed", "aria-grabbed", 0),
    ("ariahaspopup", "ariaHasPopup", "aria-haspopup", 0),
    ("ariahidden", "ariaHidden", "aria-hidden", 0),
    ("ariainvalid", "ariaInvalid", "aria-invalid", 0),
    (
        "ariakeyshortcuts",
        "ariaKeyShortcuts",
        "aria-keyshortcuts",
        0,
    ),
    ("arialabel", "ariaLabel", "aria-label", 0),
    ("arialabelledby", "ariaLabelledBy", "aria-labelledby", 4),
    ("arialevel", "ariaLevel", "aria-level", 3),
    ("arialive", "ariaLive", "aria-live", 0),
    ("ariamodal", "ariaModal", "aria-modal", 0),
    ("ariamultiline", "ariaMultiLine", "aria-multiline", 0),
    (
        "ariamultiselectable",
        "ariaMultiSelectable",
        "aria-multiselectable",
        0,
    ),
    ("ariaorientation", "ariaOrientation", "aria-orientation", 0),
    ("ariaowns", "ariaOwns", "aria-owns", 4),
    ("ariaplaceholder", "ariaPlaceholder", "aria-placeholder", 0),
    ("ariaposinset", "ariaPosInSet", "aria-posinset", 3),
    ("ariapressed", "ariaPressed", "aria-pressed", 0),
    ("ariareadonly", "ariaReadOnly", "aria-readonly", 0),
    ("ariarelevant", "ariaRelevant", "aria-relevant", 0),
    ("ariarequired", "ariaRequired", "aria-required", 0),
    (
        "ariaroledescription",
        "ariaRoleDescription",
        "aria-roledescription",
        4,
    ),
    ("ariarowcount", "ariaRowCount", "aria-rowcount", 3),
    ("ariarowindex", "ariaRowIndex", "aria-rowindex", 3),
    ("ariarowspan", "ariaRowSpan", "aria-rowspan", 3),
    ("ariaselected", "ariaSelected", "aria-selected", 0),
    ("ariasetsize", "ariaSetSize", "aria-setsize", 3),
    ("ariasort", "ariaSort", "aria-sort", 0),
    ("ariavaluemax", "ariaValueMax", "aria-valuemax", 3),
    ("ariavaluemin", "ariaValueMin", "aria-valuemin", 3),
    ("ariavaluenow", "ariaValueNow", "aria-valuenow", 3),
    ("ariavaluetext", "ariaValueText", "aria-valuetext", 0),
    ("ascent", "ascent", "ascent", 3),
    ("attributename", "attributeName", "attributeName", 0),
    ("attributetype", "attributeType", "attributeType", 0),
    ("azimuth", "azimuth", "azimuth", 3),
    ("bandwidth", "bandwidth", "bandwidth", 0),
    ("basefrequency", "baseFrequency", "baseFrequency", 0),
    ("baseline-shift", "baselineShift", "baseline-shift", 0),
    ("baselineshift", "baselineShift", "baseline-shift", 0),
    ("baseprofile", "baseProfile", "baseProfile", 0),
    ("bbox", "bbox", "bbox", 0),
    ("begin", "begin", "begin", 0),
    ("bias", "bias", "bias", 3),
    ("by", "by", "by", 0),
    ("calcmode", "calcMode", "calcMode", 0),
    ("cap-height", "capHeight", "cap-height", 3),
    ("capheight", "capHeight", "cap-height", 3),
    ("class", "className", "class", 4),
    ("classname", "className", "class", 4),
    ("clip", "clip", "clip", 0),
    ("clip-path", "clipPath", "clip-path", 0),
    ("clip-rule", "clipRule", "clip-rule", 0),
    ("clippath", "clipPath", "clip-path", 0),
    ("clippathunits", "clipPathUnits", "clipPathUnits", 0),
    ("cliprule", "clipRule", "clip-rule", 0),
    ("color", "color", "color", 0),
    (
        "color-interpolation",
        "colorInterpolation",
        "color-interpolation",
        0,
    ),
    (
        "color-interpolation-filters",
        "colorInterpolationFilters",
        "color-interpolation-filters",
        0,
    ),
    ("color-profile", "colorProfile", "color-profile", 0),
    ("color-rendering", "colorRendering", "color-rendering", 0),
    (
        "colorinterpolation",
        "colorInterpolation",
        "color-interpolation",
        0,
    ),
    (
        "colorinterpolationfilters",
        "colorInterpolationFilters",
        "color-interpolation-filters",
        0,
    ),
    ("colorprofile", "colorProfile", "color-profile", 0),
    ("colorrendering", "colorRendering", "color-rendering", 0),
    ("content", "content", "content", 0),
    (
        "contentscripttype",
        "contentScriptType",
        "contentScriptType",
        0,
    ),
    (
        "contentstyletype",
        "contentStyleType",
        "contentStyleType",
        0,
    ),
    ("crossorigin", "crossOrigin", "crossorigin", 0),
    ("cursor", "cursor", "cursor", 0),
    ("cx", "cx", "cx", 0),
    ("cy", "cy", "cy", 0),
    ("d", "d", "d", 0),
    ("datatype", "dataType", "datatype", 0),
    ("defaultaction", "defaultAction", "defaultAction", 0),
    ("descent", "descent", "descent", 3),
    ("diffuseconstant", "diffuseConstant", "diffuseConstant", 3),
    ("direction", "direction", "direction", 0),
    ("display", "display", "display", 0),
    ("divisor", "divisor", "divisor", 3),
    (
        "dominant-baseline",
        "dominantBaseline",
        "dominant-baseline",
        0,
    ),
    (
        "dominantbaseline",
        "dominantBaseline",
        "dominant-baseline",
        0,
    ),
    ("download", "download", "download", 1),
    ("dur", "dur", "dur", 0),
    ("dx", "dx", "dx", 0),
    ("dy", "dy", "dy", 0),
    ("edgemode", "edgeMode", "edgeMode", 0),
    ("editable", "editable", "editable", 0),
    ("elevation", "elevation", "elevation", 3),
    (
        "enable-background",
        "enableBackground",
        "enable-background",
        0,
    ),
    (
        "enablebackground",
        "enableBackground",
        "enable-background",
        0,
    ),
    ("end", "end", "end", 0),
    ("event", "event", "event", 0),
    ("exponent", "exponent", "exponent", 3),
    (
        "externalresourcesrequired",
        "externalResourcesRequired",
        "externalResourcesRequired",
        0,
    ),
    ("fill", "fill", "fill", 0),
    ("fill-opacity", "fillOpacity", "fill-opacity", 3),
    ("fill-rule", "fillRule", "fill-rule", 0),
    ("fillopacity", "fillOpacity", "fill-opacity", 3),
    ("fillrule", "fillRule", "fill-rule", 0),
    ("filter", "filter", "filter", 0),
    ("filterres", "filterRes", "filterRes", 0),
    ("filterunits", "filterUnits", "filterUnits", 0),
    ("flood-color", "floodColor", "flood-color", 0),
    ("flood-opacity", "floodOpacity", "flood-opacity", 0),
    ("floodcolor", "floodColor", "flood-color", 0),
    ("floodopacity", "floodOpacity", "flood-opacity", 0),
    ("focusable", "focusable", "focusable", 0),
    ("focushighlight", "focusHighlight", "focusHighlight", 0),
    ("font-family", "fontFamily", "font-family", 0),
    ("font-size", "fontSize", "font-size", 0),
    ("font-size-adjust", "fontSizeAdjust", "font-size-adjust", 0),
    ("font-stretch", "fontStretch", "font-stretch", 0),
    ("font-style", "fontStyle", "font-style", 0),
    ("font-variant", "fontVariant", "font-variant", 0),
    ("font-weight", "fontWeight", "font-weight", 0),
    ("fontfamily", "fontFamily", "font-family", 0),
    ("fontsize", "fontSize", "font-size", 0),
    ("fontsizeadjust", "fontSizeAdjust", "font-size-adjust", 0),
    ("fontstretch", "fontStretch", "font-stretch", 0),
    ("fontstyle", "fontStyle", "font-style", 0),
    ("fontvariant", "fontVariant", "font-variant", 0),
    ("fontweight", "fontWeight", "font-weight", 0),
    ("format", "format", "format", 0),
    ("fr", "fr", "fr", 0),
    ("from", "from", "from", 0),
    ("fx", "fx", "fx", 0),
    ("fy", "fy", "fy", 0),
    ("g1", "g1", "g1", 5),
    ("g2", "g2", "g2", 5),
    ("glyph-name", "glyphName", "glyph-name", 5),
    (
        "glyph-orientation-horizontal",
        "glyphOrientationHorizontal",
        "glyph-orientation-horizontal",
        0,
    ),
    (
        "glyph-orientation-vertical",
        "glyphOrientationVertical",
        "glyph-orientation-vertical",
        0,
    ),
    ("glyphname", "glyphName", "glyph-name", 5),
    (
        "glyphorientationhorizontal",
        "glyphOrientationHorizontal",
        "glyph-orientation-horizontal",
        0,
    ),
    (
        "glyphorientationvertical",
        "glyphOrientationVertical",
        "glyph-orientation-vertical",
        0,
    ),
    ("glyphref", "glyphRef", "glyphRef", 0),
    (
        "gradienttransform",
        "gradientTransform",
        "gradientTransform",
        0,
    ),
    ("gradientunits", "gradientUnits", "gradientUnits", 0),
    ("handler", "handler", "handler", 0),
    ("hanging", "hanging", "hanging", 3),
    (
        "hatchcontentunits",
        "hatchContentUnits",
        "hatchContentUnits",
        0,
    ),
    ("hatchunits", "hatchUnits", "hatchUnits", 0),
    ("height", "height", "height", 0),
    ("horiz-adv-x", "horizAdvX", "horiz-adv-x", 3),
    ("horiz-origin-x", "horizOriginX", "horiz-origin-x", 3),
    ("horiz-origin-y", "horizOriginY", "horiz-origin-y", 3),
    ("horizadvx", "horizAdvX", "horiz-adv-x", 3),
    ("horizoriginx", "horizOriginX", "horiz-origin-x", 3),
    ("horizoriginy", "horizOriginY", "horiz-origin-y", 3),
    ("href", "href", "href", 0),
    ("hreflang", "hrefLang", "hreflang", 0),
    ("id", "id", "id", 0),
    ("ideographic", "ideographic", "ideographic", 3),
    ("image-rendering", "imageRendering", "image-rendering", 0),
    ("imagerendering", "imageRendering", "image-rendering", 0),
    ("in", "in", "in", 0),
    ("in2", "in2", "in2", 0),
    (
        "initialvisibility",
        "initialVisibility",
        "initialVisibility",
        0,
    ),
    ("intercept", "intercept", "intercept", 3),
    ("k", "k", "k", 3),
    ("k1", "k1", "k1", 3),
    ("k2", "k2", "k2", 3),
    ("k3", "k3", "k3", 3),
    ("k4", "k4", "k4", 3),
    ("kernelmatrix", "kernelMatrix", "kernelMatrix", 6),
    (
        "kernelunitlength",
        "kernelUnitLength",
        "kernelUnitLength",
        0,
    ),
    ("kerning", "kerning", "kerning", 0),
    ("keypoints", "keyPoints", "keyPoints", 0),
    ("keysplines", "keySplines", "keySplines", 0),
    ("keytimes", "keyTimes", "keyTimes", 0),
    ("lang", "lang", "lang", 0),
    ("lengthadjust", "lengthAdjust", "lengthAdjust", 0),
    ("letter-spacing", "letterSpacing", "letter-spacing", 0),
    ("letterspacing", "letterSpacing", "letter-spacing", 0),
    ("lighting-color", "lightingColor", "lighting-color", 0),
    ("lightingcolor", "lightingColor", "lighting-color", 0),
    (
        "limitingconeangle",
        "limitingConeAngle",
        "limitingConeAngle",
        3,
    ),
    ("local", "local", "local", 0),
    ("marker-end", "markerEnd", "marker-end", 0),
    ("marker-mid", "markerMid", "marker-mid", 0),
    ("marker-start", "markerStart", "marker-start", 0),
    ("markerend", "markerEnd", "marker-end", 0),
    ("markerheight", "markerHeight", "markerHeight", 0),
    ("markermid", "markerMid", "marker-mid", 0),
    ("markerstart", "markerStart", "marker-start", 0),
    ("markerunits", "markerUnits", "markerUnits", 0),
    ("markerwidth", "markerWidth", "markerWidth", 0),
    ("mask", "mask", "mask", 0),
    ("mask-type", "maskType", "mask-type", 0),
    (
        "maskcontentunits",
        "maskContentUnits",
        "maskContentUnits",
        0,
    ),
    ("masktype", "maskType", "mask-type", 0),
    ("maskunits", "maskUnits", "maskUnits", 0),
    ("mathematical", "mathematical", "mathematical", 0),
    ("max", "max", "max", 0),
    ("media", "media", "media", 0),
    (
        "mediacharacterencoding",
        "mediaCharacterEncoding",
        "mediaCharacterEncoding",
        0,
    ),
    (
        "mediacontentencodings",
        "mediaContentEncodings",
        "mediaContentEncodings",
        0,
    ),
    ("mediasize", "mediaSize", "mediaSize", 3),
    ("mediatime", "mediaTime", "mediaTime", 0),
    ("method", "method", "method", 0),
    ("min", "min", "min", 0),
    ("mode", "mode", "mode", 0),
    ("name", "name", "name", 0),
    ("nav-down", "navDown", "nav-down", 0),
    ("nav-down-left", "navDownLeft", "nav-down-left", 0),
    ("nav-down-right", "navDownRight", "nav-down-right", 0),
    ("nav-left", "navLeft", "nav-left", 0),
    ("nav-next", "navNext", "nav-next", 0),
    ("nav-prev", "navPrev", "nav-prev", 0),
    ("nav-right", "navRight", "nav-right", 0),
    ("nav-up", "navUp", "nav-up", 0),
    ("nav-up-left", "navUpLeft", "nav-up-left", 0),
    ("nav-up-right", "navUpRight", "nav-up-right", 0),
    ("navdown", "navDown", "nav-down", 0),
    ("navdownleft", "navDownLeft", "nav-down-left", 0),
    ("navdownright", "navDownRight", "nav-down-right", 0),
    ("navleft", "navLeft", "nav-left", 0),
    ("navnext", "navNext", "nav-next", 0),
    ("navprev", "navPrev", "nav-prev", 0),
    ("navright", "navRight", "nav-right", 0),
    ("navup", "navUp", "nav-up", 0),
    ("navupleft", "navUpLeft", "nav-up-left", 0),
    ("navupright", "navUpRight", "nav-up-right", 0),
    ("numoctaves", "numOctaves", "numOctaves", 0),
    ("observer", "observer", "observer", 0),
    ("offset", "offset", "offset", 0),
    ("onabort", "onAbort", "onabort", 0),
    ("onactivate", "onActivate", "onactivate", 0),
    ("onafterprint", "onAfterPrint", "onafterprint", 0),
    ("onbeforeprint", "onBeforePrint", "onbeforeprint", 0),
    ("onbegin", "onBegin", "onbegin", 0),
    ("oncancel", "onCancel", "oncancel", 0),
    ("oncanplay", "onCanPlay", "oncanplay", 0),
    (
        "oncanplaythrough",
        "onCanPlayThrough",
        "oncanplaythrough",
        0,
    ),
    ("onchange", "onChange", "onchange", 0),
    ("onclick", "onClick", "onclick", 0),
    ("onclose", "onClose", "onclose", 0),
    ("oncopy", "onCopy", "oncopy", 0),
    ("oncuechange", "onCueChange", "oncuechange", 0),
    ("oncut", "onCut", "oncut", 0),
    ("ondblclick", "onDblClick", "ondblclick", 0),
    ("ondrag", "onDrag", "ondrag", 0),
    ("ondragend", "onDragEnd", "ondragend", 0),
    ("ondragenter", "onDragEnter", "ondragenter", 0),
    ("ondragexit", "onDragExit", "ondragexit", 0),
    ("ondragleave", "onDragLeave", "ondragleave", 0),
    ("ondragover", "onDragOver", "ondragover", 0),
    ("ondragstart", "onDragStart", "ondragstart", 0),
    ("ondrop", "onDrop", "ondrop", 0),
    (
        "ondurationchange",
        "onDurationChange",
        "ondurationchange",
        0,
    ),
    ("onemptied", "onEmptied", "onemptied", 0),
    ("onend", "onEnd", "onend", 0),
    ("onended", "onEnded", "onended", 0),
    ("onerror", "onError", "onerror", 0),
    ("onfocus", "onFocus", "onfocus", 0),
    ("onfocusin", "onFocusIn", "onfocusin", 0),
    ("onfocusout", "onFocusOut", "onfocusout", 0),
    ("onhashchange", "onHashChange", "onhashchange", 0),
    ("oninput", "onInput", "oninput", 0),
    ("oninvalid", "onInvalid", "oninvalid", 0),
    ("onkeydown", "onKeyDown", "onkeydown", 0),
    ("onkeypress", "onKeyPress", "onkeypress", 0),
    ("onkeyup", "onKeyUp", "onkeyup", 0),
    ("onload", "onLoad", "onload", 0),
    ("onloadeddata", "onLoadedData", "onloadeddata", 0),
    (
        "onloadedmetadata",
        "onLoadedMetadata",
        "onloadedmetadata",
        0,
    ),
    ("onloadstart", "onLoadStart", "onloadstart", 0),
    ("onmessage", "onMessage", "onmessage", 0),
    ("onmousedown", "onMouseDown", "onmousedown", 0),
    ("onmouseenter", "onMouseEnter", "onmouseenter", 0),
    ("onmouseleave", "onMouseLeave", "onmouseleave", 0),
    ("onmousemove", "onMouseMove", "onmousemove", 0),
    ("onmouseout", "onMouseOut", "onmouseout", 0),
    ("onmouseover", "onMouseOver", "onmouseover", 0),
    ("onmouseup", "onMouseUp", "onmouseup", 0),
    ("onmousewheel", "onMouseWheel", "onmousewheel", 0),
    ("onoffline", "onOffline", "onoffline", 0),
    ("ononline", "onOnline", "ononline", 0),
    ("onpagehide", "onPageHide", "onpagehide", 0),
    ("onpageshow", "onPageShow", "onpageshow", 0),
    ("onpaste", "onPaste", "onpaste", 0),
    ("onpause", "onPause", "onpause", 0),
    ("onplay", "onPlay", "onplay", 0),
    ("onplaying", "onPlaying", "onplaying", 0),
    ("onpopstate", "onPopState", "onpopstate", 0),
    ("onprogress", "onProgress", "onprogress", 0),
    ("onratechange", "onRateChange", "onratechange", 0),
    ("onrepeat", "onRepeat", "onrepeat", 0),
    ("onreset", "onReset", "onreset", 0),
    ("onresize", "onResize", "onresize", 0),
    ("onscroll", "onScroll", "onscroll", 0),
    ("onseeked", "onSeeked", "onseeked", 0),
    ("onseeking", "onSeeking", "onseeking", 0),
    ("onselect", "onSelect", "onselect", 0),
    ("onshow", "onShow", "onshow", 0),
    ("onstalled", "onStalled", "onstalled", 0),
    ("onstorage", "onStorage", "onstorage", 0),
    ("onsubmit", "onSubmit", "onsubmit", 0),
    ("onsuspend", "onSuspend", "onsuspend", 0),
    ("ontimeupdate", "onTimeUpdate", "ontimeupdate", 0),
    ("ontoggle", "onToggle", "ontoggle", 0),
    ("onunload", "onUnload", "onunload", 0),
    ("onvolumechange", "onVolumeChange", "onvolumechange", 0),
    ("onwaiting", "onWaiting", "onwaiting", 0),
    ("onzoom", "onZoom", "onzoom", 0),
    ("opacity", "opacity", "opacity", 0),
    ("operator", "operator", "operator", 0),
    ("order", "order", "order", 0),
    ("orient", "orient", "orient", 0),
    ("orientation", "orientation", "orientation", 0),
    ("origin", "origin", "origin", 0),
    ("overflow", "overflow", "overflow", 0),
    ("overlay", "overlay", "overlay", 0),
    (
        "overline-position",
        "overlinePosition",
        "overline-position",
        3,
    ),
    (
        "overline-thickness",
        "overlineThickness",
        "overline-thickness",
        3,
    ),
    (
        "overlineposition",
        "overlinePosition",
        "overline-position",
        3,
    ),
    (
        "overlinethickness",
        "overlineThickness",
        "overline-thickness",
        3,
    ),
    ("paint-order", "paintOrder", "paint-order", 0),
    ("paintorder", "paintOrder", "paint-order", 0),
    ("panose-1", "panose1", "panose-1", 0),
    ("panose1", "panose1", "panose-1", 0),
    ("path", "path", "path", 0),
    ("pathlength", "pathLength", "pathLength", 3),
    (
        "patterncontentunits",
        "patternContentUnits",
        "patternContentUnits",
        0,
    ),
    (
        "patterntransform",
        "patternTransform",
        "patternTransform",
        0,
    ),
    ("patternunits", "patternUnits", "patternUnits", 0),
    ("phase", "phase", "phase", 0),
    ("ping", "ping", "ping", 4),
    ("pitch", "pitch", "pitch", 0),
    ("playbackorder", "playbackOrder", "playbackorder", 0),
    ("pointer-events", "pointerEvents", "pointer-events", 0),
    ("pointerevents", "pointerEvents", "pointer-events", 0),
    ("points", "points", "points", 0),
    ("pointsatx", "pointsAtX", "pointsAtX", 3),
    ("pointsaty", "pointsAtY", "pointsAtY", 3),
    ("pointsatz", "pointsAtZ", "pointsAtZ", 3),
    ("preservealpha", "preserveAlpha", "preserveAlpha", 0),
    (
        "preserveaspectratio",
        "preserveAspectRatio",
        "preserveAspectRatio",
        0,
    ),
    ("primitiveunits", "primitiveUnits", "primitiveUnits", 0),
    ("propagate", "propagate", "propagate", 0),
    ("property", "property", "property", 6),
    ("r", "r", "r", 0),
    ("radius", "radius", "radius", 0),
    ("referrerpolicy", "referrerPolicy", "referrerpolicy", 0),
    ("refx", "refX", "refX", 0),
    ("refy", "refY", "refY", 0),
    ("rel", "rel", "rel", 6),
    ("rendering-intent", "renderingIntent", "rendering-intent", 0),
    ("renderingintent", "renderingIntent", "rendering-intent", 0),
    ("repeatcount", "repeatCount", "repeatCount", 0),
    ("repeatdur", "repeatDur", "repeatDur", 0),
    (
        "requiredextensions",
        "requiredExtensions",
        "requiredExtensions",
        6,
    ),
    (
        "requiredfeatures",
        "requiredFeatures",
        "requiredFeatures",
        6,
    ),
    ("requiredfonts", "requiredFonts", "requiredFonts", 6),
    ("requiredformats", "requiredFormats", "requiredFormats", 6),
    ("resource", "resource", "resource", 0),
    ("restart", "restart", "restart", 0),
    ("result", "result", "result", 0),
    ("rev", "rev", "rev", 6),
    ("role", "role", "role", 0),
    ("rotate", "rotate", "rotate", 0),
    ("rx", "rx", "rx", 0),
    ("ry", "ry", "ry", 0),
    ("scale", "scale", "scale", 0),
    ("seed", "seed", "seed", 0),
    ("shape-rendering", "shapeRendering", "shape-rendering", 0),
    ("shaperendering", "shapeRendering", "shape-rendering", 0),
    ("side", "side", "side", 0),
    ("slope", "slope", "slope", 0),
    ("snapshottime", "snapshotTime", "snapshotTime", 0),
    ("spacing", "spacing", "spacing", 0),
    (
        "specularconstant",
        "specularConstant",
        "specularConstant",
        3,
    ),
    (
        "specularexponent",
        "specularExponent",
        "specularExponent",
        3,
    ),
    ("spreadmethod", "spreadMethod", "spreadMethod", 0),
    ("startoffset", "startOffset", "startOffset", 0),
    ("stddeviation", "stdDeviation", "stdDeviation", 0),
    ("stemh", "stemh", "stemh", 0),
    ("stemv", "stemv", "stemv", 0),
    ("stitchtiles", "stitchTiles", "stitchTiles", 0),
    ("stop-color", "stopColor", "stop-color", 0),
    ("stop-opacity", "stopOpacity", "stop-opacity", 0),
    ("stopcolor", "stopColor", "stop-color", 0),
    ("stopopacity", "stopOpacity", "stop-opacity", 0),
    (
        "strikethrough-position",
        "strikethroughPosition",
        "strikethrough-position",
        3,
    ),
    (
        "strikethrough-thickness",
        "strikethroughThickness",
        "strikethrough-thickness",
        3,
    ),
    (
        "strikethroughposition",
        "strikethroughPosition",
        "strikethrough-position",
        3,
    ),
    (
        "strikethroughthickness",
        "strikethroughThickness",
        "strikethrough-thickness",
        3,
    ),
    ("string", "string", "string", 0),
    ("stroke", "stroke", "stroke", 0),
    ("stroke-dasharray", "strokeDashArray", "stroke-dasharray", 6),
    (
        "stroke-dashoffset",
        "strokeDashOffset",
        "stroke-dashoffset",
        0,
    ),
    ("stroke-linecap", "strokeLineCap", "stroke-linecap", 0),
    ("stroke-linejoin", "strokeLineJoin", "stroke-linejoin", 0),
    (
        "stroke-miterlimit",
        "strokeMiterLimit",
        "stroke-miterlimit",
        3,
    ),
    ("stroke-opacity", "strokeOpacity", "stroke-opacity", 3),
    ("stroke-width", "strokeWidth", "stroke-width", 0),
    ("strokedasharray", "strokeDashArray", "stroke-dasharray", 6),
    (
        "strokedashoffset",
        "strokeDashOffset",
        "stroke-dashoffset",
        0,
    ),
    ("strokelinecap", "strokeLineCap", "stroke-linecap", 0),
    ("strokelinejoin", "strokeLineJoin", "stroke-linejoin", 0),
    (
        "strokemiterlimit",
        "strokeMiterLimit",
        "stroke-miterlimit",
        3,
    ),
    ("strokeopacity", "strokeOpacity", "stroke-opacity", 3),
    ("strokewidth", "strokeWidth", "stroke-width", 0),
    ("style", "style", "style", 0),
    ("surfacescale", "surfaceScale", "surfaceScale", 3),
    ("syncbehavior", "syncBehavior", "syncBehavior", 0),
    (
        "syncbehaviordefault",
        "syncBehaviorDefault",
        "syncBehaviorDefault",
        0,
    ),
    ("syncmaster", "syncMaster", "syncMaster", 0),
    ("synctolerance", "syncTolerance", "syncTolerance", 0),
    (
        "synctolerancedefault",
        "syncToleranceDefault",
        "syncToleranceDefault",
        0,
    ),
    ("systemlanguage", "systemLanguage", "systemLanguage", 6),
    ("tabindex", "tabIndex", "tabindex", 3),
    ("tablevalues", "tableValues", "tableValues", 0),
    ("target", "target", "target", 0),
    ("targetx", "targetX", "targetX", 3),
    ("targety", "targetY", "targetY", 3),
    ("text-anchor", "textAnchor", "text-anchor", 0),
    ("text-decoration", "textDecoration", "text-decoration", 0),
    ("text-rendering", "textRendering", "text-rendering", 0),
    ("textanchor", "textAnchor", "text-anchor", 0),
    ("textdecoration", "textDecoration", "text-decoration", 0),
    ("textlength", "textLength", "textLength", 0),
    ("textrendering", "textRendering", "text-rendering", 0),
    ("timelinebegin", "timelineBegin", "timelinebegin", 0),
    ("title", "title", "title", 0),
    ("to", "to", "to", 0),
    ("transform", "transform", "transform", 0),
    ("transform-origin", "transformOrigin", "transform-origin", 0),
    (
        "transformbehavior",
        "transformBehavior",
        "transformBehavior",
        0,
    ),
    ("transformorigin", "transformOrigin", "transform-origin", 0),
    ("type", "type", "type", 0),
    ("typeof", "typeOf", "typeof", 6),
    ("u1", "u1", "u1", 0),
    ("u2", "u2", "u2", 0),
    (
        "underline-position",
        "underlinePosition",
        "underline-position",
        3,
    ),
    (
        "underline-thickness",
        "underlineThickness",
        "underline-thickness",
        3,
    ),
    (
        "underlineposition",
        "underlinePosition",
        "underline-position",
        3,
    ),
    (
        "underlinethickness",
        "underlineThickness",
        "underline-thickness",
        3,
    ),
    ("unicode", "unicode", "unicode", 0),
    ("unicode-bidi", "unicodeBidi", "unicode-bidi", 0),
    ("unicode-range", "unicodeRange", "unicode-range", 0),
    ("unicodebidi", "unicodeBidi", "unicode-bidi", 0),
    ("unicoderange", "unicodeRange", "unicode-range", 0),
    ("units-per-em", "unitsPerEm", "units-per-em", 3),
    ("unitsperem", "unitsPerEm", "units-per-em", 3),
    ("v-alphabetic", "vAlphabetic", "v-alphabetic", 3),
    ("v-hanging", "vHanging", "v-hanging", 3),
    ("v-ideographic", "vIdeographic", "v-ideographic", 3),
    ("v-mathematical", "vMathematical", "v-mathematical", 3),
    ("valphabetic", "vAlphabetic", "v-alphabetic", 3),
    ("values", "values", "values", 0),
    ("vector-effect", "vectorEffect", "vector-effect", 0),
    ("vectoreffect", "vectorEffect", "vector-effect", 0),
    ("version", "version", "version", 0),
    ("vert-adv-y", "vertAdvY", "vert-adv-y", 3),
    ("vert-origin-x", "vertOriginX", "vert-origin-x", 3),
    ("vert-origin-y", "vertOriginY", "vert-origin-y", 3),
    ("vertadvy", "vertAdvY", "vert-adv-y", 3),
    ("vertoriginx", "vertOriginX", "vert-origin-x", 3),
    ("vertoriginy", "vertOriginY", "vert-origin-y", 3),
    ("vhanging", "vHanging", "v-hanging", 3),
    ("videographic", "vIdeographic", "v-ideographic", 3),
    ("viewbox", "viewBox", "viewBox", 0),
    ("viewtarget", "viewTarget", "viewTarget", 0),
    ("visibility", "visibility", "visibility", 0),
    ("vmathematical", "vMathematical", "v-mathematical", 3),
    ("width", "width", "width", 0),
    ("widths", "widths", "widths", 0),
    ("word-spacing", "wordSpacing", "word-spacing", 0),
    ("wordspacing", "wordSpacing", "word-spacing", 0),
    ("writing-mode", "writingMode", "writing-mode", 0),
    ("writingmode", "writingMode", "writing-mode", 0),
    ("x", "x", "x", 0),
    ("x-height", "xHeight", "x-height", 3),
    ("x1", "x1", "x1", 0),
    ("x2", "x2", "x2", 0),
    (
        "xchannelselector",
        "xChannelSelector",
        "xChannelSelector",
        0,
    ),
    ("xheight", "xHeight", "x-height", 3),
    ("xlink:actuate", "xLinkActuate", "xlink:actuate", 0),
    ("xlink:arcrole", "xLinkArcRole", "xlink:arcrole", 0),
    ("xlink:href", "xLinkHref", "xlink:href", 0),
    ("xlink:role", "xLinkRole", "xlink:role", 0),
    ("xlink:show", "xLinkShow", "xlink:show", 0),
    ("xlink:title", "xLinkTitle", "xlink:title", 0),
    ("xlink:type", "xLinkType", "xlink:type", 0),
    ("xlinkactuate", "xLinkActuate", "xlink:actuate", 0),
    ("xlinkarcrole", "xLinkArcRole", "xlink:arcrole", 0),
    ("xlinkhref", "xLinkHref", "xlink:href", 0),
    ("xlinkrole", "xLinkRole", "xlink:role", 0),
    ("xlinkshow", "xLinkShow", "xlink:show", 0),
    ("xlinktitle", "xLinkTitle", "xlink:title", 0),
    ("xlinktype", "xLinkType", "xlink:type", 0),
    ("xml:base", "xmlBase", "xml:base", 0),
    ("xml:lang", "xmlLang", "xml:lang", 0),
    ("xml:space", "xmlSpace", "xml:space", 0),
    ("xmlbase", "xmlBase", "xml:base", 0),
    ("xmllang", "xmlLang", "xml:lang", 0),
    ("xmlns", "xmlns", "xmlns", 0),
    ("xmlns:xlink", "xmlnsXLink", "xmlns:xlink", 0),
    ("xmlnsxlink", "xmlnsXLink", "xmlns:xlink", 0),
    ("xmlspace", "xmlSpace", "xml:space", 0),
    ("y", "y", "y", 0),
    ("y1", "y1", "y1", 0),
    ("y2", "y2", "y2", 0),
    (
        "ychannelselector",
        "yChannelSelector",
        "yChannelSelector",
        0,
    ),
    ("z", "z", "z", 0),
    ("zoomandpan", "zoomAndPan", "zoomAndPan", 0),
];
