// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn container_extensions_test_1() {
    let original = r##"> Is this **bold**?
> Is this **bold**?
> ::: spoiler Is this expandable?
> Is this inside?
> :::
"##;
    let expected = r##"<blockquote>
<p>Is this <strong>bold</strong>?
Is this <strong>bold</strong>?</p>
<blockquote>
<p>Is this inside?</p>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_2() {
    let original = r##"::: spoiler Is this expandable?
Is this collapsable?
> Is this **bold**?
> Is this **bold**?
:::
**is this seperate and bold**
"##;
    let expected = r##"<blockquote>
<p>Is this collapsable?</p>
<blockquote>
<p>Is this <strong>bold</strong>?
Is this <strong>bold</strong>?</p>
</blockquote>
</blockquote>
<p><strong>is this seperate and bold</strong></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_3() {
    let original = r##"::: spoiler Is this expandable?
Is this collapsable?
> Is this **bold**?
> Is this **bold**?
> ::: spoiler Is this expandable?
> Is this inside?
> :::
:::
"##;
    let expected = r##"<blockquote>
<p>Is this collapsable?</p>
<blockquote>
<p>Is this <strong>bold</strong>?
Is this <strong>bold</strong>?</p>
<blockquote>
<p>Is this inside?</p>
</blockquote>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_4() {
    let original = r##"::: spoiler Is this expandable?
Is this collapsable?
> Is this **bold**?
> Is this **bold**?
> ::: spoiler Is this expandable?
> Is this collapsable?
> > Is this **bold**?
> > Is this **bold**?
> :::
:::
**is this seperate and bold**
"##;
    let expected = r##"<blockquote>
<p>Is this collapsable?</p>
<blockquote>
<p>Is this <strong>bold</strong>?
Is this <strong>bold</strong>?</p>
<blockquote>
<p>Is this collapsable?</p>
<blockquote>
<p>Is this <strong>bold</strong>?
Is this <strong>bold</strong>?</p>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
<p><strong>is this seperate and bold</strong></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_5() {
    let original = r##"::: spoiler Is this expandable?
Is this collapsable?
:::
**is this seperate and bold**
"##;
    let expected = r##"<blockquote>
<p>Is this collapsable?</p>
</blockquote>
<p><strong>is this seperate and bold</strong></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_6() {
    let original = r##"::: spoiler Is this expandable?
Is this collapsable?

Is this **bold**?
:::
"##;
    let expected = r##"<blockquote>
<p>Is this collapsable?</p>
<p>Is this <strong>bold</strong>?</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_7() {
    let original = r##":::spoiler Is this expandable?
Is this collapsable?

Is this **bold**?
:::
"##;
    let expected = r##"<blockquote>
<p>Is this collapsable?</p>
<p>Is this <strong>bold</strong>?</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_8() {
    let original = r##"::: example
Is this collapsable?

Is this **bold**?
:::
"##;
    let expected = r##"<blockquote>
<p>Is this collapsable?</p>
<p>Is this <strong>bold</strong>?</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_9() {
    let original = r##":::: example
Is this collapsable?

Is this **bold**?
::::
"##;
    let expected = r##"<blockquote>
<p>Is this collapsable?</p>
<p>Is this <strong>bold</strong>?</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_10() {
    let original = r##":::::spoiler Is this expandable?
Is this collapsable?

Is this **bold**?
:::::
"##;
    let expected = r##"<blockquote>
<p>Is this collapsable?</p>
<p>Is this <strong>bold</strong>?</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_11() {
    let original = r##":::

content

:::
"##;
    let expected = r##"<p>:::</p>
<p>content</p>
<p>:::</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_12() {
    let original = r##"::: block

content

::: end
"##;
    let expected = r##"<blockquote>
<p>content</p>
<blockquote>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_13() {
    let original = r##" ::: block
:::

::: block
 :::
"##;
    let expected = r##"<blockquote>
</blockquote>
<blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_14() {
    let original = r##"::: a
::: b

:::
:::
"##;
    let expected = r##"<blockquote>
<blockquote>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_15() {
    let original = r##":::: a
::: b

:::
::::
"##;
    let expected = r##"<blockquote>
<blockquote>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_16() {
    let original = r##"::: a
:::: b

::::
:::
"##;
    let expected = r##"<blockquote>
<blockquote>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_17() {
    let original = r##":::
Hi
:::
"##;
    let expected = r##"<p>:::
Hi
:::</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_18() {
    let original = r##"::::: foo
Hi
:::
::::::
"##;
    let expected = r##"<blockquote>
<p>Hi
:::</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_19() {
    let original = r##"> ::: foo
> Hi
"##;
    let expected = r##"<blockquote>
<blockquote>
<p>Hi</p>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_20() {
    let original = r##"::: c_d
Hi
:::
"##;
    let expected = r##"<blockquote>
<p>Hi</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_21() {
    let original = r##"::: container
> shouldn't close, right?
> :::
> x
:::
"##;
    let expected = r##"<blockquote>
<blockquote>
<p>shouldn't close, right?
:::
x</p>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_22() {
    let original = r##"::: container
> shouldn't close, right?
> :::
> x

:::
"##;
    let expected = r##"<blockquote>
<blockquote>
<p>shouldn't close, right?
:::
x</p>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_23() {
    let original = r##"::: a
:::: b
::::: c
::::
x
"##;
    let expected = r##"<blockquote>
<blockquote>
<blockquote>
</blockquote>
</blockquote>
<p>x</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_24() {
    let original = r##"::: a
content :::
"##;
    let expected = r##"<blockquote>
<p>content :::</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}

#[test]
fn container_extensions_test_25() {
    let original = r##":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: a
content :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
"##;
    let expected = r##"<blockquote>
<p>content :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, false, true);
}
