// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn definition_list_test_1() {
    let original = r##"Apple
:   Red.
"##;
    let expected = r##"<dl>
<dt>Apple</dt>
<dd>Red.</dd>
</dl>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, true, false);
}

#[test]
fn definition_list_test_2() {
    let original = r##"Apple

:   Red.
"##;
    let expected = r##"<dl>
<dt>Apple</dt>
<dd>
<p>Red.</p>
</dd>
</dl>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, true, false);
}

#[test]
fn definition_list_test_3() {
    let original = r##"Apple
:   Red.
:   Green.
"##;
    let expected = r##"<dl>
<dt>Apple</dt>
<dd>Red.</dd>
<dd>Green.</dd>
</dl>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, true, false);
}

#[test]
fn definition_list_test_4() {
    let original = r##"Term 1
Term 2
:   Shared definition.
"##;
    let expected = r##"<dl>
<dt>Term 1
Term 2</dt>
<dd>Shared definition.</dd>
</dl>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, true, false);
}

#[test]
fn definition_list_test_5() {
    let original = r##"*Apple*
:   A **fruit**.
"##;
    let expected = r##"<dl>
<dt><em>Apple</em></dt>
<dd>A <strong>fruit</strong>.</dd>
</dl>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, true, false);
}

#[test]
fn definition_list_test_6() {
    let original = r##"Apple
:   Red.

Orange
:   Orange.
"##;
    let expected = r##"<dl>
<dt>Apple</dt>
<dd>Red.</dd>
<dt>Orange</dt>
<dd>Orange.</dd>
</dl>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, true, false);
}
