// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn definition_lists_test_1() {
    let original = r##"apple
:   red fruit

orange
:   orange fruit
"##;
    let expected = r##"<p><p>apple</p><p><p>red fruit</p></p><p>orange</p><p><p>orange fruit</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_2() {
    let original = r##"apple

:   red fruit

orange

:   orange fruit
"##;
    let expected = r##"<p><p>apple</p><p><p>red fruit</p></p><p>orange</p><p><p>orange fruit</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_3() {
    let original = r##"apple

:   red fruit
"##;
    let expected = r##"<p><p>apple</p><p><p>red fruit</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_4() {
    let original = r##"apple
  : red fruit

orange
  : orange fruit
"##;
    let expected = r##"<p><p>apple</p><p><p>red fruit</p></p><p>orange</p><p><p>orange fruit</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_5() {
    let original = r##"apple

 : red fruit

orange

 : orange fruit
"##;
    let expected = r##"<p><p>apple</p><p><p>red fruit</p></p><p>orange</p><p><p>orange fruit</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_6() {
    let original = r##"*apple*

:   red fruit

    contains seeds,
    crisp, pleasant to taste

*orange*

:   orange fruit

        { orange code block }

    > orange block quote
"##;
    let expected = r##"<p><p><em>apple</em></p><p><p>red fruit</p><p>contains seeds,
crisp, pleasant to taste</p></p><p><em>orange</em></p><p><p>orange fruit</p><pre><code>{ orange code block }
</code></pre><blockquote>
<p>orange block quote</p>
</blockquote></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_7() {
    let original = r##"term

:   1. Para one

       Para two
"##;
    let expected = r##"<p><p>term</p><p><ol>
<li>
<p>Para one</p>
<p>Para two</p>
</li>
</ol></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_8() {
    let original = r##"apple
:   red fruit
:   computer company

orange
:   orange fruit
:   telecom company
"##;
    let expected = r##"<p><p>apple</p><p><p>red fruit</p></p><p><p>computer company</p></p><p>orange</p><p><p>orange fruit</p></p><p><p>telecom company</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_9() {
    let original = r##"apple

:   red fruit

:   computer company

orange

:   orange fruit
:   telecom company
"##;
    let expected = r##"<p><p>apple</p><p><p>red fruit</p></p><p><p>computer company</p></p><p>orange</p><p><p>orange fruit</p></p><p><p>telecom company</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_10() {
    let original = r##"apple

:   red fruit

:   computer
company

orange

:   orange
fruit
:   telecom company
"##;
    let expected = r##"<p><p>apple</p><p><p>red fruit</p></p><p><p>computer
company</p></p><p>orange</p><p><p>orange
fruit</p></p><p><p>telecom company</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_11() {
    let original = r##"apple
   : > computer company
     : red fruit

orange
   : > telecom company
   : orange fruit

chili's
   : > restaurant company
 : spicy fruit
"##;
    let expected = r##"<p><p>apple</p><p><blockquote>
<p>computer company
: red fruit</p>
</blockquote></p><p>orange</p><p><blockquote>
<p>telecom company</p>
</blockquote></p><p><p>orange fruit</p></p><p>chili's</p><p><blockquote>
<p>restaurant company</p>
</blockquote></p><p><p>spicy fruit</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_12() {
    let original = r##"> cherry
> : keyboard company
> pomegranate
: tart fruit
"##;
    let expected = r##"<blockquote>
<p><p>cherry</p><p><p>keyboard company
pomegranate
: tart fruit</p></p></p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_13() {
    let original = r##"a
b\
c

:   foo
"##;
    let expected = r##"<p><p>a
b<br>
c</p><p><p>foo</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_14() {
    let original = r##"Foo

bar
:   baz

bim
:   bor
"##;
    let expected = r##"<p>Foo</p>
<p><p>bar</p><p><p>baz</p></p><p>bim</p><p><p>bor</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_15() {
    let original = r##"bar
:   baz

bim
:   bor

Bloze
"##;
    let expected = r##"<p><p>bar</p><p><p>baz</p></p><p>bim</p><p><p>bor</p></p></p>
<p>Bloze</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_16() {
    let original = r##"bar
    :baz

Bloze
"##;
    let expected = r##"<p>bar
:baz</p>
<p>Bloze</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_17() {
    let original = r##"bar
:    baz

Bloze
"##;
    let expected = r##"<p><p>bar</p><p><p>baz</p></p></p>
<p>Bloze</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_18() {
    let original = r##"bar
:       baz

bar
 :      baz

bar
  :     baz

bar
   :    baz

bar
    :   baz
"##;
    let expected = r##"<p><p>bar</p><p><pre><code>  baz
</code></pre></p><p>bar</p><p><pre><code> baz
</code></pre></p><p>bar</p><p><pre><code>baz
</code></pre></p><p>bar</p><p><p>baz</p></p></p>
<p>bar
:   baz</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_19() {
    let original = r##"*orange*

:   orange fruit

        { orange code block }

  > orange block quote

*orange*

:     orange fruit

        { orange code block }

  > orange block quote
"##;
    let expected = r##"<p><p><em>orange</em></p><p><p>orange fruit</p><pre><code>{ orange code block }
</code></pre></p></p>
<blockquote>
<p>orange block quote</p>
</blockquote>
<p><p><em>orange</em></p><p><pre><code>orange fruit

  { orange code block }
</code></pre><blockquote>
<p>orange block quote</p>
</blockquote></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_20() {
    let original = r##"Test|Table
----|-----
: first
"##;
    let expected = r##"<p><p>Test|Table
----|-----</p><p><p>first</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_21() {
    let original = r##"first
: second

Test|Table
----|-----
: fourth
"##;
    let expected = r##"<p><p>first</p><p><p>second</p></p><p>Test|Table
----|-----</p><p><p>fourth</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_22() {
    let original = r##"My section
==========
: first
"##;
    let expected = r##"<h1>My section</h1>
<p>: first</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_23() {
    let original = r##"first
: second

My section
==========
: fourth
"##;
    let expected = r##"<p><p>first</p><p><p>second</p></p></p>
<h1>My section</h1>
<p>: fourth</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_24() {
    let original = r##"## My subsection
: first
"##;
    let expected = r##"<h2>My subsection</h2>
<p>: first</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_25() {
    let original = r##"first
: second

## My subsection
: fourth
"##;
    let expected = r##"<p><p>first</p><p><p>second</p></p></p>
<h2>My subsection</h2>
<p>: fourth</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_26() {
    let original = r##"> first
: second
"##;
    let expected = r##"<blockquote>
<p>first
: second</p>
</blockquote>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_27() {
    let original = r##"first\
: second

third  
: fourth
"##;
    let expected = r##"<p><p>first\</p><p><p>second</p></p><p>third</p><p><p>fourth</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_28() {
    let original = r##"<div>first</div>
: second

first
: second
<div>third</div>
: fourth
"##;
    let expected = r##"<div>first</div>
: second

<p><p>first</p><p><p>second</p></p></p>
<div>third</div>
: fourth
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_29() {
    let original = r##"<span>first</span>
: second

third
: fourth

<span>fifth</span>
: sixth
"##;
    let expected = r##"<p><p><span>first</span></p><p><p>second</p></p><p>third</p><p><p>fourth</p></p><p><span>fifth</span></p><p><p>sixth</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_30() {
    let original = r##"level one
: l1
    level two
    : l2
        level three
        : l3

level one
: l1
"##;
    let expected = r##"<p><p>level one</p><p><p><p>l1
level two</p><p><p><p>l2
level three</p><p><p>l3</p></p></p></p></p></p><p>level one</p><p><p>l1</p></p></p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}

#[test]
fn definition_lists_test_31() {
    let original = r##"[a]: /url
    
:
"##;
    let expected = r##"<p>:</p>
"##;

    test_markdown_html(original, expected, 0, false, false, false, false, false, true, false);
}
