// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn gfm_autolink_test_1() {
    let original = r##"www.commonmark.org
"##;
    let expected = r##"<p><a href="http://www.commonmark.org">www.commonmark.org</a></p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}

#[test]
fn gfm_autolink_test_2() {
    let original = r##"Visit www.commonmark.org/help for more information.
"##;
    let expected = r##"<p>Visit <a href="http://www.commonmark.org/help">www.commonmark.org/help</a> for more information.</p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}

#[test]
fn gfm_autolink_test_3() {
    let original = r##"Visit www.commonmark.org.

Visit www.commonmark.org/a.b.
"##;
    let expected = r##"<p>Visit <a href="http://www.commonmark.org">www.commonmark.org</a>.</p>
<p>Visit <a href="http://www.commonmark.org/a.b">www.commonmark.org/a.b</a>.</p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}

#[test]
fn gfm_autolink_test_4() {
    let original = r##"www.google.com/search?q=Markup+(business)

(www.google.com/search?q=Markup+(business))
"##;
    let expected = r##"<p><a href="http://www.google.com/search?q=Markup+(business)">www.google.com/search?q=Markup+(business)</a></p>
<p>(<a href="http://www.google.com/search?q=Markup+(business)">www.google.com/search?q=Markup+(business)</a>)</p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}

#[test]
fn gfm_autolink_test_5() {
    let original = r##"www.google.com/search?q=(business))+ok
"##;
    let expected = r##"<p><a href="http://www.google.com/search?q=(business))+ok">www.google.com/search?q=(business))+ok</a></p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}

#[test]
fn gfm_autolink_test_6() {
    let original = r##"www.google.com/search?q=commonmark&hl=en

www.google.com/search?q=commonmark&hl;
"##;
    let expected = r##"<p><a href="http://www.google.com/search?q=commonmark&amp;hl=en">www.google.com/search?q=commonmark&amp;hl=en</a></p>
<p><a href="http://www.google.com/search?q=commonmark">www.google.com/search?q=commonmark</a>&amp;hl;</p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}

#[test]
fn gfm_autolink_test_7() {
    let original = r##"www.commonmark.org/he<lp
"##;
    let expected = r##"<p><a href="http://www.commonmark.org/he">www.commonmark.org/he</a>&lt;lp</p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}

#[test]
fn gfm_autolink_test_8() {
    let original = r##"http://commonmark.org

(Visit https://encrypted.google.com/search?q=Markup+(business))

Anonymous FTP is available at ftp://foo.bar.baz.
"##;
    let expected = r##"<p><a href="http://commonmark.org">http://commonmark.org</a></p>
<p>(Visit <a href="https://encrypted.google.com/search?q=Markup+(business)">https://encrypted.google.com/search?q=Markup+(business)</a>)</p>
<p>Anonymous FTP is available at ftp://foo.bar.baz.</p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}

#[test]
fn gfm_autolink_test_9() {
    let original = r##"foo@bar.baz
"##;
    let expected = r##"<p><a href="mailto:foo@bar.baz">foo@bar.baz</a></p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}

#[test]
fn gfm_autolink_test_10() {
    let original = r##"hello@mail+xyz.example isn't valid, but hello+xyz@mail.example is.
"##;
    let expected = r##"<p>hello@mail+xyz.example isn't valid, but <a href="mailto:hello+xyz@mail.example">hello+xyz@mail.example</a> is.</p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}

#[test]
fn gfm_autolink_test_11() {
    let original = r##"a.b-c_d@a.b

a.b-c_d@a.b.

a.b-c_d@a.b-

a.b-c_d@a.b_
"##;
    let expected = r##"<p><a href="mailto:a.b-c_d@a.b">a.b-c_d@a.b</a></p>
<p><a href="mailto:a.b-c_d@a.b">a.b-c_d@a.b</a>.</p>
<p>a.b-c_d@a.b-</p>
<p>a.b-c_d@a.b_</p>
"##;

    test_markdown_html(original, expected, 2048, false, false, false, false, false, false);
}
