// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn math_test_1() {
    let original = r##"$x=y$
"##;
    let expected = r##"<p><math><mi>x</mi><mo>=</mo><mi>y</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_2() {
    let original = r##"$\sqrt{3x-1}+(1+x)^2$
"##;
    let expected = r##"<p><math><msqrt><mrow><mn>3</mn><mi>x</mi><mo>−</mo><mn>1</mn></mrow></msqrt><mo>+</mo><mo stretchy="false">(</mo><mn>1</mn><mo>+</mo><mi>x</mi><msup><mo stretchy="false">)</mo><mn>2</mn></msup></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_3() {
    let original = r##"foo$1+1 = 2$bar
"##;
    let expected = r##"<p>foo<math><mn>1</mn><mo>+</mo><mn>1</mn><mo>=</mo><mn>2</mn></math>bar</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_4() {
    let original = r##"$a$ and $b$
"##;
    let expected = r##"<p><math><mi>a</mi></math> and <math><mi>b</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_5() {
    let original = r##"$a$$b$
"##;
    let expected = r##"<p><math><mi>a</mi><mi>$</mi><mi>$</mi><mi>b</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_6() {
    let original = r##"$5x + 2 =
17$
"##;
    let expected = r##"<p><math><mn>5</mn><mi>x</mi><mo>+</mo><mn>2</mn><mo>=</mo><mn>17</mn></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_7() {
    let original = r##"$$\alpha$$
"##;
    let expected = r##"<p><math><mi>α</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_8() {
    let original = r##"$a<b>c</b>$
"##;
    let expected = r##"<p><math><mi>a</mi><mo>&lt;</mo><mi>b</mi><mo>></mo><mi>c</mi><mo>&lt;</mo><mo lspace="0" rspace="0">/</mo><mi>b</mi><mo rspace="0">></mo></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_9() {
    let original = r##"$not `code`$
"##;
    let expected = r##"<p><math><mi>n</mi><mi>o</mi><mi>t</mi><mi>‘</mi><mi>c</mi><mi>o</mi><mi>d</mi><mi>e</mi><mi>‘</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_10() {
    let original = r##"$![not an](/image)$
"##;
    let expected = r##"<p><math><mo form="postfix">!</mo><mo stretchy="false">[</mo><mi>n</mi><mi>o</mi><mi>t</mi><mi>a</mi><mi>n</mi><mo stretchy="false">]</mo><mo stretchy="false">(</mo><mo lspace="0" rspace="0">/</mo><mi>i</mi><mi>m</mi><mi>a</mi><mi>g</mi><mi>e</mi><mo stretchy="false">)</mo></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_11() {
    let original = r##"$<https://not.a.link/>$
"##;
    let expected = r##"<p><math><mo lspace="0">&lt;</mo><mi>h</mi><mi>t</mi><mi>t</mi><mi>p</mi><mi>s</mi><mo lspace="0.2778em" rspace="0.2778em">:</mo><mo lspace="0" rspace="0">/</mo><mo lspace="0" rspace="0">/</mo><mi>n</mi><mi>o</mi><mi>t</mi><mi>.</mi><mi>a</mi><mi>.</mi><mi>l</mi><mi>i</mi><mi>n</mi><mi>k</mi><mo lspace="0" rspace="0">/</mo><mo rspace="0">></mo></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_12() {
    let original = r##"$&alpha;$
"##;
    let expected = r##"<p><code class="language-math math-inline">&#x26;alpha;</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_13() {
    let original = r##"$ y=x$
"##;
    let expected = r##"<p><math><mi>y</mi><mo>=</mo><mi>x</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_14() {
    let original = r##"$y=x $
"##;
    let expected = r##"<p><math><mi>y</mi><mo>=</mo><mi>x</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_15() {
    let original = r##"Hello $world.
"##;
    let expected = r##"<p>Hello $world.</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_16() {
    let original = r##"Dollar at end of line$
"##;
    let expected = r##"<p>Dollar at end of line$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_17() {
    let original = r##"$\$$
"##;
    let expected = r##"<p>$$$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_18() {
    let original = r##"$\{a\,b\}$
"##;
    let expected = r##"<p><math><mo stretchy="false">{</mo><mi>a</mi><mspace width="0.16666667em"/><mi>b</mi><mo stretchy="false">}</mo></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_19() {
    let original = r##"_$a$ equals $b$_
"##;
    let expected = r##"<p><em><math><mi>a</mi></math> equals <math><mi>b</mi></math></em></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_20() {
    let original = r##"**$a$ equals $b$**
"##;
    let expected = r##"<p><strong><math><mi>a</mi></math> equals <math><mi>b</mi></math></strong></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_21() {
    let original = r##"a$x$
"##;
    let expected = r##"<p>a<math><mi>x</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_22() {
    let original = r##"$x=y$
"##;
    let expected = r##"<p><math><mi>x</mi><mo>=</mo><mi>y</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_23() {
    let original = r##"$n$-th order
"##;
    let expected = r##"<p><math><mi>n</mi></math>-th order</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_24() {
    let original = r##"$a <b > c$
"##;
    let expected = r##"<p><math><mi>a</mi><mo>&lt;</mo><mi>b</mi><mo>></mo><mi>c</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_25() {
    let original = r##"$[(a+b)c](d+e)$
"##;
    let expected = r##"<p><math><mo stretchy="false">[</mo><mo stretchy="false">(</mo><mi>a</mi><mo>+</mo><mi>b</mi><mo stretchy="false">)</mo><mi>c</mi><mo stretchy="false">]</mo><mo stretchy="false">(</mo><mi>d</mi><mo>+</mo><mi>e</mi><mo stretchy="false">)</mo></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_26() {
    let original = r##"${a}_b c_{d}$
"##;
    let expected = r##"<p><math><msub><mi>a</mi><mi>b</mi></msub><msub><mi>c</mi><mi>d</mi></msub></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_27() {
    let original = r##"Thus, $20,000 and USD$30,000 won't parse
"##;
    let expected = r##"<p>Thus, <math><mn>20</mn><mo>,</mo><mn>000</mn><mi>a</mi><mi>n</mi><mi>d</mi><mi>U</mi><mi>S</mi><mi>D</mi></math>30,000 won't parse</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_28() {
    let original = r##"It is 2$ for a can of soda, not 1$.
"##;
    let expected = r##"<p>It is 2<math><mi>f</mi><mi>o</mi><mi>r</mi><mi>a</mi><mi>c</mi><mi>a</mi><mi>n</mi><mi>o</mi><mi>f</mi><mi>s</mi><mi>o</mi><mi>d</mi><mi>a</mi><mo>,</mo><mi>n</mi><mi>o</mi><mi>t</mi><mn>1</mn></math>.</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_29() {
    let original = r##"I'll give $20 today, if you give me more $ tomorrow.
"##;
    let expected = r##"<p>I'll give <math><mn>20</mn><mi>t</mi><mi>o</mi><mi>d</mi><mi>a</mi><mi>y</mi><mo>,</mo><mi>i</mi><mi>f</mi><mi>y</mi><mi>o</mi><mi>u</mi><mi>g</mi><mi>i</mi><mi>v</mi><mi>e</mi><mi>m</mi><mi>e</mi><mi>m</mi><mi>o</mi><mi>r</mi><mi>e</mi></math> tomorrow.</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_30() {
    let original = r##"Money adds: $\$X + \$Y = \$Z$.
"##;
    let expected = r##"<p>Money adds: <code class="language-math math-inline">\</code>X + $Y = $Z$.</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_31() {
    let original = r##"$not a\
hard break  
either$
"##;
    let expected = r##"<p><code class="language-math math-inline">not a\
hard break  
either</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_32() {
    let original = r##"$\alpha\$
"##;
    let expected = r##"<p><code class="language-math math-inline">\alpha\</code></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_33() {
    let original = r##"$Inline `first$ then` code
"##;
    let expected = r##"<p><math><mi>I</mi><mi>n</mi><mi>l</mi><mi>i</mi><mi>n</mi><mi>e</mi><mi>‘</mi><mi>f</mi><mi>i</mi><mi>r</mi><mi>s</mi><mi>t</mi></math> then` code</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_34() {
    let original = r##"`Code $first` then$ inline
"##;
    let expected = r##"<p><code>Code $first</code> then$ inline</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_35() {
    let original = r##"$$ Display `first $$ then` code
"##;
    let expected = r##"<p><math><mi>D</mi><mi>i</mi><mi>s</mi><mi>p</mi><mi>l</mi><mi>a</mi><mi>y</mi><mi>‘</mi><mi>f</mi><mi>i</mi><mi>r</mi><mi>s</mi><mi>t</mi></math> then` code</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_36() {
    let original = r##"`Code $$ first` then $$ display
"##;
    let expected = r##"<p><code>Code $$ first</code> then $$ display</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_37() {
    let original = r##"Oops empty $$ expression.
"##;
    let expected = r##"<p>Oops empty $$ expression.</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_38() {
    let original = r##"$x$$$$$$$y$$
"##;
    let expected = r##"<p>$x$$$$$$$y$$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_39() {
    let original = r##"$x$$$$$$y$$
"##;
    let expected = r##"<p>$x$$$$$$y$$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_40() {
    let original = r##"$$x$$$$$$y$$
"##;
    let expected = r##"<p><math><mi>x</mi><mi>$</mi><mi>$</mi><mi>$</mi><mi>$</mi><mi>$</mi><mi>$</mi><mi>y</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_41() {
    let original = r##"alpha$$beta$gamma$$delta
"##;
    let expected = r##"<p>alpha<math><mi>b</mi><mi>e</mi><mi>t</mi><mi>a</mi><mi>$</mi><mi>g</mi><mi>a</mi><mi>m</mi><mi>m</mi><mi>a</mi></math>delta</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_42() {
    let original = r##"$x + y - z$

$x + y
- z$

$$ x + y
> z $$
"##;
    let expected = r##"<p><math><mi>x</mi><mo>+</mo><mi>y</mi><mo>−</mo><mi>z</mi></math></p>
<p>$x + y</p>
<ul>
<li>z$</li>
</ul>
<math display="block"><mo lspace="0">></mo><mi>z</mi><mi>$</mi><mi>$</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_43() {
    let original = r##"$not

math$

$$
not

math
$$
"##;
    let expected = r##"<p>$not</p>
<p>math$</p>
<math display="block"><mi>n</mi><mi>o</mi><mi>t</mi><mi>m</mi><mi>a</mi><mi>t</mi><mi>h</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_44() {
    let original = r##"- $not
    - *
  math$
"##;
    let expected = r##"<ul>
<li>$not
<ul>
<li>*
math$</li>
</ul>
</li>
</ul>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_45() {
    let original = r##"$$
\beta+\gamma
$$
"##;
    let expected = r##"<math display="block"><mi>β</mi><mo>+</mo><mi>γ</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_46() {
    let original = r##"**Bold**

$$
x = y
$$
"##;
    let expected = r##"<p><strong>Bold</strong></p>
<math display="block"><mi>x</mi><mo>=</mo><mi>y</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_47() {
    let original = r##"$$ meta
x
$$
"##;
    let expected = r##"<math display="block"><mi>x</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_48() {
    let original = r##"$$
$$
"##;
    let expected = r##"<math display="block"></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_49() {
    let original = r##"$$
a
$$

$$
b
$$
"##;
    let expected = r##"<math display="block"><mi>a</mi></math>
<math display="block"><mi>b</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_50() {
    let original = r##"$$$
alpha
$$$
"##;
    let expected = r##"<math display="block"><mi>a</mi><mi>l</mi><mi>p</mi><mi>h</mi><mi>a</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_51() {
    let original = r##"   $$
   x
   $$
"##;
    let expected = r##"<math display="block"><mi>x</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_52() {
    let original = r##"    $$
    x
    $$
"##;
    let expected = r##"<pre><code>$$
x
$$
</code></pre>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_53() {
    let original = r##"$$
unterminated
"##;
    let expected = r##"<math display="block"><mi>u</mi><mi>n</mi><mi>t</mi><mi>e</mi><mi>r</mi><mi>m</mi><mi>i</mi><mi>n</mi><mi>a</mi><mi>t</mi><mi>e</mi><mi>d</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_54() {
    let original = r##"- $a$
- $$
  b
  $$
"##;
    let expected = r##"<ul>
<li><math><mi>a</mi></math></li>
<li>
<math display="block"><mi>b</mi></math>
</li>
</ul>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_55() {
    let original = r##"tango
$$
\alpha
$$
"##;
    let expected = r##"<p>tango</p>
<math display="block"><mi>α</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_56() {
    let original = r##"$$
\alpha
  $$
"##;
    let expected = r##"<math display="block"><mi>α</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_57() {
    let original = r##"$$
\alpha
$$  
"##;
    let expected = r##"<math display="block"><mi>α</mi></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_58() {
    let original = r##"$$

  1
+ 1

= 2

$$
"##;
    let expected = r##"<math display="block"><mn>1</mn><mo>+</mo><mn>1</mn><mo>=</mo><mn>2</mn></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_59() {
    let original = r##"Foo \$1$ bar

\$\$
1
\$\$
"##;
    let expected = r##"<p>Foo $1$ bar</p>
<p>$$
1
$$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_60() {
    let original = r##"**The Cauchy-Schwarz Inequality**

$$
\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
$$
"##;
    let expected = r##"<p><strong>The Cauchy-Schwarz Inequality</strong></p>
<math display="block"><msup><mrow><mo>(</mo><munderover><mo lspace="0">∑</mo><mrow><mi>k</mi><mo lspace="0" rspace="0">=</mo><mn>1</mn></mrow><mi>n</mi></munderover><msub><mi>a</mi><mi>k</mi></msub><msub><mi>b</mi><mi>k</mi></msub><mo>)</mo></mrow><mn>2</mn></msup><mo>≤</mo><mrow><mo>(</mo><munderover><mo lspace="0">∑</mo><mrow><mi>k</mi><mo lspace="0" rspace="0">=</mo><mn>1</mn></mrow><mi>n</mi></munderover><msubsup><mi>a</mi><mi>k</mi><mn>2</mn></msubsup><mo>)</mo></mrow><mrow><mo>(</mo><munderover><mo lspace="0">∑</mo><mrow><mi>k</mi><mo lspace="0" rspace="0">=</mo><mn>1</mn></mrow><mi>n</mi></munderover><msubsup><mi>b</mi><mi>k</mi><mn>2</mn></msubsup><mo>)</mo></mrow></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_61() {
    let original = r##"- $a$

  $$
  a
  $$

- $$
  b
  $$
"##;
    let expected = r##"<ul>
<li>
<p><math><mi>a</mi></math></p>
<math display="block"><mi>a</mi></math>
</li>
<li>
<math display="block"><mi>b</mi></math>
</li>
</ul>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_62() {
    let original = r##"> $$
> x
> $$
"##;
    let expected = r##"<blockquote>
<math display="block"><mi>x</mi></math>
</blockquote>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_63() {
    let original = r##"$$
\text{$b$}
$$
"##;
    let expected = r##"<math display="block"><mtext>$b$</mtext></math>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_64() {
    let original = r##"When $a \ne 0$, there are two solutions to $(ax^2 + bx + c = 0)$ and they are
$$ x = {-b \pm \sqrt{b^2-4ac} \over 2a} $$
"##;
    let expected = r##"<p>When <math><mi>a</mi><mo>≠</mo><mn>0</mn></math>, there are two solutions to <math><mo stretchy="false">(</mo><mi>a</mi><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><mi>b</mi><mi>x</mi><mo>+</mo><mi>c</mi><mo>=</mo><mn>0</mn><mo stretchy="false">)</mo></math> and they are
<math><mi>x</mi><mo>=</mo><mfrac><mrow><mo lspace="0" rspace="0">−</mo><mi>b</mi><mo>±</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>−</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_65() {
    let original = r##"[$a$](x)
"##;
    let expected = r##"<p><a href="x"><math><mi>a</mi></math></a></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_66() {
    let original = r##"$\pi$
'$\pi$
"$\pi$
($\pi$
[$\pi$
{$\pi$
/$\pi$
"##;
    let expected = r##"<p><math><mi>π</mi></math>
'<math><mi>π</mi></math>
"<math><mi>π</mi></math>
(<math><mi>π</mi></math>
[<math><mi>π</mi></math>
{<math><mi>π</mi></math>
/<math><mi>π</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_67() {
    let original = r##"_Equation $\Omega(69)$ in italic text_
"##;
    let expected = r##"<p><em>Equation <math><mrow><mspace/><mi mathvariant="normal">Ω</mi></mrow><mo stretchy="false">(</mo><mn>69</mn><mo stretchy="false">)</mo></math> in italic text</em></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_68() {
    let original = r##"$x$ $`y`$
"##;
    let expected = r##"<p><math><mi>x</mi></math> <math><mi>‘</mi><mi>y</mi><mi>‘</mi></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_69() {
    let original = r##"$a <b > c$

$[(a+b)c](d+e)$

${a}_b c_{d}$
"##;
    let expected = r##"<p><math><mi>a</mi><mo>&lt;</mo><mi>b</mi><mo>></mo><mi>c</mi></math></p>
<p><math><mo stretchy="false">[</mo><mo stretchy="false">(</mo><mi>a</mi><mo>+</mo><mi>b</mi><mo stretchy="false">)</mo><mi>c</mi><mo stretchy="false">]</mo><mo stretchy="false">(</mo><mi>d</mi><mo>+</mo><mi>e</mi><mo stretchy="false">)</mo></math></p>
<p><math><msub><mi>a</mi><mi>b</mi></msub><msub><mi>c</mi><mi>d</mi></msub></math></p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_70() {
    let original = r##"$x = \$$
"##;
    let expected = r##"<p>$x = $$</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_71() {
    let original = r##"foo$-1+1 = 2$bar
"##;
    let expected = r##"<p>foo<math><mo lspace="0" rspace="0">−</mo><mn>1</mn><mo>+</mo><mn>1</mn><mo>=</mo><mn>2</mn></math>bar</p>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}

#[test]
fn math_test_72() {
    let original = r##"- ![node logo](https://nodejs.org/static/images/logo.svg)
- $x$
"##;
    let expected = r##"<ul>
<li><img src="https://nodejs.org/static/images/logo.svg" alt="node logo"></li>
<li><math><mi>x</mi></math></li>
</ul>
"##;

    test_markdown_html(original, expected, 1024, false, false, false, false, false, false);
}
