// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn smartypants_test_1() {
    let original = r##"24" monitor
"##;
    let expected = r##"<p>24” monitor</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_2() {
    let original = r##"Height 6'2"
"##;
    let expected = r##"<p>Height 6’2”</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_3() {
    let original = r##"5'8"
"##;
    let expected = r##"<p>5’8”</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_4() {
    let original = r##"6' tall
"##;
    let expected = r##"<p>6’ tall</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_5() {
    let original = r##"The "thing"
"##;
    let expected = r##"<p>The “thing”</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_6() {
    let original = r##""open only
"##;
    let expected = r##"<p>“open only</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_7() {
    let original = r##"a "b" c
"##;
    let expected = r##"<p>a “b” c</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_8() {
    let original = r##"a "*quoted*" word
"##;
    let expected = r##"<p>a “<em>quoted</em>” word</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_9() {
    let original = r##""something **bold** else"
"##;
    let expected = r##"<p>“something <strong>bold</strong> else”</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_10() {
    let original = r##"'quoted'
"##;
    let expected = r##"<p>‘quoted’</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_11() {
    let original = r##"the 70's
"##;
    let expected = r##"<p>the 70’s</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_12() {
    let original = r##"it isn't
"##;
    let expected = r##"<p>it isn’t</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_13() {
    let original = r##"'Tis the season
"##;
    let expected = r##"<p>’Tis the season</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_14() {
    let original = r##"rock 'n' roll
"##;
    let expected = r##"<p>rock ‘n’ roll</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_15() {
    let original = r##"'He said, "hi."'
"##;
    let expected = r##"<p>‘He said, “hi.”’</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_16() {
    let original = r##"a -- b
"##;
    let expected = r##"<p>a – b</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_17() {
    let original = r##"a --- b
"##;
    let expected = r##"<p>a — b</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}

#[test]
fn smartypants_test_18() {
    let original = r##"wait...
"##;
    let expected = r##"<p>wait…</p>
"##;

    test_markdown_html(original, expected, 0, true, false, false, false, false, false);
}
